<?php

namespace App\Services\Institution;

use App\Models\Institution\AttendanceModel;
use App\Models\Institution\EmploymentContractModel;
use App\Services\System\StatutoryStandardResolver;
use Core\DbPdo;
use Core\Helpers\ActorHelper;
use PDO;

class AttendanceService
{
    private AttendanceModel $model; private AttendanceScheduleService $schedule; private AttendanceCalculationPolicy $calculationPolicy; private StatutoryStandardResolver $statutory; private AttendanceWeeklyRecalculationService $weekly; private ?\Closure $actorResolver;
    public function __construct(private readonly PDO $db,?callable $actorResolver=null){$this->model=new AttendanceModel($db);$contracts=new EmploymentContractModel($db);$this->calculationPolicy=new AttendanceCalculationPolicy();$this->schedule=new AttendanceScheduleService($this->model,new EmploymentContractValidityService($contracts),$this->calculationPolicy);$this->statutory=new StatutoryStandardResolver($db);$this->weekly=new AttendanceWeeklyRecalculationService($this->model,$this->statutory,$this->calculationPolicy,$this->schedule);$this->actorResolver=$actorResolver===null?null:\Closure::fromCallable($actorResolver);}
    public function options(): array{return ['success'=>true,'data'=>$this->model->options()];}
    public function employeeIdForUser(string $userId): string{$employee=$this->model->employeeByUser($userId);if(!$employee)throw new \RuntimeException('로그인 사용자와 연결된 직원이 없습니다.');return (string)$employee['id'];}
    public function dailyList(array $q,?string $scope=null): array{$r=$this->model->listDaily($q,$scope);return ['success'=>true,'data'=>$r['rows'],'recordsTotal'=>$r['total'],'recordsFiltered'=>$r['filtered']];}
    public function exceptionList(array $q,?string $scope=null): array{$r=$this->model->listDaily($q,$scope,true);return ['success'=>true,'data'=>$r['rows'],'recordsTotal'=>$r['total'],'recordsFiltered'=>$r['filtered']];}
    public function monthlyList(array $q,?string $scope=null): array{$r=$this->model->monthlyList($q,$scope);return ['success'=>true,'data'=>$r['rows'],'recordsTotal'=>$r['total'],'recordsFiltered'=>$r['filtered']];}
    public function detail(string $employeeId,string $date): array{$employeeId=$this->required($employeeId,'직원을 선택해 주세요.');$date=$this->date($date);$d=$this->model->daily($employeeId,$date);if(!$d)throw new \RuntimeException('근태 상세를 찾을 수 없습니다.');$d['segments']=$this->model->segments($d['id']);$d['exceptions']=$this->model->exceptions($d['id']);$d['clock_events']=$this->model->clockEventsForDate($employeeId,$date);return ['success'=>true,'data'=>$d];}
    public function histories(string $closureId,?string $employeeScope=null): array{return ['success'=>true,'data'=>$this->model->histories($this->required($closureId,'마감 ID가 필요합니다.'),$employeeScope)];}
    public function recalculateApprovedLeave(string $employeeId,string $workDate,string $actor): array{$this->assertOpen($employeeId,substr($workDate,0,7));return $this->recalculateInternal($employeeId,$workDate,$actor);}
    public function registerSelfClock(array $in,string $employeeId): array{$in['source_type_code']='EMPLOYEE_WEB';return $this->registerClock($in,$employeeId);}
    public function registerAdminClock(array $in): array{$this->required($in['reason']??'','관리자 등록 사유를 입력해 주세요.');$in['source_type_code']='ADMIN';return $this->registerClock($in);}

    public function invalidateClock(array $in): array
    {
        $id=$this->required($in['clock_event_id']??'','출퇴근 원본 ID가 필요합니다.');$reason=$this->required($in['reason']??'','무효화 사유를 입력해 주세요.');$key=$this->key($in);$old=$this->model->auditByRequest($key);if($old){if($old['action_type_code']!=='INVALIDATE'||$old['target_id']!==$id)throw new \RuntimeException('동일 요청 키가 다른 작업에 사용되었습니다.');return ['success'=>true,'data'=>$this->model->clockEvent($id),'message'=>'이미 처리된 요청입니다.'];}$actor=$this->actor();
        return DbPdo::transaction(function()use($id,$reason,$key,$actor){$event=$this->model->clockEvent($id,true);if(!$event)throw new \RuntimeException('출퇴근 원본을 찾을 수 없습니다.');if(!(int)$event['is_valid'])throw new \RuntimeException('이미 무효 처리된 원본입니다.');$date=$this->schedule->resolveWorkDate($event['employee_id'],$event['occurred_at']);$this->assertOpen($event['employee_id'],substr($date,0,7));$this->model->update('institution_attendance_clock_events',$id,['is_valid'=>0,'invalid_reason'=>$reason]);$after=$this->model->clockEvent($id);$daily=$this->recalculateInternal($event['employee_id'],$date,$actor);$this->audit('CLOCK_EVENT',$id,$event['employee_id'],'INVALIDATE','ADMIN',$reason,$key,$event,$after,$actor);return ['success'=>true,'data'=>['event'=>$after,'daily_record'=>$daily],'message'=>'출퇴근 원본을 무효 처리했습니다.'];});
    }

    public function registerClock(array $in,string $forcedEmployeeId=''): array
    {
        $employeeId=$forcedEmployeeId!==''?$forcedEmployeeId:$this->required($in['employee_id']??'','직원을 선택해 주세요.');$employee=$this->model->employee($employeeId);if(!$employee)throw new \InvalidArgumentException('직원을 찾을 수 없습니다.');
        $key=$this->key($in);$existing=$this->model->eventByRequest($key);if($existing){$audit=$this->model->auditByRequest($key);if(!$audit||$audit['target_id']!==$existing['id']||$audit['action_type_code']!=='REGISTER')throw new \RuntimeException('동일 요청 키가 다른 작업에 사용되었습니다.');return ['success'=>true,'data'=>$existing,'message'=>'이미 처리된 요청입니다.'];}if($this->model->auditByRequest($key))throw new \RuntimeException('동일 요청 키가 다른 작업에 사용되었습니다.');
        $type=strtoupper((string)($in['event_type_code']??''));if(!in_array($type,['CLOCK_IN','CLOCK_OUT'],true))throw new \InvalidArgumentException('출퇴근 유형이 올바르지 않습니다.');
        $at=$this->datetime($in['occurred_at']??'');$source=strtoupper((string)($in['source_type_code']??'ADMIN'));if(!in_array($source,['ADMIN','EMPLOYEE_WEB'],true))throw new \InvalidArgumentException('입력 출처가 올바르지 않습니다.');if($this->model->duplicateEvent($employeeId,$type,$at))throw new \InvalidArgumentException('같은 시각의 동일한 출퇴근 원본이 이미 등록되어 있습니다.');$workDate=$this->schedule->resolveWorkDate($employeeId,$at);$this->assertOpen($employeeId,substr($workDate,0,7));$actor=$this->actor();$id=$this->uuid();
        return DbPdo::transaction(function()use($id,$employeeId,$type,$at,$source,$key,$in,$actor,$workDate){$now=date('Y-m-d H:i:s');$event=['id'=>$id,'employee_id'=>$employeeId,'event_type_code'=>$type,'occurred_at'=>$at,'collected_at'=>$now,'source_type_code'=>$source,'external_key'=>null,'request_key'=>$key,'device_identifier'=>null,'source_payload'=>null,'is_valid'=>1,'invalid_reason'=>null,'created_at'=>$now,'created_by'=>$actor];$this->model->insert('institution_attendance_clock_events',$event);$reason=$source==='ADMIN'?trim((string)($in['reason']??'')):'본인 웹 출퇴근 등록';$this->audit('CLOCK_EVENT',$id,$employeeId,'REGISTER',$source,$reason,$key,null,$event,$actor);$daily=$this->recalculateInternal($employeeId,$workDate,$actor);return ['success'=>true,'data'=>['event'=>$event,'daily_record'=>$daily],'message'=>'출퇴근이 등록되었습니다.'];});
    }
    public function recalculate(array $in): array{$employee=$this->required($in['employee_id']??'','직원을 선택해 주세요.');$date=$this->date($in['work_date']??'');$key=$this->key($in);$old=$this->model->auditByRequest($key);if($old){if($old['action_type_code']!=='RECALCULATE')throw new \RuntimeException('동일 요청 키가 다른 작업에 사용되었습니다.');return ['success'=>true,'data'=>$this->model->daily($employee,$date),'message'=>'이미 처리된 요청입니다.'];}$actor=$this->actor();return DbPdo::transaction(function()use($employee,$date,$key,$actor){$before=$this->model->daily($employee,$date,true);$this->assertOpen($employee,substr($date,0,7));$after=$this->recalculateInternal($employee,$date,$actor);$this->audit('DAILY_RECORD',$after['id'],$employee,'RECALCULATE','ADMIN','일별 근태 재계산',$key,$before,$after,$actor);return ['success'=>true,'data'=>$after,'message'=>'재계산했습니다.'];});}
    public function correct(array $in): array
    {
        $id=$this->required($in['daily_record_id']??'','근태 ID가 필요합니다.');$reason=$this->required($in['reason']??'','정정 사유를 입력해 주세요.');$key=$this->key($in);$oldAudit=$this->model->auditByRequest($key);if($oldAudit){if($oldAudit['action_type_code']!=='ADMIN_CORRECT'||$oldAudit['target_id']!==$id)throw new \RuntimeException('동일 요청 키가 다른 작업에 사용되었습니다.');return ['success'=>true,'data'=>$this->model->dailyById($id),'message'=>'이미 처리된 요청입니다.'];}$actor=$this->actor();
        return DbPdo::transaction(function()use($id,$reason,$key,$in,$actor){$before=$this->model->dailyById($id,true);if(!$before)throw new \RuntimeException('근태를 찾을 수 없습니다.');$this->assertOpen($before['employee_id'],substr($before['work_date'],0,7));$segments=is_array($in['segments']??null)?$in['segments']:[];$normalized=$this->normalizeSegments($segments,$before['employee_id']);$current=$this->model->segments($id);if(json_encode($this->segmentComparable($current))===json_encode($this->segmentComparable($normalized)))throw new \InvalidArgumentException('변경된 내용이 없습니다.');foreach($current as $row)$this->model->update('institution_attendance_work_segments',$row['id'],['updated_at'=>date('Y-m-d H:i:s')]);$this->db->prepare('DELETE FROM institution_attendance_work_segments WHERE daily_record_id=:id')->execute([':id'=>$id]);$now=date('Y-m-d H:i:s');foreach($normalized as $row){$row+=['id'=>$this->uuid(),'daily_record_id'=>$id,'source_type_code'=>'ADMIN','is_manual'=>1,'created_at'=>$now,'created_by'=>$actor,'updated_at'=>$now,'updated_by'=>$actor];$this->model->insert('institution_attendance_work_segments',$row);}$this->model->update('institution_attendance_daily_records',$id,['is_corrected'=>1,'updated_at'=>$now,'updated_by'=>$actor]);$after=$this->recalculateInternal($before['employee_id'],$before['work_date'],$actor,true);$after['segments']=$this->model->segments($id);$this->audit('DAILY_RECORD',$id,$before['employee_id'],'ADMIN_CORRECT','ADMIN',$reason,$key,['daily'=>$before,'segments'=>$current],$after,$actor);return ['success'=>true,'data'=>$after,'message'=>'근태를 정정했습니다.'];});
    }
    public function close(array $in): array
    {
        return DbPdo::transaction(function () use ($in): array {
            $employee = $this->required($in['employee_id'] ?? '', '직원을 선택해 주세요.');
            $month = $this->month($in['closing_month'] ?? '');
            $this->model->closure($employee, $month, true);
            $this->model->monthRows($employee, $month, true);
            return $this->closeWithinTransaction($in);
        });
    }

    private function closeWithinTransaction(array $in): array
    {
        $employee=$this->required($in['employee_id']??'','직원을 선택해 주세요.');$month=$this->month($in['closing_month']??'');$reason=$this->required($in['reason']??'','마감 사유를 입력해 주세요.');$key=$this->key($in);$existing=$this->model->historyByRequest($key);if($existing){return ['success'=>true,'data'=>$existing,'message'=>'이미 처리된 요청입니다.'];}if($this->model->auditByRequest($key))throw new \RuntimeException('동일 요청 키가 다른 작업에 사용되었습니다.');$this->weekly->assertMonthBoundaryReady($employee,$month,date('Y-m-d'),true);$actor=$this->actor();
        return DbPdo::transaction(function()use($employee,$month,$reason,$key,$actor){$closure=$this->model->closure($employee,$month,true);if($closure&&$closure['close_status_code']==='CLOSED')throw new \RuntimeException('이미 마감된 월입니다.');$rows=$this->model->monthRows($employee,$month,true);if(!$rows)throw new \RuntimeException('마감할 근태가 없습니다.');$exceptions=$this->model->monthExceptions($employee,$month);$blockingTypes=['MISSING_CLOCK_IN','MISSING_CLOCK_OUT','CONTRACT_CONFLICT','NO_SCHEDULE','LEAVE_PERIOD_CONFLICT','DUPLICATE_CLOCK_IN','DUPLICATE_CLOCK_OUT'];$blocking=array_filter($exceptions,fn($x)=>in_array($x['exception_type_code'],$blockingTypes,true));$unconfirmed=$this->model->monthConfirmationCount($employee,$month);if($blocking||$unconfirmed>0){$counts=[];foreach($blocking as $row)$counts[$row['exception_type_code']]=($counts[$row['exception_type_code']]??0)+1;if($unconfirmed>0)$counts['NEEDS_CONFIRMATION']=$unconfirmed;$labels=['MISSING_CLOCK_IN'=>'출근 누락','MISSING_CLOCK_OUT'=>'퇴근 누락','CONTRACT_CONFLICT'=>'계약 충돌','NO_SCHEDULE'=>'일정 없음','LEAVE_PERIOD_CONFLICT'=>'휴직기간 충돌','DUPLICATE_CLOCK_IN'=>'연속 출근','DUPLICATE_CLOCK_OUT'=>'연속 퇴근','NEEDS_CONFIRMATION'=>'확인 필요'];$parts=[];foreach($counts as $type=>$count)$parts[]=($labels[$type]??$type).' '.$count.'건';throw new \RuntimeException(implode(', ',$parts).'이 있어 마감할 수 없습니다.');}$now=date('Y-m-d H:i:s');if(!$closure){$closure=['id'=>$this->uuid(),'employee_id'=>$employee,'closing_month'=>$month,'close_status_code'=>'OPEN','current_revision'=>0,'current_history_id'=>null,'closed_by'=>null,'closed_at'=>null,'reopened_by'=>null,'reopened_at'=>null,'reopen_reason'=>null,'created_at'=>$now,'created_by'=>$actor,'updated_at'=>$now,'updated_by'=>$actor];$this->model->insert('institution_attendance_monthly_closures',$closure);$closure=$this->model->closure($employee,$month,true);}$revision=(int)$closure['current_revision']+1;$history=$this->aggregate($closure['id'],$employee,$month,$revision,$rows,$exceptions,$reason,$key,$actor,$now);$this->model->insert('institution_attendance_monthly_closure_histories',$history);$this->model->update('institution_attendance_monthly_closures',$closure['id'],['close_status_code'=>'CLOSED','current_revision'=>$revision,'current_history_id'=>$history['id'],'closed_by'=>$actor,'closed_at'=>$now,'updated_at'=>$now,'updated_by'=>$actor]);$this->model->setMonthClosed($employee,$month,true,$actor);$this->audit('MONTHLY_CLOSURE',$closure['id'],$employee,'CLOSE','ADMIN',$reason,$key,$closure,$history,$actor);return ['success'=>true,'data'=>$history,'message'=>'월 근태를 마감했습니다.'];});
    }
    public function reopen(array $in): array
    {
        $employee=$this->required($in['employee_id']??'','직원을 선택해 주세요.');$month=$this->month($in['closing_month']??'');$reason=$this->required($in['reason']??'','재오픈 사유를 입력해 주세요.');$key=$this->key($in);$old=$this->model->auditByRequest($key);if($old){if($old['action_type_code']!=='REOPEN')throw new \RuntimeException('동일 요청 키가 다른 작업에 사용되었습니다.');return ['success'=>true,'data'=>$this->model->closure($employee,$month),'message'=>'이미 처리된 요청입니다.'];}$actor=$this->actor();
        return DbPdo::transaction(function()use($employee,$month,$reason,$key,$actor){$before=$this->model->closure($employee,$month,true);if(!$before||$before['close_status_code']!=='CLOSED')throw new \RuntimeException('마감된 월만 재오픈할 수 있습니다.');$now=date('Y-m-d H:i:s');$this->model->update('institution_attendance_monthly_closures',$before['id'],['close_status_code'=>'REOPENED','reopened_by'=>$actor,'reopened_at'=>$now,'reopen_reason'=>$reason,'updated_at'=>$now,'updated_by'=>$actor]);$this->model->setMonthClosed($employee,$month,false,$actor);$after=$this->model->closure($employee,$month);$this->audit('MONTHLY_CLOSURE',$before['id'],$employee,'REOPEN','ADMIN',$reason,$key,$before,$after,$actor);return ['success'=>true,'data'=>$after,'message'=>'월 마감을 해제했습니다.'];});
    }

    private function recalculateInternal(string $employee,string $date,string $actor,bool $preserveManual=false): array
    {
        if(!$this->model->daily($employee,$date)){$now=date('Y-m-d H:i:s');$snapshot=$this->model->snapshot($employee,$date);$this->model->insert('institution_attendance_daily_records',['id'=>$this->uuid(),'employee_id'=>$employee,'work_date'=>$date,'employment_contract_id'=>null,'scheduled_start_at'=>null,'scheduled_end_at'=>null,'scheduled_break_seconds'=>0,'first_clock_in_at'=>null,'last_clock_out_at'=>null,'actual_work_seconds'=>0,'actual_break_seconds'=>0,'scheduled_work_seconds'=>0,'calculated_overtime_seconds'=>0,'night_work_seconds'=>0,'holiday_work_seconds'=>0,'late_candidate_seconds'=>0,'early_leave_candidate_seconds'=>0,'process_status_code'=>'CALCULATED','calculation_status_code'=>'CALCULATED','calculation_version'=>1,'is_corrected'=>0,'department_id_snapshot'=>$snapshot['department_id']??null,'department_name_snapshot'=>$snapshot['department_name']??null,'job_id_snapshot'=>$snapshot['job_id']??null,'job_name_snapshot'=>$snapshot['job_name']??null,'primary_project_id_snapshot'=>$snapshot['project_id']??null,'primary_project_name_snapshot'=>$snapshot['project_name']??null,'workplace_assignment_id_snapshot'=>$snapshot['workplace_assignment_id']??null,'workplace_name_snapshot'=>$snapshot['workplace_name']??null,'created_at'=>$now,'created_by'=>$actor,'updated_at'=>$now,'updated_by'=>$actor]);}
        $daily=$this->model->daily($employee,$date,true);$schedule=$this->schedule->resolve($employee,$date);$events=$this->model->validEvents($employee,$date.' 00:00:00',date('Y-m-d H:i:s',strtotime($date.' +2 day')));$ins=array_values(array_filter($events,fn($e)=>$e['event_type_code']==='CLOCK_IN'));$outs=array_values(array_filter($events,fn($e)=>$e['event_type_code']==='CLOCK_OUT'));$first=$ins[0]['occurred_at']??null;$last=$outs?end($outs)['occurred_at']:null;$now=date('Y-m-d H:i:s');$id=$daily['id']??$this->uuid();if(!$daily){$snapshot=$this->model->snapshot($employee,$date);$daily=['id'=>$id,'employee_id'=>$employee,'work_date'=>$date,'created_at'=>$now,'created_by'=>$actor];$daily+=['department_id_snapshot'=>$snapshot['department_id']??null,'department_name_snapshot'=>$snapshot['department_name']??null,'job_id_snapshot'=>$snapshot['job_id']??null,'job_name_snapshot'=>$snapshot['job_name']??null,'primary_project_id_snapshot'=>$snapshot['project_id']??null,'primary_project_name_snapshot'=>$snapshot['project_name']??null,'workplace_assignment_id_snapshot'=>$snapshot['workplace_assignment_id']??null,'workplace_name_snapshot'=>$snapshot['workplace_name']??null];}
        if(!$preserveManual)$this->model->deleteAutomaticSegments($id);$segments=$daily?$this->model->segments($id):[];if(!$segments&&$first&&$last&&strtotime($last)>strtotime($first)){$segments=[['id'=>$this->uuid(),'daily_record_id'=>$id,'segment_type_code'=>'WORK','started_at'=>$first,'ended_at'=>$last,'duration_seconds'=>strtotime($last)-strtotime($first),'project_id'=>null,'project_name_snapshot'=>null,'workplace_assignment_id'=>null,'workplace_name_snapshot'=>null,'source_type_code'=>'SYSTEM','is_manual'=>0,'created_at'=>$now,'created_by'=>$actor,'updated_at'=>$now,'updated_by'=>$actor]];}
        $leaveUsages=$this->model->approvedLeaveUsages($employee,$date);
        $workingStandard=$this->optionalStandard('WORKING_TIME_STANDARD',$date);$holidayStandard=$this->optionalStandard('PUBLIC_HOLIDAY_CALENDAR',$date);
        $weekContext=[];if($workingStandard){$weekStart=(int)($workingStandard['value_data']['week_start_day']??0);if($weekStart>=1&&$weekStart<=7){[$weekFrom]=$this->calculationPolicy->weekRange($date,$weekStart);$prior=$this->model->weekRowsBefore($employee,$weekFrom,$date);$weekContext=['prior_actual_seconds'=>array_sum(array_column($prior,'actual_work_seconds')),'prior_overtime_seconds'=>array_sum(array_column($prior,'calculated_overtime_seconds'))];}}
        $calculated=$this->calculationPolicy->calculate($schedule,$segments,$leaveUsages,$workingStandard,$holidayStandard,$weekContext);
        $fullLeave=(bool)array_filter($leaveUsages,fn($u)=>$u['request_unit_code']==='FULL_DAY');$amLeave=(bool)array_filter($leaveUsages,fn($u)=>$u['request_unit_code']==='AM_HALF');$pmLeave=(bool)array_filter($leaveUsages,fn($u)=>$u['request_unit_code']==='PM_HALF');$employmentStatus=$this->model->employmentStatusAt($employee,$date);$activeEmployment=$employmentStatus==='ACTIVE';
        $data=['employment_contract_id'=>$schedule['contract_id'],'working_time_standard_id'=>$workingStandard['id']??null,'public_holiday_standard_id'=>$holidayStandard['id']??null,'scheduled_start_at'=>$schedule['start'],'scheduled_end_at'=>$schedule['end'],'scheduled_break_seconds'=>$schedule['break_seconds'],'first_clock_in_at'=>$first,'last_clock_out_at'=>$last,'actual_work_seconds'=>$calculated['actual_work_seconds'],'actual_break_seconds'=>$calculated['actual_break_seconds'],'scheduled_work_seconds'=>$calculated['scheduled_work_seconds'],'contract_excess_seconds'=>$calculated['contract_excess_seconds'],'calculated_overtime_seconds'=>$calculated['calculated_overtime_seconds'],'night_work_seconds'=>$calculated['night_work_seconds'],'holiday_work_seconds'=>$calculated['holiday_work_seconds'],'late_candidate_seconds'=>$calculated['late_candidate_seconds'],'early_leave_candidate_seconds'=>$calculated['early_leave_candidate_seconds'],'process_status_code'=>'CALCULATED','calculation_status_code'=>$calculated['calculation_status_code'],'calculation_version'=>$calculated['calculation_version'],'is_corrected'=>(int)($daily['is_corrected']??0),'updated_at'=>$now,'updated_by'=>$actor];if(isset($daily['created_at']))$this->model->update('institution_attendance_daily_records',$id,$data);else{$this->model->insert('institution_attendance_daily_records',$daily+$data);foreach($segments as $s)$this->model->insert('institution_attendance_work_segments',$s);}
        $types=[];if($schedule['exception'])$types[$schedule['exception']]=0;if(($employmentStatus==='ON_LEAVE'||$this->model->leaveAt($employee,$date))&&($first||$last))$types['LEAVE_PERIOD_CONFLICT']=0;if($schedule['workday']&&!$fullLeave&&$activeEmployment){if(!$first&&!$last&&!$leaveUsages)$types['ABSENT']=0;elseif(!$first&&!$amLeave)$types['MISSING_CLOCK_IN']=0;elseif(!$last&&!$pmLeave)$types['MISSING_CLOCK_OUT']=0;if($calculated['late_candidate_seconds']>0)$types['LATE']=$calculated['late_candidate_seconds'];if($calculated['early_leave_candidate_seconds']>0)$types['EARLY_LEAVE']=$calculated['early_leave_candidate_seconds'];}$types+=$this->duplicateClockTypes($events);$this->model->syncCalculatedExceptions($id,$types,$actor,$now);$this->weekly->recalculate($employee,$date,$actor);return $this->model->dailyById($id)??[];
    }
    private function normalizeSegments(array $rows,string $employee): array
    {
        $out=[];
        foreach($rows as $r){$type=strtoupper((string)($r['segment_type_code']??''));if(!in_array($type,['WORK','BREAK','OUTSIDE'],true))throw new \InvalidArgumentException('근무 구간 유형이 올바르지 않습니다.');$start=$this->datetime($r['started_at']??'');$end=$this->datetime($r['ended_at']??'');if(strtotime($end)<=strtotime($start))throw new \InvalidArgumentException('구간 종료시각은 시작시각보다 늦어야 합니다.');$projectId=trim((string)($r['project_id']??''));$project=null;if($projectId!==''){$project=$this->model->project($projectId);if(!$project||(int)$project['is_active']!==1)throw new \InvalidArgumentException('유효한 프로젝트를 선택해 주세요.');$workDate=date('Y-m-d',strtotime($start));if((!empty($project['start_date'])&&$workDate<$project['start_date'])||(!empty($project['completion_date'])&&$workDate>$project['completion_date']))throw new \InvalidArgumentException('프로젝트 기간 밖의 근무구간입니다.');}$workplaceId=trim((string)($r['workplace_assignment_id']??''));$workplace=null;if($workplaceId!==''){$workplace=$this->model->workplace($workplaceId);if(!$workplace)throw new \InvalidArgumentException('유효한 근무지를 선택해 주세요.');}$out[]=['segment_type_code'=>$type,'started_at'=>$start,'ended_at'=>$end,'duration_seconds'=>strtotime($end)-strtotime($start),'project_id'=>$projectId?:null,'project_name_snapshot'=>$project['project_name']??null,'workplace_assignment_id'=>$workplaceId?:null,'workplace_name_snapshot'=>$workplace['workplace_name_snapshot']??null];}
        usort($out,fn($a,$b)=>strcmp($a['started_at'],$b['started_at']));for($i=1;$i<count($out);$i++)if($out[$i]['started_at']<$out[$i-1]['ended_at'])throw new \InvalidArgumentException('근무 구간이 서로 겹칩니다.');foreach($out as $segment){$workDate=date('Y-m-d',strtotime($segment['started_at']));if($segment['project_id']&&!$this->model->activeProjectAssignment($employee,$segment['project_id'],$workDate))throw new \InvalidArgumentException('해당 근무일에 유효한 직원 프로젝트 배치가 아닙니다.');if($segment['workplace_assignment_id']&&!$this->model->activeWorkplaceAssignment($employee,$segment['workplace_assignment_id'],$workDate))throw new \InvalidArgumentException('해당 근무일에 유효한 공식 근무지가 아닙니다.');}return $out;
    }
    private function segmentComparable(array $rows): array{return array_map(fn($r)=>array_intersect_key($r,array_flip(['segment_type_code','started_at','ended_at','project_id','workplace_assignment_id'])),$rows);}
    private function aggregate(string $closure,string $employee,string $month,int $revision,array $rows,array $exceptions,string $reason,string $key,string $actor,string $now): array{$sum=fn($field)=>array_sum(array_map(fn($r)=>(int)$r[$field],$rows));$count=fn($type)=>count(array_filter($exceptions,fn($x)=>$x['exception_type_code']===$type));$hashRows=[];foreach($rows as $r){$ex=array_values(array_map(fn($x)=>$x['exception_type_code'],array_filter($exceptions,fn($x)=>$x['daily_record_id']===$r['id'])));sort($ex);$hashRows[]=['daily_record_id'=>$r['id'],'work_date'=>$r['work_date'],'scheduled_work_seconds'=>(int)$r['scheduled_work_seconds'],'actual_work_seconds'=>(int)$r['actual_work_seconds'],'calculated_overtime_seconds'=>(int)$r['calculated_overtime_seconds'],'night_work_seconds'=>(int)$r['night_work_seconds'],'holiday_work_seconds'=>(int)$r['holiday_work_seconds'],'exceptions'=>$ex,'calculation_version'=>(int)$r['calculation_version']];}$hash=hash('sha256',json_encode($hashRows,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));return ['id'=>$this->uuid(),'monthly_closure_id'=>$closure,'revision'=>$revision,'employee_id'=>$employee,'closing_month'=>$month,'workday_count'=>count(array_filter($rows,fn($r)=>(int)$r['scheduled_work_seconds']>0)),'scheduled_work_seconds'=>$sum('scheduled_work_seconds'),'actual_work_seconds'=>$sum('actual_work_seconds'),'calculated_overtime_seconds'=>$sum('calculated_overtime_seconds'),'night_work_seconds'=>$sum('night_work_seconds'),'holiday_work_seconds'=>$sum('holiday_work_seconds'),'late_candidate_count'=>$count('LATE'),'late_candidate_seconds'=>$sum('late_candidate_seconds'),'early_leave_candidate_count'=>$count('EARLY_LEAVE'),'early_leave_candidate_seconds'=>$sum('early_leave_candidate_seconds'),'absence_candidate_days'=>$count('ABSENT'),'missing_clock_count'=>$count('MISSING_CLOCK_IN')+$count('MISSING_CLOCK_OUT'),'ledger_hash'=>$hash,'calculation_version'=>1,'close_reason'=>$reason,'closed_by'=>$actor,'closed_at'=>$now,'source_request_key'=>$key,'created_at'=>$now];}
    private function audit(string $domain,string $target,string $employee,string $action,string $source,string $reason,string $key,?array $before,?array $after,string $actor): void{$this->model->insert('institution_attendance_audits',['id'=>$this->uuid(),'attendance_domain'=>$domain,'target_id'=>$target,'employee_id'=>$employee,'action_type_code'=>$action,'source_type_code'=>$source,'reason'=>$reason,'request_key'=>$key,'before_data'=>$before?json_encode($before,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES):null,'after_data'=>$after?json_encode($after,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES):null,'processed_by'=>$actor,'processed_at'=>date('Y-m-d H:i:s')]);}
    private function assertOpen(string $employee,string $month): void{$c=$this->model->closure($employee,$month);if($c&&$c['close_status_code']==='CLOSED')throw new \RuntimeException('마감된 월은 변경할 수 없습니다. 먼저 마감을 해제해 주세요.');}
    private function required(mixed $v,string $m): string{$v=trim((string)$v);if($v==='')throw new \InvalidArgumentException($m);return $v;}
    private function key(array $in): string{return $this->required($in['request_key']??'','요청 키가 필요합니다.');}
    private function date(mixed $v): string{$v=$this->required($v,'근무일을 입력해 주세요.');$d=\DateTimeImmutable::createFromFormat('!Y-m-d',$v);if(!$d||$d->format('Y-m-d')!==$v)throw new \InvalidArgumentException('근무일 형식이 올바르지 않습니다.');return $v;}
    private function month(mixed $v): string{$v=$this->required($v,'귀속월을 입력해 주세요.');if(!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$v))throw new \InvalidArgumentException('귀속월 형식이 올바르지 않습니다.');return $v;}
    private function datetime(mixed $v): string{$v=$this->required($v,'일시를 입력해 주세요.');$t=strtotime($v);if($t===false)throw new \InvalidArgumentException('일시 형식이 올바르지 않습니다.');return date('Y-m-d H:i:s',$t);}
    private function uuid(): string{$hex=bin2hex(random_bytes(16));return substr($hex,0,8).'-'.substr($hex,8,4).'-4'.substr($hex,13,3).'-'.dechex((hexdec($hex[16])&3)|8).substr($hex,17,3).'-'.substr($hex,20,12);}
    private function actor(): string{return $this->actorResolver?($this->actorResolver)():ActorHelper::user();}
    private function optionalStandard(string $type,string $date): ?array{return $this->statutory->resolveOptional($type,$date);}
    private function duplicateClockTypes(array $events): array{$types=[];$previous=null;foreach($events as $event){$type=(string)$event['event_type_code'];if($previous===$type)$types[$type==='CLOCK_IN'?'DUPLICATE_CLOCK_IN':'DUPLICATE_CLOCK_OUT']=0;$previous=$type;}return $types;}
}
