<?php
namespace App\Services\Institution;
use App\Models\Institution\EducationModel;
use App\Models\Institution\QualificationEducationReferenceModel;
use App\Models\Institution\QualificationModel;
use App\Services\File\FileService;
use Core\Helpers\ActorHelper;
use Core\Helpers\ExcelValueFormatterHelper;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PDO;
class QualificationEducationService
{
 private QualificationModel $qualifications;private EducationModel $educations;private QualificationEducationReferenceModel $references;private FileService $files;
 public function __construct(private PDO $db){$this->qualifications=new QualificationModel($db);$this->educations=new EducationModel($db);$this->references=new QualificationEducationReferenceModel($db);$this->files=new FileService($db);}
 public function options(?string $scope=null): array{$data=$this->references->options();$data['courses']=array_map(fn($r)=>array_merge($r,['value'=>$r['id'],'label'=>$r['course_name']]),$this->educations->courses(false));if($scope!==null)$data['employees']=array_values(array_filter($data['employees'],fn($r)=>$r['value']===$scope));return ['success'=>true,'data'=>$data];}
 public function qualificationList(array $q,?string $scope): array{$page=$this->qualifications->page($q,$scope);return ['success'=>true,'data'=>$page['rows'],'draw'=>(int)($q['draw']??0),'recordsTotal'=>$page['total'],'recordsFiltered'=>$page['total']];}
 public function educationList(array $q,?string $scope): array{$page=$this->educations->page($q,$scope);return ['success'=>true,'data'=>$page['rows'],'draw'=>(int)($q['draw']??0),'recordsTotal'=>$page['total'],'recordsFiltered'=>$page['total']];}
 public function qualificationDetail(string $id,?string $scope): array{$row=$this->qualifications->detail($id);$this->assertScoped($row,$scope);return ['success'=>true,'data'=>$row];}
 public function educationDetail(string $id,?string $scope): array{$row=$this->educations->detail($id);$this->assertScoped($row,$scope);return ['success'=>true,'data'=>$row];}
 public function saveQualification(array $input,array $files=[]): array
 {
  $id=trim((string)($input['id']??''));$request=$this->requestKey($input);if($target=$this->qualifications->auditTargetByRequest($request))return $this->qualificationDetail($target,null);
  $before=$id!==''?$this->qualifications->detail($id):null;$employee=trim((string)($input['employee_id']??$before['employee_id']??''));if(!$this->qualifications->employeeExists($employee))throw new \InvalidArgumentException('유효한 직원을 선택해 주세요.');
  $type=$this->code($input,'qualification_type_code','QUALIFICATION_TYPE','자격 종류');$status=$this->code($input,'status_code','QUALIFICATION_STATUS','자격 상태');$name=$this->required($input,'qualification_name','자격명');$actor=ActorHelper::user();$now=date('Y-m-d H:i:s');
  if($before&&$this->references->representativeEmployeeId($id)!==null&&$employee!==$before['employee_id'])throw new \InvalidArgumentException('대표 자격증은 다른 직원으로 변경할 수 없습니다. 직원관리에서 대표 자격증을 해제한 후 처리해 주세요.');$data=['employee_id'=>$employee,'qualification_type_code'=>$type,'qualification_name'=>$name,'credential_number'=>$this->nullable($input,'credential_number'),'issuer_name'=>$this->nullable($input,'issuer_name'),'grade_code'=>$this->nullable($input,'grade_code'),'technical_field_code'=>$this->nullable($input,'technical_field_code'),'specialty_code'=>$this->nullable($input,'specialty_code'),'acquired_date'=>$this->date($input,'acquired_date'),'valid_from'=>$this->date($input,'valid_from'),'valid_to'=>$this->date($input,'valid_to'),'renewal_due_date'=>$this->date($input,'renewal_due_date'),'status_code'=>$status,'supersedes_record_id'=>$this->nullable($input,'supersedes_record_id'),'verified_at'=>$input['verified_at']??$before['verified_at']??null,'verified_by'=>$input['verified_by']??$before['verified_by']??null,'status_reason'=>$this->nullable($input,'status_reason'),'note'=>$this->nullable($input,'note'),'updated_at'=>$now,'updated_by'=>$actor];$this->dateOrder($data['valid_from'],$data['valid_to']);
  $uploaded=$this->upload($files['attachment']??null,'certificate');if($uploaded){$data['attachment_path']=$uploaded['db_path'];$data['attachment_name']=(string)($files['attachment']['name']??'');}elseif($before){$data['attachment_path']=$before['attachment_path'];$data['attachment_name']=$before['attachment_name'];}
  $this->db->beginTransaction();try{if($id===''){$data['request_key']=$request;$data['created_at']=$now;$data['created_by']=$actor;$id=$this->qualifications->create($data);$action='CREATE';}else{if(!$before)throw new \InvalidArgumentException('자격 정보를 찾을 수 없습니다.');$this->qualifications->update($id,$data);$action='UPDATE';}$after=$this->qualifications->detail($id);$this->qualifications->audit($this->audit($id,$employee,$action,$request,$before,$after,$actor,(string)($input['reason']??'자격 정보 처리')));$this->db->commit();if($uploaded&&$before&&!empty($before['attachment_path'])&&$before['attachment_path']!==$uploaded['db_path'])$this->files->delete($before['attachment_path']);return ['success'=>true,'data'=>$after,'message'=>'저장되었습니다.'];}catch(\Throwable $e){$this->db->rollBack();if($uploaded)$this->files->delete($uploaded['db_path']);throw $e;}
 }
 public function verifyQualification(array $input): array{$id=$this->required($input,'id','자격 ID');$row=$this->qualifications->detail($id);if(!$row)throw new \InvalidArgumentException('자격 정보를 찾을 수 없습니다.');$actor=ActorHelper::user();$input=array_merge($row,$input,['id'=>$id,'status_code'=>'ACTIVE','verified_at'=>date('Y-m-d H:i:s'),'verified_by'=>$actor,'reason'=>$input['reason']??'관리자 자격 검증']);return $this->saveQualification($input);}
 public function renewQualification(array $input,array $files=[]): array{$old=$this->qualifications->detail($this->required($input,'id','기존 자격 ID'));if(!$old)throw new \InvalidArgumentException('기존 자격 정보를 찾을 수 없습니다.');$request=$this->requestKey($input);$renewed=array_merge($old,$input,['supersedes_record_id'=>$old['id'],'request_key'=>$request,'status_code'=>'PENDING_VERIFICATION','verified_at'=>null,'verified_by'=>null,'reason'=>$input['reason']??'자격 갱신']);unset($renewed['id'],$renewed['created_at'],$renewed['created_by'],$renewed['updated_at'],$renewed['updated_by'],$renewed['deleted_at'],$renewed['deleted_by']);return $this->saveQualification($renewed,$files);}
 public function deleteQualification(array $input): array{$id=$this->required($input,'id','자격 ID');$request=$this->requestKey($input);if($target=$this->qualifications->auditTargetByRequest($request))return ['success'=>true,'id'=>$target];$before=$this->qualifications->detail($id);if(!$before)throw new \InvalidArgumentException('자격 정보를 찾을 수 없습니다.');$actor=ActorHelper::user();$this->db->beginTransaction();try{$this->references->clearRepresentativeQualification($id);$this->qualifications->softDelete($id,$actor);$this->qualifications->audit($this->audit($id,$before['employee_id'],'DELETE',$request,$before,null,$actor,(string)($input['reason']??'자격 삭제')));$this->db->commit();return ['success'=>true,'id'=>$id,'message'=>'삭제되었습니다.'];}catch(\Throwable $e){$this->db->rollBack();throw $e;}}
 public function saveEducation(array $input,array $files=[]): array
 {
  $id=trim((string)($input['id']??''));$request=$this->requestKey($input);if($target=$this->educations->auditTargetByRequest($request))return $this->educationDetail($target,null);$before=$id!==''?$this->educations->detail($id):null;$employee=$this->required($input,'employee_id','직원');$course=$this->educations->course($this->required($input,'course_id','교육과정'));if(!$course)throw new \InvalidArgumentException('유효한 교육과정을 선택해 주세요.');$start=$this->datetime($input,'education_start_at','교육 시작일시');$end=$this->datetime($input,'education_end_at','교육 종료일시');if(strtotime($end)<=strtotime($start))throw new \InvalidArgumentException('교육 종료일시는 시작일시보다 늦어야 합니다.');$minutes=(int)($input['education_minutes']??0);if($minutes<=0)throw new \InvalidArgumentException('교육시간을 입력해 주세요.');$actor=ActorHelper::user();$now=date('Y-m-d H:i:s');$data=['employee_id'=>$employee,'course_id'=>$course['id'],'education_name'=>trim((string)($input['education_name']??$course['course_name'])),'institution_name'=>$this->nullable($input,'institution_name')??$course['default_institution_name'],'education_start_at'=>$start,'education_end_at'=>$end,'education_minutes'=>$minutes,'attendance_status_code'=>$this->code($input,'attendance_status_code','EDUCATION_ATTENDANCE_STATUS','참석 상태'),'completion_status_code'=>$this->code($input,'completion_status_code','EDUCATION_COMPLETION_STATUS','이수 상태'),'completion_number'=>$this->nullable($input,'completion_number'),'valid_from'=>$this->date($input,'valid_from'),'valid_to'=>$this->date($input,'valid_to'),'renewal_due_date'=>$this->date($input,'renewal_due_date'),'note'=>$this->nullable($input,'note'),'updated_at'=>$now,'updated_by'=>$actor];$this->dateOrder($data['valid_from'],$data['valid_to']);$uploaded=$this->upload($files['attachment']??null,'certificate');if($uploaded){$data['attachment_path']=$uploaded['db_path'];$data['attachment_name']=(string)($files['attachment']['name']??'');}elseif($before){$data['attachment_path']=$before['attachment_path'];$data['attachment_name']=$before['attachment_name'];}
  $this->db->beginTransaction();try{if($id===''){$data['request_key']=$request;$data['created_at']=$now;$data['created_by']=$actor;$id=$this->educations->createRecord($data);$action='CREATE';}else{if(!$before)throw new \InvalidArgumentException('교육 이력을 찾을 수 없습니다.');$this->educations->updateRecord($id,$data);$action='UPDATE';}$after=$this->educations->detail($id);$this->educations->audit($this->audit($id,$employee,$action,$request,$before,$after,$actor,(string)($input['reason']??'교육 이력 처리')));$this->db->commit();if($uploaded&&$before&&!empty($before['attachment_path'])&&$before['attachment_path']!==$uploaded['db_path'])$this->files->delete($before['attachment_path']);return ['success'=>true,'data'=>$after,'message'=>'저장되었습니다.'];}catch(\Throwable $e){$this->db->rollBack();if($uploaded)$this->files->delete($uploaded['db_path']);throw $e;}
 }
 public function deleteEducation(array $input): array{$id=$this->required($input,'id','교육 이력 ID');$request=$this->requestKey($input);if($target=$this->educations->auditTargetByRequest($request))return ['success'=>true,'id'=>$target];$before=$this->educations->detail($id);if(!$before)throw new \InvalidArgumentException('교육 이력을 찾을 수 없습니다.');$actor=ActorHelper::user();$this->db->beginTransaction();try{$this->educations->deleteRecord($id,$actor);$this->educations->audit($this->audit($id,$before['employee_id'],'DELETE',$request,$before,null,$actor,(string)($input['reason']??'교육 이력 삭제')));$this->db->commit();return ['success'=>true,'id'=>$id,'message'=>'삭제되었습니다.'];}catch(\Throwable $e){$this->db->rollBack();throw $e;}}
 public function saveCourse(array $input): array{$id=trim((string)($input['id']??''));$actor=ActorHelper::user();$now=date('Y-m-d H:i:s');$data=['course_code'=>strtoupper($this->required($input,'course_code','과정 코드')),'course_name'=>$this->required($input,'course_name','과정명'),'education_type_code'=>$this->code($input,'education_type_code','EDUCATION_TYPE','교육 종류'),'default_institution_name'=>$this->nullable($input,'default_institution_name'),'default_minutes'=>max(0,(int)($input['default_minutes']??0)),'validity_months'=>$this->nullableInt($input,'validity_months'),'is_statutory'=>$this->flag($input,'is_statutory'),'is_mandatory'=>$this->flag($input,'is_mandatory'),'requires_certificate'=>$this->flag($input,'requires_certificate'),'description'=>$this->nullable($input,'description'),'is_active'=>$this->flag($input,'is_active',1),'updated_at'=>$now,'updated_by'=>$actor];if($id===''){$data['sort_no']=count($this->educations->courses(false))+1;$data['request_key']=$this->requestKey($input);$data['created_at']=$now;$data['created_by']=$actor;$id=$this->educations->createCourse($data);}else{$this->educations->updateCourse($id,$data);}return ['success'=>true,'data'=>$this->educations->course($id),'message'=>'저장되었습니다.'];}
 public function excel(array $q,?string $scope): void{$type=(string)($q['type']??'qualifications');$q['start']=0;$q['length']=100000;$rows=$type==='educations'?$this->educations->page($q,$scope)['rows']:$this->qualifications->page($q,$scope)['rows'];$book=new Spreadsheet();$sheet=$book->getActiveSheet();$sheet->setTitle($type==='educations'?'교육 이력':'자격 현황');ExcelValueFormatterHelper::writeTable($sheet,$rows?array_keys($rows[0]):['조회 결과'],$rows?array_map('array_values',$rows):[['조회 결과가 없습니다.']],'A1');header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="qualification-education-'.$type.'-'.date('Ymd-His').'.xlsx"');(new Xlsx($book))->save('php://output');$book->disconnectWorksheets();}
 public function employeeIdForUser(string $id): string{$employee=$this->qualifications->employeeIdForUser($id);if($employee==='')throw new \RuntimeException('연결된 직원 정보를 찾을 수 없습니다.');return $employee;}
 private function audit(string $target,?string $employee,string $action,string $request,?array $before,?array $after,string $actor,string $reason): array{return ['target_id'=>$target,'employee_id'=>$employee,'action_type_code'=>$action,'source_type_code'=>'ADMIN','reason'=>trim($reason)!==''?trim($reason):'관리자 처리','request_key'=>$request,'before_data'=>$before?json_encode($before,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES):null,'after_data'=>$after?json_encode($after,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES):null,'processed_by'=>$actor,'processed_at'=>date('Y-m-d H:i:s')];}
 private function upload(?array $file,string $policy): ?array{if(!$file||($file['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)return null;$r=$this->files->uploadByPolicyKey($file,$policy);if(empty($r['success']))throw new \InvalidArgumentException($r['message']??'파일 업로드 중 오류가 발생했습니다.');return $r;}
 private function assertScoped(?array $row,?string $scope): void{if(!$row)throw new \InvalidArgumentException('정보를 찾을 수 없습니다.');if($scope!==null&&($row['employee_id']??'')!==$scope)throw new \RuntimeException('다른 직원의 정보를 조회할 수 없습니다.');}
 private function code(array $in,string $field,string $group,string $label): string{$v=$this->required($in,$field,$label);if(!$this->references->codeExists($group,$v))throw new \InvalidArgumentException($label.' 값이 올바르지 않습니다.');return $v;}
 private function requestKey(array $in): string{$v=trim((string)($in['request_key']??''));if($v==='')throw new \InvalidArgumentException('request_key가 필요합니다.');return $v;}
 private function required(array $in,string $key,string $label): string{$v=trim((string)($in[$key]??''));if($v==='')throw new \InvalidArgumentException($label.'을(를) 입력해 주세요.');return $v;}
 private function nullable(array $in,string $key): ?string{$v=trim((string)($in[$key]??''));return $v===''?null:$v;}
 private function nullableInt(array $in,string $key): ?int{$v=$this->nullable($in,$key);return $v===null?null:max(0,(int)$v);}
 private function date(array $in,string $key): ?string{$v=$this->nullable($in,$key);if($v===null)return null;$d=\DateTimeImmutable::createFromFormat('Y-m-d',$v);if(!$d||$d->format('Y-m-d')!==$v)throw new \InvalidArgumentException($key.' 날짜 형식이 올바르지 않습니다.');return $v;}
 private function datetime(array $in,string $key,string $label): string{$v=$this->required($in,$key,$label);$v=str_replace('T',' ',$v);if(strlen($v)===16)$v.=':00';if(!strtotime($v))throw new \InvalidArgumentException($label.' 형식이 올바르지 않습니다.');return $v;}
 private function dateOrder(?string $from,?string $to): void{if($from&&$to&&$to<$from)throw new \InvalidArgumentException('종료일은 시작일보다 빠를 수 없습니다.');}
 private function flag(array $in,string $key,int $default=0): int{return array_key_exists($key,$in)?(in_array($in[$key],[1,'1',true,'on'],true)?1:0):$default;}
}
