<?php
namespace App\Services\Institution;
use App\Models\Institution\EducationModel;
use App\Models\Institution\QualificationEducationReferenceModel;
use App\Models\Institution\QualificationEducationPolicyModel;
use App\Models\Institution\QualificationModel;
use App\Services\File\FileService;
use App\Services\Concerns\LogsServiceOperations;
use Core\Helpers\ActorHelper;
use Core\LoggerFactory;
use PDO;
use Psr\Log\LoggerInterface;
class QualificationEducationService
{
 use LogsServiceOperations;
 private QualificationModel $qualifications;private EducationModel $educations;private QualificationEducationReferenceModel $references;private QualificationEducationPolicyModel $policies;private FileService $files;private LoggerInterface $logger;
 public function __construct(private PDO $db){$this->qualifications=new QualificationModel($db);$this->educations=new EducationModel($db);$this->references=new QualificationEducationReferenceModel($db);$this->policies=new QualificationEducationPolicyModel($db);$this->files=new FileService($db);$this->logger=LoggerFactory::getLogger('service-institution-qualification-education');}
 public function options(?string $scope=null): array{$data=$this->references->options();unset($data['employees']);$data['qualification_categories']=$data['qualification_types'];$data['courses']=array_map(fn($r)=>array_merge($r,['value'=>$r['id'],'label'=>$r['course_name']]),$this->policies->courses(false));$data['qualification_types']=array_map(fn($r)=>array_merge($r,['value'=>$r['id'],'label'=>$r['qualification_name']]),$this->policies->qualificationTypes(false));$data['jobs']=$this->policies->jobs();$data['scope_employee_id']=$scope;return ['success'=>true,'data'=>$data];}
 public function qualificationList(array $q,?string $scope): array{$page=$this->qualifications->page($q,$scope);return ['success'=>true,'data'=>$page['rows'],'draw'=>(int)($q['draw']??0),'recordsTotal'=>$page['total'],'recordsFiltered'=>$page['total']];}
 public function educationList(array $q,?string $scope): array{$page=$this->educations->page($q,$scope);return ['success'=>true,'data'=>$page['rows'],'draw'=>(int)($q['draw']??0),'recordsTotal'=>$page['total'],'recordsFiltered'=>$page['total']];}
 public function qualificationDetail(string $id,?string $scope): array{$row=$this->qualifications->detail($id);$this->assertScoped($row,$scope);return ['success'=>true,'data'=>$row];}
 public function educationDetail(string $id,?string $scope): array{$row=$this->educations->detail($id);$this->assertScoped($row,$scope);return ['success'=>true,'data'=>$row];}
 public function saveQualification(array $input,array $files=[]): array{return $this->runLoggedOperation($this->logger,'자격 정보 저장','QUALIFICATION_SAVE','save-qualification',[],fn():array=>$this->saveQualificationInternal($input,$files),'info',false);}
 private function saveQualificationInternal(array $input,array $files=[]): array
 {
  $id=trim((string)($input['id']??''));$request=$this->requestKey($input);if($target=$this->qualifications->auditTargetByRequest($request))return $this->qualificationDetail($target,null);
  $before=$id!==''?$this->qualifications->detail($id):null;$employee=trim((string)($input['employee_id']??$before['employee_id']??''));if(!$this->qualifications->employeeExists($employee))throw new \InvalidArgumentException('유효한 직원을 선택해 주세요.');
  $typeId=$this->required($input,'qualification_type_id','자격 기준');$type=$this->policies->qualificationType($typeId);if(!$type||(!(int)$type['is_active']&&(!$before||$before['qualification_type_id']!==$typeId)))throw new \InvalidArgumentException('사용 가능한 자격 기준을 선택해 주세요.');$status=$this->code($input,'status_code','QUALIFICATION_STATUS','자격 상태');$name=trim((string)($input['qualification_name']??''))?:$type['qualification_name'];$actor=ActorHelper::user();$now=date('Y-m-d H:i:s');
  if($before&&$this->references->representativeEmployeeId($id)!==null&&$employee!==$before['employee_id'])throw new \InvalidArgumentException('대표 자격증은 다른 직원으로 변경할 수 없습니다. 직원관리에서 대표 자격증을 해제한 후 처리해 주세요.');$data=['employee_id'=>$employee,'qualification_type_id'=>$typeId,'qualification_type_code'=>$type['category_code'],'qualification_name'=>$name,'credential_number'=>$this->nullable($input,'credential_number'),'issuer_name'=>$this->nullable($input,'issuer_name')??$type['default_issuer_name'],'grade_code'=>$this->nullable($input,'grade_code'),'technical_field_code'=>$this->nullable($input,'technical_field_code'),'specialty_code'=>$this->nullable($input,'specialty_code'),'acquired_date'=>$this->date($input,'acquired_date'),'valid_from'=>$this->date($input,'valid_from'),'valid_to'=>$this->date($input,'valid_to'),'renewal_due_date'=>$this->date($input,'renewal_due_date'),'status_code'=>$status,'supersedes_record_id'=>$this->nullable($input,'supersedes_record_id'),'verified_at'=>$input['verified_at']??$before['verified_at']??null,'verified_by'=>$input['verified_by']??$before['verified_by']??null,'status_reason'=>$this->nullable($input,'status_reason'),'note'=>$this->nullable($input,'note'),'updated_at'=>$now,'updated_by'=>$actor];$this->dateOrder($data['valid_from'],$data['valid_to']);
  $uploaded=$this->upload($files['attachment']??null,'certificate');if($uploaded){$data['attachment_path']=$uploaded['db_path'];$data['attachment_name']=(string)($files['attachment']['name']??'');}elseif($before){$data['attachment_path']=$before['attachment_path'];$data['attachment_name']=$before['attachment_name'];}
  $this->db->beginTransaction();try{if($id===''){$data['request_key']=$request;$data['created_at']=$now;$data['created_by']=$actor;$id=$this->qualifications->create($data);$action='CREATE';}else{if(!$before)throw new \InvalidArgumentException('자격 정보를 찾을 수 없습니다.');$this->qualifications->update($id,$data);$action='UPDATE';}if(in_array($status,['SUSPENDED','REVOKED','INVALIDATED'],true))$this->references->clearRepresentativeQualification($id);$after=$this->qualifications->detail($id);$this->qualifications->audit($this->audit($id,$employee,$action,$request,$before,$after,$actor,(string)($input['reason']??'자격 정보 처리')));$this->db->commit();if($uploaded&&$before&&!empty($before['attachment_path'])&&$before['attachment_path']!==$uploaded['db_path'])$this->files->delete($before['attachment_path']);return ['success'=>true,'data'=>$after,'message'=>'저장되었습니다.'];}catch(\Throwable $e){$this->db->rollBack();if($uploaded)$this->files->delete($uploaded['db_path']);throw $e;}
 }
 public function verifyQualification(array $input): array{$id=$this->required($input,'id','자격 ID');$row=$this->qualifications->detail($id);if(!$row)throw new \InvalidArgumentException('자격 정보를 찾을 수 없습니다.');$actor=ActorHelper::user();$input=array_merge($row,$input,['id'=>$id,'status_code'=>'ACTIVE','verified_at'=>date('Y-m-d H:i:s'),'verified_by'=>$actor,'reason'=>$input['reason']??'관리자 자격 검증']);return $this->saveQualification($input);}
 public function renewQualification(array $input,array $files=[]): array{$old=$this->qualifications->detail($this->required($input,'id','기존 자격 ID'));if(!$old)throw new \InvalidArgumentException('기존 자격 정보를 찾을 수 없습니다.');$request=$this->requestKey($input);$renewed=array_merge($old,$input,['supersedes_record_id'=>$old['id'],'request_key'=>$request,'status_code'=>'PENDING_VERIFICATION','verified_at'=>null,'verified_by'=>null,'reason'=>$input['reason']??'자격 갱신']);unset($renewed['id'],$renewed['created_at'],$renewed['created_by'],$renewed['updated_at'],$renewed['updated_by'],$renewed['deleted_at'],$renewed['deleted_by']);return $this->saveQualification($renewed,$files);}
 public function deleteQualification(array $input): array{$id=$this->required($input,'id','자격 ID');$request=$this->requestKey($input);if($target=$this->qualifications->auditTargetByRequest($request))return ['success'=>true,'id'=>$target];$before=$this->qualifications->detail($id);if(!$before)throw new \InvalidArgumentException('자격 정보를 찾을 수 없습니다.');$reason=$this->required($input,'reason','처리 사유');if($before['status_code']!=='PENDING_VERIFICATION')return $this->invalidateQualification(['id'=>$id,'request_key'=>$request,'reason'=>$reason]);$actor=ActorHelper::user();$this->db->beginTransaction();try{$this->references->clearRepresentativeQualification($id);$this->qualifications->softDelete($id,$actor);$this->qualifications->audit($this->audit($id,$before['employee_id'],'DELETE',$request,$before,null,$actor,$reason));$this->db->commit();$this->logger->info('자격 정보 삭제를 완료했습니다.',['event_code'=>'QUALIFICATION_DELETE','result'=>'SUCCESS']);return ['success'=>true,'id'=>$id,'message'=>'삭제되었습니다.'];}catch(\Throwable $e){$this->db->rollBack();$this->logOperationException($e);throw $e;}}
 public function invalidateQualification(array $input): array{$id=$this->required($input,'id','자격 ID');$before=$this->qualifications->detail($id);if(!$before)throw new \InvalidArgumentException('자격 정보를 찾을 수 없습니다.');$reason=$this->required($input,'reason','무효화 사유');return $this->saveQualification(array_merge($before,['id'=>$id,'status_code'=>'INVALIDATED','status_reason'=>$reason,'request_key'=>$this->requestKey($input),'reason'=>$reason]));}
 public function saveEducation(array $input,array $files=[]): array{return $this->runLoggedOperation($this->logger,'교육 이력 저장','EDUCATION_RECORD_SAVE','save-education',[],fn():array=>$this->saveEducationInternal($input,$files),'info',false);}
 private function saveEducationInternal(array $input,array $files=[]): array
 {
  $id=trim((string)($input['id']??''));$request=$this->requestKey($input);if($target=$this->educations->auditTargetByRequest($request))return $this->educationDetail($target,null);$before=$id!==''?$this->educations->detail($id):null;$employee=$this->required($input,'employee_id','직원');$course=$this->educations->course($this->required($input,'course_id','교육과정'));if(!$course)throw new \InvalidArgumentException('유효한 교육과정을 선택해 주세요.');$start=$this->datetime($input,'education_start_at','교육 시작일시');$end=$this->datetime($input,'education_end_at','교육 종료일시');if(strtotime($end)<=strtotime($start))throw new \InvalidArgumentException('교육 종료일시는 시작일시보다 늦어야 합니다.');$minutes=(int)($input['education_minutes']??0);if($minutes<=0)throw new \InvalidArgumentException('교육시간을 입력해 주세요.');$actor=ActorHelper::user();$now=date('Y-m-d H:i:s');$data=['employee_id'=>$employee,'course_id'=>$course['id'],'education_name'=>trim((string)($input['education_name']??$course['course_name'])),'institution_name'=>$this->nullable($input,'institution_name')??$course['default_institution_name'],'education_start_at'=>$start,'education_end_at'=>$end,'education_minutes'=>$minutes,'attendance_status_code'=>$this->code($input,'attendance_status_code','EDUCATION_ATTENDANCE_STATUS','참석 상태'),'completion_status_code'=>$this->code($input,'completion_status_code','EDUCATION_COMPLETION_STATUS','이수 상태'),'completion_number'=>$this->nullable($input,'completion_number'),'valid_from'=>$this->date($input,'valid_from'),'valid_to'=>$this->date($input,'valid_to'),'renewal_due_date'=>$this->date($input,'renewal_due_date'),'note'=>$this->nullable($input,'note'),'updated_at'=>$now,'updated_by'=>$actor];$this->dateOrder($data['valid_from'],$data['valid_to']);$uploaded=$this->upload($files['attachment']??null,'certificate');if($uploaded){$data['attachment_path']=$uploaded['db_path'];$data['attachment_name']=(string)($files['attachment']['name']??'');}elseif($before){$data['attachment_path']=$before['attachment_path'];$data['attachment_name']=$before['attachment_name'];}
  $this->db->beginTransaction();try{if($id===''){$data['request_key']=$request;$data['created_at']=$now;$data['created_by']=$actor;$id=$this->educations->createRecord($data);$action='CREATE';}else{if(!$before)throw new \InvalidArgumentException('교육 이력을 찾을 수 없습니다.');$this->educations->updateRecord($id,$data);$action='UPDATE';}$after=$this->educations->detail($id);$this->educations->audit($this->audit($id,$employee,$action,$request,$before,$after,$actor,(string)($input['reason']??'교육 이력 처리')));$this->db->commit();if($uploaded&&$before&&!empty($before['attachment_path'])&&$before['attachment_path']!==$uploaded['db_path'])$this->files->delete($before['attachment_path']);return ['success'=>true,'data'=>$after,'message'=>'저장되었습니다.'];}catch(\Throwable $e){$this->db->rollBack();if($uploaded)$this->files->delete($uploaded['db_path']);throw $e;}
 }
 public function deleteEducation(array $input): array{$id=$this->required($input,'id','교육 이력 ID');$request=$this->requestKey($input);if($target=$this->educations->auditTargetByRequest($request))return ['success'=>true,'id'=>$target];$before=$this->educations->detail($id);if(!$before)throw new \InvalidArgumentException('교육 이력을 찾을 수 없습니다.');$reason=$this->required($input,'reason','처리 사유');if($before['completion_status_code']==='COMPLETED')return $this->invalidateEducation(['id'=>$id,'request_key'=>$request,'reason'=>$reason]);$actor=ActorHelper::user();$this->db->beginTransaction();try{$this->educations->deleteRecord($id,$actor);$this->educations->audit($this->audit($id,$before['employee_id'],'DELETE',$request,$before,null,$actor,$reason));$this->db->commit();$this->logger->info('교육 이력 삭제를 완료했습니다.',['event_code'=>'EDUCATION_RECORD_DELETE','result'=>'SUCCESS']);return ['success'=>true,'id'=>$id,'message'=>'삭제되었습니다.'];}catch(\Throwable $e){$this->db->rollBack();$this->logOperationException($e);throw $e;}}
 public function invalidateEducation(array $input): array{$id=$this->required($input,'id','교육 이력 ID');$before=$this->educations->detail($id);if(!$before)throw new \InvalidArgumentException('교육 이력을 찾을 수 없습니다.');$reason=$this->required($input,'reason','무효화 사유');$note=trim((string)($before['note']??''));$note=($note!==''?$note."\n":'').'[무효화] '.$reason;return $this->saveEducation(array_merge($before,['id'=>$id,'completion_status_code'=>'INVALIDATED','note'=>$note,'request_key'=>$this->requestKey($input),'reason'=>$reason]));}
 public function saveCourse(array $input): array{$id=trim((string)($input['id']??''));$before=$id!==''?$this->policies->course($id):null;$actor=ActorHelper::user();$now=date('Y-m-d H:i:s');$policy=$this->recurrence($input);$data=['course_code'=>strtoupper($this->required($input,'course_code','과정 코드')),'course_name'=>$this->required($input,'course_name','과정명'),'education_type_code'=>$this->code($input,'education_type_code','EDUCATION_TYPE','교육 종류'),'default_institution_name'=>$this->nullable($input,'default_institution_name'),'default_minutes'=>max(0,(int)($input['default_minutes']??0)),'validity_months'=>null]+$policy+['is_statutory'=>$policy['recurrence_policy_code']==='STATUTORY'?1:$this->flag($input,'is_statutory'),'is_mandatory'=>$this->flag($input,'is_mandatory'),'requires_certificate'=>$this->flag($input,'requires_certificate'),'description'=>$this->nullable($input,'description'),'is_active'=>$this->flag($input,'is_active',1),'updated_at'=>$now,'updated_by'=>$actor];$request=$this->requestKey($input);$this->db->beginTransaction();try{if($id===''){$data['sort_no']=count($this->policies->courses(false))+1;$data['request_key']=$request;$data['created_at']=$now;$data['created_by']=$actor;$id=$this->educations->createCourse($data);$action='CREATE';}else{$this->educations->updateCourse($id,$data);$action='UPDATE';}$after=$this->policies->course($id);$this->policyAudit('EDUCATION_COURSE',$id,$action,$request,$before,$after,$actor,$input['reason']??'교육과정 정책 저장');$this->db->commit();return ['success'=>true,'data'=>$after,'message'=>'저장되었습니다.'];}catch(\Throwable $e){$this->db->rollBack();throw $e;}}
 public function qualificationTypeList(): array{return ['success'=>true,'data'=>$this->policies->qualificationTypes(false)];}
 public function courseList(): array{return ['success'=>true,'data'=>$this->policies->courses(false)];}
 public function requirementList(string $kind,array $query): array{return ['success'=>true,'data'=>$this->policies->requirements($kind,$this->nullable($query,'job_id'))];}
 public function employeeCompliance(string $employeeId,?string $asOfDate=null): array{return ['success'=>true,'data'=>$this->policies->employeeCompliance($employeeId,$asOfDate?:date('Y-m-d'))];}
 public function saveQualificationType(array $input): array{$id=trim((string)($input['id']??''));$before=$id!==''?$this->policies->qualificationType($id):null;$actor=ActorHelper::user();$now=date('Y-m-d H:i:s');$policy=$this->required($input,'validity_policy_code','유효기간 정책');$value=$this->nullableInt($input,'validity_value');$unit=$this->nullable($input,'validity_unit_code');if(!in_array($policy,['PERMANENT','FIXED_PERIOD','RECORD_SPECIFIC'],true))throw new \InvalidArgumentException('유효기간 정책이 올바르지 않습니다.');if($policy==='FIXED_PERIOD'&&(!$value||!in_array($unit,['DAY','MONTH','YEAR'],true)))throw new \InvalidArgumentException('고정 유효기간 값과 단위를 입력해 주세요.');if($policy!=='FIXED_PERIOD'){$value=null;$unit=null;}$renewal=$this->required($input,'renewal_policy_code','갱신 정책');if(!in_array($renewal,['NONE','RENEWAL','CONTINUING_EDUCATION'],true))throw new \InvalidArgumentException('갱신 정책이 올바르지 않습니다.');$request=$this->requestKey($input);$data=['qualification_code'=>strtoupper($this->required($input,'qualification_code','자격 코드')),'qualification_name'=>$this->required($input,'qualification_name','자격명'),'category_code'=>$this->code($input,'category_code','QUALIFICATION_TYPE','자격 분류'),'default_issuer_name'=>$this->nullable($input,'default_issuer_name'),'validity_policy_code'=>$policy,'validity_value'=>$value,'validity_unit_code'=>$unit,'renewal_policy_code'=>$renewal,'is_active'=>$this->flag($input,'is_active',1),'note'=>$this->nullable($input,'note'),'updated_at'=>$now,'updated_by'=>$actor];$this->db->beginTransaction();try{if($id===''){$data+=['sort_no'=>count($this->policies->qualificationTypes(false))+1,'request_key'=>$request,'created_at'=>$now,'created_by'=>$actor];}$id=$this->policies->save('institution_qualifications_types',$id,$data);$after=$this->policies->qualificationType($id);$this->policyAudit('QUALIFICATION_TYPE',$id,$before?'UPDATE':'CREATE',$request,$before,$after,$actor,$input['reason']??'자격 기준 저장');$this->db->commit();return ['success'=>true,'data'=>$after,'message'=>'자격 기준을 저장했습니다.'];}catch(\Throwable $e){$this->db->rollBack();throw $e;}}
 public function saveRequirement(string $kind,array $input): array{$id=trim((string)($input['id']??''));$before=$id!==''?$this->policies->requirement($kind,$id):null;$job=$this->required($input,'job_id','직무');$targetField=$kind==='qualification'?'qualification_type_id':'course_id';$target=$this->required($input,$targetField,$kind==='qualification'?'자격 기준':'교육과정');$level=$this->required($input,'requirement_level_code','요구수준');if(!in_array($level,['REQUIRED','PREFERRED'],true))throw new \InvalidArgumentException('요구수준이 올바르지 않습니다.');$from=$this->dateRequired($input,'effective_from','적용시작일');$to=$this->date($input,'effective_to');$this->dateOrder($from,$to);$actor=ActorHelper::user();$request=$this->requestKey($input);$table=$kind==='qualification'?'institution_qualifications_job_requirements':'institution_educations_job_requirements';$domain=$kind==='qualification'?'JOB_QUALIFICATION_REQUIREMENT':'JOB_EDUCATION_REQUIREMENT';$now=date('Y-m-d H:i:s');$data=['job_id'=>$job,$targetField=>$target,'requirement_level_code'=>$level,'effective_from'=>$from,'effective_to'=>$to,'note'=>$this->nullable($input,'note'),'updated_at'=>$now,'updated_by'=>$actor];$this->db->beginTransaction();try{$this->policies->assertNoOverlap($kind,$job,$target,$from,$to,$id);if($id==='')$data+=['request_key'=>$request,'created_at'=>$now,'created_by'=>$actor];$id=$this->policies->save($table,$id,$data);$after=$this->policies->requirement($kind,$id);$this->policyAudit($domain,$id,$before?'UPDATE':'CREATE',$request,$before,$after,$actor,$input['reason']??'직무 요구조건 저장');$this->db->commit();return ['success'=>true,'data'=>$after,'message'=>'직무 요구조건을 저장했습니다.'];}catch(\Throwable $e){$this->db->rollBack();throw $e;}}
 public function reorderPolicy(string $kind,array $input): array{$changes=is_array($input['changes']??null)?$input['changes']:[];if($changes!==[]){$first=is_array($changes[0]??null)?$changes[0]:[];$kind=(string)($first['kind']??$kind);$input['ids']=array_values(array_filter(array_map(static fn($row)=>is_array($row)?($row['id']??null):null,$changes)));$input['request_key']=$first['request_key']??($input['request_key']??null);$input['reason']=$first['reason']??($input['reason']??null);}$table=match($kind){'qualification'=>'institution_qualifications_types','education'=>'institution_educations_courses',default=>throw new \InvalidArgumentException('순서변경 대상이 올바르지 않습니다.')};$ids=$input['ids']??[];if(!is_array($ids)||$ids===[])throw new \InvalidArgumentException('순서변경 대상을 선택해 주세요.');$actor=ActorHelper::user();$request=$this->requestKey($input);$this->db->beginTransaction();try{$this->policies->reorder($table,$ids,$actor);$this->policyAudit($kind==='qualification'?'QUALIFICATION_TYPE':'EDUCATION_COURSE',(string)$ids[0],'REORDER',$request,null,['ids'=>array_values($ids)],$actor,$input['reason']??'표시순서 변경');$this->db->commit();return ['success'=>true,'message'=>'순서를 저장했습니다.'];}catch(\Throwable $e){$this->db->rollBack();throw $e;}}
 public function employeeIdForUser(string $id): string{$employee=$this->qualifications->employeeIdForUser($id);if($employee==='')throw new \RuntimeException('연결된 직원 정보를 찾을 수 없습니다.');return $employee;}
 private function recurrence(array $input): array{$policy=$this->required($input,'recurrence_policy_code','재교육 정책');if(!in_array($policy,['NONE','PERIODIC','EVENT','STATUTORY'],true))throw new \InvalidArgumentException('재교육 정책이 올바르지 않습니다.');$value=$this->nullableInt($input,'recurrence_interval_value');$unit=$this->nullable($input,'recurrence_interval_unit_code');$event=$this->nullable($input,'recurrence_event_code');$statutory=$this->nullable($input,'statutory_standard_type_code');if($policy==='PERIODIC'&&(!$value||!in_array($unit,['DAY','MONTH','YEAR'],true)))throw new \InvalidArgumentException('재교육 주기 값과 단위를 입력해 주세요.');if($policy==='EVENT'&&!in_array($event,['HIRE','JOB_ASSIGNMENT','SITE_ASSIGNMENT','WORK_TYPE_CHANGE'],true))throw new \InvalidArgumentException('재교육 발생 이벤트를 선택해 주세요.');if($policy==='STATUTORY'&&(!$statutory||!$this->policies->statutoryTypeExists($statutory)))throw new \InvalidArgumentException('유효한 법정기준 유형이 필요합니다.');return ['recurrence_policy_code'=>$policy,'recurrence_interval_value'=>$policy==='PERIODIC'?$value:null,'recurrence_interval_unit_code'=>$policy==='PERIODIC'?$unit:null,'recurrence_event_code'=>$policy==='EVENT'?$event:null,'statutory_standard_type_code'=>$policy==='STATUTORY'?$statutory:null];}
 private function policyAudit(string $domain,string $target,string $action,string $request,?array $before,?array $after,string $actor,string $reason): void{$this->policies->audit(['policy_domain_code'=>$domain,'target_id'=>$target,'action_type_code'=>$action,'source_type_code'=>'ADMIN','reason'=>trim($reason)!==''?trim($reason):'정책 처리','request_key'=>$request,'before_data'=>$before?json_encode($before,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES):null,'after_data'=>$after?json_encode($after,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES):null,'processed_by'=>$actor,'processed_at'=>date('Y-m-d H:i:s')]);$this->logger->info('자격·교육 정책 업무 처리를 완료했습니다.',['event_code'=>'QUALIFICATION_EDUCATION_'.$action,'result'=>'SUCCESS','policy_domain'=>$domain,'target_id'=>$target,'actor'=>$actor]);}
 private function logOperationException(\Throwable $exception): void{$failed=$exception instanceof \PDOException;$level=$failed?'error':'warning';$this->logger->{$level}($failed?'자격·교육 업무 처리에 실패했습니다.':'자격·교육 업무 처리가 차단되었습니다.',['event_code'=>$failed?'QUALIFICATION_EDUCATION_FAILED':'QUALIFICATION_EDUCATION_BLOCKED','result'=>$failed?'FAILED':'BLOCKED','error_code'=>get_class($exception),'error'=>$exception]);}
 private function audit(string $target,?string $employee,string $action,string $request,?array $before,?array $after,string $actor,string $reason): array{return ['target_id'=>$target,'employee_id'=>$employee,'action_type_code'=>$action,'source_type_code'=>'ADMIN','reason'=>trim($reason)!==''?trim($reason):'관리자 처리','request_key'=>$request,'before_data'=>$before?json_encode($before,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES):null,'after_data'=>$after?json_encode($after,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES):null,'processed_by'=>$actor,'processed_at'=>date('Y-m-d H:i:s')];}
 private function upload(?array $file,string $policy): ?array{if(!$file||($file['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)return null;$r=$this->files->uploadByPolicyKey($file,$policy);if(empty($r['success']))throw new \InvalidArgumentException($r['message']??'파일 업로드 중 오류가 발생했습니다.');return $r;}
 private function assertScoped(?array $row,?string $scope): void{if(!$row)throw new \InvalidArgumentException('정보를 찾을 수 없습니다.');if($scope!==null&&($row['employee_id']??'')!==$scope)throw new \RuntimeException('다른 직원의 정보를 조회할 수 없습니다.');}
 private function code(array $in,string $field,string $group,string $label): string{$v=$this->required($in,$field,$label);if(!$this->references->codeExists($group,$v))throw new \InvalidArgumentException($label.' 값이 올바르지 않습니다.');return $v;}
 private function requestKey(array $in): string{$v=trim((string)($in['request_key']??''));if($v==='')throw new \InvalidArgumentException('request_key가 필요합니다.');return $v;}
 private function required(array $in,string $key,string $label): string{$v=trim((string)($in[$key]??''));if($v==='')throw new \InvalidArgumentException($label.'을(를) 입력해 주세요.');return $v;}
 private function nullable(array $in,string $key): ?string{$v=trim((string)($in[$key]??''));return $v===''?null:$v;}
 private function nullableInt(array $in,string $key): ?int{$v=$this->nullable($in,$key);return $v===null?null:max(0,(int)$v);}
 private function date(array $in,string $key): ?string{$v=$this->nullable($in,$key);if($v===null)return null;$d=\DateTimeImmutable::createFromFormat('Y-m-d',$v);if(!$d||$d->format('Y-m-d')!==$v)throw new \InvalidArgumentException($key.' 날짜 형식이 올바르지 않습니다.');return $v;}
 private function dateRequired(array $in,string $key,string $label): string{$v=$this->date($in,$key);if($v===null)throw new \InvalidArgumentException($label.'을(를) 입력해 주세요.');return $v;}
 private function datetime(array $in,string $key,string $label): string{$v=$this->required($in,$key,$label);$v=str_replace('T',' ',$v);if(strlen($v)===16)$v.=':00';if(!strtotime($v))throw new \InvalidArgumentException($label.' 형식이 올바르지 않습니다.');return $v;}
 private function dateOrder(?string $from,?string $to): void{if($from&&$to&&$to<$from)throw new \InvalidArgumentException('종료일은 시작일보다 빠를 수 없습니다.');}
 private function flag(array $in,string $key,int $default=0): int{return array_key_exists($key,$in)?(in_array($in[$key],[1,'1',true,'on'],true)?1:0):$default;}
}
