<?php

namespace App\Services\Institution;

use App\Models\Institution\RegularEmploymentIncomeModel;
use App\Models\Institution\EmploymentContractModel;
use App\Models\Ledger\EvidenceLinkModel;
use App\Models\Ledger\SalaryReportEvidenceModel;
use App\Services\Approval\ApprovalWorkflowService;
use App\Services\Ledger\EvidenceExternalKeyService;
use App\Services\Ledger\TransactionCrudService;
use Core\Helpers\ActorHelper;
use Core\Helpers\UuidHelper;
use PDO;

class RegularEmploymentIncomeService
{
    public const DOCUMENT_TYPE='REGULAR_EMPLOYMENT_INCOME';
    public const IMPORT_TYPE='PAYROLL_REPORT';
    private RegularEmploymentIncomeModel $model;private EmploymentContractValidityService $contracts;
    public function __construct(private readonly PDO $db){$this->model=new RegularEmploymentIncomeModel($db);$this->contracts=new EmploymentContractValidityService(new EmploymentContractModel($db));}
    public function page(array$q):array{$p=$this->model->page($q);return ['success'=>true,'data'=>$p['rows'],'draw'=>(int)($q['draw']??0),'recordsTotal'=>$p['total'],'recordsFiltered'=>$p['filtered']];}
    public function detail(string$id):array{$h=$this->model->find($id);if(!$h)throw new \RuntimeException('상용근로소득 문서를 찾을 수 없습니다.');return['success'=>true,'data'=>['header'=>$h,'items'=>$this->model->items($id)]];}
    private function eligibleRows(string $month): array{$from=$month.'-01';$to=date('Y-m-t',strtotime($from));$contracts=$this->contracts->effectiveContractsForPeriod($from,$to);$byEmployee=[];foreach($contracts as$contract){$employee=(string)$contract['employee_id'];if(isset($byEmployee[$employee]))throw new \RuntimeException('귀속월에 유효한 근로계약이 중복된 직원이 있습니다.');$byEmployee[$employee]=(string)$contract['id'];}return$this->model->eligibleEmployees($month,array_values($byEmployee));}
    public function eligibleEmployees(string$month):array{if(!preg_match('/^\d{4}-\d{2}$/',$month))throw new \InvalidArgumentException('귀속연월을 확인해 주세요.');return['success'=>true,'data'=>$this->eligibleRows($month)];}
    public function save(array$input):array{return$this->transaction(function()use($input){$id=trim((string)($input['id']??''));$month=trim((string)($input['income_year_month']??''));$payment=trim((string)($input['payment_date']??''));$title=trim((string)($input['title']??''));if(!preg_match('/^\d{4}-\d{2}$/',$month))throw new \InvalidArgumentException('귀속연월을 입력해 주세요.');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$payment))throw new \InvalidArgumentException('지급일을 입력해 주세요.');if($title==='')throw new \InvalidArgumentException('제목을 입력해 주세요.');$items=$input['items']??[];if(is_string($items))$items=json_decode($items,true);if(!is_array($items)||$items===[])throw new \InvalidArgumentException('직원별 소득내역을 한 건 이상 입력해 주세요.');$actor=ActorHelper::user();$existing=$id!==''?$this->model->find($id,true):null;if($id!==''&&!$existing)throw new \RuntimeException('수정할 문서를 찾을 수 없습니다.');if($existing&&!in_array($existing['document_status'],['DRAFT','REJECTED','WITHDRAWN'],true))throw new \RuntimeException('현재 상태에서는 수정할 수 없습니다.');if($id===''){$id=UuidHelper::generate();$this->model->insertHeader(['id'=>$id,'sort_no'=>$this->model->nextSortNo(),'income_year_month'=>$month,'payment_date'=>$payment,'title'=>$title,'description'=>$input['description']??null,'memo'=>$input['memo']??null,'created_by'=>$actor,'updated_by'=>$actor]);}else{$this->model->updateHeader($id,['income_year_month'=>$month,'payment_date'=>$payment,'title'=>$title,'description'=>$input['description']??null,'memo'=>$input['memo']??null,'updated_at'=>date('Y-m-d H:i:s'),'updated_by'=>$actor]);}
        $eligible=[];foreach($this->eligibleRows($month)as$e)$eligible[$e['employee_id']]=$e;$rows=[];$totals=array_fill_keys(['gross_amount','taxable_amount','non_taxable_amount','income_tax_amount','local_income_tax_amount','national_pension_amount','health_insurance_amount','long_term_care_amount','employment_insurance_amount','other_deduction_amount','deduction_amount','net_payment_amount'],0.0);$seen=[];
        foreach(array_values($items)as$i=>$item){$employeeId=trim((string)($item['employee_id']??''));if(!isset($eligible[$employeeId]))throw new \InvalidArgumentException('귀속월에 유효한 근로계약이 없는 직원이 포함되어 있습니다.');if(isset($seen[$employeeId]))throw new \InvalidArgumentException('동일 직원은 한 번만 등록할 수 있습니다.');$seen[$employeeId]=true;$base=$this->amount($item,'base_salary_amount');$allow=$this->amount($item,'allowance_amount');$bonus=$this->amount($item,'bonus_amount');$nonTax=$this->amount($item,'non_taxable_amount');$gross=round($base+$allow+$bonus+$nonTax,2);$taxable=round($base+$allow+$bonus,2);$deductKeys=['national_pension_amount','health_insurance_amount','long_term_care_amount','employment_insurance_amount','income_tax_amount','local_income_tax_amount','other_deduction_amount'];$deduction=0.0;foreach($deductKeys as$k)$deduction+=$this->amount($item,$k);$deduction=round($deduction,2);$net=round($gross-$deduction,2);if($net<0)throw new \InvalidArgumentException('실지급액은 0원보다 작을 수 없습니다.');$e=$eligible[$employeeId];$row=['id'=>UuidHelper::generate(),'sort_no'=>$i+1,'regular_employment_income_id'=>$id,'employee_id'=>$employeeId,'employee_name_snapshot'=>$e['employee_name'],'employee_identifier_snapshot'=>$e['employee_identifier_snapshot']?:null,'department_name_snapshot'=>$e['department_name']?:null,'position_name_snapshot'=>$e['position_name']?:null,'employment_contract_id'=>$e['employment_contract_id'],'base_salary_amount'=>$base,'allowance_amount'=>$allow,'bonus_amount'=>$bonus,'non_taxable_amount'=>$nonTax,'gross_amount'=>$gross,'taxable_amount'=>$taxable,'national_pension_amount'=>$this->amount($item,'national_pension_amount'),'health_insurance_amount'=>$this->amount($item,'health_insurance_amount'),'long_term_care_amount'=>$this->amount($item,'long_term_care_amount'),'employment_insurance_amount'=>$this->amount($item,'employment_insurance_amount'),'income_tax_amount'=>$this->amount($item,'income_tax_amount'),'local_income_tax_amount'=>$this->amount($item,'local_income_tax_amount'),'other_deduction_amount'=>$this->amount($item,'other_deduction_amount'),'deduction_amount'=>$deduction,'net_payment_amount'=>$net,'description'=>$item['description']??null,'memo'=>$item['memo']??null,'created_by'=>$actor,'updated_by'=>$actor];$rows[]=$row;foreach(array_keys($totals)as$k)$totals[$k]+=((float)$row[$k]);}
        $this->model->replaceItems($id,$rows);$update=['employee_count'=>count($rows)]+array_map(fn($v)=>round($v,2),$totals);$update['updated_at']=date('Y-m-d H:i:s');$update['updated_by']=$actor;$this->model->updateHeader($id,$update);return['success'=>true,'data'=>['id'=>$id],'message'=>'저장했습니다.'];});}
    public function submit(string$id):array{return$this->transaction(function()use($id){$header=$this->assertSubmittable($id);[$userId,$actor]=$this->identity();$result=(new ApprovalWorkflowService($this->db))->submit(self::DOCUMENT_TYPE,$id,$userId,$actor);$this->model->updateWorkflow($id,'PENDING',$result['request_id'],$actor);return['success'=>true,'data'=>$result,'message'=>'결재를 요청했습니다.'];});}
    public function withdraw(string$requestId):array{return$this->transaction(function()use($requestId){[$userId,$actor]=$this->identity();$request=(new ApprovalWorkflowService($this->db))->withdraw($requestId,self::DOCUMENT_TYPE,$userId,$actor);$this->model->updateWorkflow((string)$request['document_id'],'WITHDRAWN',$requestId,$actor);return['success'=>true,'message'=>'기안을 회수했습니다.'];});}
    public function act(string$stepId,string$decision,?string$comment):array{return$this->transaction(function()use($stepId,$decision,$comment){[$userId,$actor]=$this->identity();$result=(new ApprovalWorkflowService($this->db))->act($stepId,self::DOCUMENT_TYPE,$decision,$comment,$userId,$actor);$id=(string)$result['request']['document_id'];if($result['state']==='APPROVED'){$accounting=$this->finalize($id,$actor);$this->model->updateWorkflow($id,'APPROVED',(string)$result['request']['id'],$actor);return['success'=>true,'data'=>$accounting,'message'=>'최종 승인과 회계처리를 완료했습니다.'];}$this->model->updateWorkflow($id,$result['state'],(string)$result['request']['id'],$actor);return['success'=>true,'message'=>$result['state']==='REJECTED'?'반려했습니다.':'승인했습니다.'];});}
    public function approvalDetail(array$request):array{$d=$this->detail((string)$request['document_id'])['data'];return['type'=>self::DOCUMENT_TYPE,'type_name'=>'상용근로소득','header'=>array_merge($request,$d['header']), 'items'=>$d['items'],'totals'=>['total_amount'=>$d['header']['gross_amount'],'deduction_amount'=>$d['header']['deduction_amount'],'net_payment_amount'=>$d['header']['net_payment_amount']],'detail_supported'=>true];}
    public function delete(string$id):array{$this->model->softDelete($id,ActorHelper::user());return['success'=>true,'message'=>'삭제했습니다.'];}
    private function assertSubmittable(string$id):array{$h=$this->model->find($id,true);if(!$h||!in_array($h['document_status'],['DRAFT','REJECTED','WITHDRAWN'],true))throw new \RuntimeException('결재요청할 수 있는 문서가 아닙니다.');if($this->model->items($id,true)===[])throw new \RuntimeException('직원별 소득내역이 없습니다.');return$h;}
    private function finalize(string$id,string$actor):array{$h=$this->model->find($id,true);if(!$h)throw new \RuntimeException('승인 원본을 찾을 수 없습니다.');$evidenceModel=new SalaryReportEvidenceModel($this->db);$e=$evidenceModel->findBySource($id,true);if(!$e){$eid=UuidHelper::generate();$evidenceModel->insert(['id'=>$eid,'sort_no'=>$evidenceModel->nextSortNo(),'external_key'=>(new EvidenceExternalKeyService())->key(['source_regular_employment_income_id'=>$id],self::IMPORT_TYPE),'source_type'=>'APPROVAL','import_type'=>self::IMPORT_TYPE,'source_regular_employment_income_id'=>$id,'business_unit'=>'HQ','transaction_direction'=>'EXPENSE','operation_type'=>'PAYROLL','raw_income_year_month'=>$h['income_year_month'],'raw_payment_date'=>$h['payment_date'],'raw_employee_count'=>$h['employee_count'],'raw_gross_amount'=>$h['gross_amount'],'raw_taxable_amount'=>$h['taxable_amount'],'raw_non_taxable_amount'=>$h['non_taxable_amount'],'raw_income_tax_amount'=>$h['income_tax_amount'],'raw_local_income_tax_amount'=>$h['local_income_tax_amount'],'raw_national_pension_amount'=>$h['national_pension_amount'],'raw_health_insurance_amount'=>$h['health_insurance_amount'],'raw_long_term_care_amount'=>$h['long_term_care_amount'],'raw_employment_insurance_amount'=>$h['employment_insurance_amount'],'raw_other_deduction_amount'=>$h['other_deduction_amount'],'raw_deduction_amount'=>$h['deduction_amount'],'raw_net_payment_amount'=>$h['net_payment_amount'],'raw_description'=>$h['description'],'evidence_status'=>'READY','created_by'=>$actor,'updated_by'=>$actor]);}else$eid=(string)$e['id'];$links=(new EvidenceLinkModel($this->db))->activeTransactionsForEvidence(self::IMPORT_TYPE,$eid,true);if(count($links)>1)throw new \RuntimeException('급여 증빙이 여러 활성 거래에 연결되어 있습니다.');if($links)return['evidence_id'=>$eid,'transaction_id'=>(string)$links[0]['transaction_id'],'duplicate_prevented'=>true];$tx=(new TransactionCrudService($this->db))->save(['business_unit'=>'HQ','transaction_direction'=>'EXPENSE','operation_type'=>'PAYROLL','transaction_date'=>$h['payment_date'],'transaction_supply_amount'=>$h['gross_amount'],'transaction_final_amount'=>$h['gross_amount'],'transaction_description'=>$h['title'],'transaction_note'=>$h['description'],'status'=>'completed','items'=>[['item_date'=>$h['payment_date'],'item_name'=>$h['title'],'item_quantity'=>1,'item_unit_name'=>'월','item_unit_price'=>$h['gross_amount'],'item_supply_amount'=>$h['gross_amount'],'item_description'=>$h['income_year_month'].' 귀속 상용근로소득']],'settlements'=>[],'linked_evidences'=>[['import_type'=>self::IMPORT_TYPE,'evidence_id'=>$eid]]]);if(empty($tx['success']))throw new \RuntimeException('급여 거래 생성에 실패했습니다.');return['evidence_id'=>$eid,'transaction_id'=>$tx['id'],'duplicate_prevented'=>false];}
    private function amount(array$row,string$key):float{$v=(float)str_replace(',','',(string)($row[$key]??0));if($v<0)throw new \InvalidArgumentException('금액은 0원 이상이어야 합니다.');return round($v,2);}
    private function identity():array{$p=ActorHelper::parse(ActorHelper::user());$id=trim((string)($p['id']??''));if($id==='')throw new \RuntimeException('로그인 사용자 정보를 확인할 수 없습니다.');return[$id,ActorHelper::user()];}
    private function transaction(callable$fn):array{$outer=$this->db->inTransaction();if(!$outer)$this->db->beginTransaction();try{$r=$fn();if(!$outer)$this->db->commit();return$r;}catch(\Throwable$e){if(!$outer&&$this->db->inTransaction())$this->db->rollBack();throw$e;}}
}
