<?php

namespace App\Services\Institution;

use App\Models\Institution\SocialInsuranceAssessmentBasisModel;
use App\Models\Institution\SocialInsuranceAuditModel;
use App\Models\Institution\SocialInsuranceCoverageModel;
use Core\Helpers\ActorHelper;
use Core\Helpers\UuidHelper;
use Core\LoggerFactory;
use PDO;
use Psr\Log\LoggerInterface;

class SocialInsuranceService
{
    private SocialInsuranceCoverageModel $coverages;private SocialInsuranceAssessmentBasisModel $bases;private SocialInsuranceAuditModel $audits;private LoggerInterface $logger;
    public function __construct(private readonly PDO$db){$this->coverages=new SocialInsuranceCoverageModel($db);$this->bases=new SocialInsuranceAssessmentBasisModel($db);$this->audits=new SocialInsuranceAuditModel($db);$this->logger=LoggerFactory::getLogger('service-institution-social-insurance');}
    public function currentSummary(string$employeeId,?string$date=null):array{$date=$date?:date('Y-m-d');$rows=$this->coverages->batch([$employeeId],$date,$date);$summary=['NATIONAL_PENSION'=>'UNCONFIRMED','HEALTH_INSURANCE'=>'UNCONFIRMED','LONG_TERM_CARE'=>'UNCONFIRMED','EMPLOYMENT_INSURANCE'=>'UNCONFIRMED'];foreach($rows as$row){if(!$row['confirmed_at'])continue;$summary[$row['insurance_type_code']]=$row['coverage_status_code'];}if($summary['LONG_TERM_CARE']==='UNCONFIRMED'&&$summary['HEALTH_INSURANCE']==='ACQUIRED')$summary['LONG_TERM_CARE']='DERIVED_ACQUIRED';return['statuses'=>$summary];}
    public function saveCoverage(array$input):array{return$this->transaction(function()use($input){$id=trim((string)($input['id']??''));$employee=trim((string)($input['employee_id']??''));$type=trim((string)($input['insurance_type_code']??''));$status=trim((string)($input['coverage_status_code']??''));$from=$this->date($input['effective_from']??null,'적용 시작일');$to=$this->nullableDate($input['effective_to']??null);$source=trim((string)($input['source_type_code']??'MANUAL_CONFIRMED'));$confirmed=$this->nullableDateTime($input['confirmed_at']??null);$reason=trim((string)($input['reason']??$input['exclusion_reason']??''));
      if(!in_array($type,['NATIONAL_PENSION','HEALTH_INSURANCE','LONG_TERM_CARE','EMPLOYMENT_INSURANCE'],true))throw new \InvalidArgumentException('보험종류를 확인해 주세요.');if(!in_array($status,['ACQUIRED','EXCLUDED'],true))throw new \InvalidArgumentException('적용상태를 확인해 주세요.');if($to&&$to<$from)throw new \InvalidArgumentException('적용 종료일은 시작일보다 빠를 수 없습니다.');if($status==='EXCLUDED'&&trim((string)($input['exclusion_reason_code']??''))===''&&$reason==='')throw new \InvalidArgumentException('적용제외 근거를 입력해 주세요.');if($source==='HISTORICAL_IMPORT'&&$reason==='')throw new \InvalidArgumentException('과거자료 근거 설명을 입력해 주세요.');
      $this->coverages->employeeLock($employee);$before=$id!==''?$this->coverages->find($id,true):null;if($id!==''&&!$before)throw new \RuntimeException('수정할 Coverage를 찾을 수 없습니다.');if($id!==''&&$before['employee_id']!==$employee)throw new \InvalidArgumentException('Coverage의 직원을 변경할 수 없습니다.');if($this->coverages->overlaps($employee,$type,$from,$to,$id?:null))throw new \InvalidArgumentException('동일 직원·보험종류의 적용기간이 겹칩니다.');if($type==='LONG_TERM_CARE'&&!$this->coverages->healthContains($employee,$from,$to))throw new \InvalidArgumentException('장기요양 예외기간은 확인된 건강보험 취득기간 안에 있어야 합니다.');
      $actor=ActorHelper::user();$request=trim((string)($input['request_key']??''))?:UuidHelper::generate();$data=['employee_id'=>$employee,'insurance_type_code'=>$type,'coverage_status_code'=>$status,'effective_from'=>$from,'effective_to'=>$to,'exclusion_reason_code'=>trim((string)($input['exclusion_reason_code']??''))?:null,'exclusion_reason'=>$reason?:null,'source_type_code'=>$source,'source_id'=>trim((string)($input['source_id']??''))?:null,'confirmed_at'=>$confirmed,'note'=>trim((string)($input['note']??''))?:null,'updated_at'=>date('Y-m-d H:i:s'),'updated_by'=>$actor];if(!$before){$id=UuidHelper::generate();$data=['id'=>$id,'request_key'=>$request,'created_by'=>$actor]+$data;$this->coverages->insert($data);}else$this->coverages->update($id,$data);$this->audit('COVERAGE',$id,$before?'UPDATE':'CREATE',$before,$data,$reason?:'사회보험 Coverage 등록',$actor,$request.':AUDIT');return['success'=>true,'data'=>['id'=>$id],'message'=>'사회보험 적용기간을 저장했습니다.'];});}
    public function saveBasis(array$input):array{return$this->transaction(function()use($input){$id=trim((string)($input['id']??''));$coverageId=trim((string)($input['coverage_id']??''));$coverage=$this->bases->coverageLock($coverageId);if(!$coverage)throw new \InvalidArgumentException('Coverage를 찾을 수 없습니다.');$type=trim((string)($input['basis_type_code']??''));$expected=['NATIONAL_PENSION'=>'STANDARD_MONTHLY_INCOME','HEALTH_INSURANCE'=>'MONTHLY_REMUNERATION','EMPLOYMENT_INSURANCE'=>'INSURABLE_REMUNERATION'];if(($expected[$coverage['insurance_type_code']]??null)!==$type)throw new \InvalidArgumentException('보험종류와 산정기준 유형이 일치하지 않습니다.');$from=$this->date($input['effective_from']??null,'기준 시작일');$to=$this->nullableDate($input['effective_to']??null);if($to&&$to<$from)throw new \InvalidArgumentException('기준 종료일은 시작일보다 빠를 수 없습니다.');if($from<$coverage['effective_from']||($coverage['effective_to']&&(!$to||$to>$coverage['effective_to'])))throw new \InvalidArgumentException('산정기준 기간은 Coverage 기간 안에 있어야 합니다.');$status=trim((string)($input['confirmation_status_code']??''));if(!in_array($status,['PROVISIONAL','CONFIRMED'],true))throw new \InvalidArgumentException('산정기준 확인상태를 확인해 주세요.');$amount=round((float)($input['basis_amount']??-1),2);if($amount<0)throw new \InvalidArgumentException('산정기준 금액을 확인해 주세요.');$before=$id!==''?$this->bases->find($id,true):null;if($this->bases->overlaps($coverageId,$type,$from,$to,$id?:null))throw new \InvalidArgumentException('동일 Coverage·산정기준 유형의 적용기간이 겹칩니다.');$actor=ActorHelper::user();$request=trim((string)($input['request_key']??''))?:UuidHelper::generate();$data=['coverage_id'=>$coverageId,'basis_type_code'=>$type,'effective_from'=>$from,'effective_to'=>$to,'basis_amount'=>$amount,'confirmation_status_code'=>$status,'source_type_code'=>trim((string)($input['source_type_code']??'MANUAL_CONFIRMED')),'source_id'=>trim((string)($input['source_id']??''))?:null,'confirmed_at'=>$status==='CONFIRMED'?($this->nullableDateTime($input['confirmed_at']??null)?:date('Y-m-d H:i:s')):null,'note'=>trim((string)($input['note']??''))?:null,'updated_at'=>date('Y-m-d H:i:s'),'updated_by'=>$actor];if(!$before){$id=UuidHelper::generate();$data=['id'=>$id,'request_key'=>$request,'created_by'=>$actor]+$data;$this->bases->insert($data);}else$this->bases->update($id,$data);$this->audit('ASSESSMENT_BASIS',$id,$before?'UPDATE':'CREATE',$before,$data,trim((string)($input['reason']??''))?:'사회보험 산정기준 저장',$actor,$request.':AUDIT');return['success'=>true,'data'=>['id'=>$id],'message'=>'사회보험 산정기준을 저장했습니다.'];});}
    public function batchForMonth(array$employeeIds,string$month):array{$from=$month.'-01';$to=date('Y-m-t',strtotime($from));$rows=$this->coverages->batch($employeeIds,$from,$to);$ids=array_column($rows,'id');return['coverages'=>$rows,'bases'=>$this->bases->batch($ids,$from,$to)];}
    private function audit(string$t,string$id,string$a,?array$b,array$n,string$r,string$actor,string$key):void{$this->audits->insert(['id'=>UuidHelper::generate(),'target_type_code'=>$t,'target_id'=>$id,'action_type_code'=>$a,'before_data'=>$b?json_encode($b,JSON_UNESCAPED_UNICODE):null,'after_data'=>json_encode($n,JSON_UNESCAPED_UNICODE),'reason'=>$r,'request_key'=>$key,'processed_by'=>$actor]);}
    private function transaction(callable$f):array{try{$this->db->beginTransaction();$r=$f();$this->db->commit();$this->logger->info('사회보험 정보가 저장되었습니다.',['event_code'=>'SOCIAL_INSURANCE_SAVED','result'=>'SUCCESS','service'=>self::class,'action'=>'save','actor'=>ActorHelper::user()]);return$r;}catch(\InvalidArgumentException|\DomainException$e){if($this->db->inTransaction())$this->db->rollBack();$this->logger->warning('사회보험 정보 저장이 차단되었습니다.',['event_code'=>'SOCIAL_INSURANCE_SAVE_BLOCKED','result'=>'BLOCKED','service'=>self::class,'action'=>'save','actor'=>ActorHelper::user(),'error_code'=>get_class($e),'error'=>$e]);throw$e;}catch(\Throwable$e){if($this->db->inTransaction())$this->db->rollBack();$this->logger->error('사회보험 정보 저장에 실패했습니다.',['event_code'=>'SOCIAL_INSURANCE_SAVE_FAILED','result'=>'FAILED','service'=>self::class,'action'=>'save','actor'=>ActorHelper::user(),'error_code'=>get_class($e),'error'=>$e]);throw$e;}}
    private function date(mixed$v,string$l):string{$v=trim((string)$v);if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))throw new \InvalidArgumentException($l.'을 확인해 주세요.');return$v;}
    private function nullableDate(mixed$v):?string{$v=trim((string)$v);return$v===''?null:$this->date($v,'날짜');}
    private function nullableDateTime(mixed$v):?string{$v=trim((string)$v);if($v==='')return null;$t=strtotime($v);if($t===false)throw new \InvalidArgumentException('확인일시를 확인해 주세요.');return date('Y-m-d H:i:s',$t);}
}
