<?php
use Core\Helpers\AssetHelper;
$layoutOptions=['header'=>true,'navbar'=>true,'sidebar'=>true,'footer'=>true,'wrapper'=>'single'];$pageStyles=AssetHelper::css('/assets/css/pages/ledger/book/daily/index.css');$pageScripts=AssetHelper::module('/assets/js/pages/ledger/book/daily/index.js');
?>
<main class="ledger-daily-book" id="ledgerDailyBookPage"><div class="container-fluid py-4 dt-page-shell">
 <div class="page-header"><div><h5 class="mb-0 fw-bold"><i class="bi bi-calendar-check me-2"></i>일계표</h5><div class="text-muted small mt-1">날짜별 전표·분개 차대변 균형과 선택일의 계정별 증감을 조회합니다.</div></div><span id="ledgerDailyBookCount" class="text-primary page-count"></span></div>
 <?php $searchId='ledgerDailyBook';$dateOptions='<option value="voucher_date">전표일자</option>';$searchFieldOptions='<option value="">선택</option>';$periodGuideTitle='일계표 기간 조건 안내';$periodGuideItems=['전표일자를 기준으로 일별 차변·대변을 집계합니다.','공식 장부에는 전기완료·마감 전표만 포함됩니다.'];$searchGuideTitle='일계표 검색 조건 안내';$searchGuideItems=['전표번호, 계정코드, 계정과목, 적요 조건으로 일별 집계 범위를 좁힐 수 있습니다.','선택한 검색조건은 날짜별 집계와 계정별 상세에 동일하게 적용됩니다.'];include PROJECT_ROOT.'/app/views/components/ui-search.php';?>
 <section class="daily-scope-bar"><div><strong>공식 장부</strong><span>전기완료·마감 전표만 조회합니다.</span></div></section>
 <section class="daily-summary"><div><span>거래일수</span><strong id="dailyDayCount">0일</strong></div><div><span>전표</span><strong id="dailyVoucherCount">0건</strong></div><div><span>분개</span><strong id="dailyLineCount">0건</strong></div><div><span>차변합계</span><strong id="dailyDebitTotal">0원</strong></div><div><span>대변합계</span><strong id="dailyCreditTotal">0원</strong></div><div><span>차이</span><strong id="dailyDifference">0원</strong></div></section>
 <section class="daily-panel"><div class="daily-panel-title"><strong>날짜별 집계</strong><span>날짜를 클릭하면 계정별 상세가 표시됩니다.</span></div><?php $tableId='ledgerDailyBookTable';$ajaxUrl='/api/ledger/book/daily/list';$columnsType='ledger-daily-book';$tableClass='table table-bordered align-middle table-cross-highlight ledger-daily-book-table';$enableButtons=true;$enableSearch=true;$enablePaging=true;$enableReorder=false;include PROJECT_ROOT.'/app/views/components/ui-table.php';?></section>
 <section class="daily-panel daily-detail-panel"><div class="daily-panel-title"><div><strong id="dailyDetailTitle">선택일 계정별 증감</strong><span id="dailyDetailDescription">위 목록에서 날짜를 선택해 주세요.</span></div><span id="dailyDetailCount" class="text-primary"></span></div><?php $tableId='ledgerDailyDetailTable';$ajaxUrl='/api/ledger/book/daily/detail';$columnsType='ledger-daily-detail';$tableClass='table table-bordered align-middle table-cross-highlight ledger-daily-detail-table';$enableButtons=true;$enableSearch=false;$enablePaging=true;$enableReorder=false;include PROJECT_ROOT.'/app/views/components/ui-table.php';?></section>
 <div class="daily-help text-muted small"><i class="bi bi-info-circle me-1"></i>일계표는 조회·출력 전용이며 날짜별 차대변 차이가 발생하면 원전표를 확인해야 합니다.</div>
</div></main>
