<?php
namespace App\Services\Ledger;
use App\Models\Ledger\AssetModel;
use Core\Helpers\ActorHelper;
use Core\Helpers\UuidHelper;
use Core\LoggerFactory;
use PDO;

class AssetService
{
    private AssetModel $model; private VoucherService $vouchers; private $logger;
    public function __construct(private readonly PDO $pdo){$this->model=new AssetModel($pdo);$this->vouchers=new VoucherService($pdo);$this->logger=LoggerFactory::getLogger('service-ledger-asset');}
    public function list(array $f=[]):array{return ActorHelper::enrichActorNames($this->model->list($f),['created_by_name'=>'created_by','updated_by_name'=>'updated_by']);}
    public function detail(string $id):?array{$r=$this->model->find($id);if(!$r)return null;$r['accumulated_amount']=$this->model->depreciationTotal($id);$r['book_value_amount']=(float)$r['acquisition_amount']-$r['accumulated_amount'];$r['history']=$this->model->history($id);return ActorHelper::enrichActorNamesRow($r,['created_by_name'=>'created_by','updated_by_name'=>'updated_by']);}
    public function options():array{return $this->model->options()+['categories'=>[['id'=>'LAND','name'=>'토지'],['id'=>'BUILDING','name'=>'건물'],['id'=>'STRUCTURE','name'=>'구축물'],['id'=>'MACHINERY','name'=>'기계장치'],['id'=>'VEHICLE','name'=>'차량운반구'],['id'=>'TOOLS','name'=>'공구와기구'],['id'=>'EQUIPMENT','name'=>'비품'],['id'=>'SOFTWARE','name'=>'소프트웨어'],['id'=>'OTHER','name'=>'기타자산']]];}
    public function create(array $in,?string $actorOverride=null):array{$actor=$actorOverride?:ActorHelper::user();$owns=!$this->pdo->inTransaction();try{if($owns)$this->pdo->beginTransaction();$r=$this->normalizeAsset($in);if($this->model->duplicateNo($r[':company_id'],$r[':asset_no']))throw new \InvalidArgumentException('같은 회사에 동일한 자산번호가 있습니다.');$id=UuidHelper::generate();$now=date('Y-m-d H:i:s');$r+=[':id'=>$id,':asset_status_code'=>'ACTIVE',':acquisition_voucher_id'=>null,':created_at'=>$now,':created_by'=>$actor,':updated_at'=>$now,':updated_by'=>$actor];$this->model->insert($r);$refs=$this->refs($r);$voucher=$this->postVoucher($r[':acquisition_date'],'자산취득 '.$r[':asset_no'].' '.$r[':asset_name'],[['account_id'=>$r[':asset_account_id'],'debit'=>$r[':acquisition_amount'],'credit'=>0,'line_summary'=>'자산 취득','refs'=>$refs],['account_id'=>$r[':acquisition_counter_account_id'],'debit'=>0,'credit'=>$r[':acquisition_amount'],'line_summary'=>'자산 취득대금','refs'=>$refs]],$actor);$this->model->setVoucher($id,$voucher);$this->model->addAssignment([':id'=>UuidHelper::generate(),':asset_id'=>$id,':effective_date'=>$r[':service_start_date'],':business_unit'=>$r[':business_unit'],':project_id'=>$r[':project_id'],':work_team_id'=>$r[':work_team_id'],':employee_id'=>$r[':employee_id'],':location_name'=>$r[':location_name'],':reason'=>'최초 자산 배치',':created_at'=>$now,':created_by'=>$actor]);if($owns)$this->pdo->commit();$this->writeAudit('info','자산을 등록하고 취득 전표를 전기했습니다.','ASSET_CREATED',$id,$actor);return['success'=>true,'message'=>'자산 등록과 취득 전기가 완료되었습니다.','data'=>$this->detail($id)];}catch(\Throwable $e){if($owns&&$this->pdo->inTransaction())$this->pdo->rollBack();$this->writeAudit($e instanceof \InvalidArgumentException?'warning':'error','자산 등록을 완료하지 못했습니다.','ASSET_CREATE_FAILED','',$actor,$e);throw$e;}}
    public function transfer(array $in,?string $actorOverride=null):array{$actor=$actorOverride?:ActorHelper::user();$id=trim((string)($in['asset_id']??''));$asset=$this->active($id);$date=$this->date($in['effective_date']??'','이동 적용일');$reason=trim((string)($in['reason']??''));if($reason==='')throw new \InvalidArgumentException('자산이동 사유를 입력해 주세요.');$r=[':business_unit'=>trim((string)($in['business_unit']??$asset['business_unit'])),':project_id'=>$this->null($in['project_id']??null),':work_team_id'=>$this->null($in['work_team_id']??null),':employee_id'=>$this->null($in['employee_id']??null),':location_name'=>$this->null($in['location_name']??null),':updated_at'=>date('Y-m-d H:i:s'),':updated_by'=>$actor];$owns=!$this->pdo->inTransaction();if($owns)$this->pdo->beginTransaction();try{$this->model->updateAssignment($id,$r);$this->model->addAssignment([':id'=>UuidHelper::generate(),':asset_id'=>$id,':effective_date'=>$date,':business_unit'=>$r[':business_unit'],':project_id'=>$r[':project_id'],':work_team_id'=>$r[':work_team_id'],':employee_id'=>$r[':employee_id'],':location_name'=>$r[':location_name'],':reason'=>$reason,':created_at'=>$r[':updated_at'],':created_by'=>$actor]);if($owns)$this->pdo->commit();$this->writeAudit('info','자산 배치를 이동했습니다.','ASSET_TRANSFERRED',$id,$actor);return['success'=>true,'message'=>'자산이동을 기록했습니다.','data'=>$this->detail($id)];}catch(\Throwable$e){if($owns&&$this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
    public function depreciate(array $in,?string $actorOverride=null):array{$actor=$actorOverride?:ActorHelper::user();$id=trim((string)($in['asset_id']??''));$a=$this->active($id);$month=trim((string)($in['year_month']??''));if(!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$month))throw new \InvalidArgumentException('감가상각 귀속연월을 입력해 주세요.');if($this->model->depreciationExists($id,$month))throw new \InvalidArgumentException('이미 감가상각한 귀속연월입니다.');$date=$this->date($in['depreciation_date']??($month.'-'.date('t',strtotime($month.'-01'))),'감가상각 전기일');$acc=$this->model->depreciationTotal($id);$limit=(float)$a['acquisition_amount']-(float)$a['residual_amount']-$acc;$monthly=round(((float)$a['acquisition_amount']-(float)$a['residual_amount'])/(int)$a['useful_life_months'],2);$amount=min($limit,max(0,(float)($in['amount']??$monthly)));if($amount<=0)throw new \InvalidArgumentException('상각 가능한 금액이 없습니다.');$owns=!$this->pdo->inTransaction();try{if($owns)$this->pdo->beginTransaction();$refs=$this->refsFromAsset($a);$voucher=$this->postVoucher($date,'감가상각 '.$a['asset_no'].' '.$month,[['account_id'=>$a['expense_account_id'],'debit'=>$amount,'credit'=>0,'line_summary'=>'감가상각비','refs'=>$refs],['account_id'=>$a['accumulated_account_id'],'debit'=>0,'credit'=>$amount,'line_summary'=>'감가상각누계액','refs'=>$refs]],$actor);$newAcc=$acc+$amount;$this->model->addDepreciation([':id'=>UuidHelper::generate(),':asset_id'=>$id,':depreciation_year_month'=>$month,':depreciation_date'=>$date,':depreciation_amount'=>$amount,':accumulated_amount'=>$newAcc,':book_value_amount'=>(float)$a['acquisition_amount']-$newAcc,':voucher_id'=>$voucher,':created_at'=>date('Y-m-d H:i:s'),':created_by'=>$actor]);if($owns)$this->pdo->commit();$this->writeAudit('info','감가상각을 계산하고 전기했습니다.','ASSET_DEPRECIATED',$id,$actor);return['success'=>true,'message'=>'감가상각 전기가 완료되었습니다.','data'=>$this->detail($id)];}catch(\Throwable$e){if($owns&&$this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
    public function dispose(array $in,?string $actorOverride=null):array{$actor=$actorOverride?:ActorHelper::user();$id=trim((string)($in['asset_id']??''));$a=$this->active($id);$date=$this->date($in['disposal_date']??'','처분일');$reason=trim((string)($in['reason']??''));if($reason==='')throw new \InvalidArgumentException('처분 근거와 사유를 입력해 주세요.');$proceeds=max(0,(float)($in['proceeds_amount']??0));$acc=$this->model->depreciationTotal($id);$book=(float)$a['acquisition_amount']-$acc;$gain=$proceeds-$book;foreach(['proceeds_account_id','gain_account_id','loss_account_id']as$k)if(trim((string)($in[$k]??''))==='')throw new \InvalidArgumentException('처분대금·처분이익·처분손실 계정을 모두 선택해 주세요.');$refs=$this->refsFromAsset($a);$lines=[];if($acc>0)$lines[]=['account_id'=>$a['accumulated_account_id'],'debit'=>$acc,'credit'=>0,'line_summary'=>'감가상각누계액 제거','refs'=>$refs];if($proceeds>0)$lines[]=['account_id'=>$in['proceeds_account_id'],'debit'=>$proceeds,'credit'=>0,'line_summary'=>'자산 처분대금','refs'=>$refs];if($gain<0)$lines[]=['account_id'=>$in['loss_account_id'],'debit'=>abs($gain),'credit'=>0,'line_summary'=>'유형자산처분손실','refs'=>$refs];$lines[]=['account_id'=>$a['asset_account_id'],'debit'=>0,'credit'=>$a['acquisition_amount'],'line_summary'=>'처분 자산 제거','refs'=>$refs];if($gain>0)$lines[]=['account_id'=>$in['gain_account_id'],'debit'=>0,'credit'=>$gain,'line_summary'=>'유형자산처분이익','refs'=>$refs];$owns=!$this->pdo->inTransaction();try{if($owns)$this->pdo->beginTransaction();$voucher=$this->postVoucher($date,'자산처분 '.$a['asset_no'],$lines,$actor);$this->model->addDisposal([':id'=>UuidHelper::generate(),':asset_id'=>$id,':disposal_date'=>$date,':disposal_type_code'=>strtoupper(trim((string)($in['disposal_type_code']??'SCRAP'))),':proceeds_amount'=>$proceeds,':book_value_amount'=>$book,':gain_loss_amount'=>$gain,':proceeds_account_id'=>$in['proceeds_account_id'],':gain_account_id'=>$in['gain_account_id'],':loss_account_id'=>$in['loss_account_id'],':voucher_id'=>$voucher,':reason'=>$reason,':created_at'=>date('Y-m-d H:i:s'),':created_by'=>$actor]);if($owns)$this->pdo->commit();$this->writeAudit('info','자산을 처분하고 전기했습니다.','ASSET_DISPOSED',$id,$actor);return['success'=>true,'message'=>'자산처분 전기가 완료되었습니다.','data'=>$this->detail($id)];}catch(\Throwable$e){if($owns&&$this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
    private function postVoucher(string $date,string $summary,array $lines,string $actor):string{$v=$this->vouchers->save(['voucher_date'=>$date,'source_type'=>'SYSTEM','summary'=>$summary,'lines'=>$lines,'linked_evidences'=>[]],$actor);$id=(string)$v['voucher_id'];$this->vouchers->requestReview($id,$actor);$this->vouchers->completeReview($id,$actor);$this->vouchers->post($id,$actor);return$id;}
    private function normalizeAsset(array $i):array{$required=['company_id','asset_no','asset_name','asset_category_code','acquisition_date','service_start_date','asset_account_id','accumulated_account_id','expense_account_id','acquisition_counter_account_id','business_unit'];foreach($required as$k)if(trim((string)($i[$k]??''))==='')throw new \InvalidArgumentException('자산 필수정보를 모두 입력해 주세요.');$amount=(float)($i['acquisition_amount']??0);$res=max(0,(float)($i['residual_amount']??0));$life=(int)($i['useful_life_months']??0);if($amount<=0||$res>=$amount||$life<=0)throw new \InvalidArgumentException('취득가액·잔존가액·내용연수를 확인해 주세요.');return[':company_id'=>trim($i['company_id']),':asset_no'=>trim($i['asset_no']),':asset_name'=>trim($i['asset_name']),':asset_category_code'=>trim($i['asset_category_code']),':acquisition_date'=>$this->date($i['acquisition_date'],'취득일'),':service_start_date'=>$this->date($i['service_start_date'],'사용개시일'),':acquisition_amount'=>$amount,':residual_amount'=>$res,':useful_life_months'=>$life,':depreciation_method_code'=>'STRAIGHT_LINE',':asset_account_id'=>$i['asset_account_id'],':accumulated_account_id'=>$i['accumulated_account_id'],':expense_account_id'=>$i['expense_account_id'],':acquisition_counter_account_id'=>$i['acquisition_counter_account_id'],':business_unit'=>$i['business_unit'],':project_id'=>$this->null($i['project_id']??null),':work_team_id'=>$this->null($i['work_team_id']??null),':employee_id'=>$this->null($i['employee_id']??null),':location_name'=>$this->null($i['location_name']??null),':serial_no'=>$this->null($i['serial_no']??null),':note'=>$this->null($i['note']??null)];}
    private function active(string$id):array{$a=$this->model->find($id);if(!$a)throw new \InvalidArgumentException('자산을 찾을 수 없습니다.');if($a['asset_status_code']!=='ACTIVE')throw new \InvalidArgumentException('사용 중인 자산만 처리할 수 있습니다.');return$a;}
    private function date(mixed$v,string$n):string{$v=trim((string)$v);$d=\DateTimeImmutable::createFromFormat('!Y-m-d',$v);if(!$d||$d->format('Y-m-d')!==$v)throw new \InvalidArgumentException($n.'을 확인해 주세요.');return$v;}
    private function null(mixed$v):?string{$v=trim((string)$v);return$v===''?null:$v;}
    private function refs(array$r):array{return$this->refsFromAsset(['project_id'=>$r[':project_id'],'work_team_id'=>$r[':work_team_id'],'employee_id'=>$r[':employee_id']]);}
    private function refsFromAsset(array$a):array{$r=[];foreach(['project_id'=>'PROJECT','work_team_id'=>'WORK_TEAM','employee_id'=>'EMPLOYEE']as$k=>$t)if(trim((string)($a[$k]??''))!=='')$r[]=['ref_target'=>$t,'ref_id'=>$a[$k]];return$r;}
    private function writeAudit(string$l,string$m,string$e,string$id,string$a,?\Throwable$x=null):void{$c=['event_code'=>$e,'result'=>$l==='info'?'SUCCESS':($l==='warning'?'BLOCKED':'FAILED'),'service'=>self::class,'action'=>strtolower($e),'actor'=>$a,'target_type'=>'ledger_assets','target_id'=>$id];if($x){$c['error_code']=$x::class;$c['error']=$x;}if($l==='info')$this->logger->info($m,$c);elseif($l==='warning')$this->logger->warning($m,$c);else$this->logger->error($m,$c);}
}
