<?php

namespace App\Services\Ledger;

use App\Models\Ledger\VehicleLogModel;
use Core\Helpers\ActorHelper;
use Core\Helpers\ExcelTemplateFilenameHelper;
use Core\Helpers\ExcelValueFormatterHelper;
use Core\Helpers\UuidHelper;
use Core\LoggerFactory;
use InvalidArgumentException;
use PDO;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

class VehicleLogService
{
    private VehicleLogModel $model; private $logger;
    private const PURPOSES=['BUSINESS'=>'업무용','COMMUTE'=>'출퇴근','PRIVATE'=>'비업무용','UNCLASSIFIED'=>'미분류'];
    private const SOURCES=['MANUAL'=>'직접입력','EXCEL'=>'엑셀','DOMAIN'=>'업무도메인','CARTAX'=>'카택스','GPS'=>'GPS','MOBILE'=>'모바일'];
    private const EXCEL_COLUMNS=['trip_date'=>'운행일자','vehicle_no'=>'차량번호','vehicle_name'=>'차량명','ownership_type_name'=>'소유구분','driver_name_snapshot'=>'사용자','department_name_snapshot'=>'부서','position_name_snapshot'=>'직책','purpose_type_name'=>'운행구분','purpose'=>'운행목적','started_at'=>'출발일시','origin_location'=>'출발지','start_odometer_km'=>'출발 전 누적거리(km)','ended_at'=>'도착일시','destination_location'=>'도착지','end_odometer_km'=>'도착 후 누적거리(km)','distance_km'=>'주행거리(km)','business_distance_km'=>'업무용 주행거리(km)','source_type_name'=>'자료출처','source_record_id'=>'원본 식별자','note'=>'비고'];
    public function __construct(private readonly PDO $pdo){$this->model=new VehicleLogModel($pdo);$this->logger=LoggerFactory::getLogger('service-ledger-vehicle-log');}
    public function list(array$f=[]):array{return['rows'=>ActorHelper::enrichActorNames($this->model->list($f),['created_by_name'=>'created_by','updated_by_name'=>'updated_by']),'summary'=>$this->model->summary($f)];}
    public function trash(array$f=[]):array{return ActorHelper::enrichActorNames($this->model->list($f,true),['deleted_by_name'=>'deleted_by']);}
    public function detail(string$id):?array{$r=$this->model->find($id);return$r?ActorHelper::enrichActorNamesRow($r,['created_by_name'=>'created_by','updated_by_name'=>'updated_by']):null;}
    public function options():array{return['companies'=>$this->model->companies(),'vehicles'=>$this->model->vehicleOptions(),'employees'=>$this->model->employees(),'teams'=>$this->model->teams(),'assets'=>$this->model->vehicleAssets(),'purposes'=>array_map(fn($id,$name)=>compact('id','name'),array_keys(self::PURPOSES),self::PURPOSES),'sources'=>array_map(fn($id,$name)=>compact('id','name'),array_keys(self::SOURCES),self::SOURCES)];}
    public function saveVehicle(array$input):array{$actor=ActorHelper::user();$id=trim((string)($input['id']??''));$owner=strtoupper(trim((string)($input['ownership_type_code']??'')));$asset=$this->nullable($input['asset_id']??null);$company=$this->required($input,'company_id','회사');if(!in_array($owner,['CORPORATE','PERSONAL'],true))throw new InvalidArgumentException('차량 소유구분을 선택해 주세요.');if($owner==='CORPORATE'&&$asset===null)throw new InvalidArgumentException('법인차량은 자산대장의 차량운반구와 연결해야 합니다.');if($owner==='PERSONAL'&&$asset!==null)throw new InvalidArgumentException('개인차량은 회사 고정자산과 연결할 수 없습니다.');if($asset!==null){$linked=$this->model->vehicleAsset($asset);if(!$linked||$linked['asset_category_code']!=='VEHICLE'||$linked['asset_status_code']!=='ACTIVE')throw new InvalidArgumentException('사용 중인 차량운반구 자산만 연결할 수 있습니다.');if($linked['company_id']!==$company)throw new InvalidArgumentException('차량과 연결 자산의 회사가 일치해야 합니다.');}$row=[':company_id'=>$company,':asset_id'=>$asset,':vehicle_no'=>$this->required($input,'vehicle_no','차량번호'),':vehicle_name'=>$this->required($input,'vehicle_name','차량명'),':ownership_type_code'=>$owner,':default_employee_id'=>$this->nullable($input['default_employee_id']??null),':home_location'=>$this->nullable($input['home_location']??null),':work_location'=>$this->nullable($input['work_location']??null),':commute_distance_km'=>$this->nullableNumber($input['commute_distance_km']??null),':is_active'=>isset($input['is_active'])?(int)(bool)$input['is_active']:1,':note'=>$this->nullable($input['note']??null),':updated_at'=>date('Y-m-d H:i:s'),':updated_by'=>$actor];if($this->model->vehicleNoExists($row[':company_id'],$row[':vehicle_no'],$id?:null))throw new InvalidArgumentException('같은 회사에 동일한 차량번호가 있습니다.');$this->pdo->beginTransaction();try{if($id===''){$id=UuidHelper::generate();$this->model->insertVehicle($row+[':id'=>$id,':created_at'=>$row[':updated_at'],':created_by'=>$actor]);}else{if(!$this->model->vehicle($id,true))throw new InvalidArgumentException('차량을 찾을 수 없습니다.');$this->model->updateVehicle($id,$row);}$this->pdo->commit();$this->log('info','차량 기본정보를 저장했습니다.','VEHICLE_SAVED',$id,$actor);return['success'=>true,'message'=>'차량 기본정보를 저장했습니다.','data'=>['id'=>$id]];}catch(\Throwable$e){if($this->pdo->inTransaction())$this->pdo->rollBack();$this->log('error','차량 기본정보 저장에 실패했습니다.','VEHICLE_SAVE_FAILED',$id,$actor,$e);throw$e;}}
    public function saveTrip(array$input,?string$actorOverride=null):array{$actor=$actorOverride?:ActorHelper::user();$id=trim((string)($input['id']??''));$row=$this->normalizeTrip($input,$actor);$owns=!$this->pdo->inTransaction();try{if($owns)$this->pdo->beginTransaction();if($id===''){$id=UuidHelper::generate();$this->model->insertTrip($row+[':id'=>$id,':created_at'=>$row[':updated_at'],':created_by'=>$actor]);}else{if(!$this->model->find($id,true))throw new InvalidArgumentException('운행기록을 찾을 수 없습니다.');$this->model->updateTrip($id,$row);}if($owns)$this->pdo->commit();$this->log('info','차량 운행기록을 저장했습니다.','VEHICLE_TRIP_SAVED',$id,$actor);return['success'=>true,'message'=>'차량 운행기록을 저장했습니다.','data'=>['id'=>$id]];}catch(\Throwable$e){if($owns&&$this->pdo->inTransaction())$this->pdo->rollBack();$this->log($e instanceof InvalidArgumentException?'warning':'error','차량 운행기록 저장을 완료하지 못했습니다.','VEHICLE_TRIP_SAVE_FAILED',$id,$actor,$e);throw$e;}}
    public function delete(string$id):array{$actor=ActorHelper::user();if(!$this->model->find($id))throw new InvalidArgumentException('운행기록을 찾을 수 없습니다.');$this->model->softDelete($id,$actor);$this->log('info','차량 운행기록을 휴지통으로 이동했습니다.','VEHICLE_TRIP_DELETED',$id,$actor);return['success'=>true,'message'=>'운행기록을 휴지통으로 이동했습니다.'];}
    public function restore(string$id):array{$actor=ActorHelper::user();$this->model->restore($id,$actor);$this->log('info','차량 운행기록을 복구했습니다.','VEHICLE_TRIP_RESTORED',$id,$actor);return['success'=>true,'message'=>'운행기록을 복구했습니다.'];}
    private function normalizeTrip(array$i,string$actor):array{$vehicle=$this->model->vehicle($this->required($i,'vehicle_id','차량'));if(!$vehicle||(int)$vehicle['is_active']!==1)throw new InvalidArgumentException('사용 가능한 차량을 선택해 주세요.');$employeeId=$this->required($i,'employee_id','사용자');$employee=null;foreach($this->model->employees()as$e)if($e['id']===$employeeId){$employee=$e;break;}if(!$employee)throw new InvalidArgumentException('사용 가능한 직원을 선택해 주세요.');$purpose=strtoupper(trim((string)($i['purpose_type_code']??'')));if(!isset(self::PURPOSES[$purpose]))throw new InvalidArgumentException('운행구분을 선택해 주세요.');$source=strtoupper(trim((string)($i['source_type_code']??'MANUAL')));if(!isset(self::SOURCES[$source]))throw new InvalidArgumentException('자료출처를 확인해 주세요.');$sourceId=trim((string)($i['source_record_id']??''));$exclude=trim((string)($i['id']??''));if($this->model->duplicateSource($source,$sourceId,$exclude?:null))throw new InvalidArgumentException('같은 외부 원본 식별자로 등록된 운행기록이 있습니다.');$start=$this->nullableNumber($i['start_odometer_km']??null);$end=$this->nullableNumber($i['end_odometer_km']??null);$distance=$this->number($i['distance_km']??null,'주행거리');if($start!==null&&$end!==null){if($end<$start)throw new InvalidArgumentException('도착 후 누적거리는 출발 전 누적거리보다 작을 수 없습니다.');$calculated=round($end-$start,2);if(abs($distance-$calculated)>0.01)throw new InvalidArgumentException('주행거리는 도착 후 누적거리에서 출발 전 누적거리를 뺀 값과 같아야 합니다.');}$business=$purpose==='BUSINESS'?$distance:(float)($i['business_distance_km']??0);if($business<0||$business>$distance)throw new InvalidArgumentException('업무용 주행거리를 확인해 주세요.');$date=$this->date($i['trip_date']??'','운행일자');$started=$this->dateTime($i['started_at']??null);$ended=$this->dateTime($i['ended_at']??null);if($started&&$ended&&$ended<$started)throw new InvalidArgumentException('도착일시는 출발일시보다 빠를 수 없습니다.');return[':company_id'=>$vehicle['company_id'],':vehicle_id'=>$vehicle['id'],':employee_id'=>$employeeId,':driver_name_snapshot'=>$employee['name'],':department_name_snapshot'=>$this->nullable($employee['department_name']??null),':position_name_snapshot'=>$this->nullable($employee['position_name']??null),':work_team_id'=>$this->nullable($i['work_team_id']??null),':trip_date'=>$date,':started_at'=>$started,':ended_at'=>$ended,':purpose_type_code'=>$purpose,':purpose'=>$this->required($i,'purpose','운행목적'),':origin_location'=>$this->required($i,'origin_location','출발지'),':destination_location'=>$this->required($i,'destination_location','도착지'),':start_odometer_km'=>$start,':end_odometer_km'=>$end,':distance_km'=>$distance,':business_distance_km'=>$business,':source_type_code'=>$source,':source_record_id'=>$sourceId?:null,':capture_status_code'=>in_array(($i['capture_status_code']??'COMPLETE'),['COMPLETE','REVIEW_REQUIRED'],true)?$i['capture_status_code']:'REVIEW_REQUIRED',':note'=>$this->nullable($i['note']??null),':updated_at'=>date('Y-m-d H:i:s'),':updated_by'=>$actor];}
    public function download(bool$template=false,?string$columnsCsv=null):void{$keys=$this->columns($columnsCsv);$rows=[];if(!$template){foreach($this->model->list([])as$r){$r['ownership_type_name']=$r['ownership_type_code']==='CORPORATE'?'법인차량':'개인차량';$r['purpose_type_name']=self::PURPOSES[$r['purpose_type_code']]??$r['purpose_type_code'];$r['source_type_name']=self::SOURCES[$r['source_type_code']]??$r['source_type_code'];$rows[]=array_map(fn($k)=>$r[$k]??'', $keys);}}$headers=array_map(fn($k)=>self::EXCEL_COLUMNS[$k],$keys);$sheet=(new Spreadsheet())->getActiveSheet();$sheet->setTitle('차량운행기록부');ExcelValueFormatterHelper::writeTable($sheet,$headers,$rows,'A1',array_map(fn($k)=>['key'=>$k],$keys));foreach(range('A',$sheet->getHighestColumn())as$column)$sheet->getColumnDimension($column)->setAutoSize(true);$filename=$template?ExcelTemplateFilenameHelper::build('vehicle_trip_log'):'vehicle_trip_log_'.date('Ymd_His').'.xlsx';header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="'.$filename.'"');(new Xlsx($sheet->getParent()))->save('php://output');exit;}
    public function upload(string$file):array{$sheet=IOFactory::load($file)->getActiveSheet();$data=$sheet->toArray(null,true,true,false);if(count($data)<2)throw new InvalidArgumentException('업로드할 운행기록이 없습니다.');$headers=array_map(fn($v)=>preg_replace('/\s+/u','',trim((string)$v)),$data[0]);$map=[];foreach(self::EXCEL_COLUMNS as$key=>$label)$map[preg_replace('/\s+/u','',$label)]=$key;$aliases=['사용일자'=>'trip_date','운행일시'=>'trip_date','차량번호'=>'vehicle_no','성명'=>'driver_name_snapshot','사용자'=>'driver_name_snapshot','목적'=>'purpose','운행목적'=>'purpose','출발전'=>'start_odometer_km','출발누적거리'=>'start_odometer_km','도착후'=>'end_odometer_km','도착누적거리'=>'end_odometer_km','총거리'=>'distance_km','운행거리'=>'distance_km','업무용주행거리'=>'business_distance_km'];$map+=$aliases;$keys=array_map(fn($h)=>$map[$h]??null,$headers);$employees=$this->model->employees();$companies=$this->model->companies();$saved=0;$errors=[];$this->pdo->beginTransaction();try{foreach(array_slice($data,1)as$offset=>$values){if(!array_filter($values,fn($v)=>trim((string)$v)!==''))continue;$row=[];foreach($keys as$index=>$key)if($key)$row[$key]=$values[$index]??null;$companyId=(string)($companies[0]['id']??'');$vehicle=$this->model->vehicleByNo($companyId,trim((string)($row['vehicle_no']??'')));$employee=null;foreach($employees as$e)if($e['name']===trim((string)($row['driver_name_snapshot']??''))){$employee=$e;break;}if(!$vehicle||!$employee){$errors[]='행 '.($offset+2).': 차량번호 또는 사용자를 기준정보에서 찾을 수 없습니다.';continue;}$purposeName=trim((string)($row['purpose_type_name']??'업무용'));$purposeCode=array_search($purposeName,self::PURPOSES,true)?:'BUSINESS';$tripDate=$this->excelDate($row['trip_date']??null);if(trim((string)($row['distance_km']??''))===''&&is_numeric($row['start_odometer_km']??null)&&is_numeric($row['end_odometer_km']??null))$row['distance_km']=round((float)$row['end_odometer_km']-(float)$row['start_odometer_km'],2);$payload=$row+['vehicle_id'=>$vehicle['id'],'employee_id'=>$employee['id'],'trip_date'=>$tripDate,'purpose_type_code'=>$purposeCode,'source_type_code'=>'EXCEL','capture_status_code'=>'COMPLETE'];if(empty($payload['business_distance_km'])&&$purposeCode==='BUSINESS')$payload['business_distance_km']=$payload['distance_km']??0;$this->saveTrip($payload,ActorHelper::user());$saved++;}if($errors)throw new InvalidArgumentException(implode("\n",array_slice($errors,0,10)));$this->pdo->commit();$this->log('info','차량 운행기록 엑셀 업로드를 완료했습니다.','VEHICLE_TRIP_EXCEL_UPLOADED','',ActorHelper::user());return['success'=>true,'message'=>"{$saved}건의 운행기록을 업로드했습니다.",'data'=>['saved_count'=>$saved]];}catch(\Throwable$e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
    private function columns(?string$csv):array{$requested=array_values(array_filter(array_map('trim',explode(',',(string)$csv))));$valid=array_values(array_intersect($requested,array_keys(self::EXCEL_COLUMNS)));return$valid?:array_keys(self::EXCEL_COLUMNS);}
    private function excelDate(mixed$v):string{if(is_numeric($v))return\PhpOffice\PhpSpreadsheet\Shared\Date::excelToDateTimeObject((float)$v)->format('Y-m-d');$s=trim((string)$v);if(preg_match('/^(\d{4})년\s*(\d{1,2})월\s*(\d{1,2})일/u',$s,$m))return sprintf('%04d-%02d-%02d',$m[1],$m[2],$m[3]);return$this->date(substr($s,0,10),'운행일자');}
    private function required(array$i,string$k,string$n):string{$v=trim((string)($i[$k]??''));if($v==='')throw new InvalidArgumentException($n.'을(를) 입력해 주세요.');return$v;}
    private function nullable(mixed$v):?string{$v=trim((string)$v);return$v===''?null:$v;}
    private function nullableNumber(mixed$v):?float{return trim((string)$v)===''?null:(float)$v;}
    private function number(mixed$v,string$n):float{if(trim((string)$v)===''||!is_numeric($v)||(float)$v<0)throw new InvalidArgumentException($n.'을 확인해 주세요.');return round((float)$v,2);}
    private function date(mixed$v,string$n):string{$s=trim((string)$v);$d=\DateTimeImmutable::createFromFormat('!Y-m-d',$s);if(!$d||$d->format('Y-m-d')!==$s)throw new InvalidArgumentException($n.'을 확인해 주세요.');return$s;}
    private function dateTime(mixed$v):?string{$s=trim((string)$v);if($s==='')return null;$s=str_replace('T',' ',$s);$d=\DateTimeImmutable::createFromFormat('!Y-m-d H:i',$s)?:\DateTimeImmutable::createFromFormat('!Y-m-d H:i:s',$s);if(!$d)throw new InvalidArgumentException('출발·도착일시를 확인해 주세요.');return$d->format('Y-m-d H:i:s');}
    private function log(string$level,string$message,string$event,string$id,string$actor,?\Throwable$e=null):void{$c=['event_code'=>$event,'result'=>$level==='info'?'SUCCESS':($level==='warning'?'BLOCKED':'FAILED'),'service'=>self::class,'action'=>strtolower($event),'actor'=>$actor,'target_type'=>'ledger_vehicle_trip_logs','target_id'=>$id];if($e){$c['error_code']=$e::class;$c['error']=$e;}$this->logger->{$level}($message,$c);}
}
