<?php
use Core\Helpers\AssetHelper;
$pageStyles=AssetHelper::css('/assets/css/pages/site/estimate/index.css');
$pageScripts=AssetHelper::module('/assets/js/pages/site/estimate/index.js');
$layoutOptions=['header'=>true,'navbar'=>true,'sidebar'=>true,'footer'=>true,'wrapper'=>'single'];
?>
<div class="container-fluid estimate-page py-3">
 <div class="d-flex justify-content-between align-items-center mb-3"><div><h5 class="fw-bold mb-1"><i class="bi bi-calculator me-2"></i>견적관리</h5><div class="text-muted small">실행원가를 작성하고 제출·네고·최종견적까지 한 화면에서 관리합니다.</div></div><button id="estimateNew" class="btn btn-primary"><i class="bi bi-plus-lg"></i> 신규등록</button></div>
 <div class="row g-2 mb-3"><div class="col"><div class="estimate-kpi"><span>전체 견적</span><strong id="kpiAll">0건</strong></div></div><div class="col"><div class="estimate-kpi"><span>작성·협의 중</span><strong id="kpiWorking">0건</strong></div></div><div class="col"><div class="estimate-kpi"><span>수주</span><strong id="kpiWon">0건</strong></div></div><div class="col"><div class="estimate-kpi"><span>제출 임박</span><strong id="kpiDue">0건</strong></div></div><div class="col"><div class="estimate-kpi"><span>최근 제출금액</span><strong id="kpiAmount">0원</strong></div></div></div>
 <div class="card"><div class="card-body"><div class="row g-2 mb-2"><div class="col-md-3"><input id="estimateKeyword" class="form-control" placeholder="견적번호·공사명·의뢰업체"></div><div class="col-md-2"><select id="estimateStatus" class="form-select"><option value="">전체 상태</option><option value="WRITING">작성</option><option value="SUBMITTED">제출</option><option value="NEGOTIATING">네고</option><option value="WON">수주</option><option value="LOST">실주</option><option value="HOLD">보류</option></select></div><div class="col"><button id="estimateSearch" class="btn btn-outline-primary">조회</button></div></div><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>견적번호</th><th>견적일자</th><th>공사명</th><th>의뢰업체</th><th>견적 수</th><th class="text-end">최근 제출금액</th><th>상태</th><th>담당자</th><th>최근 변경일</th></tr></thead><tbody id="estimateRows"></tbody></table></div></div></div>
</div>
<div class="modal fade" id="estimateModal" tabindex="-1"><div class="modal-dialog modal-fullscreen"><div class="modal-content"><div class="modal-header"><div><h5 class="modal-title">견적 작업실</h5><small id="estimateModalCaption" class="text-muted">견적 헤더를 먼저 저장해 주세요.</small></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body estimate-workspace">
 <section class="card mb-2"><div class="card-body py-2"><input id="estimateId" type="hidden"><div class="row g-2"><div class="col-md-2"><label>견적번호 *</label><input id="estimateNumber" class="form-control"></div><div class="col-md-2"><label>견적일자 *</label><input id="estimateDate" type="date" class="form-control"></div><div class="col-md-4"><label>공사명 *</label><input id="constructionName" class="form-control"></div><div class="col-md-2"><label>의뢰업체</label><input id="requesterName" class="form-control"></div><div class="col-md-2"><label>담당자 *</label><select id="ownerEmployee" class="form-select"></select></div><div class="col-md-2"><label>제출기한</label><input id="submissionDue" type="date" class="form-control"></div><div class="col-md-2"><label>상태</label><select id="headerStatus" class="form-select"><option value="WRITING">작성</option><option value="SUBMITTED">제출</option><option value="NEGOTIATING">네고</option><option value="WON">수주</option><option value="LOST">실주</option><option value="HOLD">보류</option></select></div><div class="col-md-6"><label>현장주소</label><input id="siteAddress" class="form-control"></div><div class="col-md-2 d-flex align-items-end"><button id="saveEstimateHeader" class="btn btn-primary w-100">헤더 저장</button></div></div></div></section>
 <div class="estimate-command mb-2"><div id="packageTabs" class="d-flex gap-1 flex-wrap"></div><button id="addPackage" class="btn btn-outline-primary btn-sm">+ 견적 추가</button><select id="versionSelect" class="form-select form-select-sm"></select><button id="copyVersion" class="btn btn-outline-secondary btn-sm">변경·제출·네고 차수</button><button id="finalizeVersion" class="btn btn-outline-success btn-sm">최종견적 확정</button></div>
 <section class="card"><div class="card-body p-2"><div class="d-flex justify-content-between mb-2"><div><strong id="versionTitle">견적을 선택해 주세요.</strong><span id="versionLock" class="badge text-bg-success d-none">최종확정</span></div><button id="addEstimateRow" class="btn btn-outline-primary btn-sm">+ 행 추가</button></div><div class="table-responsive estimate-grid-wrap"><table class="table table-bordered estimate-grid"><thead><tr><th>순번</th><th>공종</th><th>품명 *</th><th>규격</th><th>단위</th><th>수량</th><th>실행단가</th><th>실행금액</th><th>제출단가</th><th>제출금액</th><th>마진</th><th>산출근거</th><th>관리</th></tr></thead><tbody id="estimateItemRows"></tbody></table></div></div></section>
 </div><div class="modal-footer estimate-footer"><div class="estimate-summary"><span>실행원가 <strong id="sumExecution">0원</strong></span><span>제출금액 <strong id="sumSubmission">0원</strong></span><span>예상이익 <strong id="sumMargin">0원</strong></span><span>마진율 <strong id="sumMarginRate">0%</strong></span></div><button class="btn btn-secondary" data-bs-dismiss="modal">닫기</button><button id="saveEstimateItems" class="btn btn-primary">실행·제출견적 저장</button></div></div></div></div>
