<?php
use Core\Helpers\AssetHelper;
$pageStyles=AssetHelper::css('/assets/css/pages/institution/attendance/index.css');
$pageScripts=AssetHelper::module('/assets/js/pages/institution/attendance/index.js');
?>
<main class="attendance-page"><div class="container-fluid py-4">
  <div class="d-flex justify-content-between align-items-start mb-3"><div><h5 class="mb-1 fw-bold"><i class="bi bi-clock me-2"></i>근태관리</h5><p class="text-muted small mb-0">실제 출퇴근 원본과 일별 근태, 월 마감 revision을 관리합니다.</p></div></div>
  <ul class="nav nav-tabs mb-3" id="attendanceTabs"><li class="nav-item"><button class="nav-link active" data-tab="daily">일별 현황</button></li><li class="nav-item"><button class="nav-link" data-tab="monthly">월별 현황</button></li><li class="nav-item"><button class="nav-link" data-tab="exceptions">누락·이상 근태</button></li><li class="nav-item"><button class="nav-link" data-tab="closures">월 마감</button></li></ul>
  <div class="dt-content-stack"><?php $searchId='attendance';$dateOptions='<option value="work_date">근무일</option>';$searchFieldOptions='<option value="employee_id">직원</option><option value="department_id">부서</option><option value="process_status_code">진행상태</option><option value="exception_type_code">예외유형</option><option value="closing_month">귀속월</option>';include PROJECT_ROOT.'/app/views/components/ui-search.php';?>
    <?php $tableId='attendanceTable';$ajaxUrl='/api/institution/human-resources/attendance/daily-list';$columnsType='attendance';$enableButtons=true;$enableSearch=true;$enablePaging=true;$enableReorder=false;include PROJECT_ROOT.'/app/views/components/ui-table.php';?>
  </div>
</div></main>
<div class="modal fade" id="attendanceFormModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><form class="modal-content" id="attendanceForm"><div class="modal-header"><h5 class="modal-title" id="attendanceFormTitle">근태 처리</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="operation"><input type="hidden" name="daily_record_id"><input type="hidden" name="request_key"><div class="row g-3"><div class="col-md-6"><label class="form-label">직원</label><select class="form-select form-select-sm" name="employee_id"></select></div><div class="col-md-6"><label class="form-label">근무일·귀속월</label><input class="form-control form-control-sm admin-date" name="work_date"></div><div class="col-md-6 clock-field"><label class="form-label">출퇴근 유형</label><select class="form-select form-select-sm" name="event_type_code"><option value="CLOCK_IN">출근</option><option value="CLOCK_OUT">퇴근</option></select></div><div class="col-md-6 clock-field"><label class="form-label">발생일시</label><input class="form-control form-control-sm" type="datetime-local" name="occurred_at"></div><div class="col-12 reason-field"><label class="form-label">처리 사유</label><textarea class="form-control form-control-sm" name="reason" rows="2"></textarea></div><div class="col-12 segment-field"><div class="d-flex justify-content-between mb-2"><label class="form-label">실제 근무 구간</label><button class="btn btn-outline-primary btn-sm" type="button" id="attendanceAddSegment">구간 추가</button></div><div class="table-responsive"><table class="table table-sm table-bordered"><thead><tr><th>구분</th><th>시작일</th><th>시작시간</th><th>종료일</th><th>종료시간</th><th>프로젝트</th><th>근무지 배치 ID</th><th></th></tr></thead><tbody id="attendanceSegmentRows"></tbody></table></div></div></div></div><div class="modal-footer"><button class="btn btn-secondary btn-sm" data-bs-dismiss="modal" type="button">취소</button><button class="btn btn-primary btn-sm" type="submit">처리</button></div></form></div></div>
<div class="modal fade" id="attendanceDetailModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">직원 근태 상세</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body" id="attendanceDetailBody"></div></div></div></div>
<script type="application/json" id="attendanceBootstrap"><?=json_encode(['options'=>$attendanceOptions,'capabilities'=>$capabilities],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?></script>
<div id="attendanceTimePicker" class="picker admin-picker is-hidden"></div>
