CREATE TABLE IF NOT EXISTS `ledger_transaction_import_fields` (
    `field_key` VARCHAR(80) NOT NULL COMMENT '업로드 표준 필드 키',
    `field_group` VARCHAR(40) NOT NULL COMMENT '필드 그룹',
    `field_label` VARCHAR(120) NOT NULL COMMENT '표시명',
    `sort_no` INT NOT NULL DEFAULT 0 COMMENT '정렬순서',
    `is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '사용 여부',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (`field_key`),
    INDEX `idx_group_sort` (`field_group`, `sort_no`),
    INDEX `idx_active_sort` (`is_active`, `sort_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='거래 업로드 표준 필드';

INSERT INTO `ledger_transaction_import_fields` (`field_key`, `field_group`, `field_label`, `sort_no`) VALUES
('project_name', 'Header', '사업명', 10),
('description', 'Header', '적요', 20),
('transaction_date', 'Header', '작성일자', 30),
('approval_number', 'Header', '승인번호', 40),
('issue_date', 'Header', '발행일자', 50),
('transmit_date', 'Header', '전송일자', 60),
('tax_invoice_category', 'Header', '전자세금계산서분류', 70),
('tax_invoice_type', 'Header', '전자세금계산서종류', 80),
('issue_type', 'Header', '발급유형', 90),
('receipt_claim_type', 'Header', '영수/청구구분', 100),
('total_amount', 'Header', '합계금액', 110),
('supply_amount', 'Header', '공급가액', 120),
('vat_amount', 'Header', '세액', 130),
('note', 'Header', '비고', 140),
('supplier_business_number', 'Supplier', '공급자사업자등록번호', 150),
('supplier_branch_number', 'Supplier', '공급자종사업장번호', 160),
('supplier_company_name', 'Supplier', '공급자상호', 170),
('supplier_ceo_name', 'Supplier', '공급자대표자명', 180),
('supplier_address', 'Supplier', '공급자주소', 190),
('supplier_email', 'Supplier', '공급자이메일', 200),
('customer_business_number', 'Customer', '공급받는자사업자등록번호', 210),
('customer_branch_number', 'Customer', '공급받는자종사업장번호', 220),
('customer_company_name', 'Customer', '공급받는자상호', 230),
('customer_ceo_name', 'Customer', '공급받는자대표자명', 240),
('customer_address', 'Customer', '공급받는자주소', 250),
('customer_email_1', 'Customer', '공급받는자이메일1', 260),
('customer_email_2', 'Customer', '공급받는자이메일2', 270),
('broker_business_number', 'Broker', '수탁사업자등록번호', 280),
('broker_company_name', 'Broker', '수탁상호', 290),
('item_date', 'Item', '품목일자', 300),
('item_name', 'Item', '품목명', 310),
('item_spec', 'Item', '품목규격', 320),
('item_qty', 'Item', '품목수량', 330),
('item_price', 'Item', '품목단가', 340),
('item_supply_amount', 'Item', '품목공급가액', 350),
('item_vat_amount', 'Item', '품목세액', 360),
('item_note', 'Item', '품목비고', 370)
ON DUPLICATE KEY UPDATE
    `field_group` = VALUES(`field_group`),
    `field_label` = VALUES(`field_label`),
    `sort_no` = VALUES(`sort_no`),
    `is_active` = 1;
