ALTER TABLE `ledger_evidence_bank`
    MODIFY COLUMN `sort_no` INT UNSIGNED NOT NULL COMMENT '테이블 내부 순번',
    MODIFY COLUMN `evidence_sort_no` BIGINT UNSIGNED NOT NULL COMMENT '전체 증빙 공통 순번',
    MODIFY COLUMN `source_type` VARCHAR(40) COLLATE utf8mb4_general_ci NOT NULL COMMENT '증빙유형 코드',
    MODIFY COLUMN `external_key` VARCHAR(120) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '외부 원본 식별값',
    MODIFY COLUMN `evidence_date` DATE NOT NULL COMMENT '증빙일자',
    MODIFY COLUMN `client_id` VARCHAR(36) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '거래처 ID',
    MODIFY COLUMN `project_id` VARCHAR(36) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '프로젝트 ID',
    MODIFY COLUMN `raw_client_name` VARCHAR(255) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '원본 거래처명',
    MODIFY COLUMN `evidence_status` VARCHAR(30) COLLATE utf8mb4_general_ci NOT NULL COMMENT '증빙 상태(ACTIVE,DELETED,INVALID)',
    MODIFY COLUMN `transaction_date` DATE NOT NULL COMMENT '거래일자',
    MODIFY COLUMN `transaction_time` TIME NULL DEFAULT NULL COMMENT '거래시각',
    MODIFY COLUMN `transaction_datetime` DATETIME NULL DEFAULT NULL COMMENT '거래일시',
    MODIFY COLUMN `bank_account_id` VARCHAR(36) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '계좌 ID',
    MODIFY COLUMN `transaction_type` VARCHAR(30) COLLATE utf8mb4_general_ci NOT NULL COMMENT '거래구분 코드',
    MODIFY COLUMN `deposit_amount` DECIMAL(18,2) NULL DEFAULT 0.00 COMMENT '입금액',
    MODIFY COLUMN `withdraw_amount` DECIMAL(18,2) NULL DEFAULT 0.00 COMMENT '출금액',
    MODIFY COLUMN `total_amount` DECIMAL(18,2) NOT NULL COMMENT '거래금액',
    MODIFY COLUMN `balance_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '거래 후 잔액',
    MODIFY COLUMN `balance_status` VARCHAR(20) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '잔액 상태',
    MODIFY COLUMN `check_bill_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '수표어음금액',
    MODIFY COLUMN `currency_code` VARCHAR(10) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '통화코드',
    MODIFY COLUMN `exchange_rate` DECIMAL(18,6) NULL DEFAULT NULL COMMENT '환율',
    MODIFY COLUMN `description` VARCHAR(500) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '거래내용',
    MODIFY COLUMN `counterparty_name` VARCHAR(255) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '상대계좌명',
    MODIFY COLUMN `counterparty_account_number` VARCHAR(100) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '상대계좌번호',
    MODIFY COLUMN `counterparty_bank_name` VARCHAR(100) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '상대은행명',
    MODIFY COLUMN `memo` TEXT COLLATE utf8mb4_general_ci NULL COMMENT '메모',
    MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    MODIFY COLUMN `updated_at` DATETIME NULL DEFAULT NULL COMMENT '수정일시',
    MODIFY COLUMN `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '삭제일시',
    COMMENT='은행 입출금 증빙 테이블';

ALTER TABLE `ledger_evidence_card_purchase`
    MODIFY COLUMN `id` VARCHAR(36) COLLATE utf8mb4_general_ci NOT NULL COMMENT '고유 ID(UUID)',
    MODIFY COLUMN `sort_no` INT UNSIGNED NOT NULL COMMENT '테이블 내부 순번',
    MODIFY COLUMN `evidence_sort_no` BIGINT UNSIGNED NOT NULL COMMENT '전체 증빙 공통 순번',
    MODIFY COLUMN `source_type` VARCHAR(40) COLLATE utf8mb4_general_ci NOT NULL COMMENT '증빙유형 코드',
    MODIFY COLUMN `external_key` VARCHAR(120) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '외부 원본 식별값',
    MODIFY COLUMN `evidence_date` DATE NOT NULL COMMENT '증빙일자',
    MODIFY COLUMN `client_id` VARCHAR(36) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '거래처 ID',
    MODIFY COLUMN `project_id` VARCHAR(36) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '프로젝트 ID',
    MODIFY COLUMN `raw_client_name` VARCHAR(255) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '원본 거래처명',
    MODIFY COLUMN `evidence_status` VARCHAR(30) COLLATE utf8mb4_general_ci NOT NULL COMMENT '증빙 상태(ACTIVE,DELETED,INVALID)',
    MODIFY COLUMN `card_id` VARCHAR(36) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '카드 ID',
    MODIFY COLUMN `raw_card_name` VARCHAR(255) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '원본 카드명',
    MODIFY COLUMN `raw_card_number` VARCHAR(120) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '원본 카드번호',
    MODIFY COLUMN `approval_date` DATE NULL DEFAULT NULL COMMENT '승인일자',
    MODIFY COLUMN `billing_date` DATE NULL DEFAULT NULL COMMENT '청구일자',
    MODIFY COLUMN `merchant_business_number` VARCHAR(20) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '가맹점 사업자등록번호',
    MODIFY COLUMN `merchant_company_name` VARCHAR(255) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '가맹점 상호',
    MODIFY COLUMN `supply_amount` DECIMAL(18,2) NOT NULL COMMENT '공급가액',
    MODIFY COLUMN `vat_amount` DECIMAL(18,2) NOT NULL COMMENT '부가세액',
    MODIFY COLUMN `service_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '봉사료',
    MODIFY COLUMN `total_amount` DECIMAL(18,2) NOT NULL COMMENT '합계금액',
    MODIFY COLUMN `fee_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '수수료',
    MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    MODIFY COLUMN `updated_at` DATETIME NULL DEFAULT NULL COMMENT '수정일시',
    MODIFY COLUMN `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '삭제일시',
    COMMENT='카드매입 증빙 테이블';

ALTER TABLE `ledger_evidence_cash_receipt`
    MODIFY COLUMN `id` VARCHAR(36) COLLATE utf8mb4_general_ci NOT NULL COMMENT '고유 ID(UUID)',
    MODIFY COLUMN `sort_no` INT UNSIGNED NOT NULL COMMENT '테이블 내부 순번',
    MODIFY COLUMN `evidence_sort_no` BIGINT UNSIGNED NOT NULL COMMENT '전체 증빙 공통 순번',
    MODIFY COLUMN `source_type` VARCHAR(40) COLLATE utf8mb4_general_ci NOT NULL COMMENT '증빙유형 코드',
    MODIFY COLUMN `external_key` VARCHAR(120) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '외부 원본 식별값',
    MODIFY COLUMN `evidence_date` DATE NOT NULL COMMENT '증빙일자',
    MODIFY COLUMN `client_id` VARCHAR(36) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '거래처 ID',
    MODIFY COLUMN `project_id` VARCHAR(36) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '프로젝트 ID',
    MODIFY COLUMN `raw_client_name` VARCHAR(255) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '원본 거래처명',
    MODIFY COLUMN `evidence_status` VARCHAR(30) COLLATE utf8mb4_general_ci NOT NULL COMMENT '증빙 상태(ACTIVE,DELETED,INVALID)',
    MODIFY COLUMN `write_date` DATETIME NULL DEFAULT NULL COMMENT '발행일시',
    MODIFY COLUMN `issue_method` VARCHAR(30) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '발급방식',
    MODIFY COLUMN `merchant_business_number` VARCHAR(20) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '가맹점 사업자등록번호',
    MODIFY COLUMN `merchant_company_name` VARCHAR(255) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '가맹점 상호',
    MODIFY COLUMN `supply_amount` DECIMAL(18,2) NOT NULL COMMENT '공급가액',
    MODIFY COLUMN `vat_amount` DECIMAL(18,2) NOT NULL COMMENT '부가세액',
    MODIFY COLUMN `service_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '봉사료',
    MODIFY COLUMN `total_amount` DECIMAL(18,2) NOT NULL COMMENT '합계금액',
    MODIFY COLUMN `memo` TEXT COLLATE utf8mb4_general_ci NULL COMMENT '메모',
    MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    MODIFY COLUMN `updated_at` DATETIME NULL DEFAULT NULL COMMENT '수정일시',
    MODIFY COLUMN `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '삭제일시',
    COMMENT='현금영수증 증빙 테이블';

ALTER TABLE `ledger_evidence_links`
    MODIFY COLUMN `amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '연결금액',
    MODIFY COLUMN `memo` VARCHAR(500) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '메모',
    MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    MODIFY COLUMN `updated_at` DATETIME NULL DEFAULT NULL COMMENT '수정일시',
    MODIFY COLUMN `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '삭제일시',
    COMMENT='증빙 연결 테이블';

ALTER TABLE `ledger_evidence_processing`
    MODIFY COLUMN `processing_status` VARCHAR(30) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '처리상태',
    MODIFY COLUMN `review_status` VARCHAR(30) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '검토상태',
    MODIFY COLUMN `last_error_message` TEXT COLLATE utf8mb4_general_ci NULL COMMENT '마지막 오류메시지',
    MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    MODIFY COLUMN `updated_at` DATETIME NULL DEFAULT NULL COMMENT '수정일시',
    MODIFY COLUMN `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '삭제일시',
    COMMENT='증빙 처리 상태 테이블';

ALTER TABLE `ledger_evidence_processing_logs`
    MODIFY COLUMN `action_type` VARCHAR(40) COLLATE utf8mb4_general_ci NOT NULL COMMENT '처리액션 유형',
    MODIFY COLUMN `before_status` VARCHAR(100) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '변경 전 상태',
    MODIFY COLUMN `after_status` VARCHAR(100) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '변경 후 상태',
    MODIFY COLUMN `message` VARCHAR(1000) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '처리메시지',
    MODIFY COLUMN `actor_type` VARCHAR(20) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '처리주체 유형',
    MODIFY COLUMN `actor_id` VARCHAR(100) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '처리주체 ID',
    MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    COMMENT='증빙 처리 상태 로그 테이블';

ALTER TABLE `ledger_evidence_tax_invoice`
    MODIFY COLUMN `id` VARCHAR(36) COLLATE utf8mb4_general_ci NOT NULL COMMENT '고유 ID(UUID)',
    MODIFY COLUMN `sort_no` INT UNSIGNED NOT NULL COMMENT '테이블 내부 순번',
    MODIFY COLUMN `evidence_sort_no` BIGINT UNSIGNED NOT NULL COMMENT '전체 증빙 공통 순번',
    MODIFY COLUMN `source_type` VARCHAR(40) COLLATE utf8mb4_general_ci NOT NULL COMMENT '증빙유형 코드',
    MODIFY COLUMN `external_key` VARCHAR(120) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '외부 원본 식별값',
    MODIFY COLUMN `evidence_date` DATE NOT NULL COMMENT '증빙일자',
    MODIFY COLUMN `client_id` VARCHAR(36) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '거래처 ID',
    MODIFY COLUMN `project_id` VARCHAR(36) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '프로젝트 ID',
    MODIFY COLUMN `raw_client_name` VARCHAR(255) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '원본 거래처명',
    MODIFY COLUMN `evidence_status` VARCHAR(30) COLLATE utf8mb4_general_ci NOT NULL COMMENT '증빙 상태(ACTIVE,DELETED,INVALID)',
    MODIFY COLUMN `transaction_date` DATE NOT NULL COMMENT '표준일자',
    MODIFY COLUMN `issue_date` DATE NULL DEFAULT NULL COMMENT '발급일자',
    MODIFY COLUMN `transmit_date` DATE NULL DEFAULT NULL COMMENT '전송일자',
    MODIFY COLUMN `supplier_business_number` VARCHAR(20) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '공급자 사업자등록번호',
    MODIFY COLUMN `supplier_company_name` VARCHAR(255) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '공급자 상호',
    MODIFY COLUMN `customer_business_number` VARCHAR(20) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '공급받는자 사업자등록번호',
    MODIFY COLUMN `customer_company_name` VARCHAR(255) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '공급받는자 상호',
    MODIFY COLUMN `supply_amount` DECIMAL(18,2) NOT NULL COMMENT '공급가액',
    MODIFY COLUMN `vat_amount` DECIMAL(18,2) NOT NULL COMMENT '부가세액',
    MODIFY COLUMN `service_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '봉사료',
    MODIFY COLUMN `total_amount` DECIMAL(18,2) NOT NULL COMMENT '합계금액',
    MODIFY COLUMN `description` VARCHAR(500) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '적요',
    MODIFY COLUMN `memo` TEXT COLLATE utf8mb4_general_ci NULL COMMENT '메모',
    MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    MODIFY COLUMN `updated_at` DATETIME NULL DEFAULT NULL COMMENT '수정일시',
    MODIFY COLUMN `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '삭제일시',
    COMMENT='세금계산서 증빙 테이블';

ALTER TABLE `ledger_evidence_tax_invoice_items`
    MODIFY COLUMN `id` VARCHAR(36) COLLATE utf8mb4_general_ci NOT NULL COMMENT '고유 ID(UUID)',
    MODIFY COLUMN `tax_invoice_id` VARCHAR(36) COLLATE utf8mb4_general_ci NOT NULL COMMENT '세금계산서 ID',
    MODIFY COLUMN `sort_no` INT UNSIGNED NOT NULL COMMENT '테이블 내부 순번',
    MODIFY COLUMN `item_date` DATE NULL DEFAULT NULL COMMENT '품목일자',
    MODIFY COLUMN `item_name` VARCHAR(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT '품목명',
    MODIFY COLUMN `item_spec` VARCHAR(255) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '규격',
    MODIFY COLUMN `item_qty` DECIMAL(18,3) NULL DEFAULT NULL COMMENT '수량',
    MODIFY COLUMN `item_price` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '단가',
    MODIFY COLUMN `item_supply_amount` DECIMAL(18,2) NOT NULL COMMENT '품목 공급가액',
    MODIFY COLUMN `item_vat_amount` DECIMAL(18,2) NOT NULL COMMENT '품목 부가세액',
    MODIFY COLUMN `item_note` VARCHAR(500) COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '비고',
    MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    MODIFY COLUMN `updated_at` DATETIME NULL DEFAULT NULL COMMENT '수정일시',
    MODIFY COLUMN `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '삭제일시',
    COMMENT='세금계산서 품목 테이블';
