CREATE TABLE `site_sales_organizations` (
  `id` char(36) NOT NULL COMMENT '영업대상 업체 고유번호',
  `organization_name` varchar(150) NOT NULL COMMENT '영업대상 업체명',
  `organization_type_code` varchar(30) NOT NULL DEFAULT 'COMPANY' COMMENT '영업대상 구분(COMPANY:업체,INSTITUTION:기관,OTHER:기타)',
  `industry_name` varchar(100) DEFAULT NULL COMMENT '업종 또는 주력 사업분야',
  `business_area` varchar(150) DEFAULT NULL COMMENT '주요 영업지역',
  `address` varchar(255) DEFAULT NULL COMMENT '영업대상 소재지',
  `website_url` varchar(500) DEFAULT NULL COMMENT '업체 홈페이지 주소',
  `representative_name` varchar(80) DEFAULT NULL COMMENT '대표자명',
  `main_phone` varchar(50) DEFAULT NULL COMMENT '업체 대표 연락처',
  `introduction_source` varchar(150) DEFAULT NULL COMMENT '업체 또는 인물을 알게 된 경로',
  `relationship_level_code` varchar(20) NOT NULL DEFAULT 'NEW' COMMENT '현재 관계수준(NEW,COLD,WARM,HOT,TRUSTED)',
  `sales_status_code` varchar(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '영업관리 상태(ACTIVE,HOLD,CLOSED)',
  `owner_employee_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '주 영업담당 직원',
  `next_action_date` date DEFAULT NULL COMMENT '다음 영업활동 예정일',
  `next_action_summary` varchar(255) DEFAULT NULL COMMENT '다음 영업활동 내용',
  `note` text DEFAULT NULL COMMENT '업체 영업관리 참고사항',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '생성일시',
  `created_by` varchar(100) NOT NULL COMMENT '생성 Actor',
  `updated_at` datetime DEFAULT NULL COMMENT '수정일시',
  `updated_by` varchar(100) DEFAULT NULL COMMENT '수정 Actor',
  `deleted_at` datetime DEFAULT NULL COMMENT '삭제일시',
  `deleted_by` varchar(100) DEFAULT NULL COMMENT '삭제 Actor',
  PRIMARY KEY (`id`),
  KEY `idx_site_sales_organizations_owner_status` (`owner_employee_id`,`sales_status_code`),
  KEY `idx_site_sales_organizations_next_action` (`next_action_date`,`sales_status_code`),
  CONSTRAINT `fk_site_sales_organizations_owner` FOREIGN KEY (`owner_employee_id`) REFERENCES `user_employees` (`id`),
  CONSTRAINT `chk_site_sales_organizations_type` CHECK (`organization_type_code` IN ('COMPANY','INSTITUTION','OTHER')),
  CONSTRAINT `chk_site_sales_organizations_relation` CHECK (`relationship_level_code` IN ('NEW','COLD','WARM','HOT','TRUSTED')),
  CONSTRAINT `chk_site_sales_organizations_status` CHECK (`sales_status_code` IN ('ACTIVE','HOLD','CLOSED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='거래처와 독립된 업체 중심 영업관계 원본';

CREATE TABLE `site_sales_people` (
  `id` char(36) NOT NULL COMMENT '영업대상 인물 고유번호',
  `person_name` varchar(80) NOT NULL COMMENT '영업대상 인물명',
  `mobile_phone` varchar(50) DEFAULT NULL COMMENT '업무 연락용 휴대전화',
  `email` varchar(150) DEFAULT NULL COMMENT '업무 연락용 이메일',
  `preferred_contact_code` varchar(20) DEFAULT NULL COMMENT '선호 연락방식(PHONE,MESSAGE,EMAIL,VISIT)',
  `preferred_contact_time` varchar(100) DEFAULT NULL COMMENT '선호 연락시간 설명',
  `interests` varchar(500) DEFAULT NULL COMMENT '업무상 관심분야와 선호사항',
  `cautions` varchar(500) DEFAULT NULL COMMENT '영업 진행 시 주의사항과 약속사항',
  `relationship_level_code` varchar(20) NOT NULL DEFAULT 'NEW' COMMENT '인물 관계수준(NEW,COLD,WARM,HOT,TRUSTED)',
  `owner_employee_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '인물 주 영업담당 직원',
  `note` text DEFAULT NULL COMMENT '인물 영업관리 참고사항',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '생성일시',
  `created_by` varchar(100) NOT NULL COMMENT '생성 Actor',
  `updated_at` datetime DEFAULT NULL COMMENT '수정일시',
  `updated_by` varchar(100) DEFAULT NULL COMMENT '수정 Actor',
  `deleted_at` datetime DEFAULT NULL COMMENT '삭제일시',
  `deleted_by` varchar(100) DEFAULT NULL COMMENT '삭제 Actor',
  PRIMARY KEY (`id`),
  KEY `idx_site_sales_people_owner_name` (`owner_employee_id`,`person_name`),
  CONSTRAINT `fk_site_sales_people_owner` FOREIGN KEY (`owner_employee_id`) REFERENCES `user_employees` (`id`),
  CONSTRAINT `chk_site_sales_people_contact` CHECK (`preferred_contact_code` IS NULL OR `preferred_contact_code` IN ('PHONE','MESSAGE','EMAIL','VISIT')),
  CONSTRAINT `chk_site_sales_people_relation` CHECK (`relationship_level_code` IN ('NEW','COLD','WARM','HOT','TRUSTED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='소속이 바뀌어도 유지되는 인물 중심 영업관계 원본';

CREATE TABLE `site_sales_affiliations` (
  `id` char(36) NOT NULL COMMENT '인물 소속이력 고유번호',
  `person_id` char(36) NOT NULL COMMENT '소속 대상 영업 인물',
  `organization_id` char(36) NOT NULL COMMENT '소속 영업 업체',
  `department_name` varchar(100) DEFAULT NULL COMMENT '소속 부서명',
  `position_name` varchar(100) DEFAULT NULL COMMENT '직책 또는 직위명',
  `influence_role_code` varchar(30) NOT NULL DEFAULT 'PRACTITIONER' COMMENT '영업 영향역할(DECISION_MAKER,PRACTITIONER,INTRODUCER,INFLUENCER,OTHER)',
  `started_date` date DEFAULT NULL COMMENT '소속 시작일',
  `ended_date` date DEFAULT NULL COMMENT '소속 종료일',
  `is_current` tinyint(1) NOT NULL DEFAULT 1 COMMENT '현재 소속 여부',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '생성일시',
  `created_by` varchar(100) NOT NULL COMMENT '생성 Actor',
  PRIMARY KEY (`id`),
  KEY `idx_site_sales_affiliations_person_current` (`person_id`,`is_current`),
  KEY `idx_site_sales_affiliations_org_current` (`organization_id`,`is_current`),
  CONSTRAINT `fk_site_sales_affiliations_person` FOREIGN KEY (`person_id`) REFERENCES `site_sales_people` (`id`),
  CONSTRAINT `fk_site_sales_affiliations_org` FOREIGN KEY (`organization_id`) REFERENCES `site_sales_organizations` (`id`),
  CONSTRAINT `chk_site_sales_affiliations_role` CHECK (`influence_role_code` IN ('DECISION_MAKER','PRACTITIONER','INTRODUCER','INFLUENCER','OTHER')),
  CONSTRAINT `chk_site_sales_affiliations_dates` CHECK (`ended_date` IS NULL OR `started_date` IS NULL OR `ended_date` >= `started_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='영업 인물의 업체·부서·직책·영향역할 변경이력';

CREATE TABLE `site_sales_business_cards` (
  `id` char(36) NOT NULL COMMENT '영업 명함 고유번호',
  `person_id` char(36) NOT NULL COMMENT '명함 소유 영업 인물',
  `affiliation_id` char(36) DEFAULT NULL COMMENT '명함 발급 당시 소속이력',
  `file_path` varchar(1000) NOT NULL COMMENT '명함 이미지 저장경로',
  `original_file_name` varchar(255) NOT NULL COMMENT '업로드 당시 명함 파일명',
  `ocr_text` text DEFAULT NULL COMMENT '명함 이미지 문자판독 원문',
  `received_date` date DEFAULT NULL COMMENT '명함을 받은 날짜',
  `is_current` tinyint(1) NOT NULL DEFAULT 1 COMMENT '현재 사용 명함 여부',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '등록일시',
  `created_by` varchar(100) NOT NULL COMMENT '등록 Actor',
  PRIMARY KEY (`id`),
  KEY `idx_site_sales_business_cards_person` (`person_id`,`is_current`),
  CONSTRAINT `fk_site_sales_business_cards_person` FOREIGN KEY (`person_id`) REFERENCES `site_sales_people` (`id`),
  CONSTRAINT `fk_site_sales_business_cards_affiliation` FOREIGN KEY (`affiliation_id`) REFERENCES `site_sales_affiliations` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='인물별 명함 원본과 문자판독 및 변경이력';

CREATE TABLE `site_sales_opportunities` (
  `id` char(36) NOT NULL COMMENT '영업기회 고유번호',
  `organization_id` char(36) DEFAULT NULL COMMENT '관련 영업 업체',
  `person_id` char(36) DEFAULT NULL COMMENT '관련 핵심 인물',
  `opportunity_name` varchar(200) NOT NULL COMMENT '예상 공사 또는 영업기회명',
  `work_type_name` varchar(150) DEFAULT NULL COMMENT '예상 공종 또는 업무분야',
  `stage_code` varchar(30) NOT NULL DEFAULT 'DISCOVERY' COMMENT '영업단계(DISCOVERY,CONTACT,CONSULTING,ESTIMATE_READY,ESTIMATE,NEGOTIATION,WON,LOST,HOLD)',
  `owner_probability_rate` decimal(5,2) NOT NULL DEFAULT 0 COMMENT '담당자가 판단한 수주 가능률',
  `expected_amount` decimal(18,2) DEFAULT NULL COMMENT '예상 수주금액',
  `expected_order_date` date DEFAULT NULL COMMENT '예상 발주시기',
  `expected_decision_date` date DEFAULT NULL COMMENT '수주여부 예상 결정일',
  `competitor_note` varchar(500) DEFAULT NULL COMMENT '경쟁업체와 경쟁상황',
  `probability_reason` varchar(1000) DEFAULT NULL COMMENT '담당자의 수주 가능성 판단근거',
  `estimate_id` char(36) DEFAULT NULL COMMENT '추후 연결되는 견적 고유번호',
  `project_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '수주 후 연결된 프로젝트',
  `result_reason` varchar(1000) DEFAULT NULL COMMENT '수주·실주·보류 결과사유',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '생성일시',
  `created_by` varchar(100) NOT NULL COMMENT '생성 Actor',
  `updated_at` datetime DEFAULT NULL COMMENT '수정일시',
  `updated_by` varchar(100) DEFAULT NULL COMMENT '수정 Actor',
  `deleted_at` datetime DEFAULT NULL COMMENT '삭제일시',
  `deleted_by` varchar(100) DEFAULT NULL COMMENT '삭제 Actor',
  PRIMARY KEY (`id`),
  KEY `idx_site_sales_opportunities_org_stage` (`organization_id`,`stage_code`),
  KEY `idx_site_sales_opportunities_person` (`person_id`),
  KEY `idx_site_sales_opportunities_decision` (`expected_decision_date`,`stage_code`),
  CONSTRAINT `fk_site_sales_opportunities_org` FOREIGN KEY (`organization_id`) REFERENCES `site_sales_organizations` (`id`),
  CONSTRAINT `fk_site_sales_opportunities_person` FOREIGN KEY (`person_id`) REFERENCES `site_sales_people` (`id`),
  CONSTRAINT `fk_site_sales_opportunities_project` FOREIGN KEY (`project_id`) REFERENCES `system_projects` (`id`),
  CONSTRAINT `chk_site_sales_opportunities_stage` CHECK (`stage_code` IN ('DISCOVERY','CONTACT','CONSULTING','ESTIMATE_READY','ESTIMATE','NEGOTIATION','WON','LOST','HOLD')),
  CONSTRAINT `chk_site_sales_opportunities_probability` CHECK (`owner_probability_rate` >= 0 AND `owner_probability_rate` <= 100),
  CONSTRAINT `chk_site_sales_opportunities_amount` CHECK (`expected_amount` IS NULL OR `expected_amount` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='업체·인물 관계에서 구체화된 예상 공사와 수주 가능성';

CREATE TABLE `site_sales_activities` (
  `id` char(36) NOT NULL COMMENT '영업활동 고유번호',
  `organization_id` char(36) DEFAULT NULL COMMENT '활동 대상 영업 업체',
  `person_id` char(36) DEFAULT NULL COMMENT '활동 대상 영업 인물',
  `opportunity_id` char(36) DEFAULT NULL COMMENT '관련 영업기회',
  `activity_type_code` varchar(20) NOT NULL COMMENT '활동유형(PHONE,MESSAGE,EMAIL,VISIT,MEETING,MEAL,SITE,OTHER)',
  `activity_at` datetime NOT NULL COMMENT '영업활동 일시',
  `location_name` varchar(255) DEFAULT NULL COMMENT '영업활동 장소',
  `activity_summary` varchar(500) NOT NULL COMMENT '수행한 영업활동 요약',
  `customer_request` varchar(1000) DEFAULT NULL COMMENT '상대방 요청사항',
  `our_commitment` varchar(1000) DEFAULT NULL COMMENT '우리 회사가 약속한 사항',
  `response_level_code` varchar(20) DEFAULT NULL COMMENT '상대방 반응수준(NEGATIVE,NEUTRAL,POSITIVE,STRONG)',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '작성일시',
  `created_by` varchar(100) NOT NULL COMMENT '작성 Actor',
  PRIMARY KEY (`id`),
  KEY `idx_site_sales_activities_org_date` (`organization_id`,`activity_at`),
  KEY `idx_site_sales_activities_person_date` (`person_id`,`activity_at`),
  CONSTRAINT `fk_site_sales_activities_org` FOREIGN KEY (`organization_id`) REFERENCES `site_sales_organizations` (`id`),
  CONSTRAINT `fk_site_sales_activities_person` FOREIGN KEY (`person_id`) REFERENCES `site_sales_people` (`id`),
  CONSTRAINT `fk_site_sales_activities_opportunity` FOREIGN KEY (`opportunity_id`) REFERENCES `site_sales_opportunities` (`id`),
  CONSTRAINT `chk_site_sales_activities_target` CHECK (`organization_id` IS NOT NULL OR `person_id` IS NOT NULL),
  CONSTRAINT `chk_site_sales_activities_type` CHECK (`activity_type_code` IN ('PHONE','MESSAGE','EMAIL','VISIT','MEETING','MEAL','SITE','OTHER')),
  CONSTRAINT `chk_site_sales_activities_response` CHECK (`response_level_code` IS NULL OR `response_level_code` IN ('NEGATIVE','NEUTRAL','POSITIVE','STRONG'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='전화·방문·미팅과 요청·약속을 보존하는 영업활동 이력';

CREATE TABLE `site_sales_followups` (
  `id` char(36) NOT NULL COMMENT '후속 영업활동 고유번호',
  `organization_id` char(36) DEFAULT NULL COMMENT '후속활동 대상 영업 업체',
  `person_id` char(36) DEFAULT NULL COMMENT '후속활동 대상 영업 인물',
  `opportunity_id` char(36) DEFAULT NULL COMMENT '관련 영업기회',
  `assigned_employee_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '후속활동 담당 직원',
  `due_at` datetime NOT NULL COMMENT '후속활동 처리기한',
  `followup_summary` varchar(500) NOT NULL COMMENT '다음에 수행할 영업활동',
  `followup_status_code` varchar(20) NOT NULL DEFAULT 'OPEN' COMMENT '후속활동 상태(OPEN,DONE,CANCELLED)',
  `completed_at` datetime DEFAULT NULL COMMENT '후속활동 완료일시',
  `completed_note` varchar(500) DEFAULT NULL COMMENT '후속활동 처리결과',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '생성일시',
  `created_by` varchar(100) NOT NULL COMMENT '생성 Actor',
  `updated_at` datetime DEFAULT NULL COMMENT '수정일시',
  `updated_by` varchar(100) DEFAULT NULL COMMENT '수정 Actor',
  PRIMARY KEY (`id`),
  KEY `idx_site_sales_followups_assignee_due` (`assigned_employee_id`,`followup_status_code`,`due_at`),
  CONSTRAINT `fk_site_sales_followups_org` FOREIGN KEY (`organization_id`) REFERENCES `site_sales_organizations` (`id`),
  CONSTRAINT `fk_site_sales_followups_person` FOREIGN KEY (`person_id`) REFERENCES `site_sales_people` (`id`),
  CONSTRAINT `fk_site_sales_followups_opportunity` FOREIGN KEY (`opportunity_id`) REFERENCES `site_sales_opportunities` (`id`),
  CONSTRAINT `fk_site_sales_followups_employee` FOREIGN KEY (`assigned_employee_id`) REFERENCES `user_employees` (`id`),
  CONSTRAINT `chk_site_sales_followups_target` CHECK (`organization_id` IS NOT NULL OR `person_id` IS NOT NULL),
  CONSTRAINT `chk_site_sales_followups_status` CHECK (`followup_status_code` IN ('OPEN','DONE','CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='영업담당자에게 알림할 약속·다음 행동·처리기한';
