ALTER TABLE system_statutory_standards
    DROP FOREIGN KEY fk_statutory_current_revision,
    DROP INDEX uk_statutory_standard_code,
    DROP INDEX idx_statutory_standard_category,
    DROP CONSTRAINT chk_statutory_standard_structure,
    DROP COLUMN standard_code,
    DROP COLUMN category_code,
    DROP COLUMN standard_name,
    DROP COLUMN value_structure_code,
    DROP COLUMN calculation_purpose_code,
    DROP COLUMN description,
    DROP COLUMN current_revision_id,
    DROP COLUMN is_active,
    DROP COLUMN deleted_at,
    DROP COLUMN deleted_by,
    ADD COLUMN sort_no int unsigned NOT NULL AFTER id,
    ADD COLUMN standard_type_code varchar(80) NOT NULL AFTER sort_no,
    ADD COLUMN effective_from date NOT NULL AFTER standard_type_code,
    ADD COLUMN effective_to date DEFAULT NULL AFTER effective_from,
    ADD COLUMN published_at date DEFAULT NULL AFTER effective_to,
    ADD COLUMN value_data longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL AFTER published_at,
    ADD COLUMN scope_data longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL AFTER value_data,
    ADD COLUMN scope_key char(64) NOT NULL AFTER scope_data,
    ADD COLUMN note varchar(1000) DEFAULT NULL AFTER scope_key,
    ADD UNIQUE KEY uk_statutory_standard_period(standard_type_code,scope_key,effective_from),
    ADD KEY idx_statutory_standard_resolve(standard_type_code,effective_from,effective_to),
    ADD CONSTRAINT chk_statutory_standard_dates CHECK(effective_to IS NULL OR effective_to>=effective_from),
    ADD CONSTRAINT chk_statutory_standard_value_json CHECK(JSON_VALID(value_data)),
    ADD CONSTRAINT chk_statutory_standard_scope_json CHECK(JSON_VALID(scope_data)),
    COMMENT='법정기준 적용기간 SSOT';

ALTER TABLE system_statutory_standards_sources
    DROP FOREIGN KEY fk_statutory_source_corrects_same_revision,
    DROP FOREIGN KEY fk_statutory_source_revision,
    DROP INDEX uq_statutory_source_revision_identity,
    DROP INDEX uq_statutory_source_correction_parent,
    DROP INDEX idx_statutory_source_revision,
    DROP INDEX idx_statutory_source_effective,
    DROP INDEX fk_statutory_source_corrects_same_revision,
    DROP CONSTRAINT chk_statutory_source_record_type,
    DROP CONSTRAINT chk_statutory_source_correction_relation,
    DROP COLUMN source_type_code,
    DROP COLUMN record_type_code,
    DROP COLUMN corrects_source_id,
    DROP COLUMN correction_reason,
    DROP COLUMN correction_applied_at,
    DROP COLUMN effective_date,
    DROP COLUMN checked_at,
    DROP COLUMN checked_by,
    DROP COLUMN uploaded_at,
    DROP COLUMN uploaded_by,
    CHANGE COLUMN revision_id standard_id char(36) NOT NULL,
    CHANGE COLUMN publishing_agency organization_name varchar(200) DEFAULT NULL,
    CHANGE COLUMN source_title source_name varchar(300) NOT NULL,
    CHANGE COLUMN notice_name notice_no varchar(300) DEFAULT NULL,
    CHANGE COLUMN published_date published_at date DEFAULT NULL,
    CHANGE COLUMN description note varchar(1000) DEFAULT NULL,
    ADD KEY idx_statutory_source_standard(standard_id,sort_no),
    ADD CONSTRAINT fk_statutory_source_standard FOREIGN KEY(standard_id) REFERENCES system_statutory_standards(id) ON DELETE CASCADE,
    COMMENT='법정기준 관련근거';

RENAME TABLE system_statutory_standards_sources TO system_statutory_standard_sources;
