ALTER TABLE `ledger_processing_items`
    COMMENT='생성센터 workflow tree node 현재 상태 테이블. 원천 row를 업무적으로 해석, 분리, 병합, 보정, 거래/전표 생성 처리하는 핵심 엔티티';

ALTER TABLE `ledger_processing_items`
    MODIFY COLUMN `id` VARCHAR(36) NOT NULL COMMENT '처리 Item 고유 ID(UUID). 생성센터 workflow tree node의 실제 참조 키',
    MODIFY COLUMN `source_table` VARCHAR(100) NOT NULL COMMENT '원천 테이블명(내부 추적용). 업무 분기는 source_domain/source_type을 우선 사용',
    MODIFY COLUMN `source_id` VARCHAR(36) NOT NULL COMMENT '원천 row ID. 증빙, 은행입출금 등 실제 원천 데이터의 PK',
    MODIFY COLUMN `source_type` VARCHAR(30) NOT NULL COMMENT '원천 자료유형 또는 업무유형(TAX_INVOICE, BANK_TRANSACTION, CARD 등)',
    MODIFY COLUMN `source_domain` VARCHAR(30) NULL DEFAULT NULL COMMENT '원천 도메인(EVIDENCE, BANK, CARD, ORDER, IMPORT 등). 테이블명 직접 의존을 줄이기 위한 업무 분류',
    MODIFY COLUMN `parent_item_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '상위 처리 Item ID. split/계층 tree에서 부모 node를 가리킴',
    MODIFY COLUMN `source_item_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '이 Item이 파생된 직접 원본 Item ID. split/merge/재분리 출처 추적용',
    MODIFY COLUMN `lineage_root_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '최초 lineage root Item ID. split/merge 반복 후에도 원래 업무 해석 뿌리를 추적',
    MODIFY COLUMN `is_current` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '현재 생성센터 처리 대상 여부(1=current workflow item, 0=inactive lineage/history item)',
    MODIFY COLUMN `split_group_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '동일 split 작업에 속한 processing item 그룹 ID. parent SPLIT 및 child CREATED action과 연결',
    MODIFY COLUMN `merge_group_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '동일 merge 작업에 속한 processing item 그룹 ID. 병합 대상과 병합 결과를 묶는 workflow 그룹',
    MODIFY COLUMN `sort_no` INT NOT NULL DEFAULT 1 COMMENT '동일 parent/source 아래 표시 및 처리 순서. AUTO_INCREMENT 금지, workflow 정렬용 수동 순번',
    MODIFY COLUMN `item_type` VARCHAR(30) NOT NULL DEFAULT 'DEFAULT' COMMENT '처리 Item 유형(DEFAULT, SPLIT, MERGE_RESULT, ADJUSTMENT 등). 회계 line 유형이 아닌 workflow node 유형',
    MODIFY COLUMN `line_type` VARCHAR(30) NULL DEFAULT NULL COMMENT '업무 라인 성격(상품, 수수료, 관세, 환차손 등). source 해석 결과를 표현',
    MODIFY COLUMN `item_status` VARCHAR(30) NOT NULL DEFAULT 'ACTIVE' COMMENT '처리 Item 생명주기 상태(ACTIVE, SPLIT, MERGED, IGNORED, DELETED, ERROR 등)',
    MODIFY COLUMN `transaction_status` VARCHAR(30) NOT NULL DEFAULT 'NONE' COMMENT '이 processing item 기준 거래 생성 상태(NONE, PARTIAL, PROCESSING, CREATED, ERROR 등)',
    MODIFY COLUMN `voucher_status` VARCHAR(30) NOT NULL DEFAULT 'NONE' COMMENT '이 processing item 기준 전표 생성/전기 상태(NONE, PARTIAL, PROCESSING, CREATED, POSTED, ERROR 등)',
    MODIFY COLUMN `readiness_status` VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN' COMMENT '이 processing item의 생성 준비 상태(UNKNOWN, READY, NOT_READY, PARTIAL, BLOCKED 등)',
    MODIFY COLUMN `correction_status` VARCHAR(30) NOT NULL DEFAULT 'NONE' COMMENT '이 processing item의 보정 상태(NONE, NEEDS_CORRECTION, CORRECTED, REJECTED 등)',
    MODIFY COLUMN `item_date` DATE NULL DEFAULT NULL COMMENT '처리 Item 기준 업무일자. 거래/전표 생성 시 우선 참조되는 날짜',
    MODIFY COLUMN `client_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '처리 Item에 매핑된 거래처 ID. 원천 row와 다르게 split 후 child별로 달라질 수 있음',
    MODIFY COLUMN `project_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '처리 Item에 매핑된 프로젝트 ID. split/보정 후 item별 업무 귀속',
    MODIFY COLUMN `employee_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '처리 Item에 매핑된 임직원 ID. 보정/정산/비용 귀속 추적용',
    MODIFY COLUMN `bank_account_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '처리 Item에 연결된 은행계좌 ID. 은행 원천 또는 결제/수수료 item 처리용',
    MODIFY COLUMN `card_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '처리 Item에 연결된 카드 ID. 카드 원천 또는 카드 비용 item 처리용',
    MODIFY COLUMN `account_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '처리 Item에 추천/보정된 계정과목 ID. 최종 거래/전표 line 생성 전 업무 해석값',
    MODIFY COLUMN `quantity` DECIMAL(18,3) NULL DEFAULT NULL COMMENT '처리 Item 수량. split 전후 수량 합계 무결성 검증 대상',
    MODIFY COLUMN `unit_price` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '처리 Item 단가. 원천 해석 또는 사용자 보정 결과',
    MODIFY COLUMN `supply_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '처리 Item 공급가액. split/merge 전후 금액 무결성 검증 대상',
    MODIFY COLUMN `vat_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '처리 Item 부가세액. split/merge 전후 금액 무결성 검증 대상',
    MODIFY COLUMN `total_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '처리 Item 합계금액. 거래/전표 생성 및 split/merge 무결성의 핵심 금액',
    MODIFY COLUMN `currency` VARCHAR(10) NULL DEFAULT 'KRW' COMMENT '처리 Item 통화. split/merge 시 동일 통화 검증 기준',
    MODIFY COLUMN `description` TEXT NULL COMMENT '처리 Item 업무 설명/적요. 사용자 split/보정 후 거래/전표 설명 후보',
    MODIFY COLUMN `memo` TEXT NULL COMMENT '처리 Item 내부 메모. workflow 처리 사유와 별도로 item 자체에 남기는 참고 메모',
    MODIFY COLUMN `raw_json` LONGTEXT NULL COMMENT '원천 row에서 가져온 원본 payload JSON. 재처리/추적/AI 학습 시 원천값 확인용',
    MODIFY COLUMN `mapped_payload_json` LONGTEXT NULL COMMENT '생성센터가 해석/보정한 업무 payload JSON. 거래처/계정/금액/보조계정 등 생성 전 의미 데이터',
    MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '처리 Item 생성일시. 최초 backfill, split child 생성, merge result 생성 시점',
    MODIFY COLUMN `created_by` VARCHAR(100) NULL DEFAULT NULL COMMENT '처리 Item 생성 주체 ID. 사용자/시스템/batch/AI 생성 추적용',
    MODIFY COLUMN `updated_at` DATETIME NULL DEFAULT NULL COMMENT '처리 Item 현재 상태 마지막 변경일시',
    MODIFY COLUMN `updated_by` VARCHAR(100) NULL DEFAULT NULL COMMENT '처리 Item 현재 상태 마지막 변경 주체 ID',
    MODIFY COLUMN `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '처리 Item soft delete 일시. workflow lineage 삭제가 아닌 화면/처리 제외용',
    MODIFY COLUMN `deleted_by` VARCHAR(100) NULL DEFAULT NULL COMMENT '처리 Item soft delete 처리 주체 ID';

ALTER TABLE `ledger_processing_item_actions`
    COMMENT='생성센터 processing item workflow action history. 단순 audit log가 아니라 split/merge/보정/생성/rollback 업무 이력';
