CREATE TABLE `ledger_account_context_ref_policies` (
    `id` varchar(36) NOT NULL,
    `company_id` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
    `account_sub_policy_id` varchar(36) NOT NULL,
    `operation_type` varchar(30) NOT NULL,
    `accounting_role_code` varchar(50) NOT NULL,
    `effective_from` date NOT NULL,
    `effective_to` date DEFAULT NULL,
    `is_active` tinyint(1) NOT NULL DEFAULT 1,
    `sort_no` int NOT NULL DEFAULT 0,
    `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_by` varchar(100) NOT NULL,
    `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `updated_by` varchar(100) NOT NULL,
    `deleted_at` datetime DEFAULT NULL,
    `deleted_by` varchar(100) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_lacrp_context_effective` (`company_id`,`account_sub_policy_id`,`operation_type`,`accounting_role_code`,`effective_from`),
    KEY `idx_lacrp_evaluation` (`company_id`,`operation_type`,`accounting_role_code`,`account_sub_policy_id`,`is_active`,`effective_from`,`effective_to`,`deleted_at`),
    KEY `idx_lacrp_policy_lifecycle` (`account_sub_policy_id`,`is_active`,`deleted_at`),
    CONSTRAINT `fk_lacrp_company` FOREIGN KEY (`company_id`) REFERENCES `system_company` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lacrp_account_sub_policy` FOREIGN KEY (`account_sub_policy_id`) REFERENCES `ledger_accounts_sub` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `chk_lacrp_active` CHECK (`is_active` IN (0,1)),
    CONSTRAINT `chk_lacrp_effective_period` CHECK (`effective_to` IS NULL OR `effective_to` >= `effective_from`),
    CONSTRAINT `chk_lacrp_deleted_actor` CHECK ((`deleted_at` IS NULL AND `deleted_by` IS NULL) OR (`deleted_at` IS NOT NULL AND `deleted_by` IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='전표 공용 계정 Context별 보조계정 필수정책';
