-- 한글 컬럼 코멘트 보강 롤백

ALTER TABLE `institution_attendance_audits`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `attendance_domain` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `target_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `action_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `source_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `before_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '',
  MODIFY `after_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '',
  MODIFY `processed_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `processed_at` datetime NOT NULL COMMENT '';

ALTER TABLE `institution_attendance_clock_events`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `event_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `occurred_at` datetime NOT NULL COMMENT '',
  MODIFY `collected_at` datetime NOT NULL COMMENT '',
  MODIFY `source_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `external_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `device_identifier` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `source_payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '',
  MODIFY `is_valid` tinyint(1) NOT NULL DEFAULT 1 COMMENT '',
  MODIFY `invalid_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '';

ALTER TABLE `institution_attendance_daily_exceptions`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `daily_record_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `exception_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `candidate_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `source_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `resolution_status_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'OPEN' COMMENT '',
  MODIFY `resolution_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `resolved_at` datetime NULL DEFAULT NULL COMMENT '',
  MODIFY `resolved_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `updated_at` datetime NOT NULL COMMENT '',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '';

ALTER TABLE `institution_attendance_daily_records`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `work_date` date NOT NULL COMMENT '',
  MODIFY `employment_contract_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `working_time_standard_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `public_holiday_standard_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `scheduled_start_at` datetime NULL DEFAULT NULL COMMENT '',
  MODIFY `scheduled_end_at` datetime NULL DEFAULT NULL COMMENT '',
  MODIFY `scheduled_break_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `first_clock_in_at` datetime NULL DEFAULT NULL COMMENT '',
  MODIFY `last_clock_out_at` datetime NULL DEFAULT NULL COMMENT '',
  MODIFY `actual_work_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `actual_break_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `scheduled_work_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `contract_excess_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `calculated_overtime_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `night_work_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `holiday_work_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `late_candidate_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `early_leave_candidate_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `process_status_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'CALCULATED' COMMENT '',
  MODIFY `calculation_status_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'CALCULATED' COMMENT '',
  MODIFY `calculation_version` int(10) unsigned NOT NULL DEFAULT 1 COMMENT '',
  MODIFY `is_corrected` tinyint(1) NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `department_id_snapshot` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `department_name_snapshot` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `job_id_snapshot` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `job_name_snapshot` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `primary_project_id_snapshot` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `primary_project_name_snapshot` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `workplace_assignment_id_snapshot` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `workplace_name_snapshot` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `updated_at` datetime NOT NULL COMMENT '',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '';

ALTER TABLE `institution_attendance_monthly_closures`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `closing_month` char(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `close_status_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'OPEN' COMMENT '',
  MODIFY `current_revision` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `current_history_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `closed_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `closed_at` datetime NULL DEFAULT NULL COMMENT '',
  MODIFY `reopened_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `reopened_at` datetime NULL DEFAULT NULL COMMENT '',
  MODIFY `reopen_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `updated_at` datetime NOT NULL COMMENT '',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '';

ALTER TABLE `institution_attendance_monthly_closure_histories`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `monthly_closure_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `revision` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `closing_month` char(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `workday_count` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `scheduled_work_seconds` bigint(20) unsigned NOT NULL COMMENT '',
  MODIFY `actual_work_seconds` bigint(20) unsigned NOT NULL COMMENT '',
  MODIFY `calculated_overtime_seconds` bigint(20) unsigned NOT NULL COMMENT '',
  MODIFY `night_work_seconds` bigint(20) unsigned NOT NULL COMMENT '',
  MODIFY `holiday_work_seconds` bigint(20) unsigned NOT NULL COMMENT '',
  MODIFY `late_candidate_count` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `late_candidate_seconds` bigint(20) unsigned NOT NULL COMMENT '',
  MODIFY `early_leave_candidate_count` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `early_leave_candidate_seconds` bigint(20) unsigned NOT NULL COMMENT '',
  MODIFY `absence_candidate_days` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `missing_clock_count` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `ledger_hash` char(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `calculation_version` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `close_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `closed_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `closed_at` datetime NOT NULL COMMENT '',
  MODIFY `source_request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '';

ALTER TABLE `institution_attendance_work_segments`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `daily_record_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `segment_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `started_at` datetime NOT NULL COMMENT '',
  MODIFY `ended_at` datetime NOT NULL COMMENT '',
  MODIFY `duration_seconds` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `project_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `project_name_snapshot` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `workplace_assignment_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `workplace_name_snapshot` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `source_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `is_manual` tinyint(1) NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `updated_at` datetime NOT NULL COMMENT '',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '';

ALTER TABLE `institution_educations_audits`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `target_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `employee_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `action_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `source_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `before_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '',
  MODIFY `after_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '',
  MODIFY `processed_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `processed_at` datetime NOT NULL COMMENT '';

ALTER TABLE `institution_educations_courses`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `course_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `course_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `education_type_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `default_institution_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `default_minutes` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `validity_months` int(10) unsigned NULL DEFAULT NULL COMMENT '',
  MODIFY `is_statutory` tinyint(1) NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `is_mandatory` tinyint(1) NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `requires_certificate` tinyint(1) NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `description` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `sort_no` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `is_active` tinyint(1) NOT NULL DEFAULT 1 COMMENT '',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `updated_at` datetime NOT NULL COMMENT '',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `deleted_at` datetime NULL DEFAULT NULL COMMENT '',
  MODIFY `deleted_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '';

ALTER TABLE `institution_educations_employee_records`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `employee_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `course_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `education_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `institution_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `education_start_at` datetime NOT NULL COMMENT '',
  MODIFY `education_end_at` datetime NOT NULL COMMENT '',
  MODIFY `education_minutes` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `attendance_status_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'ATTENDED' COMMENT '',
  MODIFY `completion_status_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'COMPLETED' COMMENT '',
  MODIFY `completion_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `valid_from` date NULL DEFAULT NULL COMMENT '',
  MODIFY `valid_to` date NULL DEFAULT NULL COMMENT '',
  MODIFY `renewal_due_date` date NULL DEFAULT NULL COMMENT '',
  MODIFY `attachment_path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `attachment_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `note` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `updated_at` datetime NOT NULL COMMENT '',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `deleted_at` datetime NULL DEFAULT NULL COMMENT '',
  MODIFY `deleted_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '';

ALTER TABLE `institution_employment_contracts_break_schedules`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `weekly_schedule_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `sort_no` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `start_time` time NOT NULL COMMENT '',
  MODIFY `end_time` time NOT NULL COMMENT '',
  MODIFY `end_day_offset` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `updated_at` datetime NOT NULL COMMENT '',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '';

ALTER TABLE `institution_employment_rules`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `company_id` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '',
  MODIFY `rule_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `rule_type_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `title` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `description` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `owner_department_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `current_revision_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `is_active` tinyint(1) NOT NULL DEFAULT 1 COMMENT '',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `updated_at` datetime NOT NULL COMMENT '',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `deleted_at` datetime NULL DEFAULT NULL COMMENT '',
  MODIFY `deleted_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '';

ALTER TABLE `institution_employment_rules_audits`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `rule_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `revision_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `item_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `action_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `source_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `before_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '',
  MODIFY `after_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '',
  MODIFY `processed_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `processed_at` datetime NOT NULL COMMENT '';

ALTER TABLE `institution_employment_rules_items`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `revision_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `policy_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `value_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `value_text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `value_number` decimal(18,4) NULL DEFAULT NULL COMMENT '',
  MODIFY `value_boolean` tinyint(1) NULL DEFAULT NULL COMMENT '',
  MODIFY `value_date` date NULL DEFAULT NULL COMMENT '',
  MODIFY `value_time` time NULL DEFAULT NULL COMMENT '',
  MODIFY `value_minutes` int(11) NULL DEFAULT NULL COMMENT '',
  MODIFY `value_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '',
  MODIFY `unit_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `operator_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'EXACT' COMMENT '',
  MODIFY `note` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `sort_no` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `updated_at` datetime NOT NULL COMMENT '',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '';

ALTER TABLE `institution_employment_rules_revisions`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `rule_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `revision_no` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `revision_title` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `revision_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `content_text` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `effective_from` date NOT NULL COMMENT '',
  MODIFY `effective_to` date NULL DEFAULT NULL COMMENT '',
  MODIFY `status_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'DRAFT' COMMENT '',
  MODIFY `current_approval_request_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `approved_at` datetime NULL DEFAULT NULL COMMENT '',
  MODIFY `approved_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `published_at` datetime NULL DEFAULT NULL COMMENT '',
  MODIFY `published_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `document_file_path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `document_file_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `updated_at` datetime NOT NULL COMMENT '',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `deleted_at` datetime NULL DEFAULT NULL COMMENT '',
  MODIFY `deleted_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '';

ALTER TABLE `institution_employment_rules_scopes`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `revision_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `scope_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `department_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `position_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `job_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `employment_category_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `updated_at` datetime NOT NULL COMMENT '',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '';

ALTER TABLE `institution_leave_audits`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `leave_domain` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `target_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `action_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `source_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `approval_request_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `before_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '',
  MODIFY `after_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '',
  MODIFY `processed_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `processed_at` datetime NOT NULL COMMENT '';

ALTER TABLE `institution_leave_grants`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `leave_type_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `base_year` smallint(5) unsigned NOT NULL COMMENT '',
  MODIFY `granted_minutes` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `usable_from` date NOT NULL COMMENT '',
  MODIFY `usable_to` date NOT NULL COMMENT '',
  MODIFY `expires_on` date NULL DEFAULT NULL COMMENT '',
  MODIFY `reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '';

ALTER TABLE `institution_leave_ledger_entries`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `leave_type_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `base_year` smallint(5) unsigned NOT NULL COMMENT '',
  MODIFY `entry_type_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `amount_minutes` int(11) NOT NULL COMMENT '',
  MODIFY `source_domain_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `source_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `source_sequence` int(10) unsigned NOT NULL DEFAULT 1 COMMENT '',
  MODIFY `occurred_on` date NOT NULL COMMENT '',
  MODIFY `reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '';

ALTER TABLE `institution_leave_requests`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `request_no` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `request_kind_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'LEAVE' COMMENT '',
  MODIFY `original_request_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `business_status_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'DRAFT' COMMENT '',
  MODIFY `current_approval_request_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `reason` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `requested_total_minutes` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `updated_at` datetime NOT NULL COMMENT '',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '';

ALTER TABLE `institution_leave_request_items`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `leave_request_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `leave_type_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `sort_no` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `leave_date` date NOT NULL COMMENT '',
  MODIFY `request_unit_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `requested_start_at` datetime NULL DEFAULT NULL COMMENT '',
  MODIFY `requested_end_at` datetime NULL DEFAULT NULL COMMENT '',
  MODIFY `requested_minutes` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `deductible_minutes` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `employment_contract_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `scheduled_start_at_snapshot` datetime NOT NULL COMMENT '',
  MODIFY `scheduled_end_at_snapshot` datetime NOT NULL COMMENT '',
  MODIFY `scheduled_minutes_snapshot` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `breaks_json_snapshot` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '';

ALTER TABLE `institution_leave_types`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `type_code` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `type_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `is_paid` tinyint(1) NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `deducts_balance` tinyint(1) NOT NULL DEFAULT 0 COMMENT '',
  MODIFY `requires_approval` tinyint(1) NOT NULL DEFAULT 1 COMMENT '',
  MODIFY `evidence_policy_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'OPTIONAL' COMMENT '',
  MODIFY `allowed_units_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '',
  MODIFY `is_active` tinyint(1) NOT NULL DEFAULT 1 COMMENT '',
  MODIFY `sort_no` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `updated_at` datetime NOT NULL COMMENT '',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '';

ALTER TABLE `institution_leave_usages`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `request_item_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `leave_type_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `leave_date` date NOT NULL COMMENT '',
  MODIFY `request_unit_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `leave_start_at` datetime NOT NULL COMMENT '',
  MODIFY `leave_end_at` datetime NOT NULL COMMENT '',
  MODIFY `used_minutes` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `deductible_minutes` int(10) unsigned NOT NULL COMMENT '',
  MODIFY `usage_status_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'ACTIVE' COMMENT '',
  MODIFY `cancel_request_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `approved_at` datetime NOT NULL COMMENT '',
  MODIFY `approval_request_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `updated_at` datetime NOT NULL COMMENT '',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '';

ALTER TABLE `institution_qualifications_audits`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `target_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `employee_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `action_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `source_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `before_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '',
  MODIFY `after_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '',
  MODIFY `processed_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `processed_at` datetime NOT NULL COMMENT '';

ALTER TABLE `institution_qualifications_employee_records`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `employee_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `qualification_type_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `qualification_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `credential_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `issuer_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `grade_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `technical_field_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `specialty_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `acquired_date` date NULL DEFAULT NULL COMMENT '',
  MODIFY `valid_from` date NULL DEFAULT NULL COMMENT '',
  MODIFY `valid_to` date NULL DEFAULT NULL COMMENT '',
  MODIFY `renewal_due_date` date NULL DEFAULT NULL COMMENT '',
  MODIFY `status_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'PENDING_VERIFICATION' COMMENT '',
  MODIFY `status_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `attachment_path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `attachment_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `note` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `verified_at` datetime NULL DEFAULT NULL COMMENT '',
  MODIFY `verified_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `supersedes_record_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `created_at` datetime NOT NULL COMMENT '',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `updated_at` datetime NOT NULL COMMENT '',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '',
  MODIFY `deleted_at` datetime NULL DEFAULT NULL COMMENT '',
  MODIFY `deleted_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '';

ALTER TABLE `ledger_payment_schedules`
  MODIFY `cancelled_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '',
  MODIFY `cancelled_at` datetime NULL DEFAULT NULL COMMENT '',
  MODIFY `cancellation_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '';

ALTER TABLE `system_client_histories`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '';
