CREATE TABLE ledger_assets (
  id char(36) NOT NULL COMMENT '고정자산 고유번호', company_id varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '자산 소유 회사', asset_no varchar(50) NOT NULL COMMENT '회사별 자산관리번호', asset_name varchar(150) NOT NULL COMMENT '자산명', asset_category_code varchar(30) NOT NULL COMMENT '자산분류 코드', asset_status_code varchar(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '자산상태(ACTIVE,DISPOSED)', acquisition_date date NOT NULL COMMENT '자산 취득일', service_start_date date NOT NULL COMMENT '감가상각 사용개시일', acquisition_amount decimal(18,2) NOT NULL COMMENT '자산 취득가액', residual_amount decimal(18,2) NOT NULL DEFAULT 0 COMMENT '상각 종료 후 잔존가액', useful_life_months smallint unsigned NOT NULL COMMENT '내용연수 개월수', depreciation_method_code varchar(20) NOT NULL DEFAULT 'STRAIGHT_LINE' COMMENT '감가상각방법 코드', asset_account_id varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '고정자산 계정과목', accumulated_account_id varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '감가상각누계액 계정과목', expense_account_id varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '감가상각비 계정과목', acquisition_counter_account_id varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '취득대금 상대 계정과목', business_unit varchar(50) NOT NULL COMMENT '자산 귀속 사업구분', project_id varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '자산 귀속 프로젝트', work_team_id varchar(36) DEFAULT NULL COMMENT '자산 관리 팀', employee_id varchar(36) DEFAULT NULL COMMENT '자산 책임 직원', location_name varchar(150) DEFAULT NULL COMMENT '자산 설치 또는 보관 장소', serial_no varchar(100) DEFAULT NULL COMMENT '제조번호 또는 일련번호', acquisition_voucher_id varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '취득가액 전기 전표', note varchar(500) DEFAULT NULL COMMENT '자산 비고', created_at datetime NOT NULL DEFAULT current_timestamp() COMMENT '생성일시', created_by varchar(100) NOT NULL COMMENT '생성 Actor', updated_at datetime DEFAULT NULL COMMENT '수정일시', updated_by varchar(100) DEFAULT NULL COMMENT '수정 Actor', deleted_at datetime DEFAULT NULL COMMENT '삭제일시', deleted_by varchar(100) DEFAULT NULL COMMENT '삭제 Actor',
  PRIMARY KEY(id), UNIQUE KEY uk_ledger_assets_company_no(company_id,asset_no), KEY idx_ledger_assets_status(asset_status_code,acquisition_date), CONSTRAINT fk_ledger_assets_company FOREIGN KEY(company_id) REFERENCES system_company(id), CONSTRAINT fk_ledger_assets_project FOREIGN KEY(project_id) REFERENCES system_projects(id), CONSTRAINT fk_ledger_assets_asset_account FOREIGN KEY(asset_account_id) REFERENCES ledger_accounts(id), CONSTRAINT fk_ledger_assets_accumulated_account FOREIGN KEY(accumulated_account_id) REFERENCES ledger_accounts(id), CONSTRAINT fk_ledger_assets_expense_account FOREIGN KEY(expense_account_id) REFERENCES ledger_accounts(id), CONSTRAINT fk_ledger_assets_counter_account FOREIGN KEY(acquisition_counter_account_id) REFERENCES ledger_accounts(id), CONSTRAINT fk_ledger_assets_voucher FOREIGN KEY(acquisition_voucher_id) REFERENCES ledger_vouchers(id), CONSTRAINT chk_ledger_assets_amount CHECK(acquisition_amount>0 AND residual_amount>=0 AND residual_amount<acquisition_amount), CONSTRAINT chk_ledger_assets_life CHECK(useful_life_months>0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='취득부터 상각·이동·처분까지 고정자산 원본 대장';

CREATE TABLE ledger_asset_assignments (
 id char(36) NOT NULL COMMENT '자산 배치이력 고유번호', asset_id char(36) NOT NULL COMMENT '대상 고정자산', effective_date date NOT NULL COMMENT '배치 변경 적용일', business_unit varchar(50) NOT NULL COMMENT '이동 후 사업구분', project_id varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '이동 후 프로젝트', work_team_id varchar(36) DEFAULT NULL COMMENT '이동 후 팀', employee_id varchar(36) DEFAULT NULL COMMENT '이동 후 책임 직원', location_name varchar(150) DEFAULT NULL COMMENT '이동 후 장소', reason varchar(500) NOT NULL COMMENT '자산이동 사유', created_at datetime NOT NULL DEFAULT current_timestamp() COMMENT '생성일시', created_by varchar(100) NOT NULL COMMENT '처리 Actor', PRIMARY KEY(id), KEY idx_ledger_asset_assignments_asset(asset_id,effective_date), CONSTRAINT fk_ledger_asset_assignments_asset FOREIGN KEY(asset_id) REFERENCES ledger_assets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='자산의 프로젝트·팀·책임자·장소 이동 이력';

CREATE TABLE ledger_asset_depreciations (
 id char(36) NOT NULL COMMENT '감가상각 고유번호', asset_id char(36) NOT NULL COMMENT '대상 고정자산', depreciation_year_month char(7) NOT NULL COMMENT '감가상각 귀속연월', depreciation_date date NOT NULL COMMENT '감가상각 전기일', depreciation_amount decimal(18,2) NOT NULL COMMENT '당월 감가상각액', accumulated_amount decimal(18,2) NOT NULL COMMENT '상각 후 누계액', book_value_amount decimal(18,2) NOT NULL COMMENT '상각 후 장부가액', voucher_id varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '전기 완료된 감가상각 전표', created_at datetime NOT NULL DEFAULT current_timestamp() COMMENT '생성일시', created_by varchar(100) NOT NULL COMMENT '처리 Actor', PRIMARY KEY(id), UNIQUE KEY uk_ledger_asset_depreciations_month(asset_id,depreciation_year_month), CONSTRAINT fk_ledger_asset_depreciations_asset FOREIGN KEY(asset_id) REFERENCES ledger_assets(id), CONSTRAINT fk_ledger_asset_depreciations_voucher FOREIGN KEY(voucher_id) REFERENCES ledger_vouchers(id), CONSTRAINT chk_ledger_asset_depreciations_amount CHECK(depreciation_amount>0 AND accumulated_amount>=0 AND book_value_amount>=0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='월별 감가상각 계산 결과와 전기 전표';

CREATE TABLE ledger_asset_disposals (
 id char(36) NOT NULL COMMENT '자산처분 고유번호', asset_id char(36) NOT NULL COMMENT '처분 대상 고정자산', disposal_date date NOT NULL COMMENT '자산 처분일', disposal_type_code varchar(20) NOT NULL COMMENT '처분유형(SALE,SCRAP,LOSS)', proceeds_amount decimal(18,2) NOT NULL DEFAULT 0 COMMENT '처분 수입금액', book_value_amount decimal(18,2) NOT NULL COMMENT '처분 직전 장부가액', gain_loss_amount decimal(18,2) NOT NULL COMMENT '처분손익(이익 양수, 손실 음수)', proceeds_account_id varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '처분대금 수취 계정', gain_account_id varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '유형자산처분이익 계정', loss_account_id varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '유형자산처분손실 계정', voucher_id varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '전기 완료된 처분 전표', reason varchar(500) NOT NULL COMMENT '처분 근거와 사유', created_at datetime NOT NULL DEFAULT current_timestamp() COMMENT '생성일시', created_by varchar(100) NOT NULL COMMENT '처리 Actor', PRIMARY KEY(id), UNIQUE KEY uk_ledger_asset_disposals_asset(asset_id), CONSTRAINT fk_ledger_asset_disposals_asset FOREIGN KEY(asset_id) REFERENCES ledger_assets(id), CONSTRAINT fk_ledger_asset_disposals_proceeds_account FOREIGN KEY(proceeds_account_id) REFERENCES ledger_accounts(id), CONSTRAINT fk_ledger_asset_disposals_gain_account FOREIGN KEY(gain_account_id) REFERENCES ledger_accounts(id), CONSTRAINT fk_ledger_asset_disposals_loss_account FOREIGN KEY(loss_account_id) REFERENCES ledger_accounts(id), CONSTRAINT fk_ledger_asset_disposals_voucher FOREIGN KEY(voucher_id) REFERENCES ledger_vouchers(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='자산 매각·폐기·분실 처분 결과와 전기 전표';
