CREATE TABLE IF NOT EXISTS `ledger_voucher_line_source_refs` (
    `id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `company_id` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
    `source_ref_key` char(64) NOT NULL,
    `voucher_id` varchar(36) NOT NULL,
    `voucher_line_id` varchar(36) NOT NULL,
    `evidence_type` varchar(50) NOT NULL,
    `evidence_id` varchar(36) NOT NULL,
    `source_type` varchar(50) NOT NULL,
    `source_line_key` varchar(191) NOT NULL,
    `accounting_role_code` varchar(50) NOT NULL,
    `debit_credit` varchar(6) NOT NULL,
    `reference_action_code` varchar(20) NOT NULL DEFAULT 'ORIGINAL',
    `allocation_sequence` int unsigned NOT NULL DEFAULT 1,
    `source_amount` decimal(18,2) NOT NULL,
    `allocated_amount` decimal(18,2) NOT NULL,
    `journal_rule_id` varchar(36) NULL,
    `journal_rule_revision_no` int unsigned NULL,
    `recommendation_source_code` varchar(30) NOT NULL,
    `original_source_ref_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `planner_code` varchar(50) NOT NULL,
    `planner_snapshot` longtext NULL,
    `created_at` datetime NOT NULL DEFAULT current_timestamp(),
    `created_by` varchar(100) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_voucher_line_source_ref_key` (`source_ref_key`),
    KEY `idx_source_ref_voucher_line` (`company_id`,`voucher_id`,`voucher_line_id`),
    KEY `idx_source_ref_source_line` (`company_id`,`evidence_type`,`evidence_id`,`source_type`,`source_line_key`,`reference_action_code`),
    KEY `idx_source_ref_rule_revision` (`journal_rule_id`,`journal_rule_revision_no`),
    KEY `idx_source_ref_original` (`original_source_ref_id`),
    CONSTRAINT `fk_source_ref_company` FOREIGN KEY (`company_id`) REFERENCES `system_company` (`id`),
    CONSTRAINT `fk_source_ref_voucher` FOREIGN KEY (`voucher_id`) REFERENCES `ledger_vouchers` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_source_ref_voucher_line` FOREIGN KEY (`voucher_line_id`) REFERENCES `ledger_voucher_lines` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_source_ref_original` FOREIGN KEY (`original_source_ref_id`) REFERENCES `ledger_voucher_line_source_refs` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `chk_source_ref_side` CHECK (`debit_credit` IN ('DEBIT','CREDIT')),
    CONSTRAINT `chk_source_ref_action` CHECK (`reference_action_code` IN ('ORIGINAL','REVERSAL','CORRECTION')),
    CONSTRAINT `chk_source_ref_amounts` CHECK (`source_amount` >= 0 AND `allocated_amount` > 0),
    CONSTRAINT `chk_source_ref_rule_pair` CHECK ((`journal_rule_id` IS NULL AND `journal_rule_revision_no` IS NULL) OR (`journal_rule_id` IS NOT NULL AND `journal_rule_revision_no` IS NOT NULL)),
    CONSTRAINT `chk_source_ref_origin` CHECK (`recommendation_source_code` IN ('USER_MANUAL','CLIENT_DEFAULT','RECENT_POSTED','EVIDENCE_STRUCTURE','JOURNAL_RULE')),
    CONSTRAINT `chk_source_ref_original_link` CHECK ((`reference_action_code`='ORIGINAL' AND `original_source_ref_id` IS NULL) OR (`reference_action_code`<>'ORIGINAL' AND `original_source_ref_id` IS NOT NULL)),
    CONSTRAINT `chk_source_ref_planner_json` CHECK (`planner_snapshot` IS NULL OR JSON_VALID(`planner_snapshot`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='전표 Line과 증빙 원천 Line 배분 추적';

ALTER TABLE `ledger_journal_learning_events`
    ADD CONSTRAINT `fk_journal_learning_source_ref` FOREIGN KEY (`voucher_line_source_ref_id`) REFERENCES `ledger_voucher_line_source_refs` (`id`) ON DELETE RESTRICT;
