CREATE TABLE `auth_user_permission_overrides` (
  `id` varchar(36) NOT NULL COMMENT 'ID',
  `user_id` varchar(36) NOT NULL COMMENT '개별권한 대상 사용자',
  `permission_id` varchar(36) NOT NULL COMMENT '권한',
  `effect` varchar(10) NOT NULL COMMENT '개별권한 효과(ALLOW, DENY)',
  `reason` varchar(500) NOT NULL COMMENT '개별권한 변경 사유',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '생성일시',
  `created_by` varchar(100) NOT NULL COMMENT '생성자',
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '수정일시',
  `updated_by` varchar(100) NOT NULL COMMENT '수정자',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_auth_user_permission_override` (`user_id`, `permission_id`),
  KEY `idx_auth_user_permission_override_permission` (`permission_id`),
  CONSTRAINT `chk_auth_user_permission_override_effect` CHECK (`effect` IN ('ALLOW', 'DENY')),
  CONSTRAINT `fk_auth_user_permission_override_user` FOREIGN KEY (`user_id`) REFERENCES `auth_users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_auth_user_permission_override_permission` FOREIGN KEY (`permission_id`) REFERENCES `auth_permissions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='사용자별 개별 권한 Override 현재상태 SSOT';

CREATE TABLE `auth_user_permission_override_audits` (
  `id` varchar(36) NOT NULL COMMENT 'ID',
  `batch_id` varchar(36) NOT NULL COMMENT '전체 Set 저장 작업 ID',
  `user_id` varchar(36) DEFAULT NULL COMMENT '대상 사용자',
  `username_snapshot` varchar(50) NOT NULL COMMENT '대상 로그인 ID Snapshot',
  `employee_name_snapshot` varchar(50) DEFAULT NULL COMMENT '대상 직원명 Snapshot',
  `permission_id` varchar(36) DEFAULT NULL COMMENT '대상 권한',
  `permission_key_snapshot` varchar(100) NOT NULL COMMENT '권한키 Snapshot',
  `permission_name_snapshot` varchar(100) NOT NULL COMMENT '권한명 Snapshot',
  `before_effect` varchar(10) DEFAULT NULL COMMENT '변경 전 효과(NULL=INHERIT)',
  `after_effect` varchar(10) DEFAULT NULL COMMENT '변경 후 효과(NULL=INHERIT)',
  `role_allowed` tinyint(1) NOT NULL COMMENT '변경 당시 역할권한 여부',
  `effective_before` tinyint(1) NOT NULL COMMENT '변경 전 최종권한 여부',
  `effective_after` tinyint(1) NOT NULL COMMENT '변경 후 최종권한 여부',
  `reason` varchar(500) NOT NULL COMMENT '변경 사유',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '기록일시',
  `created_by` varchar(100) NOT NULL COMMENT '처리자',
  PRIMARY KEY (`id`),
  KEY `idx_auth_user_permission_override_audit_batch` (`batch_id`),
  KEY `idx_auth_user_permission_override_audit_user` (`user_id`, `created_at`),
  KEY `idx_auth_user_permission_override_audit_permission` (`permission_id`, `created_at`),
  CONSTRAINT `chk_auth_user_permission_override_audit_before` CHECK (`before_effect` IS NULL OR `before_effect` IN ('ALLOW', 'DENY')),
  CONSTRAINT `chk_auth_user_permission_override_audit_after` CHECK (`after_effect` IS NULL OR `after_effect` IN ('ALLOW', 'DENY')),
  CONSTRAINT `fk_auth_user_permission_override_audit_user` FOREIGN KEY (`user_id`) REFERENCES `auth_users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_auth_user_permission_override_audit_permission` FOREIGN KEY (`permission_id`) REFERENCES `auth_permissions` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='사용자별 개별 권한 Override 영구 감사이력';
