CREATE TABLE `approval_personal_expense_item_classification_corrections` (
    `id` varchar(36) NOT NULL COMMENT '정정 Revision ID',
    `company_id` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '회사 ID',
    `personal_expense_id` varchar(36) NOT NULL COMMENT '개인경비 문서 ID',
    `personal_expense_item_id` varchar(36) NOT NULL COMMENT '개인경비 Item ID',
    `approval_request_id` varchar(36) NOT NULL COMMENT '최종승인 요청 ID',
    `evidence_id` varchar(36) NOT NULL COMMENT '기존 Evidence ID',
    `revision_no` int unsigned NOT NULL COMMENT 'Item별 연속 Revision',
    `previous_correction_id` varchar(36) DEFAULT NULL COMMENT '직전 정정 Revision ID',
    `original_category` varchar(50) NOT NULL COMMENT '승인 Item 원본분류',
    `previous_effective_category` varchar(50) NOT NULL COMMENT '정정 직전 유효분류',
    `corrected_category` varchar(50) NOT NULL COMMENT '정정 후 유효분류',
    `amount_snapshot` decimal(18,2) NOT NULL COMMENT '승인 Item 금액 Snapshot',
    `correction_reason` varchar(500) NOT NULL COMMENT '정정 사유',
    `correction_batch_key` varchar(100) NOT NULL COMMENT '일괄 정정 멱등키',
    `request_key` varchar(100) NOT NULL COMMENT '정정 요청 멱등키',
    `processed_at` datetime NOT NULL COMMENT '정정 처리일시',
    `processed_by` varchar(100) NOT NULL COMMENT '정정 처리 Actor',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_personal_expense_classification_item_revision` (`personal_expense_item_id`,`revision_no`),
    UNIQUE KEY `uk_personal_expense_classification_request` (`company_id`,`request_key`),
    KEY `idx_personal_expense_classification_item` (`personal_expense_id`,`personal_expense_item_id`),
    KEY `idx_personal_expense_classification_approval` (`approval_request_id`),
    KEY `idx_personal_expense_classification_evidence` (`evidence_id`),
    KEY `idx_personal_expense_classification_batch` (`correction_batch_key`),
    KEY `idx_personal_expense_classification_previous` (`previous_correction_id`),
    CONSTRAINT `fk_personal_expense_classification_company` FOREIGN KEY (`company_id`) REFERENCES `system_company` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT `fk_personal_expense_classification_header` FOREIGN KEY (`personal_expense_id`) REFERENCES `approval_personal_expenses` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT `fk_personal_expense_classification_item` FOREIGN KEY (`personal_expense_item_id`) REFERENCES `approval_personal_expense_items` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT `fk_personal_expense_classification_approval` FOREIGN KEY (`approval_request_id`) REFERENCES `user_approval_requests` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT `fk_personal_expense_classification_evidence` FOREIGN KEY (`evidence_id`) REFERENCES `ledger_evidence_employee_personal_expense` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT `fk_personal_expense_classification_previous` FOREIGN KEY (`previous_correction_id`) REFERENCES `approval_personal_expense_item_classification_corrections` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT `chk_personal_expense_classification_revision` CHECK (`revision_no` >= 1),
    CONSTRAINT `chk_personal_expense_classification_amount` CHECK (`amount_snapshot` > 0),
    CONSTRAINT `chk_personal_expense_classification_original` CHECK (`original_category` <> `corrected_category`),
    CONSTRAINT `chk_personal_expense_classification_previous_effective` CHECK (`previous_effective_category` <> `corrected_category`),
    CONSTRAINT `chk_personal_expense_classification_reason` CHECK (CHAR_LENGTH(TRIM(`correction_reason`)) > 0),
    CONSTRAINT `chk_personal_expense_classification_actor` CHECK (CHAR_LENGTH(TRIM(`processed_by`)) > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='승인 개인경비 Item 회계분류 불변 정정 Revision';
