CREATE TABLE `institution_workplace_size_periods` (
  `id` varchar(36) NOT NULL COMMENT '회사규모 기간 Revision ID',
  `company_id` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '회사 ID',
  `calculation_purpose_code` varchar(60) NOT NULL COMMENT '규모 산정 목적 코드',
  `effective_from` date NOT NULL COMMENT '적용 시작일',
  `effective_to` date DEFAULT NULL COMMENT '적용 종료일',
  `business_size_code` varchar(60) NOT NULL COMMENT '안정적인 규모구분 코드',
  `business_size_name_snapshot` varchar(100) NOT NULL COMMENT '등록 당시 표시명 Snapshot',
  `regular_worker_count` int unsigned NOT NULL COMMENT '당시 상시근로자 수',
  `calculation_basis_description` varchar(1000) NOT NULL COMMENT '당시 규모 산정기준',
  `evidence_type_code` varchar(30) NOT NULL COMMENT 'OFFICIAL_CONFIRMED/MANUAL_CONFIRMED/HISTORICAL_IMPORT',
  `evidence_id` varchar(36) DEFAULT NULL COMMENT '근거 원문 ID',
  `evidence_description` varchar(1000) DEFAULT NULL COMMENT '근거 설명',
  `statutory_standard_id` varchar(36) DEFAULT NULL COMMENT '법정기준 Revision ID',
  `confirmation_status_code` varchar(30) NOT NULL COMMENT 'DRAFT/CONFIRMED',
  `confirmed_at` datetime DEFAULT NULL COMMENT '확정일시',
  `confirmed_by` varchar(100) DEFAULT NULL COMMENT '확정 Actor',
  `revision_no` int unsigned NOT NULL COMMENT '기간별 불변 Revision 번호',
  `previous_period_id` varchar(36) DEFAULT NULL COMMENT '직전 Revision ID',
  `correction_reason` varchar(1000) DEFAULT NULL COMMENT '정정 또는 기간종료 사유',
  `request_key` varchar(100) NOT NULL COMMENT '멱등 요청키',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_workplace_size_request` (`company_id`,`request_key`),
  UNIQUE KEY `uk_workplace_size_revision` (`company_id`,`calculation_purpose_code`,`effective_from`,`revision_no`),
  UNIQUE KEY `uk_workplace_size_previous` (`previous_period_id`),
  KEY `idx_workplace_size_resolve` (`company_id`,`calculation_purpose_code`,`confirmation_status_code`,`effective_from`,`effective_to`),
  KEY `idx_workplace_size_code` (`calculation_purpose_code`,`business_size_code`),
  KEY `idx_workplace_size_statutory` (`statutory_standard_id`),
  CONSTRAINT `fk_workplace_size_company` FOREIGN KEY (`company_id`) REFERENCES `system_company` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_workplace_size_previous` FOREIGN KEY (`previous_period_id`) REFERENCES `institution_workplace_size_periods` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_workplace_size_statutory` FOREIGN KEY (`statutory_standard_id`) REFERENCES `system_statutory_standards` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_workplace_size_period` CHECK (`effective_to` IS NULL OR `effective_to` >= `effective_from`),
  CONSTRAINT `chk_workplace_size_workers` CHECK (`regular_worker_count` >= 0),
  CONSTRAINT `chk_workplace_size_evidence` CHECK (`evidence_type_code` IN ('OFFICIAL_CONFIRMED','MANUAL_CONFIRMED','HISTORICAL_IMPORT')),
  CONSTRAINT `chk_workplace_size_confirmation` CHECK (`confirmation_status_code` IN ('DRAFT','CONFIRMED')),
  CONSTRAINT `chk_workplace_size_confirmed_actor` CHECK ((`confirmation_status_code` = 'DRAFT' AND `confirmed_at` IS NULL AND `confirmed_by` IS NULL) OR (`confirmation_status_code` = 'CONFIRMED' AND `confirmed_at` IS NOT NULL AND `confirmed_by` IS NOT NULL)),
  CONSTRAINT `chk_workplace_size_revision` CHECK ((`revision_no` = 1 AND `previous_period_id` IS NULL AND `correction_reason` IS NULL) OR (`revision_no` > 1 AND `previous_period_id` IS NOT NULL AND CHAR_LENGTH(TRIM(`correction_reason`)) > 0)),
  CONSTRAINT `chk_workplace_size_evidence_detail` CHECK (`evidence_id` IS NOT NULL OR CHAR_LENGTH(TRIM(COALESCE(`evidence_description`,''))) > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='계산목적별 회사규모 기간 불변 Revision SSOT';

ALTER TABLE `institution_regular_employment_income_line_items`
  ADD COLUMN `application_status_code` varchar(30) DEFAULT NULL COMMENT 'APPLICABLE/EXCLUDED/NOT_APPLICABLE' AFTER `calculation_source_code`,
  ADD COLUMN `calculation_basis_amount` decimal(18,2) DEFAULT NULL COMMENT '계산기초 금액' AFTER `application_status_code`,
  ADD COLUMN `calculation_rate` decimal(18,10) DEFAULT NULL COMMENT '계산 적용 요율' AFTER `calculation_basis_amount`,
  ADD COLUMN `calculation_before_rounding` decimal(24,10) DEFAULT NULL COMMENT '끝수처리 전 계산금액' AFTER `calculation_rate`,
  ADD COLUMN `rounding_method_code` varchar(30) DEFAULT NULL COMMENT 'TRUNCATE/ROUND/ROUND_UP/CEIL' AFTER `calculation_before_rounding`,
  ADD COLUMN `rounding_unit` decimal(18,4) DEFAULT NULL COMMENT '끝수처리 단위' AFTER `rounding_method_code`,
  ADD COLUMN `statutory_standard_id` varchar(36) DEFAULT NULL COMMENT '사용 법정기준 Revision' AFTER `rounding_unit`,
  ADD COLUMN `social_insurance_coverage_id` varchar(36) DEFAULT NULL COMMENT '사용 사회보험 Coverage' AFTER `statutory_standard_id`,
  ADD COLUMN `workplace_size_period_id` varchar(36) DEFAULT NULL COMMENT '사용 회사규모 기간 Revision' AFTER `social_insurance_coverage_id`,
  ADD KEY `idx_regular_income_line_statutory` (`statutory_standard_id`),
  ADD KEY `idx_regular_income_line_coverage` (`social_insurance_coverage_id`),
  ADD KEY `idx_regular_income_line_workplace_size` (`workplace_size_period_id`),
  ADD CONSTRAINT `fk_regular_income_line_statutory` FOREIGN KEY (`statutory_standard_id`) REFERENCES `system_statutory_standards` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `fk_regular_income_line_coverage` FOREIGN KEY (`social_insurance_coverage_id`) REFERENCES `institution_social_insurance_coverages` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `fk_regular_income_line_workplace_size` FOREIGN KEY (`workplace_size_period_id`) REFERENCES `institution_workplace_size_periods` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `chk_regular_income_line_application` CHECK (`application_status_code` IS NULL OR `application_status_code` IN ('APPLICABLE','EXCLUDED','NOT_APPLICABLE')),
  ADD CONSTRAINT `chk_regular_income_line_basis_amount` CHECK (`calculation_basis_amount` IS NULL OR `calculation_basis_amount` >= 0),
  ADD CONSTRAINT `chk_regular_income_line_rate` CHECK (`calculation_rate` IS NULL OR (`calculation_rate` >= 0 AND `calculation_rate` <= 1)),
  ADD CONSTRAINT `chk_regular_income_line_rounding_unit` CHECK (`rounding_unit` IS NULL OR `rounding_unit` > 0),
  ADD CONSTRAINT `chk_regular_income_line_rounding_method` CHECK (`rounding_method_code` IS NULL OR `rounding_method_code` IN ('TRUNCATE','ROUND','ROUND_UP','CEIL'));
