CREATE TABLE IF NOT EXISTS `ledger_evidence_bank_transaction` (
    `id` VARCHAR(36) NOT NULL COMMENT 'ID',
    `sort_no` INT(10) UNSIGNED NOT NULL COMMENT '순번',
    `evidence_sort_no` BIGINT(20) UNSIGNED NOT NULL COMMENT '증빙전체순번',
    `external_key` VARCHAR(120) NULL DEFAULT NULL COMMENT '외부원본식별값',
    `source_type` VARCHAR(40) NOT NULL COMMENT '자료출처',
    `import_type` VARCHAR(30) NULL DEFAULT NULL COMMENT '자료유형',
    `business_unit` VARCHAR(30) NULL DEFAULT NULL COMMENT '사업구분',
    `transaction_direction` VARCHAR(30) NOT NULL COMMENT '거래구분',
    `operation_type` VARCHAR(30) NULL DEFAULT NULL COMMENT '업무유형',
    `client_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '거래처',
    `project_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '프로젝트',
    `bank_account_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '계좌',
    `card_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '카드',
    `team_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '팀',
    `employee_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '직원',
    `raw_transaction_datetime` DATETIME NULL DEFAULT NULL COMMENT '거래일시',
    `raw_deposit_amount` DECIMAL(18,2) NULL DEFAULT 0.00 COMMENT '입금',
    `raw_withdraw_amount` DECIMAL(18,2) NULL DEFAULT 0.00 COMMENT '출금',
    `raw_balance_amount` DECIMAL(18,2) UNSIGNED ZEROFILL NULL DEFAULT NULL COMMENT '거래 후 잔액',
    `raw_description` VARCHAR(500) NULL DEFAULT NULL COMMENT '거래내용',
    `raw_counterparty_account_number` VARCHAR(100) NULL DEFAULT NULL COMMENT '상대계좌번호',
    `raw_counterparty_bank_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '상대은행',
    `raw_memo` TEXT NULL DEFAULT NULL COMMENT '메모',
    `raw_transaction_type` VARCHAR(100) NULL DEFAULT NULL COMMENT '원본 거래구분',
    `raw_check_bill_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '수표어음금액',
    `raw_cms_code` VARCHAR(10) NULL DEFAULT NULL COMMENT 'CMS코드',
    `raw_counterparty_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '상대계좌예금주명',
    `evidence_status` VARCHAR(30) NOT NULL COMMENT '증빙 상태',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    `created_by` VARCHAR(100) NULL DEFAULT NULL COMMENT '생성자',
    `updated_at` DATETIME NULL DEFAULT NULL COMMENT '수정일시',
    `updated_by` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정자',
    `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '삭제일시',
    `deleted_by` VARCHAR(100) NULL DEFAULT NULL COMMENT '삭제자',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_evb_evidence_sort_no` (`evidence_sort_no`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci
  COMMENT='Runtime SSOT body table for BANK_TRANSACTION';

CREATE TABLE IF NOT EXISTS `ledger_evidence_tax_invoice_manual` (
    `id` VARCHAR(36) NOT NULL COMMENT 'ID',
    `sort_no` INT(10) UNSIGNED NOT NULL COMMENT '순번',
    `evidence_sort_no` BIGINT(20) UNSIGNED NOT NULL COMMENT '증빙전체순번',
    `external_key` VARCHAR(120) NULL DEFAULT NULL COMMENT '외부원본식별값',
    `source_type` VARCHAR(40) NOT NULL COMMENT '자료출처',
    `import_type` VARCHAR(30) NULL DEFAULT NULL COMMENT '자료유형',
    `business_unit` VARCHAR(30) NULL DEFAULT NULL COMMENT '사업구분',
    `transaction_direction` VARCHAR(30) NULL DEFAULT NULL COMMENT '거래구분',
    `operation_type` VARCHAR(30) NULL DEFAULT NULL COMMENT '업무유형',
    `client_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '거래처',
    `project_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '프로젝트',
    `bank_account_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '계좌',
    `card_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '카드',
    `team_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '팀',
    `employee_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '직원',
    `raw_written_date` DATE NULL DEFAULT NULL COMMENT '작성일자',
    `raw_supplier_business_number` VARCHAR(20) NULL DEFAULT NULL COMMENT '공급자사업자등록번호',
    `raw_supplier_branch_no` VARCHAR(20) NULL DEFAULT NULL COMMENT '공급자종사업장번호',
    `raw_supplier_company_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '공급자상호',
    `raw_supplier_ceo_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '공급자대표자명',
    `raw_supplier_address` VARCHAR(500) NULL DEFAULT NULL COMMENT '공급자주소',
    `raw_customer_business_number` VARCHAR(20) NULL DEFAULT NULL COMMENT '공급받는자사업자등록번호',
    `raw_customer_branch_no` VARCHAR(20) NULL DEFAULT NULL COMMENT '공급받는자종사업장번호',
    `raw_customer_company_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '공급받는자상호',
    `raw_customer_ceo_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '공급받는자대표자명',
    `raw_customer_address` VARCHAR(500) NULL DEFAULT NULL COMMENT '공급받는자주소',
    `raw_total_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '합계금액',
    `raw_supply_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '공급가액',
    `raw_vat_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '세액',
    `raw_note` TEXT NULL DEFAULT NULL COMMENT '비고',
    `raw_claim_type` VARCHAR(30) NULL DEFAULT NULL COMMENT '영수청구구분',
    `raw_item_date` DATETIME NULL DEFAULT NULL COMMENT '품목일자',
    `raw_item_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '품목명',
    `raw_item_spec` VARCHAR(255) NULL DEFAULT NULL COMMENT '품목규격',
    `raw_item_quantity` DECIMAL(18,4) NULL DEFAULT NULL COMMENT '품목수량',
    `raw_item_unit_price` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '품목단가',
    `raw_item_supply_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '품목공급가액',
    `raw_item_tax_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '품목세액',
    `raw_item_note` VARCHAR(500) NULL DEFAULT NULL COMMENT '품목비고',
    `evidence_status` VARCHAR(30) NOT NULL COMMENT '증빙 상태',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    `created_by` VARCHAR(100) NULL DEFAULT NULL COMMENT '생성자',
    `updated_at` DATETIME NULL DEFAULT NULL COMMENT '수정일시',
    `updated_by` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정자',
    `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '삭제일시',
    `deleted_by` VARCHAR(100) NULL DEFAULT NULL COMMENT '삭제자',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE KEY `uk_evti_evidence_sort_no` (`evidence_sort_no`) USING BTREE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci
  COMMENT='Runtime SSOT body table for TAX_INVOICE_MANUAL';

CREATE TABLE IF NOT EXISTS `ledger_evidence_card_hometax` (
    `id` VARCHAR(36) NOT NULL COMMENT 'ID',
    `sort_no` INT(10) UNSIGNED NOT NULL COMMENT '순번',
    `evidence_sort_no` BIGINT(20) UNSIGNED NOT NULL COMMENT '증빙전체순번',
    `external_key` VARCHAR(120) NULL DEFAULT NULL COMMENT '외부원본식별값',
    `source_type` VARCHAR(40) NOT NULL COMMENT '자료출처',
    `import_type` VARCHAR(30) NULL DEFAULT NULL COMMENT '자료유형',
    `business_unit` VARCHAR(30) NULL DEFAULT NULL COMMENT '사업구분',
    `transaction_direction` VARCHAR(30) NULL DEFAULT NULL COMMENT '거래구분',
    `operation_type` VARCHAR(30) NULL DEFAULT NULL COMMENT '업무유형',
    `client_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '거래처',
    `project_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '프로젝트',
    `bank_account_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '계좌',
    `card_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '카드',
    `team_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '팀',
    `employee_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '직원',
    `raw_approval_date` DATE NULL DEFAULT NULL COMMENT '승인일자',
    `raw_card_company_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '카드사',
    `raw_card_number` VARCHAR(120) NULL DEFAULT NULL COMMENT '카드번호',
    `raw_merchant_business_number` VARCHAR(20) NULL DEFAULT NULL COMMENT '가맹점사업자번호',
    `raw_merchant_company_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '가맹점명',
    `raw_supply_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '공급가액',
    `raw_vat_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '세액',
    `raw_tax_free_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '비과세',
    `raw_total_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '합계',
    `raw_merchant_type` VARCHAR(100) NULL DEFAULT NULL COMMENT '가맹점유형',
    `raw_business_type` VARCHAR(255) NULL DEFAULT NULL COMMENT '업태',
    `raw_business_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '업종',
    `raw_deduction_status` VARCHAR(100) NULL DEFAULT NULL COMMENT '공제여부',
    `raw_note` TEXT NULL DEFAULT NULL COMMENT '비고',
    `evidence_status` VARCHAR(30) NOT NULL COMMENT '증빙 상태',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    `created_by` VARCHAR(100) NULL DEFAULT NULL COMMENT '생성자',
    `updated_at` DATETIME NULL DEFAULT NULL COMMENT '수정일시',
    `updated_by` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정자',
    `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '삭제일시',
    `deleted_by` VARCHAR(100) NULL DEFAULT NULL COMMENT '삭제자',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_evcp_evidence_sort_no` (`evidence_sort_no`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci
  COMMENT='Runtime SSOT body table for CARD_HOMETAX';

CREATE TABLE IF NOT EXISTS `ledger_evidence_card_statement` (
    `id` VARCHAR(36) NOT NULL COMMENT 'ID',
    `sort_no` INT(10) UNSIGNED NOT NULL COMMENT '순번',
    `evidence_sort_no` BIGINT(20) UNSIGNED NOT NULL COMMENT '증빙전체순번',
    `external_key` VARCHAR(120) NULL DEFAULT NULL COMMENT '외부원본식별값',
    `source_type` VARCHAR(40) NOT NULL COMMENT '증빙유형 코드',
    `import_type` VARCHAR(30) NULL DEFAULT NULL COMMENT '자료유형',
    `business_unit` VARCHAR(30) NULL DEFAULT NULL COMMENT '사업구분',
    `transaction_direction` VARCHAR(30) NULL DEFAULT NULL COMMENT '거래구분',
    `operation_type` VARCHAR(30) NULL DEFAULT NULL COMMENT '업무유형',
    `client_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '거래처',
    `project_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '프로젝트',
    `bank_account_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '계좌',
    `card_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '카드',
    `team_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '팀',
    `employee_id` VARCHAR(36) NULL DEFAULT NULL COMMENT '직원',
    `raw_receive_info_type_code` VARCHAR(50) NULL DEFAULT NULL COMMENT '수신정보구분코드',
    `raw_card_number` VARCHAR(120) NULL DEFAULT NULL COMMENT '카드번호',
    `raw_card_type` VARCHAR(100) NULL DEFAULT NULL COMMENT '카드종류',
    `raw_payment_account_number` VARCHAR(100) NULL DEFAULT NULL COMMENT '결제계좌번호',
    `raw_payment_account_bank_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '결제계좌은행명',
    `raw_holder_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '지정자한글명',
    `raw_domestic_overseas_type` VARCHAR(30) NULL DEFAULT NULL COMMENT '국내외사용구분',
    `raw_approval_number` VARCHAR(50) NULL DEFAULT NULL COMMENT '승인번호',
    `raw_approval_date` DATE NULL DEFAULT NULL COMMENT '승인일자',
    `raw_sales_type` VARCHAR(50) NULL DEFAULT NULL COMMENT '매출종류',
    `raw_amount_sign_code` VARCHAR(20) NULL DEFAULT NULL COMMENT '금액SIGN코드',
    `raw_transaction_amount_krw` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '거래금액(원화)',
    `raw_vat_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '부가세',
    `raw_service_fee_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '봉사료',
    `raw_installment_period` VARCHAR(20) NULL DEFAULT NULL COMMENT '할부기간',
    `raw_installment_round` VARCHAR(20) NULL DEFAULT NULL COMMENT '할부회차',
    `raw_purchase_amount_krw` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '매입금액(원화)',
    `raw_billing_date` DATE NULL DEFAULT NULL COMMENT '청구일자',
    `raw_billing_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '청구금액',
    `raw_billing_fee_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '청구수수료',
    `raw_actual_billing_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '실청구금액',
    `raw_prior_notice_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '기통지액',
    `raw_transaction_amount_foreign` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '거래금액(외화)',
    `raw_local_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '현지금액',
    `raw_local_currency_code` VARCHAR(20) NULL DEFAULT NULL COMMENT '현지화폐코드',
    `raw_exchange_rate` DECIMAL(18,6) NULL DEFAULT NULL COMMENT '외화거래일환율',
    `raw_country_code` VARCHAR(20) NULL DEFAULT NULL COMMENT '외화거래국가코드',
    `raw_country_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '외화거래국가명',
    `raw_city_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '외화거래도시명',
    `raw_merchant_business_number` VARCHAR(20) NULL DEFAULT NULL COMMENT '가맹점사업자번호',
    `raw_merchant_company_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '가맹점명',
    `raw_merchant_business_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '가맹점업종',
    `raw_merchant_zip_code` VARCHAR(20) NULL DEFAULT NULL COMMENT '가맹점우편번호',
    `raw_merchant_address1` VARCHAR(255) NULL DEFAULT NULL COMMENT '가맹점주소1',
    `raw_merchant_address2` VARCHAR(255) NULL DEFAULT NULL COMMENT '가맹점주소2',
    `raw_merchant_phone` VARCHAR(50) NULL DEFAULT NULL COMMENT '가맹점전화번호',
    `raw_account_code_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '회계코드명',
    `raw_account_code` VARCHAR(100) NULL DEFAULT NULL COMMENT '회계코드',
    `raw_headquarters_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '본부명',
    `raw_department_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '부서명',
    `evidence_status` VARCHAR(30) NOT NULL COMMENT '증빙 상태',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    `created_by` VARCHAR(100) NULL DEFAULT NULL COMMENT '생성자',
    `updated_at` DATETIME NULL DEFAULT NULL COMMENT '수정일시',
    `updated_by` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정자',
    `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '삭제일시',
    `deleted_by` VARCHAR(100) NULL DEFAULT NULL COMMENT '삭제자',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE KEY `uk_evcs_evidence_sort_no` (`evidence_sort_no`) USING BTREE,
    KEY `idx_evcs_sort_no` (`sort_no`) USING BTREE,
    KEY `idx_evcs_source_date` (`source_type`,`raw_approval_date`) USING BTREE,
    KEY `idx_evcs_external_key` (`external_key`) USING BTREE,
    KEY `idx_evcs_card_number` (`raw_card_number`) USING BTREE,
    KEY `idx_evcs_approval_number` (`raw_approval_number`) USING BTREE,
    KEY `idx_evcs_merchant_bn` (`raw_merchant_business_number`) USING BTREE,
    KEY `idx_evcs_client_id` (`client_id`) USING BTREE,
    KEY `idx_evcs_project_id` (`project_id`) USING BTREE,
    KEY `idx_evcs_card_id` (`card_id`) USING BTREE,
    KEY `idx_evcs_bank_account_id` (`bank_account_id`) USING BTREE,
    KEY `idx_evcs_deleted_at` (`deleted_at`) USING BTREE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci
  COMMENT='Runtime SSOT body table for CARD_STATEMENT';
