CREATE TABLE IF NOT EXISTS `system_page_registry` (
    `page_key` VARCHAR(191) NOT NULL COMMENT '공통 page 식별자',
    `module_key` VARCHAR(100) NOT NULL COMMENT '최상위 모듈 key',
    `module_label` VARCHAR(100) NOT NULL COMMENT '최상위 모듈 표시명',
    `menu_key` VARCHAR(191) NOT NULL COMMENT '메뉴 key',
    `menu_label` VARCHAR(100) NOT NULL COMMENT '메뉴 표시명',
    `page_label` VARCHAR(100) NOT NULL COMMENT '화면 표시명',
    `page_description` VARCHAR(255) NULL DEFAULT NULL COMMENT '화면 설명',
    `breadcrumb` VARCHAR(255) NOT NULL COMMENT '모듈 > 메뉴 > 화면 경로',
    `default_route_key` VARCHAR(191) NULL DEFAULT NULL COMMENT '대표 WEB route key',
    `default_route_url` VARCHAR(255) NULL DEFAULT NULL COMMENT '대표 WEB route URL',
    `source_description` VARCHAR(255) NOT NULL COMMENT '초기 생성에 사용한 source description',
    `is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '활성 여부',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (`page_key`),
    KEY `idx_system_page_registry_module` (`module_key`),
    KEY `idx_system_page_registry_menu` (`menu_key`),
    KEY `idx_system_page_registry_default_route_key` (`default_route_key`),
    KEY `idx_system_page_registry_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='ERP 공통 Page Registry';

INSERT INTO `system_page_registry` (
    `page_key`,
    `module_key`,
    `module_label`,
    `menu_key`,
    `menu_label`,
    `page_label`,
    `page_description`,
    `breadcrumb`,
    `default_route_key`,
    `default_route_url`,
    `source_description`,
    `is_active`
) VALUES
('approval.dashboard', 'approval', '전자결재', 'approval.main', '결재', '전자결재', '전자결재 > 결재 > 전자결재', '전자결재 > 결재 > 전자결재', 'web.approval.index', '/approval', '전자결재 > 결재 > 전자결재', 1),
('auth.account_lock', 'auth', '인증', 'auth.security', '계정보안', '계정잠금', '인증 > 계정보안 > 계정잠금', '인증 > 계정보안 > 계정잠금', NULL, NULL, '인증 > 계정보안 > 계정잠금', 1),
('dashboard.activity', 'dashboard', '대시보드', 'dashboard.main', '대시보드', '최근 활동', '대시보드 > 대시보드 > 최근 활동', '대시보드 > 대시보드 > 최근 활동', 'web.dashboard.activity', '/dashboard/activity', '대시보드 > 대시보드 > 최근 활동', 1),
('dashboard.calendar', 'dashboard', '대시보드', 'dashboard.main', '대시보드', '일정/캘린더', '대시보드 > 대시보드 > 일정/캘린더', '대시보드 > 대시보드 > 일정/캘린더', 'web.dashboard.calendar', '/dashboard/calendar', '대시보드 > 대시보드 > 일정/캘린더', 1),
('dashboard.kpi', 'dashboard', '대시보드', 'dashboard.main', '대시보드', '실적 현황', '대시보드 > 대시보드 > 실적 현황', '대시보드 > 대시보드 > 실적 현황', 'web.dashboard.kpi', '/dashboard/kpi', '대시보드 > 대시보드 > 실적 현황', 1),
('dashboard.main', 'dashboard', '대시보드', 'dashboard.main', '대시보드', '대시보드', '대시보드 > 대시보드 > 대시보드', '대시보드 > 대시보드 > 대시보드', 'web.dashboard.main', '/dashboard', '대시보드 > 대시보드 > 대시보드', 1),
('dashboard.notifications', 'dashboard', '대시보드', 'dashboard.main', '대시보드', '공지사항', '대시보드 > 대시보드 > 공지사항', '대시보드 > 대시보드 > 공지사항', 'web.dashboard.notifications', '/dashboard/notifications', '대시보드 > 대시보드 > 공지사항', 1),
('dashboard.report', 'dashboard', '대시보드', 'dashboard.main', '대시보드', '통합 보고서', '대시보드 > 대시보드 > 통합 보고서', '대시보드 > 대시보드 > 통합 보고서', 'web.dashboard.report', '/dashboard/report', '대시보드 > 대시보드 > 통합 보고서', 1),
('dashboard.settings', 'dashboard', '대시보드', 'dashboard.main', '대시보드', '설정', '대시보드 > 대시보드 > 설정', '대시보드 > 대시보드 > 설정', 'web.dashboard.settings', '/dashboard/settings', '대시보드 > 대시보드 > 설정', 1),
('document.dashboard', 'document', '내부문서', 'document.main', '문서', '문서관리', '내부문서 > 문서 > 문서관리', '내부문서 > 문서 > 문서관리', 'web.document.index', '/document', '내부문서 > 문서 > 문서관리', 1),
('document.edit', 'document', '내부문서', 'document.main', '문서', '문서수정', '내부문서 > 문서 > 문서수정', '내부문서 > 문서 > 문서수정', 'web.document.edit', '/document/edit', '내부문서 > 문서 > 문서수정', 1),
('document.file_register', 'document', '내부문서', 'document.main', '문서', '문서등록', '내부문서 > 문서 > 문서등록', '내부문서 > 문서 > 문서등록', 'web.document.file_register', '/document/file_register', '내부문서 > 문서 > 문서등록', 1),
('document.stats', 'document', '내부문서', 'document.main', '문서', '문서통계', '내부문서 > 문서 > 문서통계', '내부문서 > 문서 > 문서통계', 'web.document.stats', '/document/stats', '내부문서 > 문서 > 문서통계', 1),
('document.view', 'document', '내부문서', 'document.main', '문서', '문서보기', '내부문서 > 문서 > 문서보기', '내부문서 > 문서 > 문서보기', 'web.document.view', '/document/view', '내부문서 > 문서 > 문서보기', 1),
('institution.dashboard', 'institution', '대외기관업무', 'institution.main', '대외기관', '대외기관업무', '대외기관업무 > 대외기관 > 대외기관업무', '대외기관업무 > 대외기관 > 대외기관업무', 'web.institution.index', '/institution', '대외기관업무 > 대외기관 > 대외기관업무', 1),
('ledger.assets.create', 'ledger', '회계관리', 'ledger.asset', '자산관리', '자산등록', '회계관리 > 자산관리 > 자산등록', '회계관리 > 자산관리 > 자산등록', 'web.ledger.assets.create', NULL, '회계관리 > 자산관리 > 자산등록', 1),
('ledger.assets.depreciation', 'ledger', '회계관리', 'ledger.asset', '자산관리', '감가상각', '회계관리 > 자산관리 > 감가상각', '회계관리 > 자산관리 > 감가상각', 'web.ledger.assets.depreciation', NULL, '회계관리 > 자산관리 > 감가상각', 1),
('ledger.assets.disposal', 'ledger', '회계관리', 'ledger.asset', '자산관리', '자산폐기', '회계관리 > 자산관리 > 자산폐기', '회계관리 > 자산관리 > 자산폐기', 'web.ledger.assets.disposal', NULL, '회계관리 > 자산관리 > 자산폐기', 1),
('ledger.assets.index', 'ledger', '회계관리', 'ledger.asset', '자산관리', '자산목록', '회계관리 > 자산관리 > 자산목록', '회계관리 > 자산관리 > 자산목록', 'web.ledger.assets.index', NULL, '회계관리 > 자산관리 > 자산목록', 1),
('ledger.assets.transfer', 'ledger', '회계관리', 'ledger.asset', '자산관리', '자산이관', '회계관리 > 자산관리 > 자산이관', '회계관리 > 자산관리 > 자산이관', 'web.ledger.assets.transfer', NULL, '회계관리 > 자산관리 > 자산이관', 1),
('ledger.book.account', 'ledger', '회계관리', 'ledger.book', '장부관리', '계정별원장', '회계관리 > 장부관리 > 계정별원장', '회계관리 > 장부관리 > 계정별원장', 'web.ledger.book.account', NULL, '회계관리 > 장부관리 > 계정별원장', 1),
('ledger.book.daily', 'ledger', '회계관리', 'ledger.book', '장부관리', '일계표', '회계관리 > 장부관리 > 일계표', '회계관리 > 장부관리 > 일계표', 'web.ledger.book.daily', NULL, '회계관리 > 장부관리 > 일계표', 1),
('ledger.book.general', 'ledger', '회계관리', 'ledger.book', '장부관리', '총계정원장', '회계관리 > 장부관리 > 총계정원장', '회계관리 > 장부관리 > 총계정원장', 'web.ledger.book.general', NULL, '회계관리 > 장부관리 > 총계정원장', 1),
('ledger.book.journal', 'ledger', '회계관리', 'ledger.book', '장부관리', '분개장', '회계관리 > 장부관리 > 분개장', '회계관리 > 장부관리 > 분개장', 'web.ledger.book.journal', NULL, '회계관리 > 장부관리 > 분개장', 1),
('ledger.book.partner', 'ledger', '회계관리', 'ledger.book', '장부관리', '거래처원장', '회계관리 > 장부관리 > 거래처원장', '회계관리 > 장부관리 > 거래처원장', 'web.ledger.book.partner', NULL, '회계관리 > 장부관리 > 거래처원장', 1),
('ledger.book.project', 'ledger', '회계관리', 'ledger.book', '장부관리', '프로젝트원장', '회계관리 > 장부관리 > 프로젝트원장', '회계관리 > 장부관리 > 프로젝트원장', 'web.ledger.book.project', NULL, '회계관리 > 장부관리 > 프로젝트원장', 1),
('ledger.book.purchase_sales', 'ledger', '회계관리', 'ledger.book', '장부관리', '매입매출장', '회계관리 > 장부관리 > 매입매출장', '회계관리 > 장부관리 > 매입매출장', 'web.ledger.book.purchase_sales', NULL, '회계관리 > 장부관리 > 매입매출장', 1),
('ledger.book.vehicle_log', 'ledger', '회계관리', 'ledger.book', '장부관리', '차량운행일지', '회계관리 > 장부관리 > 차량운행일지', '회계관리 > 장부관리 > 차량운행일지', 'web.ledger.book.vehicle_log', NULL, '회계관리 > 장부관리 > 차량운행일지', 1),
('ledger.dashboard', 'ledger', '회계관리', 'ledger.main', '회계', '회계 대시보드', '회계관리 > 회계 > 회계 대시보드', '회계관리 > 회계 > 회계 대시보드', 'web.ledger.dashboard', '/ledger', '회계관리 > 회계 > 회계 대시보드', 1),
('ledger.data.create_center', 'ledger', '회계관리', 'ledger.data', '자료관리', '생성센터', '회계관리 > 자료관리 > 생성센터', '회계관리 > 자료관리 > 생성센터', 'web.ledger.data.create', '/ledger/data/create', '회계관리 > 자료관리 > 생성센터', 1),
('ledger.data.formats', 'ledger', '회계관리', 'ledger.data', '자료관리', '양식관리', '회계관리 > 자료관리 > 양식관리', '회계관리 > 자료관리 > 양식관리', 'web.ledger.data.formats', '/ledger/data/formats', '회계관리 > 자료관리 > 양식관리', 1),
('ledger.data.list', 'ledger', '회계관리', 'ledger.data', '자료관리', '증빙원본', '회계관리 > 자료관리 > 증빙원본', '회계관리 > 자료관리 > 증빙원본', 'web.ledger.data.index', '/ledger/data', '회계관리 > 자료관리 > 증빙원본', 1),
('ledger.data.upload', 'ledger', '회계관리', 'ledger.data', '자료관리', '자료업로드', '회계관리 > 자료관리 > 자료업로드', '회계관리 > 자료관리 > 자료업로드', 'web.ledger.data.upload', '/ledger/data/upload', '회계관리 > 자료관리 > 자료업로드', 1),
('ledger.financial.construction_cost', 'ledger', '회계관리', 'ledger.financial', '재무제표', '공사원가명세서', '회계관리 > 재무제표 > 공사원가명세서', '회계관리 > 재무제표 > 공사원가명세서', 'web.ledger.financial.construction_cost', NULL, '회계관리 > 재무제표 > 공사원가명세서', 1),
('ledger.financial.income_statement', 'ledger', '회계관리', 'ledger.financial', '재무제표', '손익계산서', '회계관리 > 재무제표 > 손익계산서', '회계관리 > 재무제표 > 손익계산서', 'web.ledger.financial.income_statement', NULL, '회계관리 > 재무제표 > 손익계산서', 1),
('ledger.financial.product_cost', 'ledger', '회계관리', 'ledger.financial', '재무제표', '제조원가명세서', '회계관리 > 재무제표 > 제조원가명세서', '회계관리 > 재무제표 > 제조원가명세서', 'web.ledger.financial.product_cost', NULL, '회계관리 > 재무제표 > 제조원가명세서', 1),
('ledger.financial.retained_earnings', 'ledger', '회계관리', 'ledger.financial', '재무제표', '이익잉여금처분계산서', '회계관리 > 재무제표 > 이익잉여금처분계산서', '회계관리 > 재무제표 > 이익잉여금처분계산서', 'web.ledger.financial.retained_earnings', NULL, '회계관리 > 재무제표 > 이익잉여금처분계산서', 1),
('ledger.financial.statement_position', 'ledger', '회계관리', 'ledger.financial', '재무제표', '재무상태표', '회계관리 > 재무제표 > 재무상태표', '회계관리 > 재무제표 > 재무상태표', 'web.ledger.financial.statement_position', NULL, '회계관리 > 재무제표 > 재무상태표', 1),
('ledger.financial.trial_balance', 'ledger', '회계관리', 'ledger.financial', '재무제표', '합계잔액시산표', '회계관리 > 재무제표 > 합계잔액시산표', '회계관리 > 재무제표 > 합계잔액시산표', 'web.ledger.financial.trial_balance', NULL, '회계관리 > 재무제표 > 합계잔액시산표', 1),
('ledger.funds.account_balances', 'ledger', '회계관리', 'ledger.funds', '자금관리', '계정잔액', '회계관리 > 자금관리 > 계정잔액', '회계관리 > 자금관리 > 계정잔액', 'web.ledger.funds.account_balances', NULL, '회계관리 > 자금관리 > 계정잔액', 1),
('ledger.funds.bank_transactions', 'ledger', '회계관리', 'ledger.funds', '자금관리', '계좌별거래내역', '회계관리 > 자금관리 > 계좌별거래내역', '회계관리 > 자금관리 > 계좌별거래내역', 'web.ledger.funds.account_transactions', '/ledger/funds/account-transactions', '회계관리 > 자금관리 > 계좌별거래내역', 1),
('ledger.funds.cash_ledger', 'ledger', '회계관리', 'ledger.funds', '자금관리', '현금출납장', '회계관리 > 자금관리 > 현금출납장', '회계관리 > 자금관리 > 현금출납장', 'web.ledger.funds.cash_ledger', NULL, '회계관리 > 자금관리 > 현금출납장', 1),
('ledger.funds.daily_report', 'ledger', '회계관리', 'ledger.funds', '자금관리', '일일자금보고', '회계관리 > 자금관리 > 일일자금보고', '회계관리 > 자금관리 > 일일자금보고', 'web.ledger.funds.daily_report', NULL, '회계관리 > 자금관리 > 일일자금보고', 1),
('ledger.funds.deposit_ledger', 'ledger', '회계관리', 'ledger.funds', '자금관리', '예금출납장', '회계관리 > 자금관리 > 예금출납장', '회계관리 > 자금관리 > 예금출납장', 'web.ledger.funds.deposit_ledger', NULL, '회계관리 > 자금관리 > 예금출납장', 1),
('ledger.funds.payment_info', 'ledger', '회계관리', 'ledger.funds', '자금관리', '결제정보', '회계관리 > 자금관리 > 결제정보', '회계관리 > 자금관리 > 결제정보', 'web.ledger.funds.payment_info', '/ledger/funds/payment-info', '회계관리 > 자금관리 > 결제정보', 1),
('ledger.funds.payment_schedule', 'ledger', '회계관리', 'ledger.funds', '자금관리', '지급스케줄', '회계관리 > 자금관리 > 지급스케줄', '회계관리 > 자금관리 > 지급스케줄', 'web.ledger.funds.payment_schedule', NULL, '회계관리 > 자금관리 > 지급스케줄', 1),
('ledger.funds.reconciliation', 'ledger', '회계관리', 'ledger.funds', '자금관리', '계좌대사', '회계관리 > 자금관리 > 계좌대사', '회계관리 > 자금관리 > 계좌대사', 'web.ledger.funds.reconciliation', NULL, '회계관리 > 자금관리 > 계좌대사', 1),
('ledger.funds.unlinked_transactions', 'ledger', '회계관리', 'ledger.funds', '자금관리', '미연결 거래', '회계관리 > 자금관리 > 미연결 거래', '회계관리 > 자금관리 > 미연결 거래', 'web.ledger.funds.unlinked_transactions', NULL, '회계관리 > 자금관리 > 미연결 거래', 1),
('ledger.journal', 'ledger', '회계관리', 'ledger.vouchers', '전표관리', '전표입력', '회계관리 > 전표관리 > 전표입력', '회계관리 > 전표관리 > 전표입력', 'web.ledger.journal', '/ledger/journal', '회계관리 > 전표관리 > 전표입력', 1),
('ledger.settings.accounts', 'ledger', '회계관리', 'ledger.settings', '기초정보관리', '계정과목', '회계관리 > 기초정보관리 > 계정과목', '회계관리 > 기초정보관리 > 계정과목', 'web.ledger.settings.accounts', '/ledger/settings/accounts', '회계관리 > 기초정보관리 > 계정과목', 1),
('ledger.settings.journal_rules', 'ledger', '회계관리', 'ledger.settings', '기초정보관리', '분개규칙', '회계관리 > 기초정보관리 > 분개규칙', '회계관리 > 기초정보관리 > 분개규칙', 'web.ledger.journal_rules', '/ledger/settings/journal-rules', '회계관리 > 기초정보관리 > 분개규칙', 1),
('ledger.settings.opening_balances', 'ledger', '회계관리', 'ledger.settings', '기초정보관리', '기초금액', '회계관리 > 기초정보관리 > 기초금액', '회계관리 > 기초정보관리 > 기초금액', 'web.ledger.opening_balances', NULL, '회계관리 > 기초정보관리 > 기초금액', 1),
('ledger.settings.sub_accounts', 'ledger', '회계관리', 'ledger.settings', '기초정보관리', '보조계정', '회계관리 > 기초정보관리 > 보조계정', '회계관리 > 기초정보관리 > 보조계정', 'web.ledger.sub_accounts', NULL, '회계관리 > 기초정보관리 > 보조계정', 1),
('ledger.tax.comparison', 'ledger', '회계관리', 'ledger.tax', '세무자료', '비교분석', '회계관리 > 세무자료 > 비교분석', '회계관리 > 세무자료 > 비교분석', 'web.ledger.tax.comparison', NULL, '회계관리 > 세무자료 > 비교분석', 1),
('ledger.tax.cost_statement', 'ledger', '회계관리', 'ledger.tax', '세무자료', '원가명세서', '회계관리 > 세무자료 > 원가명세서', '회계관리 > 세무자료 > 원가명세서', 'web.ledger.tax.cost_statement', NULL, '회계관리 > 세무자료 > 원가명세서', 1),
('ledger.tax.income_statement', 'ledger', '회계관리', 'ledger.tax', '세무자료', '손익계산서', '회계관리 > 세무자료 > 손익계산서', '회계관리 > 세무자료 > 손익계산서', 'web.ledger.tax.income_statement', NULL, '회계관리 > 세무자료 > 손익계산서', 1),
('ledger.tax.retained_earnings', 'ledger', '회계관리', 'ledger.tax', '세무자료', '이익잉여금처분계산서', '회계관리 > 세무자료 > 이익잉여금처분계산서', '회계관리 > 세무자료 > 이익잉여금처분계산서', 'web.ledger.tax.retained_earnings', NULL, '회계관리 > 세무자료 > 이익잉여금처분계산서', 1),
('ledger.tax.statement_position', 'ledger', '회계관리', 'ledger.tax', '세무자료', '재무상태표', '회계관리 > 세무자료 > 재무상태표', '회계관리 > 세무자료 > 재무상태표', 'web.ledger.tax.statement_position', NULL, '회계관리 > 세무자료 > 재무상태표', 1),
('ledger.tax.trial_balance', 'ledger', '회계관리', 'ledger.tax', '세무자료', '합계잔액시산표', '회계관리 > 세무자료 > 합계잔액시산표', '회계관리 > 세무자료 > 합계잔액시산표', 'web.ledger.tax.trial_balance', NULL, '회계관리 > 세무자료 > 합계잔액시산표', 1),
('ledger.transactions', 'ledger', '회계관리', 'ledger.vouchers', '전표관리', '거래입력', '회계관리 > 전표관리 > 거래입력', '회계관리 > 전표관리 > 거래입력', 'web.ledger.transactions.input', '/ledger/transactions/input', '회계관리 > 전표관리 > 거래입력', 1),
('ledger.vouchers', 'ledger', '회계관리', 'ledger.vouchers', '전표관리', '전표입력', '회계관리 > 전표관리 > 전표입력', '회계관리 > 전표관리 > 전표입력', 'web.ledger.vouchers.input', '/ledger/vouchers/input', '회계관리 > 전표관리 > 전표입력', 1),
('ledger.vouchers.index', 'ledger', '회계관리', 'ledger.vouchers', '전표관리', '전표조회', '회계관리 > 전표관리 > 전표조회', '회계관리 > 전표관리 > 전표조회', 'web.ledger.vouchers.index', NULL, '회계관리 > 전표관리 > 전표조회', 1),
('notice.index', 'notice', '공지/회의', 'notice.main', '공지', '공지/회의', '공지/회의 > 공지 > 공지/회의', '공지/회의 > 공지 > 공지/회의', 'web.notice.index', '/notice', '공지/회의 > 공지 > 공지/회의', 1),
('profile.view', 'profile', '내정보', 'profile.main', '프로필', '내정보 관리', '내정보 > 프로필 > 내정보 관리', '내정보 > 프로필 > 내정보 관리', 'web.user.profile.view', '/profile', '내정보 > 프로필 > 내정보 관리', 1),
('public.about', 'public', '공개사이트', 'public.main', '소개', '회사소개', '공개사이트 > 소개 > 회사소개', '공개사이트 > 소개 > 회사소개', 'web.admin.about.view', '/admin/about', '공개사이트 > 소개 > 회사소개', 1),
('settings.base_info.bank_accounts', 'settings', '설정', 'settings.base_info', '기준정보관리', '계좌', '설정 > 기준정보관리 > 계좌', '설정 > 기준정보관리 > 계좌', 'web.settings.base-info.accounts', '/dashboard/settings/base-info/bank-accounts', '설정 > 기준정보관리 > 계좌', 1),
('settings.base_info.brand', 'settings', '설정', 'settings.base_info', '기준정보관리', '브랜드', '설정 > 기준정보관리 > 브랜드', '설정 > 기준정보관리 > 브랜드', 'web.settings.base-info.brand_logo', '/dashboard/settings/base-info/brand-logo', '설정 > 기준정보관리 > 브랜드', 1),
('settings.base_info.cards', 'settings', '설정', 'settings.base_info', '기준정보관리', '카드', '설정 > 기준정보관리 > 카드', '설정 > 기준정보관리 > 카드', 'web.settings.base-info.cards', '/dashboard/settings/base-info/cards', '설정 > 기준정보관리 > 카드', 1),
('settings.base_info.clients', 'settings', '설정', 'settings.base_info', '기준정보관리', '거래처', '설정 > 기준정보관리 > 거래처', '설정 > 기준정보관리 > 거래처', 'web.settings.base-info.clients', '/dashboard/settings/base-info/clients', '설정 > 기준정보관리 > 거래처', 1),
('settings.base_info.company', 'settings', '설정', 'settings.base_info', '기준정보관리', '회사정보', '설정 > 기준정보관리 > 회사정보', '설정 > 기준정보관리 > 회사정보', 'web.settings.base-info.company', '/dashboard/settings/base-info/company', '설정 > 기준정보관리 > 회사정보', 1),
('settings.base_info.cover', 'settings', '설정', 'settings.base_info', '기준정보관리', '커버이미지', '설정 > 기준정보관리 > 커버이미지', '설정 > 기준정보관리 > 커버이미지', 'web.settings.base-info.cover', '/dashboard/settings/base-info/cover', '설정 > 기준정보관리 > 커버이미지', 1),
('settings.base_info.projects', 'settings', '설정', 'settings.base_info', '기준정보관리', '프로젝트', '설정 > 기준정보관리 > 프로젝트', '설정 > 기준정보관리 > 프로젝트', 'web.settings.base-info.projects', '/dashboard/settings/base-info/projects', '설정 > 기준정보관리 > 프로젝트', 1),
('settings.base_info.work_teams', 'settings', '설정', 'settings.base_info', '기준정보관리', '팀관리', '설정 > 기준정보관리 > 팀관리', '설정 > 기준정보관리 > 팀관리', 'web.settings.base-info.work-teams', NULL, '설정 > 기준정보관리 > 팀관리', 1),
('settings.organization.approval', 'settings', '설정', 'settings.organization', '조직관리', '결재템플릿', '설정 > 조직관리 > 결재템플릿', '설정 > 조직관리 > 결재템플릿', 'web.settings.organization.approval', '/dashboard/settings/organization/approval', '설정 > 조직관리 > 결재템플릿', 1),
('settings.organization.departments', 'settings', '설정', 'settings.organization', '조직관리', '부서', '설정 > 조직관리 > 부서', '설정 > 조직관리 > 부서', 'web.settings.organization.departments', '/dashboard/settings/organization/departments', '설정 > 조직관리 > 부서', 1),
('settings.organization.employees', 'settings', '설정', 'settings.organization', '조직관리', '직원', '설정 > 조직관리 > 직원', '설정 > 조직관리 > 직원', 'web.settings.organization.employees', '/dashboard/settings/organization/employees', '설정 > 조직관리 > 직원', 1),
('settings.organization.permissions', 'settings', '설정', 'settings.organization', '조직관리', '권한관리', '설정 > 조직관리 > 권한관리', '설정 > 조직관리 > 권한관리', 'web.settings.organization.permissions', NULL, '설정 > 조직관리 > 권한관리', 1),
('settings.organization.positions', 'settings', '설정', 'settings.organization', '조직관리', '직책', '설정 > 조직관리 > 직책', '설정 > 조직관리 > 직책', 'web.settings.organization.positions', '/dashboard/settings/organization/positions', '설정 > 조직관리 > 직책', 1),
('settings.organization.role_permissions', 'settings', '설정', 'settings.organization', '조직관리', '권한부여', '설정 > 조직관리 > 권한부여', '설정 > 조직관리 > 권한부여', 'web.settings.organization.role_permissions', '/dashboard/settings/organization/role_permissions', '설정 > 조직관리 > 권한부여', 1),
('settings.organization.roles', 'settings', '설정', 'settings.organization', '조직관리', '역할', '설정 > 조직관리 > 역할', '설정 > 조직관리 > 역할', 'web.settings.organization.roles', '/dashboard/settings/organization/roles', '설정 > 조직관리 > 역할', 1),
('settings.system.api', 'settings', '설정', 'settings.system', '시스템설정', 'API관리', '설정 > 시스템설정 > API관리', '설정 > 시스템설정 > API관리', 'web.settings.system.api', '/dashboard/settings/system/api', '설정 > 시스템설정 > API관리', 1),
('settings.system.codes', 'settings', '설정', 'settings.system', '시스템설정', '코드관리', '설정 > 시스템설정 > 코드관리', '설정 > 시스템설정 > 코드관리', 'web.settings.base-info.codes', NULL, '설정 > 시스템설정 > 코드관리', 1),
('settings.system.database_backup', 'settings', '설정', 'settings.system', '시스템설정', '데이터백업', '설정 > 시스템설정 > 데이터백업', '설정 > 시스템설정 > 데이터백업', 'web.settings.system.databasebackup', '/dashboard/settings/system/databasebackup', '설정 > 시스템설정 > 데이터백업', 1),
('settings.system.external_services', 'settings', '설정', 'settings.system', '시스템설정', '외부서비스', '설정 > 시스템설정 > 외부서비스', '설정 > 시스템설정 > 외부서비스', 'web.settings.system.external_services', '/dashboard/settings/system/external_services', '설정 > 시스템설정 > 외부서비스', 1),
('settings.system.logs', 'settings', '설정', 'settings.system', '시스템설정', '로그관리', '설정 > 시스템설정 > 로그관리', '설정 > 시스템설정 > 로그관리', 'web.settings.system.logs', '/dashboard/settings/system/logs', '설정 > 시스템설정 > 로그관리', 1),
('settings.system.security', 'settings', '설정', 'settings.system', '시스템설정', '보안정책', '설정 > 시스템설정 > 보안정책', '설정 > 시스템설정 > 보안정책', 'web.settings.system.security', '/dashboard/settings/system/security', '설정 > 시스템설정 > 보안정책', 1),
('settings.system.session', 'settings', '설정', 'settings.system', '시스템설정', '세션관리', '설정 > 시스템설정 > 세션관리', '설정 > 시스템설정 > 세션관리', 'web.settings.system.session', '/dashboard/settings/system/session', '설정 > 시스템설정 > 세션관리', 1),
('settings.system.site', 'settings', '설정', 'settings.system', '시스템설정', '사이트정보', '설정 > 시스템설정 > 사이트정보', '설정 > 시스템설정 > 사이트정보', 'web.settings.system.site', '/dashboard/settings/system/site', '설정 > 시스템설정 > 사이트정보', 1),
('settings.system.storage', 'settings', '설정', 'settings.system', '시스템설정', '파일저장소', '설정 > 시스템설정 > 파일저장소', '설정 > 시스템설정 > 파일저장소', 'web.settings.system.storage', '/dashboard/settings/system/storage', '설정 > 시스템설정 > 파일저장소', 1),
('shop.categories', 'shop', '쇼핑몰관리', 'shop.main', '쇼핑몰', '분류관리', '쇼핑몰관리 > 쇼핑몰 > 분류관리', '쇼핑몰관리 > 쇼핑몰 > 분류관리', 'web.shop.categories', '/shop/categories', '쇼핑몰관리 > 쇼핑몰 > 분류관리', 1),
('shop.dashboard', 'shop', '쇼핑몰관리', 'shop.main', '쇼핑몰', '쇼핑몰 대시보드', '쇼핑몰관리 > 쇼핑몰 > 쇼핑몰 대시보드', '쇼핑몰관리 > 쇼핑몰 > 쇼핑몰 대시보드', 'web.shop.index', '/shop', '쇼핑몰관리 > 쇼핑몰 > 쇼핑몰 대시보드', 1),
('shop.orders', 'shop', '쇼핑몰관리', 'shop.main', '쇼핑몰', '주문관리', '쇼핑몰관리 > 쇼핑몰 > 주문관리', '쇼핑몰관리 > 쇼핑몰 > 주문관리', 'web.shop.orders', '/shop/orders', '쇼핑몰관리 > 쇼핑몰 > 주문관리', 1),
('shop.payments', 'shop', '쇼핑몰관리', 'shop.main', '쇼핑몰', '결제관리', '쇼핑몰관리 > 쇼핑몰 > 결제관리', '쇼핑몰관리 > 쇼핑몰 > 결제관리', 'web.shop.payments', '/shop/payments', '쇼핑몰관리 > 쇼핑몰 > 결제관리', 1),
('shop.products', 'shop', '쇼핑몰관리', 'shop.main', '쇼핑몰', '상품관리', '쇼핑몰관리 > 쇼핑몰 > 상품관리', '쇼핑몰관리 > 쇼핑몰 > 상품관리', 'web.shop.products', '/shop/products', '쇼핑몰관리 > 쇼핑몰 > 상품관리', 1),
('shop.settlement', 'shop', '쇼핑몰관리', 'shop.main', '쇼핑몰', '정산관리', '쇼핑몰관리 > 쇼핑몰 > 정산관리', '쇼핑몰관리 > 쇼핑몰 > 정산관리', 'web.shop.settlement', '/shop/settlement', '쇼핑몰관리 > 쇼핑몰 > 정산관리', 1),
('site.dashboard', 'site', '현장관리', 'site.main', '현장', '현장 대시보드', '현장관리 > 현장 > 현장 대시보드', '현장관리 > 현장 > 현장 대시보드', 'web.site.dashboard', '/site', '현장관리 > 현장 > 현장 대시보드', 1),
('site.entry_create', 'site', '현장관리', 'site.main', '현장', '거래등록', '현장관리 > 현장 > 거래등록', '현장관리 > 현장 > 거래등록', 'web.site.entry.create', '/site/entry/create', '현장관리 > 현장 > 거래등록', 1),
('site.entry_index', 'site', '현장관리', 'site.main', '현장', '거래입력', '현장관리 > 현장 > 거래입력', '현장관리 > 현장 > 거래입력', 'web.site.entry.index', '/site/entry', '현장관리 > 현장 > 거래입력', 1)
ON DUPLICATE KEY UPDATE
    `module_key` = VALUES(`module_key`),
    `module_label` = VALUES(`module_label`),
    `menu_key` = VALUES(`menu_key`),
    `menu_label` = VALUES(`menu_label`),
    `page_label` = VALUES(`page_label`),
    `page_description` = VALUES(`page_description`),
    `breadcrumb` = VALUES(`breadcrumb`),
    `default_route_key` = VALUES(`default_route_key`),
    `default_route_url` = VALUES(`default_route_url`),
    `source_description` = VALUES(`source_description`),
    `is_active` = VALUES(`is_active`),
    `updated_at` = CURRENT_TIMESTAMP;
