CREATE TABLE IF NOT EXISTS `ledger_evidence_card_sales` (
    `id` VARCHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '고유 ID(UUID)',
    `sort_no` INT UNSIGNED NOT NULL COMMENT '테이블 내부 순번',
    `evidence_sort_no` BIGINT UNSIGNED NOT NULL COMMENT '전체 증빙 공통 순번',
    `source_type` VARCHAR(40) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '증빙유형 코드',
    `external_key` VARCHAR(120) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '외부 원본 식별값(승인번호)',
    `evidence_date` DATE NOT NULL COMMENT '증빙일자',
    `client_id` VARCHAR(36) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '거래처 ID',
    `project_id` VARCHAR(36) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '프로젝트 ID',
    `raw_client_name` VARCHAR(255) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '원본 거래처명',
    `evidence_status` VARCHAR(30) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '증빙 상태(ACTIVE,DELETED,INVALID)',
    `card_id` VARCHAR(36) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '카드 ID',
    `raw_card_name` VARCHAR(255) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '원본 카드명',
    `raw_card_number` VARCHAR(120) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '원본 카드번호',
    `approval_date` DATE NULL DEFAULT NULL COMMENT '승인일자',
    `merchant_business_number` VARCHAR(20) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '가맹점 사업자등록번호',
    `merchant_company_name` VARCHAR(255) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '가맹점 상호',
    `merchant_business_type` VARCHAR(120) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '가맹점 업태',
    `merchant_business_category` VARCHAR(120) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '가맹점 업종',
    `supply_amount` DECIMAL(18,2) NOT NULL COMMENT '공급가액',
    `vat_amount` DECIMAL(18,2) NOT NULL COMMENT '부가세액',
    `service_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '봉사료',
    `total_amount` DECIMAL(18,2) NOT NULL COMMENT '합계금액',
    `fee_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '수수료',
    `currency_code` VARCHAR(10) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '통화코드',
    `exchange_rate` DECIMAL(18,6) NULL DEFAULT NULL COMMENT '환율',
    `memo` TEXT COLLATE utf8mb4_unicode_ci NULL COMMENT '메모',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    `updated_at` DATETIME NULL DEFAULT NULL COMMENT '수정일시',
    `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '삭제일시',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_evcs_evidence_sort_no` (`evidence_sort_no`),
    INDEX `idx_evcs_sort_no` (`sort_no`),
    INDEX `idx_evcs_source_date` (`source_type`, `evidence_date`),
    INDEX `idx_evcs_external_key` (`external_key`),
    INDEX `idx_evcs_card_id` (`card_id`),
    INDEX `idx_evcs_client_id` (`client_id`),
    INDEX `idx_evcs_project_id` (`project_id`),
    INDEX `idx_evcs_deleted_at` (`deleted_at`),
    CONSTRAINT `fk_evcs_card` FOREIGN KEY (`card_id`) REFERENCES `system_cards` (`id`),
    CONSTRAINT `fk_evcs_client` FOREIGN KEY (`client_id`) REFERENCES `system_clients` (`id`),
    CONSTRAINT `fk_evcs_project` FOREIGN KEY (`project_id`) REFERENCES `system_projects` (`id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='카드매출 증빙 테이블';

CREATE TABLE IF NOT EXISTS `ledger_evidence_employee_expense` (
    `id` VARCHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '고유 ID(UUID)',
    `sort_no` INT UNSIGNED NOT NULL COMMENT '테이블 내부 순번',
    `evidence_sort_no` BIGINT UNSIGNED NOT NULL COMMENT '전체 증빙 공통 순번',
    `source_type` VARCHAR(40) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '증빙유형 코드',
    `external_key` VARCHAR(120) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '외부 원본 식별값',
    `evidence_date` DATE NOT NULL COMMENT '증빙일자',
    `client_id` VARCHAR(36) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '거래처 ID',
    `project_id` VARCHAR(36) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '프로젝트 ID',
    `raw_client_name` VARCHAR(255) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '원본 거래처명',
    `evidence_status` VARCHAR(30) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '증빙 상태(ACTIVE,DELETED,INVALID)',
    `employee_name` VARCHAR(120) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '직원명',
    `expense_type` VARCHAR(40) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '경비유형',
    `expense_date` DATE NULL DEFAULT NULL COMMENT '지출일자',
    `supply_amount` DECIMAL(18,2) NOT NULL COMMENT '공급가액',
    `vat_amount` DECIMAL(18,2) NOT NULL COMMENT '부가세액',
    `service_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '봉사료',
    `total_amount` DECIMAL(18,2) NOT NULL COMMENT '합계금액',
    `payment_method` VARCHAR(30) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '결제수단',
    `memo` TEXT COLLATE utf8mb4_unicode_ci NULL COMMENT '메모',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    `updated_at` DATETIME NULL DEFAULT NULL COMMENT '수정일시',
    `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '삭제일시',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_evee_evidence_sort_no` (`evidence_sort_no`),
    INDEX `idx_evee_sort_no` (`sort_no`),
    INDEX `idx_evee_source_date` (`source_type`, `evidence_date`),
    INDEX `idx_evee_external_key` (`external_key`),
    INDEX `idx_evee_client_id` (`client_id`),
    INDEX `idx_evee_project_id` (`project_id`),
    INDEX `idx_evee_deleted_at` (`deleted_at`),
    CONSTRAINT `fk_evee_client` FOREIGN KEY (`client_id`) REFERENCES `system_clients` (`id`),
    CONSTRAINT `fk_evee_project` FOREIGN KEY (`project_id`) REFERENCES `system_projects` (`id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='직원경비 증빙 테이블';

CREATE TABLE IF NOT EXISTS `ledger_evidence_payroll` (
    `id` VARCHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '고유 ID(UUID)',
    `sort_no` INT UNSIGNED NOT NULL COMMENT '테이블 내부 순번',
    `evidence_sort_no` BIGINT UNSIGNED NOT NULL COMMENT '전체 증빙 공통 순번',
    `source_type` VARCHAR(40) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '증빙유형 코드',
    `external_key` VARCHAR(120) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '외부 원본 식별값',
    `evidence_date` DATE NOT NULL COMMENT '증빙일자',
    `client_id` VARCHAR(36) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '거래처 ID',
    `project_id` VARCHAR(36) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '프로젝트 ID',
    `raw_client_name` VARCHAR(255) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '원본 거래처명',
    `evidence_status` VARCHAR(30) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '증빙 상태(ACTIVE,DELETED,INVALID)',
    `payroll_month` CHAR(7) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '급여대상월(YYYY-MM)',
    `pay_date` DATE NULL DEFAULT NULL COMMENT '지급일자',
    `employee_count` INT UNSIGNED NULL DEFAULT NULL COMMENT '직원수',
    `supply_amount` DECIMAL(18,2) NOT NULL COMMENT '총지급액(공급가액)',
    `vat_amount` DECIMAL(18,2) NOT NULL COMMENT '세액 합계',
    `service_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '기타수당 합계',
    `total_amount` DECIMAL(18,2) NOT NULL COMMENT '합계금액',
    `memo` TEXT COLLATE utf8mb4_unicode_ci NULL COMMENT '메모',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    `updated_at` DATETIME NULL DEFAULT NULL COMMENT '수정일시',
    `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '삭제일시',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_evpay_evidence_sort_no` (`evidence_sort_no`),
    INDEX `idx_evpay_sort_no` (`sort_no`),
    INDEX `idx_evpay_source_date` (`source_type`, `evidence_date`),
    INDEX `idx_evpay_external_key` (`external_key`),
    INDEX `idx_evpay_client_id` (`client_id`),
    INDEX `idx_evpay_project_id` (`project_id`),
    INDEX `idx_evpay_deleted_at` (`deleted_at`),
    CONSTRAINT `fk_evpay_client` FOREIGN KEY (`client_id`) REFERENCES `system_clients` (`id`),
    CONSTRAINT `fk_evpay_project` FOREIGN KEY (`project_id`) REFERENCES `system_projects` (`id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='급여 신고 증빙 테이블';

CREATE TABLE IF NOT EXISTS `ledger_evidence_daily_worker` (
    `id` VARCHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '고유 ID(UUID)',
    `sort_no` INT UNSIGNED NOT NULL COMMENT '테이블 내부 순번',
    `evidence_sort_no` BIGINT UNSIGNED NOT NULL COMMENT '전체 증빙 공통 순번',
    `source_type` VARCHAR(40) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '증빙유형 코드',
    `external_key` VARCHAR(120) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '외부 원본 식별값',
    `evidence_date` DATE NOT NULL COMMENT '증빙일자',
    `client_id` VARCHAR(36) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '거래처 ID',
    `project_id` VARCHAR(36) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '프로젝트 ID',
    `raw_client_name` VARCHAR(255) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '원본 거래처명',
    `evidence_status` VARCHAR(30) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '증빙 상태(ACTIVE,DELETED,INVALID)',
    `work_date` DATE NULL DEFAULT NULL COMMENT '근무일자',
    `worker_count` INT UNSIGNED NULL DEFAULT NULL COMMENT '인원수',
    `supply_amount` DECIMAL(18,2) NOT NULL COMMENT '지급총액(공급가액)',
    `vat_amount` DECIMAL(18,2) NOT NULL COMMENT '원천세 등 세액',
    `service_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '기타비용',
    `total_amount` DECIMAL(18,2) NOT NULL COMMENT '합계금액',
    `memo` TEXT COLLATE utf8mb4_unicode_ci NULL COMMENT '메모',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    `updated_at` DATETIME NULL DEFAULT NULL COMMENT '수정일시',
    `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '삭제일시',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_evdw_evidence_sort_no` (`evidence_sort_no`),
    INDEX `idx_evdw_sort_no` (`sort_no`),
    INDEX `idx_evdw_source_date` (`source_type`, `evidence_date`),
    INDEX `idx_evdw_external_key` (`external_key`),
    INDEX `idx_evdw_client_id` (`client_id`),
    INDEX `idx_evdw_project_id` (`project_id`),
    INDEX `idx_evdw_deleted_at` (`deleted_at`),
    CONSTRAINT `fk_evdw_client` FOREIGN KEY (`client_id`) REFERENCES `system_clients` (`id`),
    CONSTRAINT `fk_evdw_project` FOREIGN KEY (`project_id`) REFERENCES `system_projects` (`id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='일용직 신고 증빙 테이블';

CREATE TABLE IF NOT EXISTS `ledger_evidence_business_income` (
    `id` VARCHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '고유 ID(UUID)',
    `sort_no` INT UNSIGNED NOT NULL COMMENT '테이블 내부 순번',
    `evidence_sort_no` BIGINT UNSIGNED NOT NULL COMMENT '전체 증빙 공통 순번',
    `source_type` VARCHAR(40) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '증빙유형 코드',
    `external_key` VARCHAR(120) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '외부 원본 식별값',
    `evidence_date` DATE NOT NULL COMMENT '증빙일자',
    `client_id` VARCHAR(36) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '거래처 ID',
    `project_id` VARCHAR(36) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '프로젝트 ID',
    `raw_client_name` VARCHAR(255) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '원본 거래처명',
    `evidence_status` VARCHAR(30) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '증빙 상태(ACTIVE,DELETED,INVALID)',
    `income_date` DATE NULL DEFAULT NULL COMMENT '소득지급일자',
    `provider_name` VARCHAR(120) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '제공자명',
    `provider_reg_no` VARCHAR(40) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '제공자 등록번호',
    `supply_amount` DECIMAL(18,2) NOT NULL COMMENT '지급총액(공급가액)',
    `vat_amount` DECIMAL(18,2) NOT NULL COMMENT '원천세 등 세액',
    `service_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '기타비용',
    `total_amount` DECIMAL(18,2) NOT NULL COMMENT '합계금액',
    `memo` TEXT COLLATE utf8mb4_unicode_ci NULL COMMENT '메모',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    `updated_at` DATETIME NULL DEFAULT NULL COMMENT '수정일시',
    `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '삭제일시',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_evbi_evidence_sort_no` (`evidence_sort_no`),
    INDEX `idx_evbi_sort_no` (`sort_no`),
    INDEX `idx_evbi_source_date` (`source_type`, `evidence_date`),
    INDEX `idx_evbi_external_key` (`external_key`),
    INDEX `idx_evbi_client_id` (`client_id`),
    INDEX `idx_evbi_project_id` (`project_id`),
    INDEX `idx_evbi_deleted_at` (`deleted_at`),
    CONSTRAINT `fk_evbi_client` FOREIGN KEY (`client_id`) REFERENCES `system_clients` (`id`),
    CONSTRAINT `fk_evbi_project` FOREIGN KEY (`project_id`) REFERENCES `system_projects` (`id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='사업소득 신고 증빙 테이블';

CREATE TABLE IF NOT EXISTS `ledger_evidence_cash_sales` (
    `id` VARCHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '고유 ID(UUID)',
    `sort_no` INT UNSIGNED NOT NULL COMMENT '테이블 내부 순번',
    `evidence_sort_no` BIGINT UNSIGNED NOT NULL COMMENT '전체 증빙 공통 순번',
    `source_type` VARCHAR(40) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '증빙유형 코드',
    `external_key` VARCHAR(120) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '외부 원본 식별값',
    `evidence_date` DATE NOT NULL COMMENT '증빙일자',
    `client_id` VARCHAR(36) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '거래처 ID',
    `project_id` VARCHAR(36) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '프로젝트 ID',
    `raw_client_name` VARCHAR(255) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '원본 거래처명',
    `evidence_status` VARCHAR(30) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '증빙 상태(ACTIVE,DELETED,INVALID)',
    `sales_date` DATE NULL DEFAULT NULL COMMENT '매출일자',
    `sales_channel` VARCHAR(40) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '매출채널',
    `order_count` INT UNSIGNED NULL DEFAULT NULL COMMENT '주문건수',
    `supply_amount` DECIMAL(18,2) NOT NULL COMMENT '공급가액',
    `vat_amount` DECIMAL(18,2) NOT NULL COMMENT '부가세액',
    `service_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT '수수료',
    `total_amount` DECIMAL(18,2) NOT NULL COMMENT '합계금액',
    `memo` TEXT COLLATE utf8mb4_unicode_ci NULL COMMENT '메모',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    `updated_at` DATETIME NULL DEFAULT NULL COMMENT '수정일시',
    `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '삭제일시',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_evcas_evidence_sort_no` (`evidence_sort_no`),
    INDEX `idx_evcas_sort_no` (`sort_no`),
    INDEX `idx_evcas_source_date` (`source_type`, `evidence_date`),
    INDEX `idx_evcas_external_key` (`external_key`),
    INDEX `idx_evcas_client_id` (`client_id`),
    INDEX `idx_evcas_project_id` (`project_id`),
    INDEX `idx_evcas_deleted_at` (`deleted_at`),
    CONSTRAINT `fk_evcas_client` FOREIGN KEY (`client_id`) REFERENCES `system_clients` (`id`),
    CONSTRAINT `fk_evcas_project` FOREIGN KEY (`project_id`) REFERENCES `system_projects` (`id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='현금매출 증빙 테이블';
