DELETE FROM system_codes
WHERE code_group IN (
    'INCOME_STATUTORY_CALCULATION_SOURCE',
    'INCOME_ACTUAL_APPLICATION_SOURCE',
    'INCOME_PAYMENT_CONFIRMATION_STATUS',
    'INCOME_STATUTORY_CALCULATION_STATUS'
);
