CREATE TABLE institution_business_incomes (
    id VARCHAR(36) NOT NULL,
    income_year_month CHAR(7) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT NULL,
    document_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    calculation_status VARCHAR(30) NOT NULL DEFAULT 'NOT_CALCULATED',
    approval_status VARCHAR(30) NOT NULL DEFAULT 'NOT_REQUESTED',
    payment_status VARCHAR(30) NOT NULL DEFAULT 'NOT_CREATED',
    withholding_filing_status VARCHAR(30) NOT NULL DEFAULT 'NOT_FILED',
    simplified_statement_status VARCHAR(30) NOT NULL DEFAULT 'NOT_SUBMITTED',
    current_calculation_revision_id VARCHAR(36) NULL,
    current_approval_request_id VARCHAR(36) NULL,
    sort_no INT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    deleted_at DATETIME NULL,
    deleted_by VARCHAR(100) NULL,
    PRIMARY KEY (id),
    KEY idx_business_income_month (income_year_month,sort_no,id),
    KEY idx_business_income_status (document_status,calculation_status,approval_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='사업소득 귀속연월 Header';

CREATE TABLE institution_business_income_groups (
    id VARCHAR(36) NOT NULL,
    business_income_id VARCHAR(36) NOT NULL,
    payment_date DATE NOT NULL,
    business_unit VARCHAR(50) NOT NULL,
    project_id VARCHAR(36) NULL,
    work_team_id VARCHAR(36) NULL,
    group_description VARCHAR(500) NULL,
    sort_no INT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    deleted_at DATETIME NULL,
    deleted_by VARCHAR(100) NULL,
    PRIMARY KEY (id),
    KEY idx_business_income_group_header (business_income_id,sort_no,id),
    CONSTRAINT fk_business_income_group_header FOREIGN KEY (business_income_id) REFERENCES institution_business_incomes(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='사업소득 동일 지급조건 Group';

CREATE TABLE institution_business_income_items (
    id VARCHAR(36) NOT NULL,
    group_id VARCHAR(36) NOT NULL,
    client_id VARCHAR(36) NOT NULL,
    client_tax_profile_id VARCHAR(36) NOT NULL,
    service_type_code VARCHAR(50) NOT NULL,
    service_description VARCHAR(1000) NULL,
    gross_payment_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    income_tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    local_income_tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    other_deduction_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    total_deduction_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    net_payment_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    recipient_tax_snapshot_json JSON NOT NULL,
    sort_no INT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    deleted_at DATETIME NULL,
    deleted_by VARCHAR(100) NULL,
    PRIMARY KEY (id),
    KEY idx_business_income_item_group (group_id,sort_no,id),
    KEY idx_business_income_item_client (client_id,client_tax_profile_id),
    CONSTRAINT fk_business_income_item_group FOREIGN KEY (group_id) REFERENCES institution_business_income_groups(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_business_income_item_client FOREIGN KEY (client_id) REFERENCES system_clients(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_business_income_item_tax_profile FOREIGN KEY (client_tax_profile_id) REFERENCES system_client_tax_profiles(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT chk_business_income_item_amounts CHECK (gross_payment_amount>=0 AND income_tax_amount>=0 AND local_income_tax_amount>=0 AND other_deduction_amount>=0 AND total_deduction_amount>=0 AND net_payment_amount>=0),
    CONSTRAINT chk_business_income_item_reconciliation CHECK (total_deduction_amount=income_tax_amount+local_income_tax_amount+other_deduction_amount AND net_payment_amount=gross_payment_amount-total_deduction_amount)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='사업소득 소득자별 개별 용역 지급 Item';
