-- Fresh-environment baseline generated from the verified production schema.
-- Do not run against an existing ERP database.

CREATE TABLE `institution_employment_pay_components` (
  `id` varchar(36) NOT NULL COMMENT 'ID',
  `sort_no` int(11) NOT NULL COMMENT '순번',
  `component_code` varchar(50) NOT NULL COMMENT '급여항목코드',
  `component_name` varchar(100) NOT NULL COMMENT '급여항목명',
  `component_type` varchar(30) NOT NULL COMMENT '항목구분: BASE_PAY/ALLOWANCE/STATUTORY_PREMIUM/BONUS/OTHER_WAGE',
  `default_calculation_type` varchar(30) NOT NULL COMMENT '기본계산방식',
  `default_tax_type` varchar(30) NOT NULL COMMENT '기본과세구분',
  `tax_policy_code` varchar(50) DEFAULT NULL COMMENT '과세정책코드',
  `ordinary_wage_treatment` varchar(30) NOT NULL DEFAULT 'REVIEW_REQUIRED' COMMENT '통상임금처리: INCLUDED/EXCLUDED/REVIEW_REQUIRED',
  `average_wage_treatment` varchar(30) NOT NULL DEFAULT 'REVIEW_REQUIRED' COMMENT '평균임금처리: INCLUDED/EXCLUDED/REVIEW_REQUIRED',
  `minimum_wage_treatment` varchar(30) NOT NULL DEFAULT 'REVIEW_REQUIRED' COMMENT '최저임금산입처리',
  `is_active` tinyint(1) NOT NULL DEFAULT 1 COMMENT '사용여부',
  `effective_from` date DEFAULT NULL COMMENT '적용시작일',
  `effective_to` date DEFAULT NULL COMMENT '적용종료일',
  `note` varchar(255) DEFAULT NULL COMMENT '비고',
  `memo` text DEFAULT NULL COMMENT '메모',
  `created_at` datetime NOT NULL COMMENT '생성일시',
  `created_by` varchar(100) NOT NULL COMMENT '생성자',
  `updated_at` datetime DEFAULT NULL COMMENT '수정일시',
  `updated_by` varchar(100) DEFAULT NULL COMMENT '수정자',
  `deleted_at` datetime DEFAULT NULL COMMENT '삭제일시',
  `deleted_by` varchar(100) DEFAULT NULL COMMENT '삭제자',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_institution_pay_component_sort_no` (`sort_no`) USING BTREE,
  UNIQUE KEY `uk_institution_pay_component_code` (`component_code`) USING BTREE,
  KEY `idx_institution_pay_component_type` (`component_type`,`is_active`,`deleted_at`) USING BTREE,
  CONSTRAINT `chk_institution_pay_component_period` CHECK (`effective_to` is null or `effective_from` is null or `effective_to` >= `effective_from`),
  CONSTRAINT `chk_institution_pay_component_active` CHECK (`is_active` in (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='급여항목 공용 마스터';

CREATE TABLE `institution_employment_contracts` (
  `id` varchar(36) NOT NULL COMMENT 'ID',
  `sort_no` int(11) NOT NULL COMMENT '순번',
  `contract_no` varchar(50) NOT NULL COMMENT '계약번호',
  `employee_id` varchar(36) NOT NULL COMMENT '직원',
  `employee_name_snapshot` varchar(100) DEFAULT NULL COMMENT '근로자명스냅샷',
  `employee_address_snapshot` varchar(255) DEFAULT NULL COMMENT '근로자주소스냅샷',
  `employee_identifier_snapshot` varchar(255) DEFAULT NULL COMMENT '근로자식별정보암호문스냅샷',
  `employer_name_snapshot` varchar(150) DEFAULT NULL COMMENT '사용자명스냅샷',
  `employer_registration_no_snapshot` varchar(50) DEFAULT NULL COMMENT '사업자등록번호스냅샷',
  `employer_address_snapshot` varchar(255) DEFAULT NULL COMMENT '사용자주소스냅샷',
  `employer_representative_snapshot` varchar(100) DEFAULT NULL COMMENT '사용자대표자스냅샷',
  `previous_contract_id` varchar(36) DEFAULT NULL COMMENT '이전계약',
  `revision_no` int(11) NOT NULL DEFAULT 1 COMMENT '개정차수',
  `revision_reason` varchar(255) DEFAULT NULL COMMENT '개정사유',
  `contract_type` varchar(30) NOT NULL COMMENT '계약종류',
  `employment_type` varchar(30) NOT NULL COMMENT '고용형태',
  `contract_party_type` varchar(30) NOT NULL DEFAULT 'EMPLOYEE' COMMENT '계약대상구분: EMPLOYEE/EXECUTIVE/REPRESENTATIVE_DIRECTOR',
  `worker_status` varchar(30) NOT NULL DEFAULT 'WORKER' COMMENT '근로자성판정: WORKER/NON_WORKER/REVIEW_REQUIRED',
  `contract_start_date` date NOT NULL COMMENT '계약시작일',
  `contract_end_date` date DEFAULT NULL COMMENT '계약종료일',
  `fixed_term_reason_code` varchar(30) DEFAULT NULL COMMENT '기간제계약사유코드',
  `fixed_term_reason_detail` varchar(255) DEFAULT NULL COMMENT '기간제계약사유상세',
  `work_location_type` varchar(30) NOT NULL COMMENT '근무장소구분',
  `project_id` varchar(36) DEFAULT NULL COMMENT '프로젝트',
  `work_location_detail` varchar(255) DEFAULT NULL COMMENT '근무장소',
  `job_title_snapshot` varchar(100) DEFAULT NULL COMMENT '계약당시직위·직책',
  `job_description` text DEFAULT NULL COMMENT '종사업무내용',
  `work_schedule_type` varchar(30) NOT NULL COMMENT '근무형태',
  `weekly_work_days` decimal(4,2) NOT NULL COMMENT '주근무일수',
  `weekly_work_hours` decimal(6,2) NOT NULL COMMENT '주근무시간',
  `daily_work_hours` decimal(5,2) NOT NULL COMMENT '일근무시간',
  `standard_start_time` time DEFAULT NULL COMMENT '출근시간',
  `standard_end_time` time DEFAULT NULL COMMENT '퇴근시간',
  `break_minutes` int(11) NOT NULL DEFAULT 0 COMMENT '휴게시간(분)',
  `weekly_holiday_day` tinyint(3) unsigned DEFAULT NULL COMMENT '주휴일요일: 1월요일~7일요일',
  `weekly_holiday_paid` tinyint(1) NOT NULL DEFAULT 1 COMMENT '주휴일유급여부',
  `public_holiday_policy` varchar(30) NOT NULL DEFAULT 'STATUTORY' COMMENT '공휴일정책',
  `labor_day_policy` varchar(30) NOT NULL DEFAULT 'PAID_HOLIDAY' COMMENT '근로자의날정책',
  `annual_leave_policy` varchar(30) NOT NULL DEFAULT 'STATUTORY' COMMENT '연차유급휴가정책',
  `annual_leave_detail` varchar(500) DEFAULT NULL COMMENT '연차유급휴가상세',
  `salary_type` varchar(30) NOT NULL COMMENT '급여형태',
  `payment_day` tinyint(3) unsigned NOT NULL COMMENT '급여지급일',
  `payment_timing` varchar(20) NOT NULL COMMENT '급여지급기준',
  `probation_start_date` date DEFAULT NULL COMMENT '수습시작일',
  `probation_end_date` date DEFAULT NULL COMMENT '수습종료일',
  `probation_rate` decimal(5,2) DEFAULT NULL COMMENT '수습급여율',
  `contract_status` varchar(30) NOT NULL DEFAULT 'DRAFT' COMMENT '계약상태',
  `current_approval_request_id` varchar(36) DEFAULT NULL COMMENT '현재결재요청',
  `approved_at` datetime DEFAULT NULL COMMENT '승인일시',
  `printed_at` datetime DEFAULT NULL COMMENT '계약서출력일시',
  `contracted_at` datetime DEFAULT NULL COMMENT '계약체결일시',
  `delivery_status` varchar(30) NOT NULL DEFAULT 'NOT_DELIVERED' COMMENT '교부상태: NOT_DELIVERED/DELIVERED/FAILED',
  `delivered_at` datetime DEFAULT NULL COMMENT '계약서교부일시',
  `delivery_method` varchar(30) DEFAULT NULL COMMENT '교부방법: PAPER/ELECTRONIC/EMAIL/OTHER',
  `paper_document_status` varchar(30) NOT NULL DEFAULT 'NOT_PRINTED' COMMENT '서면문서상태: NOT_PRINTED/PRINTED/SIGNED/DELIVERED/STORED',
  `paper_storage_location` varchar(255) DEFAULT NULL COMMENT '서면원본보관위치',
  `terminated_at` datetime DEFAULT NULL COMMENT '종료일시',
  `termination_reason` varchar(255) DEFAULT NULL COMMENT '종료사유',
  `note` varchar(255) DEFAULT NULL COMMENT '비고',
  `memo` text DEFAULT NULL COMMENT '메모',
  `created_at` datetime NOT NULL COMMENT '생성일시',
  `created_by` varchar(100) NOT NULL COMMENT '생성자',
  `updated_at` datetime DEFAULT NULL COMMENT '수정일시',
  `updated_by` varchar(100) DEFAULT NULL COMMENT '수정자',
  `deleted_at` datetime DEFAULT NULL COMMENT '삭제일시',
  `deleted_by` varchar(100) DEFAULT NULL COMMENT '삭제자',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_institution_employment_contract_no` (`contract_no`) USING BTREE,
  UNIQUE KEY `uk_institution_employment_contract_sort_no` (`sort_no`) USING BTREE,
  KEY `idx_institution_employment_contract_employee` (`employee_id`) USING BTREE,
  KEY `idx_institution_employment_contract_previous` (`previous_contract_id`) USING BTREE,
  KEY `idx_institution_employment_contract_project` (`project_id`) USING BTREE,
  KEY `idx_institution_employment_contract_period` (`contract_start_date`,`contract_end_date`) USING BTREE,
  KEY `idx_institution_employment_contract_status` (`contract_status`,`deleted_at`) USING BTREE,
  KEY `idx_institution_employment_contract_approval` (`current_approval_request_id`) USING BTREE,
  CONSTRAINT `fk_institution_employment_contract_approval` FOREIGN KEY (`current_approval_request_id`) REFERENCES `user_approval_requests` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_institution_employment_contract_employee` FOREIGN KEY (`employee_id`) REFERENCES `user_employees` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_institution_employment_contract_previous` FOREIGN KEY (`previous_contract_id`) REFERENCES `institution_employment_contracts` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_institution_employment_contract_project` FOREIGN KEY (`project_id`) REFERENCES `system_projects` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_institution_employment_contract_period` CHECK (`contract_end_date` is null or `contract_end_date` >= `contract_start_date`),
  CONSTRAINT `chk_institution_employment_contract_work_days` CHECK (`weekly_work_days` > 0 and `weekly_work_days` <= 7),
  CONSTRAINT `chk_institution_employment_contract_weekly_hours` CHECK (`weekly_work_hours` > 0 and `weekly_work_hours` <= 168),
  CONSTRAINT `chk_institution_employment_contract_daily_hours` CHECK (`daily_work_hours` > 0 and `daily_work_hours` <= 24),
  CONSTRAINT `chk_institution_employment_contract_break_minutes` CHECK (`break_minutes` >= 0 and `break_minutes` <= 1440),
  CONSTRAINT `chk_institution_employment_contract_payment_day` CHECK (`payment_day` >= 1 and `payment_day` <= 31),
  CONSTRAINT `chk_institution_employment_contract_probation_period` CHECK (`probation_start_date` is null and `probation_end_date` is null or `probation_start_date` is not null and `probation_end_date` is not null and `probation_end_date` >= `probation_start_date`),
  CONSTRAINT `chk_institution_employment_contract_probation_rate` CHECK (`probation_rate` is null or `probation_rate` >= 0 and `probation_rate` <= 100),
  CONSTRAINT `chk_institution_employment_contract_weekly_holiday_day` CHECK (`weekly_holiday_day` is null or `weekly_holiday_day` between 1 and 7),
  CONSTRAINT `chk_institution_employment_contract_weekly_holiday_paid` CHECK (`weekly_holiday_paid` in (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='근로계약관리';

CREATE TABLE `institution_employment_contract_components` (
  `id` varchar(36) NOT NULL COMMENT 'ID',
  `sort_no` int(11) NOT NULL COMMENT '순번',
  `contract_id` varchar(36) NOT NULL COMMENT '근로계약',
  `pay_component_id` varchar(36) DEFAULT NULL COMMENT '급여항목마스터',
  `component_type` varchar(30) NOT NULL COMMENT '항목구분',
  `work_type` varchar(30) DEFAULT NULL COMMENT '근로수당구분: OVERTIME/NIGHT/HOLIDAY',
  `component_code` varchar(50) NOT NULL COMMENT '항목코드',
  `component_name` varchar(100) NOT NULL COMMENT '항목명',
  `calculation_type` varchar(30) NOT NULL COMMENT '계산방식',
  `amount` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '금액',
  `rate` decimal(10,4) DEFAULT NULL COMMENT '적용률',
  `quantity` decimal(12,4) DEFAULT NULL COMMENT '적용수량',
  `included_hours_per_week` decimal(8,2) DEFAULT NULL COMMENT '주포함시간',
  `included_hours_per_month` decimal(8,2) DEFAULT NULL COMMENT '월포함시간',
  `premium_rate` decimal(8,4) DEFAULT NULL COMMENT '가산배율',
  `excess_payment_policy` varchar(30) DEFAULT NULL COMMENT '초과분처리: SEPARATE_PAYMENT/NOT_APPLICABLE',
  `agreement_basis` varchar(500) DEFAULT NULL COMMENT '수당산정및약정근거',
  `formula_code` varchar(50) DEFAULT NULL COMMENT '계산공식코드',
  `formula_snapshot` varchar(500) DEFAULT NULL COMMENT '계산공식스냅샷',
  `base_component_code` varchar(50) DEFAULT NULL COMMENT '계산기준항목코드',
  `tax_type` varchar(30) NOT NULL COMMENT '과세구분',
  `tax_policy_code` varchar(50) DEFAULT NULL COMMENT '과세정책코드',
  `payment_cycle` varchar(30) NOT NULL COMMENT '지급주기',
  `is_fixed` tinyint(1) NOT NULL DEFAULT 1 COMMENT '고정항목여부',
  `minimum_wage_treatment` varchar(30) NOT NULL DEFAULT 'REVIEW_REQUIRED' COMMENT '최저임금산입처리',
  `ordinary_wage_treatment` varchar(30) NOT NULL DEFAULT 'REVIEW_REQUIRED' COMMENT '통상임금처리: INCLUDED/EXCLUDED/REVIEW_REQUIRED',
  `average_wage_treatment` varchar(30) NOT NULL DEFAULT 'REVIEW_REQUIRED' COMMENT '평균임금처리: INCLUDED/EXCLUDED/REVIEW_REQUIRED',
  `wage_treatment_basis` varchar(500) DEFAULT NULL COMMENT '임금산입판정근거',
  `manual_override_reason` varchar(500) DEFAULT NULL COMMENT '수동판정변경사유',
  `note` varchar(255) DEFAULT NULL COMMENT '비고',
  `memo` text DEFAULT NULL COMMENT '메모',
  `created_at` datetime NOT NULL COMMENT '생성일시',
  `created_by` varchar(100) NOT NULL COMMENT '생성자',
  `updated_at` datetime DEFAULT NULL COMMENT '수정일시',
  `updated_by` varchar(100) DEFAULT NULL COMMENT '수정자',
  `deleted_at` datetime DEFAULT NULL COMMENT '삭제일시',
  `deleted_by` varchar(100) DEFAULT NULL COMMENT '삭제자',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_institution_contract_component_sort_no` (`contract_id`,`sort_no`) USING BTREE,
  UNIQUE KEY `uk_institution_contract_component_code` (`contract_id`,`component_code`) USING BTREE,
  KEY `idx_institution_contract_component_contract` (`contract_id`) USING BTREE,
  KEY `idx_institution_contract_component_type` (`component_type`) USING BTREE,
  KEY `idx_institution_contract_component_pay_component` (`pay_component_id`) USING BTREE,
  CONSTRAINT `fk_institution_contract_component_contract` FOREIGN KEY (`contract_id`) REFERENCES `institution_employment_contracts` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_institution_contract_component_pay_component` FOREIGN KEY (`pay_component_id`) REFERENCES `institution_employment_pay_components` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `chk_institution_contract_component_amount` CHECK (`amount` >= 0),
  CONSTRAINT `chk_institution_contract_component_rate` CHECK (`rate` is null or `rate` >= 0),
  CONSTRAINT `chk_institution_contract_component_quantity` CHECK (`quantity` is null or `quantity` >= 0),
  CONSTRAINT `chk_institution_contract_component_included_week_hours` CHECK (`included_hours_per_week` is null or `included_hours_per_week` >= 0),
  CONSTRAINT `chk_institution_contract_component_included_month_hours` CHECK (`included_hours_per_month` is null or `included_hours_per_month` >= 0),
  CONSTRAINT `chk_institution_contract_component_premium_rate` CHECK (`premium_rate` is null or `premium_rate` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='근로계약 지급조건';
