-- 공용 TableSettings 기본값 복원을 위한 한글 컬럼 코멘트 보강
-- COLUMN_COMMENT는 사용컬럼명, IS_NULLABLE은 필수구분의 DB 원본 기준이다.

ALTER TABLE `institution_attendance_audits`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `attendance_domain` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '근태 업무영역',
  MODIFY `target_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '변경 대상 식별자',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '직원 식별자',
  MODIFY `action_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '변경 유형 코드',
  MODIFY `source_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '원천 유형 코드',
  MODIFY `reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '사유',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '요청 식별키',
  MODIFY `before_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '변경 전 정보',
  MODIFY `after_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '변경 후 정보',
  MODIFY `processed_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '처리자',
  MODIFY `processed_at` datetime NOT NULL COMMENT '처리일시';

ALTER TABLE `institution_attendance_clock_events`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '직원 식별자',
  MODIFY `event_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '출퇴근 이벤트 유형 코드',
  MODIFY `occurred_at` datetime NOT NULL COMMENT '발생일시',
  MODIFY `collected_at` datetime NOT NULL COMMENT '수집일시',
  MODIFY `source_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '원천 유형 코드',
  MODIFY `external_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '외부 식별키',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '요청 식별키',
  MODIFY `device_identifier` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '장치 식별자',
  MODIFY `source_payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '원천 수집정보',
  MODIFY `is_valid` tinyint(1) NOT NULL DEFAULT 1 COMMENT '유효 여부',
  MODIFY `invalid_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '무효 사유',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '생성자';

ALTER TABLE `institution_attendance_daily_exceptions`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `daily_record_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '일별 근태 식별자',
  MODIFY `exception_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '예외 유형 코드',
  MODIFY `candidate_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '예외 후보 시간(초)',
  MODIFY `source_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '원천 유형 코드',
  MODIFY `resolution_status_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'OPEN' COMMENT '처리 상태 코드',
  MODIFY `resolution_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '처리 사유',
  MODIFY `resolved_at` datetime NULL DEFAULT NULL COMMENT '처리완료일시',
  MODIFY `resolved_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '처리완료자',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '생성자',
  MODIFY `updated_at` datetime NOT NULL COMMENT '수정일시',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '수정자';

ALTER TABLE `institution_attendance_daily_records`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '직원 식별자',
  MODIFY `work_date` date NOT NULL COMMENT '근무일자',
  MODIFY `employment_contract_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '근로계약 식별자',
  MODIFY `working_time_standard_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '근로시간 기준 식별자',
  MODIFY `public_holiday_standard_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '공휴일 기준 식별자',
  MODIFY `scheduled_start_at` datetime NULL DEFAULT NULL COMMENT '예정 시작일시',
  MODIFY `scheduled_end_at` datetime NULL DEFAULT NULL COMMENT '예정 종료일시',
  MODIFY `scheduled_break_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '예정 휴게시간(초)',
  MODIFY `first_clock_in_at` datetime NULL DEFAULT NULL COMMENT '최초 출근일시',
  MODIFY `last_clock_out_at` datetime NULL DEFAULT NULL COMMENT '최종 퇴근일시',
  MODIFY `actual_work_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '실제 근로시간(초)',
  MODIFY `actual_break_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '실제 휴게시간(초)',
  MODIFY `scheduled_work_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '예정 근로시간(초)',
  MODIFY `contract_excess_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '계약 초과시간(초)',
  MODIFY `calculated_overtime_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '계산 연장근로시간(초)',
  MODIFY `night_work_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '야간근로시간(초)',
  MODIFY `holiday_work_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '휴일근로시간(초)',
  MODIFY `late_candidate_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '지각 후보시간(초)',
  MODIFY `early_leave_candidate_seconds` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '조퇴 후보시간(초)',
  MODIFY `process_status_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'CALCULATED' COMMENT '처리 상태 코드',
  MODIFY `calculation_status_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'CALCULATED' COMMENT '계산 상태 코드',
  MODIFY `calculation_version` int(10) unsigned NOT NULL DEFAULT 1 COMMENT '계산 버전',
  MODIFY `is_corrected` tinyint(1) NOT NULL DEFAULT 0 COMMENT '보정 여부',
  MODIFY `department_id_snapshot` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '부서 식별자 스냅샷',
  MODIFY `department_name_snapshot` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '부서명 스냅샷',
  MODIFY `job_id_snapshot` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '직무 식별자 스냅샷',
  MODIFY `job_name_snapshot` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '직무명 스냅샷',
  MODIFY `primary_project_id_snapshot` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '주 프로젝트 식별자 스냅샷',
  MODIFY `primary_project_name_snapshot` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '주 프로젝트명 스냅샷',
  MODIFY `workplace_assignment_id_snapshot` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '근무지 배치 식별자 스냅샷',
  MODIFY `workplace_name_snapshot` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '근무지명 스냅샷',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '생성자',
  MODIFY `updated_at` datetime NOT NULL COMMENT '수정일시',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '수정자';

ALTER TABLE `institution_attendance_monthly_closures`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '직원 식별자',
  MODIFY `closing_month` char(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '마감연월',
  MODIFY `close_status_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'OPEN' COMMENT '마감 상태 코드',
  MODIFY `current_revision` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '현재 개정번호',
  MODIFY `current_history_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '현재 마감이력 식별자',
  MODIFY `closed_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '마감자',
  MODIFY `closed_at` datetime NULL DEFAULT NULL COMMENT '마감일시',
  MODIFY `reopened_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '마감해제자',
  MODIFY `reopened_at` datetime NULL DEFAULT NULL COMMENT '마감해제일시',
  MODIFY `reopen_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '마감해제 사유',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '생성자',
  MODIFY `updated_at` datetime NOT NULL COMMENT '수정일시',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '수정자';

ALTER TABLE `institution_attendance_monthly_closure_histories`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `monthly_closure_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '월 마감 식별자',
  MODIFY `revision` int(10) unsigned NOT NULL COMMENT '개정번호',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '직원 식별자',
  MODIFY `closing_month` char(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '마감연월',
  MODIFY `workday_count` int(10) unsigned NOT NULL COMMENT '근무일수',
  MODIFY `scheduled_work_seconds` bigint(20) unsigned NOT NULL COMMENT '예정 근로시간(초)',
  MODIFY `actual_work_seconds` bigint(20) unsigned NOT NULL COMMENT '실제 근로시간(초)',
  MODIFY `calculated_overtime_seconds` bigint(20) unsigned NOT NULL COMMENT '계산 연장근로시간(초)',
  MODIFY `night_work_seconds` bigint(20) unsigned NOT NULL COMMENT '야간근로시간(초)',
  MODIFY `holiday_work_seconds` bigint(20) unsigned NOT NULL COMMENT '휴일근로시간(초)',
  MODIFY `late_candidate_count` int(10) unsigned NOT NULL COMMENT '지각 후보건수',
  MODIFY `late_candidate_seconds` bigint(20) unsigned NOT NULL COMMENT '지각 후보시간(초)',
  MODIFY `early_leave_candidate_count` int(10) unsigned NOT NULL COMMENT '조퇴 후보건수',
  MODIFY `early_leave_candidate_seconds` bigint(20) unsigned NOT NULL COMMENT '조퇴 후보시간(초)',
  MODIFY `absence_candidate_days` int(10) unsigned NOT NULL COMMENT '결근 후보일수',
  MODIFY `missing_clock_count` int(10) unsigned NOT NULL COMMENT '출퇴근 누락건수',
  MODIFY `ledger_hash` char(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '원장 검증값',
  MODIFY `calculation_version` int(10) unsigned NOT NULL COMMENT '계산 버전',
  MODIFY `close_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '마감 사유',
  MODIFY `closed_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '마감자',
  MODIFY `closed_at` datetime NOT NULL COMMENT '마감일시',
  MODIFY `source_request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '원천 요청 식별키',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시';

ALTER TABLE `institution_attendance_work_segments`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `daily_record_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '일별 근태 식별자',
  MODIFY `segment_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '근무구간 유형 코드',
  MODIFY `started_at` datetime NOT NULL COMMENT '시작일시',
  MODIFY `ended_at` datetime NOT NULL COMMENT '종료일시',
  MODIFY `duration_seconds` int(10) unsigned NOT NULL COMMENT '구간시간(초)',
  MODIFY `project_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '프로젝트 식별자',
  MODIFY `project_name_snapshot` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '프로젝트명 스냅샷',
  MODIFY `workplace_assignment_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '근무지 배치 식별자',
  MODIFY `workplace_name_snapshot` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '근무지명 스냅샷',
  MODIFY `source_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '원천 유형 코드',
  MODIFY `is_manual` tinyint(1) NOT NULL DEFAULT 0 COMMENT '수동등록 여부',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '생성자',
  MODIFY `updated_at` datetime NOT NULL COMMENT '수정일시',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '수정자';

ALTER TABLE `institution_educations_audits`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `target_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '변경 대상 식별자',
  MODIFY `employee_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '직원 식별자',
  MODIFY `action_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '변경 유형 코드',
  MODIFY `source_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '원천 유형 코드',
  MODIFY `reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '사유',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '요청 식별키',
  MODIFY `before_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '변경 전 정보',
  MODIFY `after_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '변경 후 정보',
  MODIFY `processed_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '처리자',
  MODIFY `processed_at` datetime NOT NULL COMMENT '처리일시';

ALTER TABLE `institution_educations_courses`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `course_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '교육과정 코드',
  MODIFY `course_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '교육과정명',
  MODIFY `education_type_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '교육 유형 코드',
  MODIFY `default_institution_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '기본 교육기관명',
  MODIFY `default_minutes` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '기본 교육시간(분)',
  MODIFY `validity_months` int(10) unsigned NULL DEFAULT NULL COMMENT '유효기간(개월)',
  MODIFY `is_statutory` tinyint(1) NOT NULL DEFAULT 0 COMMENT '법정교육 여부',
  MODIFY `is_mandatory` tinyint(1) NOT NULL DEFAULT 0 COMMENT '의무교육 여부',
  MODIFY `requires_certificate` tinyint(1) NOT NULL DEFAULT 0 COMMENT '수료증 필요 여부',
  MODIFY `description` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '교육과정 설명',
  MODIFY `sort_no` int(10) unsigned NOT NULL COMMENT '정렬순번',
  MODIFY `is_active` tinyint(1) NOT NULL DEFAULT 1 COMMENT '사용 여부',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '요청 식별키',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '생성자',
  MODIFY `updated_at` datetime NOT NULL COMMENT '수정일시',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '수정자',
  MODIFY `deleted_at` datetime NULL DEFAULT NULL COMMENT '삭제일시',
  MODIFY `deleted_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '삭제자';

ALTER TABLE `institution_educations_employee_records`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `employee_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '직원 식별자',
  MODIFY `course_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '교육과정 식별자',
  MODIFY `education_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '교육명',
  MODIFY `institution_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '교육기관명',
  MODIFY `education_start_at` datetime NOT NULL COMMENT '교육 시작일시',
  MODIFY `education_end_at` datetime NOT NULL COMMENT '교육 종료일시',
  MODIFY `education_minutes` int(10) unsigned NOT NULL COMMENT '교육시간(분)',
  MODIFY `attendance_status_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'ATTENDED' COMMENT '참석 상태 코드',
  MODIFY `completion_status_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'COMPLETED' COMMENT '이수 상태 코드',
  MODIFY `completion_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '이수번호',
  MODIFY `valid_from` date NULL DEFAULT NULL COMMENT '유효 시작일',
  MODIFY `valid_to` date NULL DEFAULT NULL COMMENT '유효 종료일',
  MODIFY `renewal_due_date` date NULL DEFAULT NULL COMMENT '갱신 예정일',
  MODIFY `attachment_path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '첨부파일 경로',
  MODIFY `attachment_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '첨부파일명',
  MODIFY `note` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '비고',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '요청 식별키',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '생성자',
  MODIFY `updated_at` datetime NOT NULL COMMENT '수정일시',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '수정자',
  MODIFY `deleted_at` datetime NULL DEFAULT NULL COMMENT '삭제일시',
  MODIFY `deleted_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '삭제자';

ALTER TABLE `institution_employment_contracts_break_schedules`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `weekly_schedule_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '주간 근무일정 식별자',
  MODIFY `sort_no` int(10) unsigned NOT NULL COMMENT '휴게구간 정렬순번',
  MODIFY `start_time` time NOT NULL COMMENT '시작시간',
  MODIFY `end_time` time NOT NULL COMMENT '종료시간',
  MODIFY `end_day_offset` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT '종료일 일자차이',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '생성자',
  MODIFY `updated_at` datetime NOT NULL COMMENT '수정일시',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '수정자';

ALTER TABLE `institution_employment_rules`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `company_id` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '회사 식별자',
  MODIFY `rule_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '취업규칙 코드',
  MODIFY `rule_type_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '취업규칙 유형 코드',
  MODIFY `title` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '제목',
  MODIFY `description` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '취업규칙 설명',
  MODIFY `owner_department_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '소관 부서 식별자',
  MODIFY `current_revision_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '현재 개정본 식별자',
  MODIFY `is_active` tinyint(1) NOT NULL DEFAULT 1 COMMENT '사용 여부',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '요청 식별키',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '생성자',
  MODIFY `updated_at` datetime NOT NULL COMMENT '수정일시',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '수정자',
  MODIFY `deleted_at` datetime NULL DEFAULT NULL COMMENT '삭제일시',
  MODIFY `deleted_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '삭제자';

ALTER TABLE `institution_employment_rules_audits`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `rule_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '취업규칙 식별자',
  MODIFY `revision_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '개정본 식별자',
  MODIFY `item_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '규정항목 식별자',
  MODIFY `action_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '변경 유형 코드',
  MODIFY `source_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '원천 유형 코드',
  MODIFY `reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '사유',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '요청 식별키',
  MODIFY `before_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '변경 전 정보',
  MODIFY `after_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '변경 후 정보',
  MODIFY `processed_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '처리자',
  MODIFY `processed_at` datetime NOT NULL COMMENT '처리일시';

ALTER TABLE `institution_employment_rules_items`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `revision_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '개정본 식별자',
  MODIFY `policy_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '정책 코드',
  MODIFY `value_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '값 유형 코드',
  MODIFY `value_text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '문자 값',
  MODIFY `value_number` decimal(18,4) NULL DEFAULT NULL COMMENT '숫자 값',
  MODIFY `value_boolean` tinyint(1) NULL DEFAULT NULL COMMENT '논리 값',
  MODIFY `value_date` date NULL DEFAULT NULL COMMENT '날짜 값',
  MODIFY `value_time` time NULL DEFAULT NULL COMMENT '시간 값',
  MODIFY `value_minutes` int(11) NULL DEFAULT NULL COMMENT '분 단위 값',
  MODIFY `value_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '구조화 값',
  MODIFY `unit_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '단위 코드',
  MODIFY `operator_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'EXACT' COMMENT '연산자 코드',
  MODIFY `note` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '비고',
  MODIFY `sort_no` int(10) unsigned NOT NULL COMMENT '규정항목 정렬순번',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '생성자',
  MODIFY `updated_at` datetime NOT NULL COMMENT '수정일시',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '수정자';

ALTER TABLE `institution_employment_rules_revisions`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `rule_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '취업규칙 식별자',
  MODIFY `revision_no` int(10) unsigned NOT NULL COMMENT '개정번호',
  MODIFY `revision_title` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '개정본 제목',
  MODIFY `revision_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '개정 사유',
  MODIFY `content_text` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '규정 본문',
  MODIFY `effective_from` date NOT NULL COMMENT '시행 시작일',
  MODIFY `effective_to` date NULL DEFAULT NULL COMMENT '시행 종료일',
  MODIFY `status_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'DRAFT' COMMENT '상태 코드',
  MODIFY `current_approval_request_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '현재 결재요청 식별자',
  MODIFY `approved_at` datetime NULL DEFAULT NULL COMMENT '승인일시',
  MODIFY `approved_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '승인자',
  MODIFY `published_at` datetime NULL DEFAULT NULL COMMENT '게시일시',
  MODIFY `published_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '게시자',
  MODIFY `document_file_path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '문서파일 경로',
  MODIFY `document_file_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '문서파일명',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '요청 식별키',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '생성자',
  MODIFY `updated_at` datetime NOT NULL COMMENT '수정일시',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '수정자',
  MODIFY `deleted_at` datetime NULL DEFAULT NULL COMMENT '삭제일시',
  MODIFY `deleted_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '삭제자';

ALTER TABLE `institution_employment_rules_scopes`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `revision_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '개정본 식별자',
  MODIFY `scope_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '적용범위 유형 코드',
  MODIFY `department_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '부서 식별자',
  MODIFY `position_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '직위 식별자',
  MODIFY `job_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '직무 식별자',
  MODIFY `employment_category_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '고용구분 코드',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '생성자',
  MODIFY `updated_at` datetime NOT NULL COMMENT '수정일시',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '수정자';

ALTER TABLE `institution_leave_audits`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `leave_domain` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '휴가 업무영역',
  MODIFY `target_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '변경 대상 식별자',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '직원 식별자',
  MODIFY `action_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '변경 유형 코드',
  MODIFY `source_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '원천 유형 코드',
  MODIFY `reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '사유',
  MODIFY `approval_request_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '결재요청 식별자',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '요청 식별키',
  MODIFY `before_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '변경 전 정보',
  MODIFY `after_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '변경 후 정보',
  MODIFY `processed_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '처리자',
  MODIFY `processed_at` datetime NOT NULL COMMENT '처리일시';

ALTER TABLE `institution_leave_grants`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '직원 식별자',
  MODIFY `leave_type_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '휴가종류 식별자',
  MODIFY `base_year` smallint(5) unsigned NOT NULL COMMENT '기준연도',
  MODIFY `granted_minutes` int(10) unsigned NOT NULL COMMENT '부여시간(분)',
  MODIFY `usable_from` date NOT NULL COMMENT '사용 시작일',
  MODIFY `usable_to` date NOT NULL COMMENT '사용 종료일',
  MODIFY `expires_on` date NULL DEFAULT NULL COMMENT '소멸일',
  MODIFY `reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '부여 사유',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '요청 식별키',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '생성자';

ALTER TABLE `institution_leave_ledger_entries`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '직원 식별자',
  MODIFY `leave_type_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '휴가종류 식별자',
  MODIFY `base_year` smallint(5) unsigned NOT NULL COMMENT '기준연도',
  MODIFY `entry_type_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '원장항목 유형 코드',
  MODIFY `amount_minutes` int(11) NOT NULL COMMENT '증감시간(분)',
  MODIFY `source_domain_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '원천 업무영역 코드',
  MODIFY `source_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '원천 식별자',
  MODIFY `source_sequence` int(10) unsigned NOT NULL DEFAULT 1 COMMENT '원천 순번',
  MODIFY `occurred_on` date NOT NULL COMMENT '발생일',
  MODIFY `reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '원장 반영 사유',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '요청 식별키',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '생성자';

ALTER TABLE `institution_leave_requests`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `request_no` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '신청번호',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '직원 식별자',
  MODIFY `request_kind_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'LEAVE' COMMENT '신청 종류 코드',
  MODIFY `original_request_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '원신청 식별자',
  MODIFY `business_status_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'DRAFT' COMMENT '업무 상태 코드',
  MODIFY `current_approval_request_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '현재 결재요청 식별자',
  MODIFY `reason` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '신청 사유',
  MODIFY `requested_total_minutes` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '총 신청시간(분)',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '요청 식별키',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '생성자',
  MODIFY `updated_at` datetime NOT NULL COMMENT '수정일시',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '수정자';

ALTER TABLE `institution_leave_request_items`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `leave_request_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '휴가신청 식별자',
  MODIFY `leave_type_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '휴가종류 식별자',
  MODIFY `sort_no` int(10) unsigned NOT NULL COMMENT '신청항목 정렬순번',
  MODIFY `leave_date` date NOT NULL COMMENT '휴가일자',
  MODIFY `request_unit_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '신청 단위 코드',
  MODIFY `requested_start_at` datetime NULL DEFAULT NULL COMMENT '신청 시작일시',
  MODIFY `requested_end_at` datetime NULL DEFAULT NULL COMMENT '신청 종료일시',
  MODIFY `requested_minutes` int(10) unsigned NOT NULL COMMENT '신청시간(분)',
  MODIFY `deductible_minutes` int(10) unsigned NOT NULL COMMENT '차감시간(분)',
  MODIFY `employment_contract_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '근로계약 식별자',
  MODIFY `scheduled_start_at_snapshot` datetime NOT NULL COMMENT '예정 시작일시 스냅샷',
  MODIFY `scheduled_end_at_snapshot` datetime NOT NULL COMMENT '예정 종료일시 스냅샷',
  MODIFY `scheduled_minutes_snapshot` int(10) unsigned NOT NULL COMMENT '예정시간(분) 스냅샷',
  MODIFY `breaks_json_snapshot` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '휴게구간 스냅샷',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '생성자';

ALTER TABLE `institution_leave_types`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `type_code` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '휴가종류 코드',
  MODIFY `type_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '휴가종류명',
  MODIFY `is_paid` tinyint(1) NOT NULL DEFAULT 0 COMMENT '유급 여부',
  MODIFY `deducts_balance` tinyint(1) NOT NULL DEFAULT 0 COMMENT '잔액 차감 여부',
  MODIFY `requires_approval` tinyint(1) NOT NULL DEFAULT 1 COMMENT '결재 필요 여부',
  MODIFY `evidence_policy_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'OPTIONAL' COMMENT '증빙 정책 코드',
  MODIFY `allowed_units_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '허용 신청단위',
  MODIFY `is_active` tinyint(1) NOT NULL DEFAULT 1 COMMENT '사용 여부',
  MODIFY `sort_no` int(10) unsigned NOT NULL COMMENT '휴가종류 정렬순번',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '생성자',
  MODIFY `updated_at` datetime NOT NULL COMMENT '수정일시',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '수정자';

ALTER TABLE `institution_leave_usages`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `request_item_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '휴가신청 항목 식별자',
  MODIFY `employee_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '직원 식별자',
  MODIFY `leave_type_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '휴가종류 식별자',
  MODIFY `leave_date` date NOT NULL COMMENT '휴가일자',
  MODIFY `request_unit_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '신청 단위 코드',
  MODIFY `leave_start_at` datetime NOT NULL COMMENT '휴가 시작일시',
  MODIFY `leave_end_at` datetime NOT NULL COMMENT '휴가 종료일시',
  MODIFY `used_minutes` int(10) unsigned NOT NULL COMMENT '사용시간(분)',
  MODIFY `deductible_minutes` int(10) unsigned NOT NULL COMMENT '차감시간(분)',
  MODIFY `usage_status_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'ACTIVE' COMMENT '사용 상태 코드',
  MODIFY `cancel_request_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '취소신청 식별자',
  MODIFY `approved_at` datetime NOT NULL COMMENT '승인일시',
  MODIFY `approval_request_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '결재요청 식별자',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '생성자',
  MODIFY `updated_at` datetime NOT NULL COMMENT '수정일시',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '수정자';

ALTER TABLE `institution_qualifications_audits`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `target_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '변경 대상 식별자',
  MODIFY `employee_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '직원 식별자',
  MODIFY `action_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '변경 유형 코드',
  MODIFY `source_type_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '원천 유형 코드',
  MODIFY `reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '사유',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '요청 식별키',
  MODIFY `before_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '변경 전 정보',
  MODIFY `after_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '변경 후 정보',
  MODIFY `processed_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '처리자',
  MODIFY `processed_at` datetime NOT NULL COMMENT '처리일시';

ALTER TABLE `institution_qualifications_employee_records`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '식별자',
  MODIFY `employee_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '직원 식별자',
  MODIFY `qualification_type_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '자격 유형 코드',
  MODIFY `qualification_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '자격명',
  MODIFY `credential_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '자격번호',
  MODIFY `issuer_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '발급기관명',
  MODIFY `grade_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '등급 코드',
  MODIFY `technical_field_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '기술분야 코드',
  MODIFY `specialty_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '전문분야 코드',
  MODIFY `acquired_date` date NULL DEFAULT NULL COMMENT '취득일',
  MODIFY `valid_from` date NULL DEFAULT NULL COMMENT '유효 시작일',
  MODIFY `valid_to` date NULL DEFAULT NULL COMMENT '유효 종료일',
  MODIFY `renewal_due_date` date NULL DEFAULT NULL COMMENT '갱신 예정일',
  MODIFY `status_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'PENDING_VERIFICATION' COMMENT '상태 코드',
  MODIFY `status_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '상태 사유',
  MODIFY `attachment_path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '첨부파일 경로',
  MODIFY `attachment_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '첨부파일명',
  MODIFY `note` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '비고',
  MODIFY `verified_at` datetime NULL DEFAULT NULL COMMENT '검증일시',
  MODIFY `verified_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '검증자',
  MODIFY `supersedes_record_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '대체 이전기록 식별자',
  MODIFY `request_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '요청 식별키',
  MODIFY `created_at` datetime NOT NULL COMMENT '생성일시',
  MODIFY `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '생성자',
  MODIFY `updated_at` datetime NOT NULL COMMENT '수정일시',
  MODIFY `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '수정자',
  MODIFY `deleted_at` datetime NULL DEFAULT NULL COMMENT '삭제일시',
  MODIFY `deleted_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '삭제자';

ALTER TABLE `ledger_payment_schedules`
  MODIFY `cancelled_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '취소자',
  MODIFY `cancelled_at` datetime NULL DEFAULT NULL COMMENT '취소일시',
  MODIFY `cancellation_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '취소 사유';

ALTER TABLE `system_client_histories`
  MODIFY `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '거래처 이력 식별자';
