-- 20260826_06은 실제 company SSOT 문자셋과 불일치하여 적용 전 실패했다.
-- 상용근로소득과 동일하게 company_id만 system_company.id 정의를 따른다.

SET NAMES utf8mb4;

CREATE TABLE system_work_team_assignments (
    id VARCHAR(36) NOT NULL,
    company_id VARCHAR(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
    work_scope_code VARCHAR(20) NOT NULL,
    project_id VARCHAR(36) NULL,
    scope_project_key VARCHAR(50) GENERATED ALWAYS AS (IFNULL(project_id, 'HEAD_OFFICE')) STORED,
    work_team_id VARCHAR(36) NOT NULL,
    worker_client_id VARCHAR(36) NOT NULL,
    assignment_role_code VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    status_code VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    evidence_description VARCHAR(500) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_work_team_assignment_start (company_id, scope_project_key, work_team_id, worker_client_id, effective_from),
    KEY idx_work_team_assignment_resolve (company_id, worker_client_id, effective_from, effective_to, status_code),
    CONSTRAINT fk_work_team_assignment_company FOREIGN KEY (company_id) REFERENCES system_company(id),
    CONSTRAINT fk_work_team_assignment_project FOREIGN KEY (project_id) REFERENCES system_projects(id),
    CONSTRAINT fk_work_team_assignment_team FOREIGN KEY (work_team_id) REFERENCES system_work_teams(id),
    CONSTRAINT fk_work_team_assignment_worker FOREIGN KEY (worker_client_id) REFERENCES system_clients(id),
    CONSTRAINT ck_work_team_assignment_scope CHECK ((work_scope_code = 'PROJECT' AND project_id IS NOT NULL) OR (work_scope_code = 'HEAD_OFFICE' AND project_id IS NULL)),
    CONSTRAINT ck_work_team_assignment_role CHECK (assignment_role_code IN ('LEADER', 'MEMBER')),
    CONSTRAINT ck_work_team_assignment_status CHECK (status_code IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_work_team_assignment_period CHECK (effective_to IS NULL OR effective_to >= effective_from)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='일용근로자 작업팀 기간 배치';

CREATE TABLE institution_social_insurance_workplaces (
    id VARCHAR(36) NOT NULL,
    company_id VARCHAR(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
    work_scope_code VARCHAR(20) NOT NULL,
    project_id VARCHAR(36) NULL,
    scope_project_key VARCHAR(50) GENERATED ALWAYS AS (IFNULL(project_id, 'HEAD_OFFICE')) STORED,
    workplace_name VARCHAR(200) NOT NULL,
    management_number VARCHAR(100) NULL,
    confirmation_status_code VARCHAR(20) NOT NULL DEFAULT 'UNCONFIRMED',
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    evidence_type_code VARCHAR(30) NOT NULL,
    evidence_id VARCHAR(100) NULL,
    evidence_description VARCHAR(500) NULL,
    confirmed_by VARCHAR(100) NULL,
    confirmed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_social_workplace_start (company_id, scope_project_key, effective_from),
    KEY idx_social_workplace_resolve (company_id, scope_project_key, effective_from, effective_to, confirmation_status_code),
    CONSTRAINT fk_social_workplace_company FOREIGN KEY (company_id) REFERENCES system_company(id),
    CONSTRAINT fk_social_workplace_project FOREIGN KEY (project_id) REFERENCES system_projects(id),
    CONSTRAINT ck_social_workplace_scope CHECK ((work_scope_code = 'PROJECT' AND project_id IS NOT NULL) OR (work_scope_code = 'HEAD_OFFICE' AND project_id IS NULL)),
    CONSTRAINT ck_social_workplace_confirmation CHECK (confirmation_status_code IN ('CONFIRMED', 'UNCONFIRMED', 'NOT_REQUIRED')),
    CONSTRAINT ck_social_workplace_period CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT ck_social_workplace_management_number CHECK (confirmation_status_code <> 'CONFIRMED' OR NULLIF(TRIM(management_number), '') IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='사회보험 사업장 기간 기준';

CREATE TABLE institution_daily_worker_social_insurance_coverages (
    id VARCHAR(36) NOT NULL,
    company_id VARCHAR(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
    worker_client_id VARCHAR(36) NOT NULL,
    social_insurance_workplace_id VARCHAR(36) NOT NULL,
    insurance_type_code VARCHAR(30) NOT NULL,
    application_status_code VARCHAR(20) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    exclusion_reason_code VARCHAR(50) NULL,
    exclusion_reason_description VARCHAR(500) NULL,
    evidence_type_code VARCHAR(30) NOT NULL,
    evidence_id VARCHAR(100) NULL,
    evidence_description VARCHAR(500) NULL,
    confirmed_by VARCHAR(100) NOT NULL,
    confirmed_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_daily_worker_coverage_start (worker_client_id, social_insurance_workplace_id, insurance_type_code, effective_from),
    KEY idx_daily_worker_coverage_resolve (company_id, worker_client_id, insurance_type_code, effective_from, effective_to),
    CONSTRAINT fk_daily_coverage_company FOREIGN KEY (company_id) REFERENCES system_company(id),
    CONSTRAINT fk_daily_coverage_worker FOREIGN KEY (worker_client_id) REFERENCES system_clients(id),
    CONSTRAINT fk_daily_coverage_workplace FOREIGN KEY (social_insurance_workplace_id) REFERENCES institution_social_insurance_workplaces(id),
    CONSTRAINT ck_daily_coverage_status CHECK (application_status_code IN ('APPLICABLE', 'EXCLUDED', 'NOT_APPLICABLE')),
    CONSTRAINT ck_daily_coverage_period CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT ck_daily_coverage_exclusion CHECK (application_status_code <> 'EXCLUDED' OR NULLIF(TRIM(COALESCE(exclusion_reason_code, exclusion_reason_description)), '') IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='일용근로자 사회보험 적용 기간';

CREATE TABLE institution_daily_employment_incomes (
    id VARCHAR(36) NOT NULL,
    company_id VARCHAR(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
    income_year_month CHAR(7) NOT NULL,
    payment_date DATE NOT NULL,
    document_number VARCHAR(50) NOT NULL,
    document_title VARCHAR(200) NOT NULL,
    status_code VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    total_work_days DECIMAL(10,2) NOT NULL DEFAULT 0,
    total_gross_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    total_deduction_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    total_net_payment_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    total_employer_burden_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    approval_request_id VARCHAR(36) NULL,
    approved_by VARCHAR(100) NULL,
    approved_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_daily_income_document_number (company_id, document_number),
    KEY idx_daily_income_month_status (company_id, income_year_month, status_code),
    CONSTRAINT fk_daily_income_company FOREIGN KEY (company_id) REFERENCES system_company(id),
    CONSTRAINT fk_daily_income_approval FOREIGN KEY (approval_request_id) REFERENCES user_approval_requests(id),
    CONSTRAINT ck_daily_income_status CHECK (status_code IN ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='일용근로소득 문서';

CREATE TABLE institution_daily_employment_income_items (
    id VARCHAR(36) NOT NULL,
    daily_employment_income_id VARCHAR(36) NOT NULL,
    sort_no INT NOT NULL DEFAULT 0,
    work_scope_code VARCHAR(20) NOT NULL,
    project_id VARCHAR(36) NULL,
    scope_project_key VARCHAR(50) GENERATED ALWAYS AS (IFNULL(project_id, 'HEAD_OFFICE')) STORED,
    work_team_id VARCHAR(36) NOT NULL,
    worker_client_id VARCHAR(36) NOT NULL,
    worker_name_snapshot VARCHAR(100) NOT NULL,
    worker_registration_number_snapshot VARCHAR(100) NULL,
    total_work_days DECIMAL(10,2) NOT NULL DEFAULT 0,
    total_gross_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    total_deduction_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    total_net_payment_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    total_employer_burden_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_daily_income_item_business (daily_employment_income_id, scope_project_key, work_team_id, worker_client_id),
    KEY idx_daily_income_item_worker (worker_client_id, daily_employment_income_id),
    CONSTRAINT fk_daily_item_header FOREIGN KEY (daily_employment_income_id) REFERENCES institution_daily_employment_incomes(id),
    CONSTRAINT fk_daily_item_project FOREIGN KEY (project_id) REFERENCES system_projects(id),
    CONSTRAINT fk_daily_item_team FOREIGN KEY (work_team_id) REFERENCES system_work_teams(id),
    CONSTRAINT fk_daily_item_worker FOREIGN KEY (worker_client_id) REFERENCES system_clients(id),
    CONSTRAINT ck_daily_item_scope CHECK ((work_scope_code = 'PROJECT' AND project_id IS NOT NULL) OR (work_scope_code = 'HEAD_OFFICE' AND project_id IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='일용근로소득 근로자·현장 정산 단위';

CREATE TABLE institution_daily_employment_income_workdays (
    id VARCHAR(36) NOT NULL,
    daily_employment_income_item_id VARCHAR(36) NOT NULL,
    work_date DATE NOT NULL,
    work_quantity DECIMAL(10,2) NOT NULL DEFAULT 1,
    daily_rate_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    base_pay_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    allowance_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    adjustment_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    non_taxable_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    taxable_amount DECIMAL(18,2) NULL,
    income_tax_amount DECIMAL(18,2) NULL,
    local_income_tax_amount DECIMAL(18,2) NULL,
    worker_social_insurance_amount DECIMAL(18,2) NULL,
    employer_social_insurance_amount DECIMAL(18,2) NULL,
    net_payment_amount DECIMAL(18,2) NULL,
    work_team_assignment_id VARCHAR(36) NOT NULL,
    social_insurance_workplace_id VARCHAR(36) NULL,
    calculation_status_code VARCHAR(30) NOT NULL DEFAULT 'CALCULATED',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_daily_income_workday (daily_employment_income_item_id, work_date),
    CONSTRAINT fk_daily_workday_item FOREIGN KEY (daily_employment_income_item_id) REFERENCES institution_daily_employment_income_items(id),
    CONSTRAINT fk_daily_workday_assignment FOREIGN KEY (work_team_assignment_id) REFERENCES system_work_team_assignments(id),
    CONSTRAINT fk_daily_workday_workplace FOREIGN KEY (social_insurance_workplace_id) REFERENCES institution_social_insurance_workplaces(id),
    CONSTRAINT ck_daily_workday_status CHECK (calculation_status_code IN ('CALCULATED', 'CONFIRMATION_REQUIRED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='일용근로소득 근무일 계산';

CREATE TABLE institution_daily_employment_income_lines (
    id VARCHAR(36) NOT NULL,
    daily_employment_income_item_id VARCHAR(36) NOT NULL,
    daily_employment_income_workday_id VARCHAR(36) NULL,
    line_type_code VARCHAR(30) NOT NULL,
    line_code VARCHAR(50) NOT NULL,
    line_name_snapshot VARCHAR(100) NOT NULL,
    sort_no INT NOT NULL DEFAULT 0,
    application_status_code VARCHAR(20) NULL,
    calculation_basis_amount DECIMAL(18,6) NULL,
    calculation_rate DECIMAL(18,10) NULL,
    calculation_before_rounding DECIMAL(24,10) NULL,
    rounding_method_code VARCHAR(30) NULL,
    rounding_unit DECIMAL(18,6) NULL,
    statutory_standard_id CHAR(36) NULL,
    coverage_id VARCHAR(36) NULL,
    social_insurance_workplace_id VARCHAR(36) NULL,
    final_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_daily_income_line (daily_employment_income_item_id, daily_employment_income_workday_id, line_type_code, line_code),
    KEY idx_daily_income_line_standard (statutory_standard_id),
    CONSTRAINT fk_daily_line_item FOREIGN KEY (daily_employment_income_item_id) REFERENCES institution_daily_employment_income_items(id),
    CONSTRAINT fk_daily_line_workday FOREIGN KEY (daily_employment_income_workday_id) REFERENCES institution_daily_employment_income_workdays(id),
    CONSTRAINT fk_daily_line_standard FOREIGN KEY (statutory_standard_id) REFERENCES system_statutory_standards(id),
    CONSTRAINT fk_daily_line_coverage FOREIGN KEY (coverage_id) REFERENCES institution_daily_worker_social_insurance_coverages(id),
    CONSTRAINT fk_daily_line_workplace FOREIGN KEY (social_insurance_workplace_id) REFERENCES institution_social_insurance_workplaces(id),
    CONSTRAINT ck_daily_line_type CHECK (line_type_code IN ('PAY', 'DEDUCTION', 'EMPLOYER_BURDEN')),
    CONSTRAINT ck_daily_line_application CHECK (application_status_code IS NULL OR application_status_code IN ('APPLICABLE', 'EXCLUDED', 'NOT_APPLICABLE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='일용근로소득 지급·공제·사용자부담 계산 Snapshot';

CREATE TABLE ledger_evidence_daily_employment_income (
    id VARCHAR(36) NOT NULL,
    source_daily_employment_income_id VARCHAR(36) NOT NULL,
    daily_employment_income_item_id VARCHAR(36) NOT NULL,
    approval_request_id VARCHAR(36) NOT NULL,
    worker_client_id VARCHAR(36) NOT NULL,
    work_scope_code VARCHAR(20) NOT NULL,
    project_id VARCHAR(36) NULL,
    work_team_id VARCHAR(36) NOT NULL,
    income_year_month CHAR(7) NOT NULL,
    payment_date DATE NOT NULL,
    total_work_days DECIMAL(10,2) NOT NULL,
    total_gross_amount DECIMAL(18,2) NOT NULL,
    total_deduction_amount DECIMAL(18,2) NOT NULL,
    total_net_payment_amount DECIMAL(18,2) NOT NULL,
    total_employer_burden_amount DECIMAL(18,2) NOT NULL,
    evidence_status_code VARCHAR(30) NOT NULL DEFAULT 'CORRECTION_REQUIRED',
    approved_by VARCHAR(100) NOT NULL,
    approved_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_daily_income_evidence_item (source_daily_employment_income_id, daily_employment_income_item_id),
    UNIQUE KEY uq_daily_income_evidence_approval_item (approval_request_id, daily_employment_income_item_id),
    CONSTRAINT fk_daily_evidence_header FOREIGN KEY (source_daily_employment_income_id) REFERENCES institution_daily_employment_incomes(id),
    CONSTRAINT fk_daily_evidence_item FOREIGN KEY (daily_employment_income_item_id) REFERENCES institution_daily_employment_income_items(id),
    CONSTRAINT fk_daily_evidence_approval FOREIGN KEY (approval_request_id) REFERENCES user_approval_requests(id),
    CONSTRAINT fk_daily_evidence_worker FOREIGN KEY (worker_client_id) REFERENCES system_clients(id),
    CONSTRAINT fk_daily_evidence_project FOREIGN KEY (project_id) REFERENCES system_projects(id),
    CONSTRAINT fk_daily_evidence_team FOREIGN KEY (work_team_id) REFERENCES system_work_teams(id),
    CONSTRAINT ck_daily_evidence_scope CHECK ((work_scope_code = 'PROJECT' AND project_id IS NOT NULL) OR (work_scope_code = 'HEAD_OFFICE' AND project_id IS NULL)),
    CONSTRAINT ck_daily_evidence_status CHECK (evidence_status_code IN ('CORRECTION_REQUIRED', 'COMPLETED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='일용근로소득 Item별 증빙원본';
