CREATE TABLE `ledger_inventory_balances` (
  `id` char(36) NOT NULL COMMENT '회계연도별 재고관리 문서 고유번호',
  `company_id` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '재고관리 대상 회사',
  `fiscal_year` smallint unsigned NOT NULL COMMENT '재고가 귀속되는 회계연도',
  `status_code` varchar(20) NOT NULL DEFAULT 'DRAFT' COMMENT '재고관리 문서 상태(DRAFT, CONFIRMED)',
  `note` varchar(500) DEFAULT NULL COMMENT '재고관리 문서 비고',
  `confirmed_at` datetime DEFAULT NULL COMMENT '기말재고 확정일시',
  `confirmed_by` varchar(100) DEFAULT NULL COMMENT '기말재고 확정 Actor',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '재고관리 문서 생성일시',
  `created_by` varchar(100) NOT NULL COMMENT '재고관리 문서 생성 Actor',
  `updated_at` datetime DEFAULT NULL COMMENT '재고관리 문서 수정일시',
  `updated_by` varchar(100) DEFAULT NULL COMMENT '재고관리 문서 수정 Actor',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ledger_inventory_balances_company_year` (`company_id`,`fiscal_year`),
  KEY `idx_ledger_inventory_balances_status` (`status_code`,`fiscal_year`),
  CONSTRAINT `fk_ledger_inventory_balances_company` FOREIGN KEY (`company_id`) REFERENCES `system_company` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_ledger_inventory_balances_year` CHECK (`fiscal_year` between 1900 and 9999),
  CONSTRAINT `chk_ledger_inventory_balances_status` CHECK (`status_code` IN ('DRAFT','CONFIRMED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='회사·회계연도별 기초재고와 당기 증감을 근거로 기말재고를 확정하는 문서';

CREATE TABLE `ledger_inventory_balance_items` (
  `id` char(36) NOT NULL COMMENT '재고가액 증감 근거행 고유번호',
  `inventory_balance_id` char(36) NOT NULL COMMENT '상위 재고관리 문서',
  `sort_no` int unsigned NOT NULL COMMENT '문서 안 재고행 정렬순서',
  `business_unit` varchar(30) NOT NULL COMMENT '재고 귀속 사업구분(BUSINESS_UNIT)',
  `project_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '전문건설업 재고 귀속 프로젝트',
  `inventory_category_code` varchar(30) NOT NULL COMMENT '재고구분(원재료, 부재료, 상품, 저장품, 기타)',
  `item_name` varchar(150) NOT NULL COMMENT '재고 품명 또는 관리 묶음명',
  `opening_amount` decimal(18,2) NOT NULL DEFAULT 0 COMMENT '회계연도 기초재고액',
  `increase_amount` decimal(18,2) NOT NULL DEFAULT 0 COMMENT '당기 재고가액 증가액',
  `decrease_amount` decimal(18,2) NOT NULL DEFAULT 0 COMMENT '당기 재고가액 감소액',
  `calculation_basis` varchar(1000) NOT NULL COMMENT '기초·증가·감소 금액의 산출근거',
  `evidence_reference` varchar(500) NOT NULL COMMENT '증빙원본·거래·문서·사진·엑셀 등 증거자료 참조',
  `note` varchar(500) DEFAULT NULL COMMENT '재고가액 증감 근거행 비고',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '재고행 생성일시',
  `created_by` varchar(100) NOT NULL COMMENT '재고행 생성 Actor',
  `updated_at` datetime DEFAULT NULL COMMENT '재고행 수정일시',
  `updated_by` varchar(100) DEFAULT NULL COMMENT '재고행 수정 Actor',
  PRIMARY KEY (`id`),
  KEY `idx_ledger_inventory_items_document` (`inventory_balance_id`,`sort_no`),
  KEY `idx_ledger_inventory_items_scope` (`business_unit`,`project_id`,`inventory_category_code`),
  CONSTRAINT `fk_ledger_inventory_items_document` FOREIGN KEY (`inventory_balance_id`) REFERENCES `ledger_inventory_balances` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `fk_ledger_inventory_items_project` FOREIGN KEY (`project_id`) REFERENCES `system_projects` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_ledger_inventory_items_amounts` CHECK (`opening_amount` >= 0 AND `increase_amount` >= 0 AND `decrease_amount` >= 0),
  CONSTRAINT `chk_ledger_inventory_items_project` CHECK (`business_unit` <> 'CONSTRUCTION' OR `project_id` IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사업구분·프로젝트·재고구분별 기초재고와 당기 증감의 금액 및 증거 근거';
