CREATE TABLE `ledger_vehicles` (
  `id` char(36) NOT NULL COMMENT '업무용 차량 고유번호',
  `company_id` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '차량 비용을 부담하는 회사',
  `asset_id` char(36) DEFAULT NULL COMMENT '법인차량인 경우 연결된 고정자산',
  `vehicle_no` varchar(30) NOT NULL COMMENT '차량등록번호',
  `vehicle_name` varchar(100) NOT NULL COMMENT '차종 또는 차량명',
  `ownership_type_code` varchar(20) NOT NULL COMMENT '차량 소유구분(CORPORATE:법인차량,PERSONAL:개인차량)',
  `default_employee_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '차량 기본 사용자',
  `home_location` varchar(255) DEFAULT NULL COMMENT '기본 자택 또는 출발지',
  `work_location` varchar(255) DEFAULT NULL COMMENT '기본 근무지',
  `commute_distance_km` decimal(10,2) DEFAULT NULL COMMENT '편도 출퇴근 기준거리(km)',
  `is_active` tinyint(1) NOT NULL DEFAULT 1 COMMENT '차량 사용 여부',
  `note` varchar(500) DEFAULT NULL COMMENT '차량 관리 비고',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '생성일시',
  `created_by` varchar(100) NOT NULL COMMENT '생성 Actor',
  `updated_at` datetime DEFAULT NULL COMMENT '수정일시',
  `updated_by` varchar(100) DEFAULT NULL COMMENT '수정 Actor',
  `deleted_at` datetime DEFAULT NULL COMMENT '삭제일시',
  `deleted_by` varchar(100) DEFAULT NULL COMMENT '삭제 Actor',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ledger_vehicles_company_vehicle_no` (`company_id`,`vehicle_no`),
  UNIQUE KEY `uk_ledger_vehicles_asset` (`asset_id`),
  KEY `idx_ledger_vehicles_owner_active` (`ownership_type_code`,`is_active`),
  KEY `idx_ledger_vehicles_asset` (`asset_id`),
  KEY `idx_ledger_vehicles_employee` (`default_employee_id`),
  CONSTRAINT `fk_ledger_vehicles_company` FOREIGN KEY (`company_id`) REFERENCES `system_company` (`id`),
  CONSTRAINT `fk_ledger_vehicles_asset` FOREIGN KEY (`asset_id`) REFERENCES `ledger_assets` (`id`),
  CONSTRAINT `fk_ledger_vehicles_employee` FOREIGN KEY (`default_employee_id`) REFERENCES `user_employees` (`id`),
  CONSTRAINT `chk_ledger_vehicles_owner` CHECK (`ownership_type_code` IN ('CORPORATE','PERSONAL')),
  CONSTRAINT `chk_ledger_vehicles_commute` CHECK (`commute_distance_km` IS NULL OR `commute_distance_km` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='회사 비용으로 운행하는 법인·개인 차량 마스터';

CREATE TABLE `ledger_vehicle_trip_logs` (
  `id` char(36) NOT NULL COMMENT '차량 운행기록 고유번호',
  `company_id` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '운행비용을 부담하는 회사',
  `vehicle_id` char(36) NOT NULL COMMENT '운행 차량',
  `employee_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '실제 차량 사용자',
  `driver_name_snapshot` varchar(50) NOT NULL COMMENT '운행 당시 사용자명 Snapshot',
  `department_name_snapshot` varchar(100) DEFAULT NULL COMMENT '운행 당시 부서명 Snapshot',
  `position_name_snapshot` varchar(100) DEFAULT NULL COMMENT '운행 당시 직위명 Snapshot',
  `work_team_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '운행 귀속 작업팀',
  `trip_date` date NOT NULL COMMENT '운행일자',
  `started_at` datetime DEFAULT NULL COMMENT '운행 출발일시',
  `ended_at` datetime DEFAULT NULL COMMENT '운행 도착일시',
  `purpose_type_code` varchar(20) NOT NULL COMMENT '운행구분(BUSINESS:업무용,COMMUTE:출퇴근,PRIVATE:비업무용,UNCLASSIFIED:미분류)',
  `purpose` varchar(255) NOT NULL COMMENT '운행목적',
  `origin_location` varchar(255) NOT NULL COMMENT '출발지',
  `destination_location` varchar(255) NOT NULL COMMENT '도착지',
  `start_odometer_km` decimal(12,2) DEFAULT NULL COMMENT '출발 전 누적거리(km)',
  `end_odometer_km` decimal(12,2) DEFAULT NULL COMMENT '도착 후 누적거리(km)',
  `distance_km` decimal(10,2) NOT NULL COMMENT '총 주행거리(km)',
  `business_distance_km` decimal(10,2) NOT NULL COMMENT '업무용 주행거리(km)',
  `source_type_code` varchar(20) NOT NULL DEFAULT 'MANUAL' COMMENT '자료출처(MANUAL,EXCEL,DOMAIN,CARTAX,GPS,MOBILE)',
  `source_record_id` varchar(150) DEFAULT NULL COMMENT '업무도메인·외부시스템 원본 식별자',
  `capture_status_code` varchar(20) NOT NULL DEFAULT 'COMPLETE' COMMENT '기록상태(COMPLETE,REVIEW_REQUIRED)',
  `note` varchar(500) DEFAULT NULL COMMENT '운행기록 비고',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '생성일시',
  `created_by` varchar(100) NOT NULL COMMENT '생성 Actor',
  `updated_at` datetime DEFAULT NULL COMMENT '수정일시',
  `updated_by` varchar(100) DEFAULT NULL COMMENT '수정 Actor',
  `deleted_at` datetime DEFAULT NULL COMMENT '삭제일시',
  `deleted_by` varchar(100) DEFAULT NULL COMMENT '삭제 Actor',
  `restored_at` datetime DEFAULT NULL COMMENT '복구일시',
  `restored_by` varchar(100) DEFAULT NULL COMMENT '복구 Actor',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ledger_vehicle_trip_source` (`source_type_code`,`source_record_id`),
  KEY `idx_ledger_vehicle_trip_date_vehicle` (`trip_date`,`vehicle_id`),
  KEY `idx_ledger_vehicle_trip_employee` (`employee_id`,`trip_date`),
  KEY `idx_ledger_vehicle_trip_company` (`company_id`,`trip_date`),
  KEY `idx_ledger_vehicle_trip_team` (`work_team_id`,`trip_date`),
  CONSTRAINT `fk_ledger_vehicle_trip_company` FOREIGN KEY (`company_id`) REFERENCES `system_company` (`id`),
  CONSTRAINT `fk_ledger_vehicle_trip_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `ledger_vehicles` (`id`),
  CONSTRAINT `fk_ledger_vehicle_trip_employee` FOREIGN KEY (`employee_id`) REFERENCES `user_employees` (`id`),
  CONSTRAINT `chk_ledger_vehicle_trip_purpose` CHECK (`purpose_type_code` IN ('BUSINESS','COMMUTE','PRIVATE','UNCLASSIFIED')),
  CONSTRAINT `chk_ledger_vehicle_trip_source` CHECK (`source_type_code` IN ('MANUAL','EXCEL','DOMAIN','CARTAX','GPS','MOBILE')),
  CONSTRAINT `chk_ledger_vehicle_trip_status` CHECK (`capture_status_code` IN ('COMPLETE','REVIEW_REQUIRED')),
  CONSTRAINT `chk_ledger_vehicle_trip_distance` CHECK (`distance_km` >= 0 AND `business_distance_km` >= 0 AND `business_distance_km` <= `distance_km`),
  CONSTRAINT `chk_ledger_vehicle_trip_time` CHECK (`ended_at` IS NULL OR `started_at` IS NULL OR `ended_at` >= `started_at`),
  CONSTRAINT `chk_ledger_vehicle_trip_odometer` CHECK (`end_odometer_km` IS NULL OR `start_odometer_km` IS NULL OR `end_odometer_km` >= `start_odometer_km`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='수동·엑셀·업무도메인·GPS 공용 차량 운행기록 원장';
