<?php
use Core\Helpers\AssetHelper;
$pageStyles=AssetHelper::css('/assets/css/pages/institution/leave/index.css');
$pageScripts=AssetHelper::module('/assets/js/pages/institution/leave/index.js');
?>
<main class="leave-page"><div class="container-fluid py-4">
  <div class="d-flex justify-content-between align-items-start mb-3"><div><h5 class="mb-1 fw-bold"><i class="bi bi-calendar-check me-2"></i>휴가관리</h5><p class="text-muted small mb-0">휴가 신청, 부여, 잔액과 승인된 사용 이력을 관리합니다.</p></div><div class="d-flex gap-2"><?php if(!empty($capabilities['save'])):?><button class="btn btn-primary btn-sm" data-leave-action="request">휴가 신청</button><?php endif;?><?php if(!empty($capabilities['grant'])):?><button class="btn btn-outline-primary btn-sm" data-leave-action="grant">휴가 부여</button><?php endif;?><?php if(!empty($capabilities['adjust'])):?><button class="btn btn-outline-secondary btn-sm" data-leave-action="adjust">잔액 조정</button><?php endif;?><?php if(!empty($capabilities['excel'])):?><a class="btn btn-outline-success btn-sm" id="leaveExcel" href="/api/institution/human-resources/leave/excel?type=requests">Excel 다운로드</a><?php endif;?></div></div>
  <ul class="nav nav-tabs mb-3" id="leaveTabs"><li class="nav-item"><button class="nav-link active" data-tab="self">내 휴가</button></li><li class="nav-item"><button class="nav-link" data-tab="history">휴가 신청·이력</button></li><?php if(!empty($capabilities['view_all'])):?><li class="nav-item"><button class="nav-link" data-tab="all">전체 휴가 현황</button></li><li class="nav-item"><button class="nav-link" data-tab="balances">휴가 부여·잔액</button></li><?php endif;?><?php if(!empty($capabilities['type_save'])):?><li class="nav-item"><button class="nav-link" data-tab="settings">휴가 설정</button></li><?php endif;?></ul>
  <div class="dt-content-stack" id="leaveListArea"><?php $searchId='leave';$dateOptions='<option value="leave_date">휴가일</option>';$searchFieldOptions='<option value="employee_id">직원</option><option value="status_code">신청상태</option><option value="base_year">기준연도</option>';include PROJECT_ROOT.'/app/views/components/ui-search.php';?><?php $tableId='leaveTable';$ajaxUrl='/api/institution/human-resources/leave/list';$columnsType='leave';$enableButtons=true;$enableSearch=true;$enablePaging=true;$enableReorder=false;include PROJECT_ROOT.'/app/views/components/ui-table.php';?></div>
</div></main>
<div class="modal fade" id="leaveFormModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><form class="modal-content" id="leaveForm"><div class="modal-header"><h5 class="modal-title" id="leaveFormTitle">휴가 처리</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="operation"><input type="hidden" name="id"><input type="hidden" name="request_key"><div class="row g-3"><div class="col-md-4 admin-field"><label class="form-label">직원</label><select class="form-select form-select-sm" name="employee_id"></select></div><div class="col-md-4 common-field"><label class="form-label">휴가 종류</label><select class="form-select form-select-sm" name="leave_type_id"></select></div><div class="col-md-4 grant-field adjust-field"><label class="form-label">기준연도</label><input class="form-control form-control-sm" type="number" name="base_year"></div><div class="col-md-4 grant-field"><label class="form-label">부여량(분)</label><input class="form-control form-control-sm" type="number" name="granted_minutes"></div><div class="col-md-4 adjust-field"><label class="form-label">증감 분</label><input class="form-control form-control-sm" type="number" name="amount_minutes"></div><div class="col-md-4 grant-field"><label class="form-label">사용 시작일</label><input class="form-control form-control-sm admin-date" type="date" name="usable_from"></div><div class="col-md-4 grant-field"><label class="form-label">사용 종료일</label><input class="form-control form-control-sm admin-date" type="date" name="usable_to"></div><div class="col-md-4 grant-field"><label class="form-label">소멸일</label><input class="form-control form-control-sm admin-date" type="date" name="expires_on"></div><div class="col-12 request-field"><div class="d-flex justify-content-between align-items-center mb-2"><label class="form-label mb-0">날짜별 휴가 사용</label><button class="btn btn-outline-primary btn-sm" id="leaveAddItem" type="button">사용일 추가</button></div><div class="table-responsive"><table class="table table-sm table-bordered"><thead><tr><th>휴가 종류</th><th>휴가일</th><th>신청단위</th><th>시작시각</th><th>종료시각</th><th></th></tr></thead><tbody id="leaveItemRows"></tbody></table></div></div><div class="col-12"><label class="form-label">사유</label><textarea class="form-control form-control-sm" name="reason" rows="3"></textarea></div></div></div><div class="modal-footer"><button class="btn btn-secondary btn-sm" type="button" data-bs-dismiss="modal">취소</button><button class="btn btn-primary btn-sm" type="submit">저장</button></div></form></div></div>
<div class="modal fade" id="leaveDetailModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">휴가 상세</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body" id="leaveDetailBody"></div></div></div></div>
<div class="modal fade" id="leaveTypeModal" tabindex="-1"><div class="modal-dialog"><form class="modal-content" id="leaveTypeForm"><div class="modal-header"><h5 class="modal-title">휴가 정책 수정</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="id"><div class="mb-3"><label class="form-label">휴가 종류명</label><input class="form-control form-control-sm" name="type_name" required></div><div class="d-flex gap-3 mb-3"><label><input type="checkbox" name="is_paid"> 유급</label><label><input type="checkbox" name="deducts_balance"> 잔액 차감</label><label><input type="checkbox" name="is_active"> 사용</label></div><div class="mb-3"><label class="form-label">증빙 정책</label><select class="form-select form-select-sm" name="evidence_policy_code"><option value="NONE">없음</option><option value="OPTIONAL">선택</option><option value="REQUIRED">필수</option></select></div><div><label class="form-label">허용 신청단위</label><div class="d-flex flex-wrap gap-3"><?php foreach(['FULL_DAY'=>'전일','AM_HALF'=>'오전 반차','PM_HALF'=>'오후 반차','HOURLY'=>'시간차'] as $value=>$label):?><label><input type="checkbox" name="allowed_units[]" value="<?=$value?>"> <?=$label?></label><?php endforeach;?></div></div></div><div class="modal-footer"><button class="btn btn-secondary btn-sm" type="button" data-bs-dismiss="modal">취소</button><button class="btn btn-primary btn-sm" type="submit">저장</button></div></form></div></div>
<div id="leaveTimePicker" class="picker admin-picker is-hidden"></div>
<script type="application/json" id="leaveBootstrap"><?=json_encode(['options'=>$leaveOptions,'capabilities'=>$capabilities],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?></script>
