<?php
use Core\Helpers\AssetHelper;
$pageStyles=AssetHelper::css('/assets/css/pages/institution/leave/index.css');
$pageScripts=AssetHelper::module('/assets/js/pages/institution/leave/index.js');
?>
<main class="leave-page"><div class="container-fluid py-4 dt-page-shell">
  <div class="mb-3"><h5 class="mb-1 fw-bold"><i class="bi bi-calendar-check me-2"></i>휴가관리</h5><p class="text-muted small mb-0">전체 직원의 휴가 현황, 부여·잔액과 휴가유형 정책을 관리합니다.</p></div>
  <ul class="nav nav-tabs mb-3" id="leaveTabs"><li class="nav-item"><button class="nav-link active" data-tab="status">휴가 현황</button></li><li class="nav-item"><button class="nav-link" data-tab="balances">부여·잔액</button></li><li class="nav-item"><button class="nav-link" data-tab="types">휴가 유형</button></li></ul>
  <div class="dt-content-stack"><?php $searchId='leave-admin';$dateOptions='<option value="leave_date">휴가일</option>';$searchFieldOptions='<option value="employee_id">직원</option><option value="status_code">상태</option><option value="base_year">기준연도</option>';include PROJECT_ROOT.'/app/views/components/ui-search.php';?><?php $tableId='leaveTable';$ajaxUrl='/api/institution/human-resources/leave/status-list';$columnsType='leave-admin';$enableButtons=true;$enableSearch=true;$enablePaging=true;$enableReorder=false;include PROJECT_ROOT.'/app/views/components/ui-table.php';?></div>
</div></main>
<div class="modal fade" id="leaveAdminModal" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" id="leaveAdminForm"><div class="modal-header"><h5 class="modal-title">휴가 관리</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="operation"><input type="hidden" name="request_key"><div class="row g-3"><div class="col-md-6"><label class="form-label">직원</label><select class="form-select" name="employee_id" required></select></div><div class="col-md-6"><label class="form-label">휴가유형</label><select class="form-select" name="leave_type_id" required></select></div><div class="col-md-4"><label class="form-label">기준연도</label><input class="form-control" type="number" name="base_year" required></div><div class="col-md-4 grant-field"><label class="form-label">부여량(분)</label><input class="form-control" type="number" name="granted_minutes"></div><div class="col-md-4 adjust-field"><label class="form-label">조정량(분)</label><input class="form-control" type="number" name="amount_minutes"></div><div class="col-md-4 grant-field"><label class="form-label">사용 시작일</label><input class="form-control admin-date" name="usable_from" readonly></div><div class="col-md-4 grant-field"><label class="form-label">사용 종료일</label><input class="form-control admin-date" name="usable_to" readonly></div><div class="col-md-4 grant-field"><label class="form-label">소멸일</label><input class="form-control admin-date" name="expires_on" readonly></div><div class="col-12"><label class="form-label">사유</label><textarea class="form-control" name="reason" required></textarea></div></div></div><div class="modal-footer"><button class="btn btn-secondary btn-sm" type="button" data-bs-dismiss="modal">닫기</button><button class="btn btn-primary btn-sm" type="submit">저장</button></div></form></div></div>
<div class="modal fade" id="leaveTypeModal" tabindex="-1"><div class="modal-dialog"><form class="modal-content" id="leaveTypeForm"><div class="modal-header"><h5 class="modal-title">휴가 유형 수정</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="id"><label class="form-label">유형명</label><input class="form-control mb-3" name="type_name" required><div class="d-flex gap-3 mb-3"><label><input type="checkbox" name="is_paid"> 유급</label><label><input type="checkbox" name="deducts_balance"> 잔액 차감</label><label><input type="checkbox" name="is_active"> 활성</label></div><label class="form-label">증빙 정책</label><select class="form-select mb-3" name="evidence_policy_code"><option value="NONE">없음</option><option value="OPTIONAL">선택</option><option value="REQUIRED">필수(현재 상신 미지원)</option></select><div class="d-flex gap-3 flex-wrap"><?php foreach(['FULL_DAY'=>'전일','AM_HALF'=>'오전 반차','PM_HALF'=>'오후 반차','HOURLY'=>'시간차'] as $value=>$label):?><label><input type="checkbox" name="allowed_units[]" value="<?=$value?>"> <?=$label?></label><?php endforeach;?></div></div><div class="modal-footer"><button class="btn btn-secondary btn-sm" type="button" data-bs-dismiss="modal">닫기</button><button class="btn btn-primary btn-sm" type="submit">저장</button></div></form></div></div>
<div id="leaveAdminDatePicker" class="picker admin-picker is-hidden"></div><script type="application/json" id="leaveBootstrap"><?=json_encode(['options'=>$leaveOptions,'capabilities'=>$capabilities],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?></script>
