<?php

use Core\Helpers\AssetHelper;

$pageStyles = AssetHelper::css('/assets/css/pages/institution/regular-employment-income.css');
$pageScripts = AssetHelper::module('/assets/js/pages/institution/regular-employment-income/index.js');
?>
<div class="regular-employment-income-page">
 <div class="page-header d-flex align-items-center gap-2"><h4 class="mb-0 fw-bold">상용근로소득</h4><span id="regularIncomeCount" class="text-primary"></span></div>
 <div class="content-area mt-3">
 <?php $searchId='regularIncome';$dateOptions='<option value="payment_date">지급일</option>';$searchFieldOptions='<option value="income_year_month">귀속연월</option><option value="title">제목</option><option value="document_status">문서상태</option>';include PROJECT_ROOT.'/app/views/components/ui-search.php';$tableId='regular-income-table';$ajaxUrl='/api/institution/income-data/regular-employment/list';$columnsType='regularIncome';$enableButtons=true;$enableSearch=true;$enablePaging=true;$enableReorder=false;include PROJECT_ROOT.'/app/views/components/ui-table.php';?>
 </div>
</div>
<div class="modal fade" id="regularIncomeModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><form class="modal-content" id="regularIncomeForm"><div class="modal-header"><h5 class="modal-title">상용근로소득</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="id"><input type="hidden" name="current_approval_request_id"><div class="row g-3"><div class="col-md-3"><label class="form-label">귀속연월</label><input class="form-control" name="income_year_month" type="month" required></div><div class="col-md-3"><label class="form-label">지급일</label><input class="form-control admin-date" name="payment_date" required></div><div class="col-md-6"><label class="form-label">제목</label><input class="form-control" name="title" required></div><div class="col-12"><label class="form-label">비고</label><input class="form-control" name="description"></div></div><div class="d-flex justify-content-between align-items-center mt-4 mb-2"><h6 class="mb-0">직원별 소득내역</h6><button type="button" class="btn btn-outline-primary btn-sm" id="loadEligibleEmployees">귀속월 대상직원 불러오기</button></div><div class="table-responsive"><table class="table table-bordered table-sm" id="regularIncomeItems"><thead><tr><th>직원</th><th>기본급</th><th>과세수당</th><th>상여금</th><th>비과세</th><th>국민연금</th><th>건강보험</th><th>장기요양</th><th>고용보험</th><th>근로소득세</th><th>지방소득세</th><th>기타공제</th><th>관리</th></tr></thead><tbody></tbody></table></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-danger me-auto" id="regularIncomeDelete">삭제</button><button type="button" class="btn btn-outline-secondary" id="regularIncomeWithdraw">회수</button><button type="button" class="btn btn-primary" id="regularIncomeSubmit">결재요청</button><button type="submit" class="btn btn-success">저장</button><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button></div></form></div></div>
