<?php

declare(strict_types=1);

return [
    'app/Services/Approval/ApprovalDocumentAdapterInterface.php' => 'PURE',
    'app/Services/Approval/ApprovalInboxService.php' => 'DELEGATED',
    'app/Services/Approval/BusinessIncomeApprovalAdapter.php' => 'DELEGATED',
    'app/Services/Approval/DailyEmploymentIncomeApprovalAdapter.php' => 'DELEGATED',
    'app/Services/Approval/EmploymentContractApprovalAdapter.php' => 'DELEGATED',
    'app/Services/Approval/EmploymentRuleApprovalAdapter.php' => 'DELEGATED',
    'app/Services/Approval/LeaveApprovalAdapter.php' => 'DELEGATED',
    'app/Services/Approval/LeaveRequestService.php' => 'DELEGATED',
    'app/Services/Approval/PersonalExpenseApprovalAdapter.php' => 'DELEGATED',
    'app/Services/Approval/PersonnelActionApprovalAdapter.php' => 'DELEGATED',
    'app/Services/Approval/RegularEmploymentIncomeApprovalAdapter.php' => 'DELEGATED',
    'app/Services/Auth/AuthSessionService.php' => 'INFRASTRUCTURE',
    'app/Services/Auth/LogService.php' => 'INFRASTRUCTURE',
    'app/Services/Auth/TokenService.php' => 'INFRASTRUCTURE',
    'app/Services/Ledger/AccountContextRefPolicyService.php' => 'PURE',
    'app/Services/Ledger/EvidenceBatchSaveService.php' => 'DELEGATED',
    'app/Services/Ledger/EvidenceClientSyncService.php' => 'DELEGATED',
    'app/Services/Ledger/EvidenceDeleteRestoreService.php' => 'DELEGATED',
    'app/Services/Ledger/EvidenceImportBusinessService.php' => 'DELEGATED',
    'app/Services/Ledger/EvidenceLinkHelperService.php' => 'DELEGATED',
    'app/Services/Ledger/JournalLearningPolicyService.php' => 'DELEGATED',
    'app/Services/Ledger/JournalLearningFeedbackService.php' => 'DELEGATED',
    'app/Services/Ledger/EvidenceStatusHelperService.php' => 'PURE',
    'app/Services/Ledger/EvidenceUploadParserService.php' => 'PURE',
    'app/Services/Ledger/EvidenceUploadService.php' => 'INFRASTRUCTURE',
    'app/Services/Ledger/EvidenceTemplateDropdownService.php' => 'PURE',
    'app/Services/Ledger/EvidenceTypePolicyService.php' => 'PURE',
    'app/Services/Ledger/EvidenceWorkflowPolicyService.php' => 'PURE',
    'app/Services/Ledger/VoucherCreateService.php' => 'DELEGATED',
    'app/Services/Ledger/VoucherLineSourceRefService.php' => 'DELEGATED',
    'app/Services/Ledger/VoucherLineRefService.php' => 'DELEGATED',
    'app/Services/Ledger/VoucherPolicyService.php' => 'PURE',
    'app/Services/Ledger/VoucherNumberService.php' => 'DELEGATED',
    'app/Services/Ledger/VoucherPurgeService.php' => 'DELEGATED',
    'app/Services/Ledger/VoucherQueryService.php' => 'PURE',
    'app/Services/Mail/AdminApprovalMail.php' => 'DELEGATED',
    'app/Services/Mail/ContactMail.php' => 'DELEGATED',
    'app/Services/Mail/TwoFactorMail.php' => 'DELEGATED',
    'app/Services/Mail/MailToken.php' => 'PURE',
    'app/Services/System/ClientFileService.php' => 'DELEGATED',
    'app/Services/System/ClientExcelService.php' => 'DELEGATED',
    'app/Services/System/ProjectExcelService.php' => 'DELEGATED',
    'app/Services/System/ProjectTrashService.php' => 'DELEGATED',
    'app/Services/Institution/EmployeeHrBaselineService.php' => 'DELEGATED',
    'app/Services/Institution/PersonnelActionChangePolicy.php' => 'PURE',
    'app/Services/Funds/PaymentObligationService.php' => 'DELEGATED',
];
