<?php
use Core\Helpers\AssetHelper;
$layoutOptions=['header'=>true,'navbar'=>true,'sidebar'=>true,'footer'=>true,'wrapper'=>'single'];$pageStyles=AssetHelper::css('/assets/css/pages/ledger/book/project/index.css');$pageScripts=AssetHelper::module('/assets/js/pages/ledger/book/project/index.js');
?>
<main class="ledger-project-book" id="ledgerProjectBookPage"><div class="container-fluid py-4 dt-page-shell">
 <div class="page-header"><div><h5 class="mb-0 fw-bold"><i class="bi bi-building me-2"></i>프로젝트원장</h5><div class="text-muted small mt-1">선택 프로젝트와 연결된 계정별 기초잔액·전표 증감·잔액을 조회합니다.</div></div><span id="ledgerProjectBookCount" class="text-primary page-count"></span></div>
 <section class="project-selector-bar"><label for="projectLedgerProject"><span>조회 프로젝트</span><strong>*</strong></label><select id="projectLedgerProject" class="form-select form-select-sm" aria-label="조회 프로젝트"><option value="">프로젝트 검색</option></select><span id="projectLedgerSelectionGuide">프로젝트명을 검색해 선택해 주세요.</span></section>
 <?php $searchId='ledgerProjectBook';$dateOptions='<option value="voucher_date">전표일자</option>';$searchFieldOptions='<option value="">선택</option>';$periodGuideTitle='프로젝트원장 기간 조건 안내';$periodGuideItems=['조회 시작일에 적용되는 프로젝트별 기초금액과 기간 내 분개를 합산합니다.','공식 장부에는 전기완료·마감 전표만 포함됩니다.'];$searchGuideTitle='프로젝트원장 검색 조건 안내';$searchGuideItems=['전표번호, 계정코드, 계정과목, 적요로 검색할 수 있습니다.','선택 프로젝트가 보조원장으로 연결된 분개만 조회합니다.'];include PROJECT_ROOT.'/app/views/components/ui-search.php';?>
 <section class="project-scope-bar"><div><strong>공식 장부</strong><span>전기완료·마감 전표만 조회합니다.</span></div></section>
 <section class="project-summary" aria-label="프로젝트원장 합계"><div><span>사용계정</span><strong id="projectAccountCount">0개</strong></div><div><span>기초차변</span><strong id="projectOpeningDebit">0원</strong></div><div><span>기초대변</span><strong id="projectOpeningCredit">0원</strong></div><div><span>당기차변</span><strong id="projectPeriodDebit">0원</strong></div><div><span>당기대변</span><strong id="projectPeriodCredit">0원</strong></div><div><span>기말차변</span><strong id="projectEndingDebit">0원</strong></div><div><span>기말대변</span><strong id="projectEndingCredit">0원</strong></div><div><span>전표/분개</span><strong id="projectVoucherLines">0건 / 0건</strong></div></section>
 <section class="project-table-panel"><?php $tableId='ledgerProjectBookTable';$ajaxUrl='/api/ledger/book/project/list';$columnsType='ledger-project-book';$tableClass='table table-bordered align-middle table-cross-highlight ledger-project-book-table';$enableButtons=true;$enableSearch=true;$enablePaging=true;$enableReorder=false;include PROJECT_ROOT.'/app/views/components/ui-table.php';?></section>
 <div class="project-help text-muted small"><i class="bi bi-info-circle me-1"></i>프로젝트에 연결된 계정별 잔액을 보존하며, 원장 오류는 전표 취소·정정으로 처리합니다.</div>
</div></main>
