<?php
namespace App\Models\Site;
use PDO;
final class EstimateModel
{
    public function __construct(private readonly PDO $db){}
    public function list(array $f):array{$w=['e.deleted_at IS NULL'];$p=[];if(($f['status']??'')!==''){$w[]='e.estimate_status_code=:status';$p[':status']=$f['status'];}if(($f['keyword']??'')!==''){$w[]='(e.estimate_number LIKE :q OR e.construction_name LIKE :q OR e.requester_name LIKE :q)';$p[':q']='%'.$f['keyword'].'%';}return$this->all('SELECT e.*,u.employee_name owner_employee_name,(SELECT COUNT(*) FROM site_estimate_packages p WHERE p.estimate_id=e.id) package_count,(SELECT COALESCE(SUM(i.quantity*i.submission_unit_price),0) FROM site_estimate_packages p JOIN site_estimate_versions v ON v.estimate_package_id=p.id JOIN site_estimate_items i ON i.estimate_version_id=v.id WHERE p.estimate_id=e.id AND v.version_no=(SELECT MAX(v2.version_no) FROM site_estimate_versions v2 WHERE v2.estimate_package_id=p.id)) latest_submission_amount FROM site_estimates e JOIN user_employees u ON u.id=e.owner_employee_id WHERE '.implode(' AND ',$w).' ORDER BY e.estimate_date DESC,e.estimate_number DESC',$p);}
    public function estimate(string$id,bool$lock=false):?array{return$this->one('SELECT e.*,u.employee_name owner_employee_name FROM site_estimates e JOIN user_employees u ON u.id=e.owner_employee_id WHERE e.id=:id AND e.deleted_at IS NULL'.($lock?' FOR UPDATE':''),[':id'=>$id]);}
    public function packages(string$id):array{return$this->all('SELECT p.* FROM site_estimate_packages p WHERE p.estimate_id=:id ORDER BY p.sort_no,p.id',[':id'=>$id]);}
    public function versions(string$id):array{return$this->all('SELECT v.*,COALESCE(SUM(i.quantity*i.execution_unit_price),0) execution_amount,COALESCE(SUM(i.quantity*i.submission_unit_price),0) submission_amount FROM site_estimate_versions v LEFT JOIN site_estimate_items i ON i.estimate_version_id=v.id WHERE v.estimate_package_id=:id GROUP BY v.id ORDER BY v.version_no DESC',[':id'=>$id]);}
    public function version(string$id,bool$lock=false):?array{return$this->one('SELECT * FROM site_estimate_versions WHERE id=:id'.($lock?' FOR UPDATE':''),[':id'=>$id]);}
    public function items(string$id):array{return$this->all('SELECT i.*,(i.quantity*i.execution_unit_price) execution_amount,(i.quantity*i.submission_unit_price) submission_amount,((i.quantity*i.submission_unit_price)-(i.quantity*i.execution_unit_price)) margin_amount FROM site_estimate_items i WHERE i.estimate_version_id=:id ORDER BY i.sort_no,i.id',[':id'=>$id]);}
    public function costs(string$id):array{return$this->all('SELECT c.*,(c.quantity*c.unit_price) cost_amount FROM site_estimate_item_costs c WHERE c.estimate_item_id=:id ORDER BY c.sort_no,c.id',[':id'=>$id]);}
    public function insertEstimate(array$p):void{$this->run('INSERT INTO site_estimates(id,estimate_number,estimate_date,construction_name,requester_name,requester_person_name,site_address,owner_employee_id,submission_due_date,estimate_status_code,folder_path,note,created_at,created_by,updated_at,updated_by) VALUES(:id,:estimate_number,:estimate_date,:construction_name,:requester_name,:requester_person_name,:site_address,:owner_employee_id,:submission_due_date,:estimate_status_code,:folder_path,:note,:created_at,:created_by,:updated_at,:updated_by)',$p);}
    public function updateEstimate(string$id,array$p):void{$p[':id']=$id;$this->run('UPDATE site_estimates SET estimate_number=:estimate_number,estimate_date=:estimate_date,construction_name=:construction_name,requester_name=:requester_name,requester_person_name=:requester_person_name,site_address=:site_address,owner_employee_id=:owner_employee_id,submission_due_date=:submission_due_date,estimate_status_code=:estimate_status_code,folder_path=:folder_path,note=:note,updated_at=:updated_at,updated_by=:updated_by WHERE id=:id',$p);}
    public function duplicateNumber(string$n,string$id=''):bool{return(bool)$this->scalar('SELECT COUNT(*) FROM site_estimates WHERE estimate_number=:n AND deleted_at IS NULL AND id<>:id',[':n'=>$n,':id'=>$id]);}
    public function insertPackage(array$p):void{$this->run('INSERT INTO site_estimate_packages(id,estimate_id,package_name,work_scope,sort_no,package_status_code,created_at,created_by,updated_at,updated_by) VALUES(:id,:estimate_id,:package_name,:work_scope,:sort_no,:package_status_code,:created_at,:created_by,:updated_at,:updated_by)',$p);}
    public function insertVersion(array$p):void{$this->run('INSERT INTO site_estimate_versions(id,estimate_package_id,version_no,version_type_code,version_name,change_reason,overhead_rate,risk_rate,profit_rate,rounding_unit,adjustment_amount,is_locked,confirmed_at,confirmed_by,created_at,created_by,updated_at,updated_by) VALUES(:id,:estimate_package_id,:version_no,:version_type_code,:version_name,:change_reason,:overhead_rate,:risk_rate,:profit_rate,:rounding_unit,:adjustment_amount,:is_locked,:confirmed_at,:confirmed_by,:created_at,:created_by,:updated_at,:updated_by)',$p);}
    public function nextVersionNo(string$id):int{return(int)$this->scalar('SELECT COALESCE(MAX(version_no),0)+1 FROM site_estimate_versions WHERE estimate_package_id=:id',[':id'=>$id]);}
    public function replaceItems(string$versionId,array$items,string$actor,string$at):void{$this->run('DELETE FROM site_estimate_items WHERE estimate_version_id=:id',[':id'=>$versionId]);foreach($items as$i){$this->run('INSERT INTO site_estimate_items(id,estimate_version_id,sort_no,work_category_name,item_name,specification,unit_name,quantity,execution_unit_price,submission_unit_price,calculation_basis,note,created_at,created_by,updated_at,updated_by) VALUES(:id,:version,:sort_no,:work_category_name,:item_name,:specification,:unit_name,:quantity,:execution_unit_price,:submission_unit_price,:calculation_basis,:note,:created_at,:created_by,:updated_at,:updated_by)',$i+[':version'=>$versionId,':created_at'=>$at,':created_by'=>$actor,':updated_at'=>$at,':updated_by'=>$actor]);}}
    public function lockFinal(string$id,string$actor,string$at):void{$this->run("UPDATE site_estimate_versions SET version_type_code='FINAL',is_locked=1,confirmed_at=:at,confirmed_by=:actor,updated_at=:at2,updated_by=:actor2 WHERE id=:id",[':at'=>$at,':actor'=>$actor,':at2'=>$at,':actor2'=>$actor,':id'=>$id]);}
    public function softDelete(string$id,string$actor,string$at):void{$this->run('UPDATE site_estimates SET deleted_at=:at,deleted_by=:actor,updated_at=:at2,updated_by=:actor2 WHERE id=:id',[':at'=>$at,':actor'=>$actor,':at2'=>$at,':actor2'=>$actor,':id'=>$id]);}
    public function options():array{return['employees'=>$this->all("SELECT id,employee_name name FROM user_employees WHERE employment_status<>'RETIRED' ORDER BY sort_no,employee_name"),'units'=>$this->all("SELECT code id,code_name name FROM system_codes WHERE code_group IN ('UNIT','ITEM_UNIT') AND is_active=1 ORDER BY sort_no")];}
    private function all(string$s,array$p=[]):array{$q=$this->db->prepare($s);$q->execute($p);return$q->fetchAll(PDO::FETCH_ASSOC)?:[];}private function one(string$s,array$p=[]):?array{$r=$this->all($s,$p);return$r[0]??null;}private function scalar(string$s,array$p=[]):mixed{$q=$this->db->prepare($s);$q->execute($p);return$q->fetchColumn();}private function run(string$s,array$p):void{$q=$this->db->prepare($s);$q->execute($p);}
}
