<?php
namespace App\Models\Site;
use PDO;

class SalesModel
{
    public function __construct(private readonly PDO $db) {}

    public function organizations(array $filters=[]):array
    {
        $sql="SELECT o.*,e.employee_name owner_employee_name,
          (SELECT MAX(a.activity_at) FROM site_sales_activities a WHERE a.organization_id=o.id) last_activity_at,
          (SELECT COUNT(*) FROM site_sales_activities a WHERE a.organization_id=o.id) activity_count,
          (SELECT COUNT(*) FROM site_sales_people p JOIN site_sales_affiliations af ON af.person_id=p.id AND af.is_current=1 WHERE af.organization_id=o.id AND p.deleted_at IS NULL) people_count,
          (SELECT COUNT(*) FROM site_sales_followups f WHERE f.organization_id=o.id AND f.followup_status_code='OPEN') open_followup_count,
          (SELECT MIN(f.due_at) FROM site_sales_followups f WHERE f.organization_id=o.id AND f.followup_status_code='OPEN') nearest_followup_at,
          (SELECT MAX(op.owner_probability_rate) FROM site_sales_opportunities op WHERE op.organization_id=o.id AND op.deleted_at IS NULL AND op.stage_code NOT IN ('WON','LOST')) owner_probability_rate,
          (SELECT COALESCE(SUM(op.expected_amount),0) FROM site_sales_opportunities op WHERE op.organization_id=o.id AND op.deleted_at IS NULL AND op.stage_code NOT IN ('WON','LOST')) expected_amount
        FROM site_sales_organizations o JOIN user_employees e ON e.id=o.owner_employee_id WHERE o.deleted_at IS NULL";
        $params=[];
        $id=trim((string)($filters['id']??''));if($id!==''){$sql.=' AND o.id=:id';$params[':id']=$id;}
        foreach(['sales_status_code','relationship_level_code','owner_employee_id'] as$key){$value=trim((string)($filters[$key]??''));if($value!==''){$sql.=" AND o.$key=:$key";$params[":$key"]=$value;}}
        $keyword=trim((string)($filters['keyword']??''));if($keyword!==''){$sql.=' AND (o.organization_name LIKE :keyword OR o.industry_name LIKE :keyword OR o.business_area LIKE :keyword OR o.representative_name LIKE :keyword)';$params[':keyword']='%'.$keyword.'%';}
        return $this->all($sql.' ORDER BY COALESCE(o.next_action_date,\'9999-12-31\'),o.organization_name',$params);
    }
    public function organization(string$id,bool$lock=false):?array{return $this->one('SELECT * FROM site_sales_organizations WHERE id=:id AND deleted_at IS NULL'.($lock?' FOR UPDATE':''),[':id'=>$id]);}
    public function insertOrganization(array$r):void{$this->exec('INSERT INTO site_sales_organizations (id,organization_name,organization_type_code,industry_name,business_area,address,website_url,representative_name,main_phone,introduction_source,relationship_level_code,sales_status_code,owner_employee_id,next_action_date,next_action_summary,note,created_at,created_by,updated_at,updated_by) VALUES (:id,:organization_name,:organization_type_code,:industry_name,:business_area,:address,:website_url,:representative_name,:main_phone,:introduction_source,:relationship_level_code,:sales_status_code,:owner_employee_id,:next_action_date,:next_action_summary,:note,:created_at,:created_by,:updated_at,:updated_by)',$r);}
    public function updateOrganization(string$id,array$r):void{$r[':id']=$id;$this->exec('UPDATE site_sales_organizations SET organization_name=:organization_name,organization_type_code=:organization_type_code,industry_name=:industry_name,business_area=:business_area,address=:address,website_url=:website_url,representative_name=:representative_name,main_phone=:main_phone,introduction_source=:introduction_source,relationship_level_code=:relationship_level_code,sales_status_code=:sales_status_code,owner_employee_id=:owner_employee_id,next_action_date=:next_action_date,next_action_summary=:next_action_summary,note=:note,updated_at=:updated_at,updated_by=:updated_by WHERE id=:id',$r);}
    public function people(string$organizationId):array{return$this->all("SELECT p.*,af.id affiliation_id,af.department_name,af.position_name,af.influence_role_code,af.started_date,e.employee_name owner_employee_name FROM site_sales_affiliations af JOIN site_sales_people p ON p.id=af.person_id AND p.deleted_at IS NULL JOIN user_employees e ON e.id=p.owner_employee_id WHERE af.organization_id=:id AND af.is_current=1 ORDER BY FIELD(af.influence_role_code,'DECISION_MAKER','INFLUENCER','PRACTITIONER','INTRODUCER','OTHER'),p.person_name",[':id'=>$organizationId]);}
    public function insertPerson(array$r):void{$this->exec('INSERT INTO site_sales_people (id,person_name,mobile_phone,email,preferred_contact_code,preferred_contact_time,interests,cautions,relationship_level_code,owner_employee_id,note,created_at,created_by,updated_at,updated_by) VALUES (:id,:person_name,:mobile_phone,:email,:preferred_contact_code,:preferred_contact_time,:interests,:cautions,:relationship_level_code,:owner_employee_id,:note,:created_at,:created_by,:updated_at,:updated_by)',$r);}
    public function insertAffiliation(array$r):void{$this->exec('INSERT INTO site_sales_affiliations (id,person_id,organization_id,department_name,position_name,influence_role_code,started_date,ended_date,is_current,created_at,created_by) VALUES (:id,:person_id,:organization_id,:department_name,:position_name,:influence_role_code,:started_date,NULL,1,:created_at,:created_by)',$r);}
    public function activities(string$organizationId):array{return$this->all('SELECT a.*,p.person_name,op.opportunity_name FROM site_sales_activities a LEFT JOIN site_sales_people p ON p.id=a.person_id LEFT JOIN site_sales_opportunities op ON op.id=a.opportunity_id WHERE a.organization_id=:id ORDER BY a.activity_at DESC,a.created_at DESC',[':id'=>$organizationId]);}
    public function insertActivity(array$r):void{$this->exec('INSERT INTO site_sales_activities (id,organization_id,person_id,opportunity_id,activity_type_code,activity_at,location_name,activity_summary,customer_request,our_commitment,response_level_code,created_at,created_by) VALUES (:id,:organization_id,:person_id,:opportunity_id,:activity_type_code,:activity_at,:location_name,:activity_summary,:customer_request,:our_commitment,:response_level_code,:created_at,:created_by)',$r);}
    public function opportunities(string$organizationId):array{return$this->all('SELECT op.*,p.person_name,pr.project_name FROM site_sales_opportunities op LEFT JOIN site_sales_people p ON p.id=op.person_id LEFT JOIN system_projects pr ON pr.id=op.project_id WHERE op.organization_id=:id AND op.deleted_at IS NULL ORDER BY FIELD(op.stage_code,\'NEGOTIATION\',\'ESTIMATE\',\'ESTIMATE_READY\',\'CONSULTING\',\'CONTACT\',\'DISCOVERY\',\'HOLD\',\'WON\',\'LOST\'),op.updated_at DESC',[':id'=>$organizationId]);}
    public function insertOpportunity(array$r):void{$this->exec('INSERT INTO site_sales_opportunities (id,organization_id,person_id,opportunity_name,work_type_name,stage_code,owner_probability_rate,expected_amount,expected_order_date,expected_decision_date,competitor_note,probability_reason,estimate_id,project_id,result_reason,created_at,created_by,updated_at,updated_by) VALUES (:id,:organization_id,:person_id,:opportunity_name,:work_type_name,:stage_code,:owner_probability_rate,:expected_amount,:expected_order_date,:expected_decision_date,:competitor_note,:probability_reason,NULL,NULL,:result_reason,:created_at,:created_by,:updated_at,:updated_by)',$r);}
    public function followups(string$organizationId):array{return$this->all('SELECT f.*,p.person_name,op.opportunity_name,e.employee_name assigned_employee_name FROM site_sales_followups f LEFT JOIN site_sales_people p ON p.id=f.person_id LEFT JOIN site_sales_opportunities op ON op.id=f.opportunity_id JOIN user_employees e ON e.id=f.assigned_employee_id WHERE f.organization_id=:id ORDER BY FIELD(f.followup_status_code,\'OPEN\',\'DONE\',\'CANCELLED\'),f.due_at',[':id'=>$organizationId]);}
    public function insertFollowup(array$r):void{$this->exec('INSERT INTO site_sales_followups (id,organization_id,person_id,opportunity_id,assigned_employee_id,due_at,followup_summary,followup_status_code,created_at,created_by,updated_at,updated_by) VALUES (:id,:organization_id,:person_id,:opportunity_id,:assigned_employee_id,:due_at,:followup_summary,\'OPEN\',:created_at,:created_by,:updated_at,:updated_by)',$r);}
    public function completeFollowup(string$id,string$at,string$actor,string$note):void{$this->exec("UPDATE site_sales_followups SET followup_status_code='DONE',completed_at=:completed_at,completed_note=:note,updated_at=:updated_at,updated_by=:actor WHERE id=:id AND followup_status_code='OPEN'",[':id'=>$id,':completed_at'=>$at,':updated_at'=>$at,':note'=>$note,':actor'=>$actor]);}
    public function dashboard():array{return['organizations'=>(int)$this->scalar("SELECT COUNT(*) FROM site_sales_organizations WHERE deleted_at IS NULL AND sales_status_code='ACTIVE'"),'people'=>(int)$this->scalar('SELECT COUNT(*) FROM site_sales_people WHERE deleted_at IS NULL'),'open_followups'=>(int)$this->scalar("SELECT COUNT(*) FROM site_sales_followups WHERE followup_status_code='OPEN'"),'overdue_followups'=>(int)$this->scalar("SELECT COUNT(*) FROM site_sales_followups WHERE followup_status_code='OPEN' AND due_at<NOW()"),'active_opportunities'=>(int)$this->scalar("SELECT COUNT(*) FROM site_sales_opportunities WHERE deleted_at IS NULL AND stage_code NOT IN ('WON','LOST','HOLD')"),'expected_amount'=>(float)$this->scalar("SELECT COALESCE(SUM(expected_amount),0) FROM site_sales_opportunities WHERE deleted_at IS NULL AND stage_code NOT IN ('WON','LOST','HOLD')")];}
    public function options():array{return['employees'=>$this->all('SELECT id,employee_name name FROM user_employees ORDER BY employee_name')];}
    private function all(string$sql,array$params=[]):array{$q=$this->db->prepare($sql);$q->execute($params);return$q->fetchAll(PDO::FETCH_ASSOC)?:[];}
    private function one(string$sql,array$params=[]):?array{$q=$this->db->prepare($sql);$q->execute($params);return$q->fetch(PDO::FETCH_ASSOC)?:null;}
    private function scalar(string$sql,array$params=[]):mixed{$q=$this->db->prepare($sql);$q->execute($params);return$q->fetchColumn();}
    private function exec(string$sql,array$params):void{$q=$this->db->prepare($sql);$q->execute($params);}
}
