<?php
use Core\Helpers\AssetHelper;
$pageStyles = AssetHelper::css('/assets/css/pages/approval/leave-request/index.css');
$pageScripts = AssetHelper::module('/assets/js/pages/approval/leave-request/index.js');
?>
<main class="leave-request-page"><div class="container-fluid py-4 dt-page-shell">
  <div class="mb-3"><h5 class="mb-1 fw-bold"><i class="bi bi-calendar2-check me-2"></i>휴가신청</h5><p class="text-muted small mb-0">본인의 휴가를 신청하고 결재 진행상태와 이력을 확인합니다.</p></div>
  <div class="dt-content-stack"><?php $searchId='leave-request';$dateOptions='<option value="leave_date">신청일</option>';$searchFieldOptions='<option value="keyword">검색어</option><option value="leave_type_id">휴가유형</option><option value="status_code">신청상태</option><option value="approval_status">결재상태</option>';include PROJECT_ROOT.'/app/views/components/ui-search.php';?><?php $tableId='leaveRequestTable';$ajaxUrl='/api/approval/leave-request/list';$columnsType='leave-request';$enableButtons=true;$enableSearch=true;$enablePaging=true;$enableReorder=false;include PROJECT_ROOT.'/app/views/components/ui-table.php';?></div>
</div></main>
<div class="modal fade" id="leaveRequestModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><form class="modal-content" id="leaveRequestForm"><div class="modal-header"><h5 class="modal-title">휴가 신청</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="id"><input type="hidden" name="request_key"><div class="d-flex justify-content-between align-items-center mb-2"><label class="form-label mb-0">휴가 사용일</label><button class="btn btn-outline-primary btn-sm" id="leaveRequestAddItem" type="button">사용일 추가</button></div><div class="table-responsive"><table class="table table-sm table-bordered"><thead><tr><th>휴가유형</th><th>휴가일</th><th>신청단위</th><th>시작시간</th><th>종료시간</th><th></th></tr></thead><tbody id="leaveRequestItems"></tbody></table></div><div class="mt-3"><label class="form-label">신청사유</label><textarea class="form-control" name="reason" rows="3" required></textarea></div><div class="alert alert-secondary small mt-3 mb-0" id="leaveEvidencePolicy">증빙 정책은 선택한 휴가유형을 따릅니다.</div><div id="leaveRequestHistory" class="mt-3"></div></div><div class="modal-footer"><button class="btn btn-outline-secondary btn-sm" type="button" data-bs-dismiss="modal">닫기</button><button class="btn btn-outline-primary btn-sm" type="submit" data-mode="save">임시저장</button><button class="btn btn-primary btn-sm" type="submit" data-mode="submit">저장 후 상신</button></div></form></div></div>
<div id="leaveRequestDatePicker" class="picker admin-picker is-hidden"></div><div id="leaveRequestTimePicker" class="picker admin-picker is-hidden"></div>
<script type="application/json" id="leaveRequestBootstrap"><?=json_encode(['options'=>$leaveOptions],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?></script>
