<?php
namespace App\Services\Site;
use App\Models\Site\EstimateModel;use Core\Helpers\ActorHelper;use Core\LoggerFactory;use Core\Helpers\UuidHelper;use InvalidArgumentException;use PDO;use Throwable;
final class EstimateService
{
    private EstimateModel$model;private$logger;public function __construct(private readonly PDO$db){$this->model=new EstimateModel($db);$this->logger=LoggerFactory::getLogger('service-site-estimate');}
    public function list(array$f):array{return['success'=>true,'data'=>ActorHelper::enrichActorNames($this->model->list(['status'=>trim((string)($f['status']??'')),'keyword'=>trim((string)($f['keyword']??''))]),['created_by_name'=>'created_by','updated_by_name'=>'updated_by'])];}
    public function options():array{return['success'=>true,'data'=>$this->model->options()];}
    public function detail(string$id):array{$e=$this->model->estimate($id);if(!$e)throw new InvalidArgumentException('견적을 찾을 수 없습니다.');$packages=$this->model->packages($id);foreach($packages as&$p){$p['versions']=$this->model->versions($p['id']);foreach($p['versions']as&$v){$v['items']=$this->model->items($v['id']);}}return['success'=>true,'data'=>['estimate'=>ActorHelper::enrichActorNamesRow($e,['created_by_name'=>'created_by','updated_by_name'=>'updated_by']),'packages'=>$packages]];}
    public function saveEstimate(array$i):array{return$this->boundary('save_estimate',function()use($i){$id=trim((string)($i['id']??''));$actor=ActorHelper::user();$at=date('Y-m-d H:i:s');$number=$this->required($i,'estimate_number','견적번호');if($this->model->duplicateNumber($number,$id))throw new InvalidArgumentException('이미 사용 중인 견적번호입니다.');$p=[':estimate_number'=>$number,':estimate_date'=>$this->date($i['estimate_date']??'','견적일자'),':construction_name'=>$this->required($i,'construction_name','공사명'),':requester_name'=>$this->null($i['requester_name']??null),':requester_person_name'=>$this->null($i['requester_person_name']??null),':site_address'=>$this->null($i['site_address']??null),':owner_employee_id'=>$this->required($i,'owner_employee_id','견적 담당자'),':submission_due_date'=>$this->dateNull($i['submission_due_date']??null),':estimate_status_code'=>$this->enum($i['estimate_status_code']??'WRITING',['WRITING','SUBMITTED','NEGOTIATING','WON','LOST','HOLD']),':folder_path'=>$this->null($i['folder_path']??null),':note'=>$this->null($i['note']??null),':updated_at'=>$at,':updated_by'=>$actor];if($id===''){$id=UuidHelper::generate();$this->model->insertEstimate($p+[':id'=>$id,':created_at'=>$at,':created_by'=>$actor]);$event='ESTIMATE_CREATED';}else{if(!$this->model->estimate($id,true))throw new InvalidArgumentException('수정할 견적을 찾을 수 없습니다.');$this->model->updateEstimate($id,$p);$event='ESTIMATE_UPDATED';}$this->log('info','견적 헤더를 저장했습니다.',$event,$id,$actor);return['success'=>true,'message'=>'견적을 저장했습니다.','data'=>$this->detail($id)['data']];},'ESTIMATE_SAVE_FAILED');}
    public function addPackage(array$i):array{return$this->boundary('add_package',function()use($i){$eid=$this->required($i,'estimate_id','견적');if(!$this->model->estimate($eid))throw new InvalidArgumentException('견적을 찾을 수 없습니다.');$actor=ActorHelper::user();$at=date('Y-m-d H:i:s');$id=UuidHelper::generate();$this->model->insertPackage([':id'=>$id,':estimate_id'=>$eid,':package_name'=>$this->required($i,'package_name','견적명'),':work_scope'=>$this->null($i['work_scope']??null),':sort_no'=>count($this->model->packages($eid))+1,':package_status_code'=>'WRITING',':created_at'=>$at,':created_by'=>$actor,':updated_at'=>$at,':updated_by'=>$actor]);$vid=UuidHelper::generate();$this->model->insertVersion($this->versionParams($vid,$id,1,'DRAFT','최초견적',null,$i,$actor,$at));$this->log('info','견적 묶음과 최초 차수를 생성했습니다.','ESTIMATE_PACKAGE_CREATED',$id,$actor);return['success'=>true,'message'=>'견적을 추가했습니다.','data'=>$this->detail($eid)['data']];},'ESTIMATE_PACKAGE_CREATE_FAILED');}
    public function saveVersion(array$i):array{return$this->boundary('save_version',function()use($i){$id=$this->required($i,'version_id','견적 차수');$v=$this->model->version($id,true);if(!$v)throw new InvalidArgumentException('견적 차수를 찾을 수 없습니다.');if((int)$v['is_locked']===1)throw new InvalidArgumentException('최종 확정된 견적은 수정할 수 없습니다.');$items=$this->items($i['items']??[]);$actor=ActorHelper::user();$at=date('Y-m-d H:i:s');$this->model->replaceItems($id,$items,$actor,$at);$this->log('info','견적 차수 아이템을 저장했습니다.','ESTIMATE_VERSION_SAVED',$id,$actor);return['success'=>true,'message'=>'실행·제출 견적을 저장했습니다.','data'=>['items'=>$this->model->items($id)]];},'ESTIMATE_VERSION_SAVE_FAILED');}
    public function copyVersion(array$i):array{return$this->boundary('copy_version',function()use($i){$source=$this->required($i,'version_id','원본 차수');$v=$this->model->version($source);if(!$v)throw new InvalidArgumentException('원본 차수를 찾을 수 없습니다.');$actor=ActorHelper::user();$at=date('Y-m-d H:i:s');$id=UuidHelper::generate();$no=$this->model->nextVersionNo($v['estimate_package_id']);$type=$this->enum($i['version_type_code']??'CHANGE',['CHANGE','SUBMISSION','NEGOTIATION']);$name=trim((string)($i['version_name']??''))?:$no.'차 '.$type;$this->model->insertVersion($this->versionParams($id,$v['estimate_package_id'],$no,$type,$name,$this->null($i['change_reason']??null),$i+$v,$actor,$at));$rows=[];foreach($this->model->items($source)as$r){$r['id']=UuidHelper::generate();$rows[]=$this->itemParams($r,count($rows)+1);}$this->model->replaceItems($id,$rows,$actor,$at);$this->log('info','이전 견적을 복사해 새 차수를 생성했습니다.','ESTIMATE_VERSION_COPIED',$id,$actor);return['success'=>true,'message'=>'새 견적 차수를 생성했습니다.','data'=>['version_id'=>$id]];},'ESTIMATE_VERSION_COPY_FAILED');}
    public function finalize(array$i):array{return$this->boundary('finalize',function()use($i){$id=$this->required($i,'version_id','견적 차수');$v=$this->model->version($id,true);if(!$v)throw new InvalidArgumentException('견적 차수를 찾을 수 없습니다.');if(!$this->model->items($id))throw new InvalidArgumentException('최종 확정할 견적 아이템이 없습니다.');$actor=ActorHelper::user();$this->model->lockFinal($id,$actor,date('Y-m-d H:i:s'));$this->log('info','네고 결과를 최종견적으로 확정했습니다.','ESTIMATE_FINALIZED',$id,$actor);return['success'=>true,'message'=>'최종견적으로 확정했습니다.'];},'ESTIMATE_FINALIZE_FAILED');}
    public function delete(array$i):array{return$this->boundary('delete',function()use($i){$id=$this->required($i,'id','견적');$actor=ActorHelper::user();$this->model->softDelete($id,$actor,date('Y-m-d H:i:s'));$this->log('info','견적을 삭제했습니다.','ESTIMATE_DELETED',$id,$actor);return['success'=>true,'message'=>'견적을 삭제했습니다.'];},'ESTIMATE_DELETE_FAILED');}
    private function items(mixed$rows):array{if(!is_array($rows)||$rows===[])throw new InvalidArgumentException('견적 아이템을 한 개 이상 입력해 주세요.');$out=[];foreach(array_values($rows)as$n=>$r){if(trim((string)($r['item_name']??''))==='')throw new InvalidArgumentException(($n+1).'행 품명을 입력해 주세요.');$out[]=$this->itemParams($r,$n+1);}return$out;}private function itemParams(array$r,int$n):array{return[':id'=>(string)($r['id']??UuidHelper::generate()),':sort_no'=>$n,':work_category_name'=>$this->null($r['work_category_name']??null),':item_name'=>trim((string)$r['item_name']),':specification'=>$this->null($r['specification']??null),':unit_name'=>$this->null($r['unit_name']??null),':quantity'=>(float)($r['quantity']??0),':execution_unit_price'=>(float)($r['execution_unit_price']??0),':submission_unit_price'=>(float)($r['submission_unit_price']??0),':calculation_basis'=>$this->null($r['calculation_basis']??null),':note'=>$this->null($r['note']??null)];}
    private function versionParams(string$id,string$pid,int$no,string$type,string$name,?string$reason,array$i,string$a,string$at):array{return[':id'=>$id,':estimate_package_id'=>$pid,':version_no'=>$no,':version_type_code'=>$type,':version_name'=>$name,':change_reason'=>$reason,':overhead_rate'=>(float)($i['overhead_rate']??0),':risk_rate'=>(float)($i['risk_rate']??0),':profit_rate'=>(float)($i['profit_rate']??0),':rounding_unit'=>max(1,(int)($i['rounding_unit']??1)),':adjustment_amount'=>(float)($i['adjustment_amount']??0),':is_locked'=>0,':confirmed_at'=>null,':confirmed_by'=>null,':created_at'=>$at,':created_by'=>$a,':updated_at'=>$at,':updated_by'=>$a];}
    private function boundary(string$action,callable$fn,string$fail):array{$owns=!$this->db->inTransaction();try{if($owns)$this->db->beginTransaction();$r=$fn();if($owns)$this->db->commit();return$r;}catch(Throwable$e){if($owns&&$this->db->inTransaction())$this->db->rollBack();$this->log($e instanceof InvalidArgumentException?'warning':'error','견적관리 업무를 완료하지 못했습니다.',$fail,null,ActorHelper::user(),$e);throw$e;}}private function log(string$l,string$m,string$e,?string$id,string$a,?Throwable$x=null):void{$c=['event_code'=>$e,'result'=>$x?'FAILED':'SUCCESS','service'=>self::class,'action'=>strtolower($e),'actor'=>$a,'target_type'=>'site_estimates','target_id'=>$id,'error_code'=>$x?get_class($x):null];$this->logger->{$l}($m,$c);}
    private function required(array$i,string$k,string$l):string{$v=trim((string)($i[$k]??''));if($v==='')throw new InvalidArgumentException($l.'을(를) 입력해 주세요.');return$v;}private function enum(mixed$v,array$a):string{$v=strtoupper(trim((string)$v));if(!in_array($v,$a,true))throw new InvalidArgumentException('유효하지 않은 상태값입니다.');return$v;}private function date(mixed$v,string$l):string{$v=trim((string)$v);$d=\DateTime::createFromFormat('Y-m-d',$v);if(!$d||$d->format('Y-m-d')!==$v)throw new InvalidArgumentException($l.'을(를) 확인해 주세요.');return$v;}private function dateNull(mixed$v):?string{return trim((string)$v)===''?null:$this->date($v,'날짜');}private function null(mixed$v):?string{$v=trim((string)$v);return$v===''?null:$v;}
}
