<?php
namespace App\Services\Site;
use App\Models\Site\SalesModel;
use Core\Helpers\ActorHelper;
use Core\Helpers\UuidHelper;
use Core\LoggerFactory;
use InvalidArgumentException;
use PDO;
use Throwable;

class SalesService
{
    private SalesModel $model;private $logger;
    public function __construct(private readonly PDO $pdo){$this->model=new SalesModel($pdo);$this->logger=LoggerFactory::getLogger('service-site-sales');}
    public function list(array$f=[]):array{return array_map(fn(array$r)=>$this->analyze($r),ActorHelper::enrichActorNames($this->model->organizations($f),['created_by_name'=>'created_by','updated_by_name'=>'updated_by']));}
    public function dashboard():array{return$this->model->dashboard();}
    public function options():array{return$this->model->options();}
    public function detail(string$id):array{$this->requiredOrganization($id);$rows=$this->model->organizations(['id'=>$id]);$org=$this->analyze($rows[0]??[]);$org['people']=$this->model->people($id);$org['activities']=ActorHelper::enrichActorNames($this->model->activities($id),['created_by_name'=>'created_by']);$org['opportunities']=$this->model->opportunities($id);$org['followups']=ActorHelper::enrichActorNames($this->model->followups($id),['created_by_name'=>'created_by','updated_by_name'=>'updated_by']);return$org;}
    public function saveOrganization(array$in):array{$actor=ActorHelper::user();$id=trim((string)($in['id']??''));$row=$this->organizationInput($in);$now=date('Y-m-d H:i:s');$params=$row+[':updated_at'=>$now,':updated_by'=>$actor];try{if($id===''){$id=UuidHelper::generate();$params+=[':id'=>$id,':created_at'=>$now,':created_by'=>$actor];$this->model->insertOrganization($params);$event='SALES_ORGANIZATION_CREATED';$message='영업대상 업체를 등록했습니다.';}else{$this->requiredOrganization($id);$this->model->updateOrganization($id,$params);$event='SALES_ORGANIZATION_UPDATED';$message='영업대상 업체정보를 수정했습니다.';}$this->audit('info',$message,$event,'site_sales_organizations',$id,$actor);return['success'=>true,'message'=>$message,'data'=>$this->detail($id)];}catch(Throwable$e){$this->audit($e instanceof InvalidArgumentException?'warning':'error','영업대상 업체 저장을 완료하지 못했습니다.','SALES_ORGANIZATION_SAVE_FAILED','site_sales_organizations',$id,$actor,$e);throw$e;}}
    public function addPerson(array$in):array{$actor=ActorHelper::user();$organizationId=$this->requiredId($in,'organization_id','업체');$this->requiredOrganization($organizationId);$name=$this->requiredText($in,'person_name','인물명',80);$owner=$this->requiredId($in,'owner_employee_id','영업담당자');$now=date('Y-m-d H:i:s');$personId=UuidHelper::generate();$owns=!$this->pdo->inTransaction();try{if($owns)$this->pdo->beginTransaction();$this->model->insertPerson([':id'=>$personId,':person_name'=>$name,':mobile_phone'=>$this->nullable($in['mobile_phone']??null),':email'=>$this->nullable($in['email']??null),':preferred_contact_code'=>$this->enumOrNull($in['preferred_contact_code']??null,['PHONE','MESSAGE','EMAIL','VISIT'],'선호 연락방식'),':preferred_contact_time'=>$this->nullable($in['preferred_contact_time']??null),':interests'=>$this->nullable($in['interests']??null),':cautions'=>$this->nullable($in['cautions']??null),':relationship_level_code'=>$this->enum($in['relationship_level_code']??'NEW',['NEW','COLD','WARM','HOT','TRUSTED'],'관계수준'),':owner_employee_id'=>$owner,':note'=>$this->nullable($in['note']??null),':created_at'=>$now,':created_by'=>$actor,':updated_at'=>$now,':updated_by'=>$actor]);$this->model->insertAffiliation([':id'=>UuidHelper::generate(),':person_id'=>$personId,':organization_id'=>$organizationId,':department_name'=>$this->nullable($in['department_name']??null),':position_name'=>$this->nullable($in['position_name']??null),':influence_role_code'=>$this->enum($in['influence_role_code']??'PRACTITIONER',['DECISION_MAKER','PRACTITIONER','INTRODUCER','INFLUENCER','OTHER'],'영향역할'),':started_date'=>$this->dateOrNull($in['started_date']??null,'소속 시작일'),':created_at'=>$now,':created_by'=>$actor]);if($owns)$this->pdo->commit();$this->audit('info','영업 인물과 소속정보를 등록했습니다.','SALES_PERSON_CREATED','site_sales_people',$personId,$actor);return['success'=>true,'message'=>'인물과 소속정보를 등록했습니다.','data'=>$this->detail($organizationId)];}catch(Throwable$e){if($owns&&$this->pdo->inTransaction())$this->pdo->rollBack();$this->audit($e instanceof InvalidArgumentException?'warning':'error','영업 인물 등록을 완료하지 못했습니다.','SALES_PERSON_CREATE_FAILED','site_sales_people',$personId,$actor,$e);throw$e;}}
    public function addActivity(array$in):array{$actor=ActorHelper::user();$org=$this->requiredId($in,'organization_id','업체');$this->requiredOrganization($org);$id=UuidHelper::generate();$now=date('Y-m-d H:i:s');$this->model->insertActivity([':id'=>$id,':organization_id'=>$org,':person_id'=>$this->nullable($in['person_id']??null),':opportunity_id'=>$this->nullable($in['opportunity_id']??null),':activity_type_code'=>$this->enum($in['activity_type_code']??'PHONE',['PHONE','MESSAGE','EMAIL','VISIT','MEETING','MEAL','SITE','OTHER'],'활동유형'),':activity_at'=>$this->dateTime($in['activity_at']??'','활동일시'),':location_name'=>$this->nullable($in['location_name']??null),':activity_summary'=>$this->requiredText($in,'activity_summary','활동내용',500),':customer_request'=>$this->nullable($in['customer_request']??null),':our_commitment'=>$this->nullable($in['our_commitment']??null),':response_level_code'=>$this->enumOrNull($in['response_level_code']??null,['NEGATIVE','NEUTRAL','POSITIVE','STRONG'],'상대방 반응'),':created_at'=>$now,':created_by'=>$actor]);$this->audit('info','영업활동을 기록했습니다.','SALES_ACTIVITY_CREATED','site_sales_activities',$id,$actor);return['success'=>true,'message'=>'영업활동을 기록했습니다.','data'=>$this->detail($org)];}
    public function addOpportunity(array$in):array{$actor=ActorHelper::user();$org=$this->requiredId($in,'organization_id','업체');$this->requiredOrganization($org);$id=UuidHelper::generate();$now=date('Y-m-d H:i:s');$rate=max(0,min(100,(float)($in['owner_probability_rate']??0)));$this->model->insertOpportunity([':id'=>$id,':organization_id'=>$org,':person_id'=>$this->nullable($in['person_id']??null),':opportunity_name'=>$this->requiredText($in,'opportunity_name','영업기회명',200),':work_type_name'=>$this->nullable($in['work_type_name']??null),':stage_code'=>$this->enum($in['stage_code']??'DISCOVERY',['DISCOVERY','CONTACT','CONSULTING','ESTIMATE_READY','ESTIMATE','NEGOTIATION','WON','LOST','HOLD'],'영업단계'),':owner_probability_rate'=>$rate,':expected_amount'=>$this->numberOrNull($in['expected_amount']??null),':expected_order_date'=>$this->dateOrNull($in['expected_order_date']??null,'예상 발주일'),':expected_decision_date'=>$this->dateOrNull($in['expected_decision_date']??null,'예상 결정일'),':competitor_note'=>$this->nullable($in['competitor_note']??null),':probability_reason'=>$this->nullable($in['probability_reason']??null),':result_reason'=>$this->nullable($in['result_reason']??null),':created_at'=>$now,':created_by'=>$actor,':updated_at'=>$now,':updated_by'=>$actor]);$this->audit('info','영업기회를 등록했습니다.','SALES_OPPORTUNITY_CREATED','site_sales_opportunities',$id,$actor);return['success'=>true,'message'=>'영업기회를 등록했습니다.','data'=>$this->detail($org)];}
    public function addFollowup(array$in):array{$actor=ActorHelper::user();$org=$this->requiredId($in,'organization_id','업체');$this->requiredOrganization($org);$id=UuidHelper::generate();$now=date('Y-m-d H:i:s');$this->model->insertFollowup([':id'=>$id,':organization_id'=>$org,':person_id'=>$this->nullable($in['person_id']??null),':opportunity_id'=>$this->nullable($in['opportunity_id']??null),':assigned_employee_id'=>$this->requiredId($in,'assigned_employee_id','담당자'),':due_at'=>$this->dateTime($in['due_at']??'','처리기한'),':followup_summary'=>$this->requiredText($in,'followup_summary','다음 활동',500),':created_at'=>$now,':created_by'=>$actor,':updated_at'=>$now,':updated_by'=>$actor]);$this->audit('info','후속 영업활동을 등록했습니다.','SALES_FOLLOWUP_CREATED','site_sales_followups',$id,$actor);return['success'=>true,'message'=>'다음 활동과 알림기한을 등록했습니다.','data'=>$this->detail($org)];}
    public function completeFollowup(array$in):array{$actor=ActorHelper::user();$id=$this->requiredId($in,'id','후속활동');$org=$this->requiredId($in,'organization_id','업체');$this->model->completeFollowup($id,date('Y-m-d H:i:s'),$actor,trim((string)($in['completed_note']??'')));$this->audit('info','후속 영업활동을 완료했습니다.','SALES_FOLLOWUP_COMPLETED','site_sales_followups',$id,$actor);return['success'=>true,'message'=>'후속활동을 완료했습니다.','data'=>$this->detail($org)];}
    private function analyze(array$r):array{$score=(int)round((float)($r['owner_probability_rate']??0));$reasons=[];$last=trim((string)($r['last_activity_at']??''));if($last!==''){$days=(int)floor((time()-strtotime($last))/86400);if($days<=14){$score+=10;$reasons[]='최근 14일 이내 활동이 있습니다.';}elseif($days>=60){$score-=15;$reasons[]='최근 활동 후 60일 이상 지났습니다.';}}else{$score-=10;$reasons[]='아직 활동기록이 없습니다.';}$nearest=trim((string)($r['nearest_followup_at']??''));if($nearest!==''&&strtotime($nearest)<time()){$score-=10;$reasons[]='처리기한이 지난 후속활동이 있습니다.';}if((float)($r['expected_amount']??0)>0){$score+=5;$reasons[]='구체적인 예상금액이 등록되어 있습니다.';}if((int)($r['people_count']??0)>0){$score+=5;$reasons[]='연결된 담당 인물이 있습니다.';}$r['analysis_score']=max(0,min(100,$score));$r['analysis_reason']=$reasons?implode(' ',$reasons):'판단할 활동정보가 부족합니다.';return$r;}
    private function organizationInput(array$i):array{return[':organization_name'=>$this->requiredText($i,'organization_name','업체명',150),':organization_type_code'=>$this->enum($i['organization_type_code']??'COMPANY',['COMPANY','INSTITUTION','OTHER'],'업체구분'),':industry_name'=>$this->nullable($i['industry_name']??null),':business_area'=>$this->nullable($i['business_area']??null),':address'=>$this->nullable($i['address']??null),':website_url'=>$this->nullable($i['website_url']??null),':representative_name'=>$this->nullable($i['representative_name']??null),':main_phone'=>$this->nullable($i['main_phone']??null),':introduction_source'=>$this->nullable($i['introduction_source']??null),':relationship_level_code'=>$this->enum($i['relationship_level_code']??'NEW',['NEW','COLD','WARM','HOT','TRUSTED'],'관계수준'),':sales_status_code'=>$this->enum($i['sales_status_code']??'ACTIVE',['ACTIVE','HOLD','CLOSED'],'영업상태'),':owner_employee_id'=>$this->requiredId($i,'owner_employee_id','영업담당자'),':next_action_date'=>$this->dateOrNull($i['next_action_date']??null,'다음 활동일'),':next_action_summary'=>$this->nullable($i['next_action_summary']??null),':note'=>$this->nullable($i['note']??null)];}
    private function requiredOrganization(string$id):array{$r=$this->model->organization($id);if(!$r)throw new InvalidArgumentException('영업대상 업체를 찾을 수 없습니다.');return$r;}
    private function requiredId(array$i,string$k,string$n):string{$v=trim((string)($i[$k]??''));if($v==='')throw new InvalidArgumentException($n.'을(를) 선택해 주세요.');return$v;}
    private function requiredText(array$i,string$k,string$n,int$max):string{$v=trim((string)($i[$k]??''));if($v==='')throw new InvalidArgumentException($n.'을(를) 입력해 주세요.');if(mb_strlen($v)>$max)throw new InvalidArgumentException($n.'이(가) 너무 깁니다.');return$v;}
    private function nullable(mixed$v):?string{$v=trim((string)$v);return$v===''?null:$v;}
    private function enum(mixed$v,array$a,string$n):string{$v=strtoupper(trim((string)$v));if(!in_array($v,$a,true))throw new InvalidArgumentException($n.'을(를) 확인해 주세요.');return$v;}
    private function enumOrNull(mixed$v,array$a,string$n):?string{$v=trim((string)$v);return$v===''?null:$this->enum($v,$a,$n);}
    private function dateOrNull(mixed$v,string$n):?string{$v=trim((string)$v);if($v==='')return null;$d=\DateTimeImmutable::createFromFormat('!Y-m-d',$v);if(!$d||$d->format('Y-m-d')!==$v)throw new InvalidArgumentException($n.'을 확인해 주세요.');return$v;}
    private function dateTime(mixed$v,string$n):string{$v=trim((string)$v);if($v==='')throw new InvalidArgumentException($n.'을 입력해 주세요.');$timestamp=strtotime($v);if($timestamp===false)throw new InvalidArgumentException($n.'을 확인해 주세요.');return date('Y-m-d H:i:s',$timestamp);}
    private function numberOrNull(mixed$v):?float{$v=trim((string)$v);if($v==='')return null;$n=(float)$v;if($n<0)throw new InvalidArgumentException('예상금액은 0 이상이어야 합니다.');return$n;}
    private function audit(string$l,string$m,string$e,string$t,string$id,string$a,?Throwable$x=null):void{$c=['event_code'=>$e,'result'=>$l==='info'?'SUCCESS':($l==='warning'?'BLOCKED':'FAILED'),'service'=>self::class,'action'=>strtolower($e),'actor'=>$a,'target_type'=>$t,'target_id'=>$id];if($x){$c['error_code']=$x::class;$c['error']=$x;}if($l==='info')$this->logger->info($m,$c);elseif($l==='warning')$this->logger->warning($m,$c);else$this->logger->error($m,$c);}
}
