<?php

define('PROJECT_ROOT', dirname(__DIR__, 2));
require PROJECT_ROOT . '/vendor/autoload.php';
require PROJECT_ROOT . '/core/Database.php';
require PROJECT_ROOT . '/core/DbPdo.php';
require PROJECT_ROOT . '/core/Storage.php';

use App\Models\Institution\AttendanceModel;
use App\Services\Institution\AttendanceService;
use Core\DbPdo;
use Core\Helpers\ActorHelper;

function tabsUuid(): string{$hex=bin2hex(random_bytes(16));return substr($hex,0,8).'-'.substr($hex,8,4).'-4'.substr($hex,13,3).'-8'.substr($hex,17,3).'-'.substr($hex,20,12);}
function tabsAssert(bool $condition,string $message): void{if(!$condition)throw new RuntimeException($message);}
function tabsCounts(PDO $pdo,array $tables): array{$out=[];foreach($tables as $table)$out[$table]=(int)$pdo->query("SELECT COUNT(*) FROM `{$table}`")->fetchColumn();return$out;}

$pdo=DbPdo::conn();$model=new AttendanceModel($pdo);$service=new AttendanceService($pdo,static fn():string=>ActorHelper::system('근태 탭 Runtime rollback Fixture'));
$tables=['institution_employment_contracts','institution_employment_contracts_weekly_schedules','institution_employment_contracts_break_schedules','institution_attendance_clock_events','institution_attendance_daily_records','institution_attendance_work_segments','institution_attendance_daily_exceptions','institution_attendance_audits','institution_attendance_monthly_closures','institution_attendance_monthly_closure_histories','system_statutory_standards'];
$before=tabsCounts($pdo,$tables);$source=$pdo->query("SELECT * FROM institution_employment_contracts WHERE contract_status='APPROVED' AND deleted_at IS NULL ORDER BY approved_at DESC,id LIMIT 1")->fetch(PDO::FETCH_ASSOC);tabsAssert(is_array($source),'승인 근로계약 Fixture 기준이 없습니다.');
$sourceSchedules=$pdo->query('SELECT * FROM institution_employment_contracts_weekly_schedules WHERE contract_id='.$pdo->quote((string)$source['id']).' ORDER BY day_of_week')->fetchAll(PDO::FETCH_ASSOC);tabsAssert(count($sourceSchedules)===7,'주간일정 Fixture 기준이 7건이 아닙니다.');
$employees=$pdo->query('SELECT id,employee_name FROM user_employees ORDER BY sort_no,id LIMIT 3')->fetchAll(PDO::FETCH_ASSOC);tabsAssert(count($employees)===3,'근태 탭 Fixture 직원 3명이 필요합니다.');
$actor=ActorHelper::system('근태 탭 Runtime rollback Fixture');$now=date('Y-m-d H:i:s');$workDate='1990-09-28';$month='1990-09';$fixtureIds=[];$results=[];

$pdo->beginTransaction();
try{
    foreach([['WORKING_TIME_STANDARD',['daily_legal_work_seconds'=>28800,'weekly_legal_work_seconds'=>144000,'week_start_day'=>1,'night_start_time'=>'22:00','night_end_time'=>'06:00']],['PUBLIC_HOLIDAY_CALENDAR',['holidays'=>[]]]] as[$type,$value]){$id=tabsUuid();$fixtureIds[]=$id;$model->insert('system_statutory_standards',['id'=>$id,'sort_no'=>100001,'standard_type_code'=>$type,'effective_from'=>'1990-09-01','effective_to'=>'1990-09-30','value_data'=>json_encode($value,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'note'=>'attendance tabs rollback fixture','created_at'=>$now,'created_by'=>$actor,'updated_at'=>$now,'updated_by'=>$actor]);}
    $contexts=[];
    foreach($employees as$index=>$employee){$contract=$source;$contractId=tabsUuid();$fixtureIds[]=$contractId;$contract['id']=$contractId;$contract['sort_no']=(int)$source['sort_no']+100001+$index;$contract['contract_no']='TAB-ROLLBACK-'.str_replace('-','',$contractId);$contract['employee_id']=$employee['id'];$contract['employee_name_snapshot']=$employee['employee_name'];$contract['previous_contract_id']=null;$contract['revision_no']=1;$contract['revision_reason']='rollback Fixture';$contract['contract_start_date']='1990-09-01';if($contract['contract_period_type']==='FIXED_TERM')$contract['contract_end_date']='1990-09-30';else{$contract['contract_end_date']=null;$contract['fixed_term_reason_code']=null;$contract['fixed_term_reason_detail']=null;}$contract['work_schedule_type']='NORMAL';$contract['probation_start_date']=null;$contract['probation_end_date']=null;$contract['probation_rate']=null;$contract['contract_status']='APPROVED';$contract['current_approval_request_id']=null;$contract['approved_at']=$now;$contract['terminated_at']=null;$contract['termination_reason']=null;$contract['note']='attendance tabs rollback fixture';$contract['created_at']=$now;$contract['created_by']=$actor;$contract['updated_at']=$now;$contract['updated_by']=$actor;$contract['deleted_at']=null;$contract['deleted_by']=null;$model->insert('institution_employment_contracts',$contract);
        $workScheduleId='';foreach($sourceSchedules as$row){$schedule=$row;$schedule['id']=tabsUuid();$schedule['contract_id']=$contractId;if((int)$schedule['day_of_week']===5){$workScheduleId=$schedule['id'];$schedule['day_type']='WORKDAY';$schedule['start_time']='09:00:00';$schedule['end_time']='18:00:00';$schedule['end_day_offset']=0;$schedule['break_minutes']=60;}$schedule['created_at']=$now;$schedule['created_by']=$actor;$schedule['updated_at']=$now;$schedule['updated_by']=$actor;$model->insert('institution_employment_contracts_weekly_schedules',$schedule);}tabsAssert($workScheduleId!=='','금요일 근무일정 생성 실패');
        if($index!==1)$model->insert('institution_employment_contracts_break_schedules',['id'=>tabsUuid(),'weekly_schedule_id'=>$workScheduleId,'sort_no'=>1,'start_time'=>'12:00:00','end_time'=>'13:00:00','end_day_offset'=>0,'created_at'=>$now,'created_by'=>$actor,'updated_at'=>$now,'updated_by'=>$actor]);
        $contexts[]=['employee'=>$employee,'contract_id'=>$contractId,'schedule_id'=>$workScheduleId];
    }

    $clock=static function(AttendanceService $service,array $employee,string $type,string $at,string $reason):array{return$service->registerAdminClock(['employee_id'=>$employee['id'],'event_type_code'=>$type,'occurred_at'=>$at,'reason'=>$reason,'request_key'=>tabsUuid()]);};
    $clock($service,$contexts[0]['employee'],'CLOCK_IN',$workDate.' 09:00:00','직원 A 정상 출근');$aOut=$clock($service,$contexts[0]['employee'],'CLOCK_OUT',$workDate.' 18:00:00','직원 A 정상 퇴근');$dailyA=$aOut['data']['daily_record'];tabsAssert((int)$dailyA['actual_work_seconds']===28800&&$dailyA['calculation_status_code']==='CALCULATED','직원 A 정상 근태 계산 실패');
    $liveA=$service->monthlyList(['draw'=>1,'start'=>0,'length'=>10,'closing_month'=>$month,'employee_id'=>$contexts[0]['employee']['id']],$contexts[0]['employee']['id'])['data'][0];tabsAssert((int)$liveA['actual_work_seconds']===28800&&$liveA['aggregate_source_code']==='LIVE','직원 A 미마감 실시간 월 누계 실패');
    $closeA=$service->close(['employee_id'=>$contexts[0]['employee']['id'],'closing_month'=>$month,'reason'=>'직원 A Runtime 마감','request_key'=>tabsUuid()]);tabsAssert((int)$closeA['data']['revision']===1,'직원 A Revision 생성 실패');$closedA=$service->monthlyList(['draw'=>1,'start'=>0,'length'=>10,'closing_month'=>$month],$contexts[0]['employee']['id'])['data'][0];tabsAssert($closedA['aggregate_source_code']==='SNAPSHOT'&&(int)$closedA['actual_work_seconds']===28800,'직원 A 마감 Snapshot 조회 실패');

    $clock($service,$contexts[1]['employee'],'CLOCK_IN',$workDate.' 09:00:00','직원 B 출근');$bOut=$clock($service,$contexts[1]['employee'],'CLOCK_OUT',$workDate.' 18:00:00','직원 B 퇴근');$dailyB=$bOut['data']['daily_record'];tabsAssert($dailyB['calculation_status_code']==='NEEDS_CONFIRMATION','직원 B 확인 필요 미발생');$closureB=$service->closureList(['draw'=>1,'start'=>0,'length'=>10,'closing_month'=>$month],$contexts[1]['employee']['id'])['data'][0];tabsAssert($closureB['readiness_status_code']==='BLOCKED'&&(int)$closureB['confirmation_count']>0&&str_contains($closureB['readiness_reason'],'확인 필요'),'직원 B 마감 차단사유 표시 실패');

    $cIn=$clock($service,$contexts[2]['employee'],'CLOCK_IN',$workDate.' 09:00:00','직원 C 출근');$dailyC=$cIn['data']['daily_record'];$model->insert('institution_attendance_daily_exceptions',['id'=>tabsUuid(),'daily_record_id'=>$dailyC['id'],'exception_type_code'=>'MISSING_CLOCK_OUT','candidate_seconds'=>0,'source_type_code'=>'CALCULATION','resolution_status_code'=>'OPEN','resolution_reason'=>null,'resolved_at'=>null,'resolved_by'=>null,'created_at'=>$now,'created_by'=>$actor,'updated_at'=>$now,'updated_by'=>$actor]);$exceptionsC=$service->exceptionList(['draw'=>1,'start'=>0,'length'=>10,'date_from'=>$workDate,'date_to'=>$workDate],$contexts[2]['employee']['id']);tabsAssert((int)$exceptionsC['recordsFiltered']===1&&str_contains((string)$exceptionsC['data'][0]['exception_labels'],'퇴근'),'직원 C 누락·이상 목록 노출 실패');$detailC=$service->detail($contexts[2]['employee']['id'],$workDate)['data'];tabsAssert(count($detailC['clock_events'])===1&&count($detailC['exceptions'])>=1,'직원 C 확인·조치 문맥 조회 실패');$clock($service,$contexts[2]['employee'],'CLOCK_OUT',$workDate.' 18:00:00','직원 C 누락 퇴근 보정');$service->recalculate(['employee_id'=>$contexts[2]['employee']['id'],'work_date'=>$workDate,'request_key'=>tabsUuid()]);$exceptionsAfter=$service->exceptionList(['draw'=>1,'start'=>0,'length'=>10,'date_from'=>$workDate,'date_to'=>$workDate],$contexts[2]['employee']['id']);tabsAssert((int)$exceptionsAfter['recordsFiltered']===0,'직원 C 보정·재계산 후 예외 해소 실패');$closureC=$service->closureList(['draw'=>1,'start'=>0,'length'=>10,'closing_month'=>$month],$contexts[2]['employee']['id'])['data'][0];tabsAssert($closureC['readiness_status_code']==='READY','직원 C 마감 가능 전환 실패');
    $results=['A'=>['live_seconds'=>(int)$liveA['actual_work_seconds'],'closed_source'=>$closedA['aggregate_source_code'],'revision'=>(int)$closeA['data']['revision']],'B'=>['status'=>$dailyB['calculation_status_code'],'readiness'=>$closureB['readiness_status_code'],'reason'=>$closureB['readiness_reason']],'C'=>['before_exceptions'=>(int)$exceptionsC['recordsFiltered'],'after_exceptions'=>(int)$exceptionsAfter['recordsFiltered'],'readiness'=>$closureC['readiness_status_code']]];
}finally{if($pdo->inTransaction())$pdo->rollBack();}
$after=tabsCounts($pdo,$tables);tabsAssert($after===$before,'근태 탭 Runtime Fixture ROLLBACK 전후 건수가 다릅니다.');$remaining=(int)$pdo->query("SELECT COUNT(*) FROM institution_employment_contracts WHERE note='attendance tabs rollback fixture'")->fetchColumn();tabsAssert($remaining===0,'근태 탭 Runtime Fixture 계약이 잔존합니다.');
echo json_encode(['success'=>true,'scenarios'=>$results,'before_counts'=>$before,'after_counts'=>$after,'remaining_fixture_contracts'=>$remaining],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES).PHP_EOL;
