<?php
declare(strict_types=1);
define('PROJECT_ROOT',dirname(__DIR__,2));require PROJECT_ROOT.'/vendor/autoload.php';require_once PROJECT_ROOT.'/core/Storage.php';
use App\Services\Ledger\AssetService;use Core\DbPdo;use Core\Helpers\ActorHelper;
$db=DbPdo::conn();$tables=['ledger_assets','ledger_asset_assignments','ledger_asset_depreciations','ledger_asset_disposals','ledger_vouchers'];
$counts=function()use($db,$tables):array{$r=[];foreach($tables as$t)$r[$t]=(int)$db->query("SELECT COUNT(*) FROM $t")->fetchColumn();return$r;};$before=$counts();
$company=(string)$db->query('SELECT id FROM system_company LIMIT 1')->fetchColumn();$accounts=$db->query("SELECT a.id FROM ledger_accounts a WHERE a.deleted_at IS NULL AND a.is_active=1 AND a.is_posting=1 AND NOT EXISTS(SELECT 1 FROM ledger_accounts_sub s WHERE s.account_id=a.id AND s.is_required=1) ORDER BY a.account_code LIMIT 7")->fetchAll(PDO::FETCH_COLUMN);$business=(string)$db->query("SELECT code FROM system_codes WHERE code_group='BUSINESS_UNIT' AND is_active=1 ORDER BY sort_no LIMIT 1")->fetchColumn();if(!$company||count($accounts)<7||!$business)throw new RuntimeException('자산 회귀검증 기준정보가 부족합니다.');
$service=new AssetService($db);$actor=ActorHelper::system('ASSET_REGRESSION');$checks=['list_api_query'=>is_array($service->list())];$db->beginTransaction();try{
$c=$service->create(['company_id'=>$company,'asset_no'=>'TEST-ASSET-'.date('His'),'asset_name'=>'회귀검증 자산','asset_category_code'=>'EQUIPMENT','acquisition_date'=>'2026-01-01','service_start_date'=>'2026-01-01','acquisition_amount'=>1200000,'residual_amount'=>0,'useful_life_months'=>60,'asset_account_id'=>$accounts[0],'accumulated_account_id'=>$accounts[1],'expense_account_id'=>$accounts[2],'acquisition_counter_account_id'=>$accounts[3],'business_unit'=>$business,'location_name'=>'검증장소'],$actor);$id=(string)$c['data']['id'];$voucherStatus=function(string$table,string$field)use($db,$id):string{return strtoupper((string)$db->query("SELECT v.status FROM $table a JOIN ledger_vouchers v ON v.id=a.$field WHERE a.".($table==='ledger_assets'?'id':'asset_id').'='.$db->quote($id))->fetchColumn());};$checks['asset_created']=$id!=='';$checks['acquisition_posted']=$voucherStatus('ledger_assets','acquisition_voucher_id')==='POSTED';
$service->transfer(['asset_id'=>$id,'effective_date'=>'2026-02-01','business_unit'=>$business,'location_name'=>'이동장소','reason'=>'회귀검증 이동'],$actor);$checks['assignment_history']=(int)$db->query('SELECT COUNT(*) FROM ledger_asset_assignments WHERE asset_id='.$db->quote($id))->fetchColumn()===2;
$service->depreciate(['asset_id'=>$id,'year_month'=>'2026-01','depreciation_date'=>'2026-01-31'],$actor);$checks['depreciation_posted']=$voucherStatus('ledger_asset_depreciations','voucher_id')==='POSTED';
$service->dispose(['asset_id'=>$id,'disposal_date'=>'2026-03-01','disposal_type_code'=>'SALE','proceeds_amount'=>1100000,'proceeds_account_id'=>$accounts[4],'gain_account_id'=>$accounts[5],'loss_account_id'=>$accounts[6],'reason'=>'회귀검증 처분'],$actor);$checks['disposed']=($service->detail($id)['asset_status_code']??'')==='DISPOSED';$checks['disposal_posted']=$voucherStatus('ledger_asset_disposals','voucher_id')==='POSTED';
}finally{$db->rollBack();}$after=$counts();$passed=!in_array(false,$checks,true)&&$before===$after;echo json_encode(['passed'=>$passed,'checks'=>$checks,'before'=>$before,'after'=>$after,'rolled_back'=>$before===$after],JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT).PHP_EOL;exit($passed?0:1);
