<?php
declare(strict_types=1);
define('PROJECT_ROOT', dirname(__DIR__));
require PROJECT_ROOT . '/vendor/autoload.php';
require_once PROJECT_ROOT . '/core/Storage.php';
$mode=strtolower((string)($argv[1]??'verify'));if(!in_array($mode,['up','verify'],true))throw new InvalidArgumentException('사용법: php tools/apply_evidence_link_cardinality_migration.php [up|verify]');
$db=Core\DbPdo::conn();$before=['evidence'=>(int)$db->query('SELECT COUNT(*) FROM ledger_evidence_metadata')->fetchColumn(),'transaction'=>(int)$db->query('SELECT COUNT(*) FROM ledger_transactions')->fetchColumn(),'link'=>(int)$db->query('SELECT COUNT(*) FROM ledger_evidence_links')->fetchColumn(),'active'=>(int)$db->query('SELECT COUNT(*) FROM ledger_evidence_links WHERE deleted_at IS NULL')->fetchColumn()];
if($mode==='up'){$sql=(string)file_get_contents(PROJECT_ROOT.'/app/migrations/20260822_03_enable_evidence_transaction_many_to_many.up.sql');if(!preg_match('/DELIMITER \$\$(.*?)\$\$\s*DELIMITER ;/s',$sql,$m))throw new RuntimeException('Migration 구문을 해석할 수 없습니다.');foreach(preg_split('/\$\$\s*/',trim($m[1]))?:[]as$s)if(trim($s)!=='')$db->exec(trim($s));}
$after=['evidence'=>(int)$db->query('SELECT COUNT(*) FROM ledger_evidence_metadata')->fetchColumn(),'transaction'=>(int)$db->query('SELECT COUNT(*) FROM ledger_transactions')->fetchColumn(),'link'=>(int)$db->query('SELECT COUNT(*) FROM ledger_evidence_links')->fetchColumn(),'active'=>(int)$db->query('SELECT COUNT(*) FROM ledger_evidence_links WHERE deleted_at IS NULL')->fetchColumn()];if($before!==$after)throw new RuntimeException('Migration 전후 업무데이터 건수가 달라졌습니다.');$indexes=$db->query("SELECT INDEX_NAME,NON_UNIQUE,GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) columns_in_order FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='ledger_evidence_links' GROUP BY INDEX_NAME,NON_UNIQUE ORDER BY INDEX_NAME")->fetchAll(PDO::FETCH_ASSOC)?:[];echo json_encode(['success'=>true,'mode'=>$mode,'before'=>$before,'after'=>$after,'indexes'=>$indexes],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE).PHP_EOL;
