<?php
declare(strict_types=1);
define('PROJECT_ROOT',dirname(__DIR__));require PROJECT_ROOT.'/vendor/autoload.php';require_once PROJECT_ROOT.'/core/Storage.php';
use App\Services\Institution\SocialInsuranceService;use App\Services\Institution\RegularEmploymentIncomeCalculationService;
$db=Core\DbPdo::conn();$employee=(string)$db->query('SELECT id FROM user_employees ORDER BY id LIMIT 1')->fetchColumn();$user=(string)$db->query('SELECT id FROM auth_users ORDER BY id LIMIT 1')->fetchColumn();if($employee===''||$user==='')throw new RuntimeException('Fixture 대상 직원 또는 사용자가 없습니다.');Core\Session::start(480);$_SESSION['user']=['id'=>$user];$_SESSION['auth_state']=['user_id'=>$user,'status'=>'NORMAL'];
$service=new SocialInsuranceService($db);$prefix='FIXTURE:SOCIAL:'.bin2hex(random_bytes(4));$ids=[];$checks=[];
try{
foreach([['NATIONAL_PENSION','STANDARD_MONTHLY_INCOME','CONFIRMED'],['HEALTH_INSURANCE','MONTHLY_REMUNERATION','CONFIRMED'],['EMPLOYMENT_INSURANCE','INSURABLE_REMUNERATION','CONFIRMED']]as$i=>$row){[$type,$basisType,$status]=$row;$from=$type==='EMPLOYMENT_INSURANCE'?'2026-08-10':'2026-01-01';$to=$type==='EMPLOYMENT_INSURANCE'?'2026-08-31':'2026-12-31';$saved=$service->saveCoverage(['employee_id'=>$employee,'insurance_type_code'=>$type,'coverage_status_code'=>'ACQUIRED','effective_from'=>$from,'effective_to'=>$to,'source_type_code'=>'MANUAL_CONFIRMED','confirmed_at'=>'2026-01-01','reason'=>'Runtime Fixture','request_key'=>$prefix.':C'.$i]);$ids[]=$saved['data']['id'];$service->saveBasis(['coverage_id'=>$saved['data']['id'],'basis_type_code'=>$basisType,'effective_from'=>$from,'effective_to'=>$to,'basis_amount'=>3000000,'confirmation_status_code'=>$status,'source_type_code'=>'MANUAL_CONFIRMED','reason'=>'Runtime Fixture','request_key'=>$prefix.':B'.$i]);}
 $checks['coverage_count']=$db->query("SELECT COUNT(*) FROM institution_social_insurance_coverages WHERE request_key LIKE ".$db->quote($prefix.'%'))->fetchColumn();$checks['basis_count']=$db->query("SELECT COUNT(*) FROM institution_social_insurance_assessment_bases WHERE request_key LIKE ".$db->quote($prefix.'%'))->fetchColumn();
 try{$service->saveCoverage(['employee_id'=>$employee,'insurance_type_code'=>'NATIONAL_PENSION','coverage_status_code'=>'ACQUIRED','effective_from'=>'2026-06-01','effective_to'=>'2026-06-30','source_type_code'=>'MANUAL_CONFIRMED','confirmed_at'=>'2026-01-01','reason'=>'Overlap','request_key'=>$prefix.':OVERLAP']);$checks['coverage_overlap']=false;}catch(InvalidArgumentException){$checks['coverage_overlap']=true;}
 try{$service->saveBasis(['coverage_id'=>$ids[0],'basis_type_code'=>'STANDARD_MONTHLY_INCOME','effective_from'=>'2026-06-01','effective_to'=>'2026-06-30','basis_amount'=>1,'confirmation_status_code'=>'CONFIRMED','source_type_code'=>'MANUAL_CONFIRMED','reason'=>'Overlap','request_key'=>$prefix.':BOVERLAP']);$checks['basis_overlap']=false;}catch(InvalidArgumentException){$checks['basis_overlap']=true;}
 $preview=(new RegularEmploymentIncomeCalculationService($db))->preview('2026-08','2026-08-25',[$employee],'SYSTEM:FIXTURE');$message=(string)$preview['results'][0]['calculation_message'];$lineCodes=array_column($preview['results'][0]['line_items'],'item_code');$employmentLine=array_values(array_filter($preview['results'][0]['line_items'],static fn(array $line):bool=>($line['item_code']??'')==='EMPLOYMENT_INSURANCE'))[0]??[];$checks['health_rounding_resolved']=in_array('HEALTH_INSURANCE',$lineCodes,true);$checks['care_rounding_resolved']=in_array('LONG_TERM_CARE',$lineCodes,true);$checks['employment_rounding_resolved']=($employmentLine['rounding_method']??'')==='TRUNCATE'&&(int)($employmentLine['rounding_unit']??0)===10&&$employmentLine['calculated_amount']!==null;$checks['employment_month_conditioned']=!str_contains($message,'고용보험 월중 취득·상실 공식 정책이 없습니다.');$checks['employment_business_size_decoupled']=!str_contains($message,'고용보험 사용자 추가부담 사업규모 SSOT가 없습니다.');$checks['health_rounding_not_blocked']=!str_contains($message,'건강보험 공식 계산정책이 없습니다.');$checks['care_rounding_not_blocked']=!str_contains($message,'장기요양 공식 계산정책이 없습니다.');$checks['readiness']=$preview['readiness'];$checks['audit_count']=$db->query("SELECT COUNT(*) FROM institution_social_insurance_audits WHERE request_key LIKE ".$db->quote($prefix.'%'))->fetchColumn();
}finally{$db->beginTransaction();foreach(['institution_social_insurance_audits','institution_social_insurance_assessment_bases','institution_social_insurance_coverages']as$t)$db->exec("DELETE FROM `$t` WHERE request_key LIKE ".$db->quote($prefix.'%'));$db->commit();}
$checks['residual']=(int)$db->query("SELECT (SELECT COUNT(*) FROM institution_social_insurance_coverages WHERE request_key LIKE ".$db->quote($prefix.'%').")+(SELECT COUNT(*) FROM institution_social_insurance_assessment_bases WHERE request_key LIKE ".$db->quote($prefix.'%').")+(SELECT COUNT(*) FROM institution_social_insurance_audits WHERE request_key LIKE ".$db->quote($prefix.'%').")")->fetchColumn();if((int)$checks['coverage_count']!==3||(int)$checks['basis_count']!==3||!$checks['coverage_overlap']||!$checks['basis_overlap']||!$checks['health_rounding_resolved']||!$checks['care_rounding_resolved']||!$checks['employment_rounding_resolved']||!$checks['employment_month_conditioned']||!$checks['employment_business_size_decoupled']||!$checks['health_rounding_not_blocked']||!$checks['care_rounding_not_blocked']||$checks['readiness']!=='BLOCKED'||(int)$checks['audit_count']<6||$checks['residual']!==0)throw new RuntimeException('사회보험 Runtime Fixture가 실패했습니다.');echo json_encode(['success'=>true,'checks'=>$checks],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE).PHP_EOL;
