<?php
namespace App\Models\Ledger;
use PDO;

class AssetModel
{
    public function __construct(private readonly PDO $db) {}
    public function list(array $f=[]): array {
        $sql="SELECT a.*,c.company_name_ko company_name,p.project_name,t.team_name,e.employee_name,aa.account_code asset_account_code,aa.account_name asset_account_name,COALESCE(d.accumulated_amount,0) accumulated_amount,a.acquisition_amount-COALESCE(d.accumulated_amount,0) book_value_amount FROM ledger_assets a JOIN system_company c ON c.id=a.company_id JOIN ledger_accounts aa ON aa.id=a.asset_account_id LEFT JOIN system_projects p ON p.id=a.project_id LEFT JOIN system_work_teams t ON t.id=a.work_team_id LEFT JOIN user_employees e ON e.id=a.employee_id LEFT JOIN (SELECT asset_id,MAX(accumulated_amount) accumulated_amount FROM ledger_asset_depreciations GROUP BY asset_id)d ON d.asset_id=a.id WHERE a.deleted_at IS NULL";$p=[];
        foreach(['company_id','asset_status_code','asset_category_code','business_unit'] as $k)if(trim((string)($f[$k]??''))!==''){$sql.=" AND a.$k=:$k";$p[":$k"]=$f[$k];}
        if(trim((string)($f['keyword']??''))!==''){$sql.=' AND (a.asset_no LIKE :q OR a.asset_name LIKE :q OR a.serial_no LIKE :q)';$p[':q']='%'.trim($f['keyword']).'%';}
        $sql.=' ORDER BY a.asset_no,a.id';return $this->all($sql,$p);
    }
    public function find(string $id,bool $lock=false):?array{return $this->one('SELECT * FROM ledger_assets WHERE id=:id AND deleted_at IS NULL'.($lock?' FOR UPDATE':''),[':id'=>$id]);}
    public function duplicateNo(string $company,string $no):?array{return $this->one('SELECT id FROM ledger_assets WHERE company_id=:c AND asset_no=:n AND deleted_at IS NULL',[':c'=>$company,':n'=>$no]);}
    public function insert(array $r):void{$this->exec('INSERT INTO ledger_assets (id,company_id,asset_no,asset_name,asset_category_code,asset_status_code,acquisition_date,service_start_date,acquisition_amount,residual_amount,useful_life_months,depreciation_method_code,asset_account_id,accumulated_account_id,expense_account_id,acquisition_counter_account_id,business_unit,project_id,work_team_id,employee_id,location_name,serial_no,acquisition_voucher_id,note,created_at,created_by,updated_at,updated_by) VALUES (:id,:company_id,:asset_no,:asset_name,:asset_category_code,:asset_status_code,:acquisition_date,:service_start_date,:acquisition_amount,:residual_amount,:useful_life_months,:depreciation_method_code,:asset_account_id,:accumulated_account_id,:expense_account_id,:acquisition_counter_account_id,:business_unit,:project_id,:work_team_id,:employee_id,:location_name,:serial_no,:acquisition_voucher_id,:note,:created_at,:created_by,:updated_at,:updated_by)',$r);}
    public function updateAssignment(string $id,array $r):void{$r[':id']=$id;$this->exec('UPDATE ledger_assets SET business_unit=:business_unit,project_id=:project_id,work_team_id=:work_team_id,employee_id=:employee_id,location_name=:location_name,updated_at=:updated_at,updated_by=:updated_by WHERE id=:id',$r);}
    public function setVoucher(string $id,string $voucher):void{$this->exec('UPDATE ledger_assets SET acquisition_voucher_id=:v WHERE id=:id',[':v'=>$voucher,':id'=>$id]);}
    public function addAssignment(array $r):void{$this->exec('INSERT INTO ledger_asset_assignments (id,asset_id,effective_date,business_unit,project_id,work_team_id,employee_id,location_name,reason,created_at,created_by) VALUES (:id,:asset_id,:effective_date,:business_unit,:project_id,:work_team_id,:employee_id,:location_name,:reason,:created_at,:created_by)',$r);}
    public function depreciationTotal(string $id):float{return(float)$this->scalar('SELECT COALESCE(SUM(depreciation_amount),0) FROM ledger_asset_depreciations WHERE asset_id=:id',[':id'=>$id]);}
    public function depreciationExists(string $id,string $month):bool{return(int)$this->scalar('SELECT COUNT(*) FROM ledger_asset_depreciations WHERE asset_id=:id AND depreciation_year_month=:m',[':id'=>$id,':m'=>$month])>0;}
    public function addDepreciation(array $r):void{$this->exec('INSERT INTO ledger_asset_depreciations (id,asset_id,depreciation_year_month,depreciation_date,depreciation_amount,accumulated_amount,book_value_amount,voucher_id,created_at,created_by) VALUES (:id,:asset_id,:depreciation_year_month,:depreciation_date,:depreciation_amount,:accumulated_amount,:book_value_amount,:voucher_id,:created_at,:created_by)',$r);}
    public function addDisposal(array $r):void{$this->exec('INSERT INTO ledger_asset_disposals (id,asset_id,disposal_date,disposal_type_code,proceeds_amount,book_value_amount,gain_loss_amount,proceeds_account_id,gain_account_id,loss_account_id,voucher_id,reason,created_at,created_by) VALUES (:id,:asset_id,:disposal_date,:disposal_type_code,:proceeds_amount,:book_value_amount,:gain_loss_amount,:proceeds_account_id,:gain_account_id,:loss_account_id,:voucher_id,:reason,:created_at,:created_by)',$r);$this->exec("UPDATE ledger_assets SET asset_status_code='DISPOSED',updated_at=:at,updated_by=:by WHERE id=:id",[':at'=>$r[':created_at'],':by'=>$r[':created_by'],':id'=>$r[':asset_id']]);}
    public function history(string $id):array{return ['assignments'=>$this->all('SELECT * FROM ledger_asset_assignments WHERE asset_id=:id ORDER BY effective_date DESC,created_at DESC',[':id'=>$id]),'depreciations'=>$this->all('SELECT * FROM ledger_asset_depreciations WHERE asset_id=:id ORDER BY depreciation_year_month DESC',[':id'=>$id]),'disposal'=>$this->one('SELECT * FROM ledger_asset_disposals WHERE asset_id=:id',[':id'=>$id])];}
    public function options():array{return ['companies'=>$this->all('SELECT id,company_name_ko name FROM system_company ORDER BY company_name_ko'),'accounts'=>$this->all("SELECT id,CONCAT(account_code,' ',account_name) name FROM ledger_accounts WHERE deleted_at IS NULL AND is_active=1 AND is_posting=1 ORDER BY account_code"),'projects'=>$this->all('SELECT id,project_name name FROM system_projects WHERE deleted_at IS NULL ORDER BY project_name'),'work_teams'=>$this->all('SELECT id,team_name name,business_unit FROM system_work_teams WHERE deleted_at IS NULL AND is_active=1 ORDER BY sort_no,team_name'),'employees'=>$this->all('SELECT id,employee_name name FROM user_employees ORDER BY employee_name'),'business_units'=>$this->all("SELECT code id,code_name name FROM system_codes WHERE code_group='BUSINESS_UNIT' AND is_active=1 ORDER BY sort_no")];}
    private function all(string $s,array $p=[]):array{$q=$this->db->prepare($s);$q->execute($p);return$q->fetchAll(PDO::FETCH_ASSOC)?:[];}private function one(string $s,array $p=[]):?array{$q=$this->db->prepare($s);$q->execute($p);return$q->fetch(PDO::FETCH_ASSOC)?:null;}private function scalar(string $s,array $p=[]):mixed{$q=$this->db->prepare($s);$q->execute($p);return$q->fetchColumn();}private function exec(string $s,array $p):void{$q=$this->db->prepare($s);$q->execute($p);}
}
