<?php

namespace App\Models\Ledger;

use PDO;

class PeriodClosureModel
{
    public function __construct(private readonly PDO $db) {}
    public function list(): array { return $this->all("SELECT c.*,s.company_name_ko AS company_name FROM ledger_period_closures c JOIN system_company s ON s.id=c.company_id ORDER BY c.fiscal_year DESC,s.company_name_ko"); }
    public function find(string $companyId,int $year,bool $lock=false): ?array { return $this->one('SELECT * FROM ledger_period_closures WHERE company_id=:company_id AND fiscal_year=:fiscal_year'.($lock?' FOR UPDATE':''),[':company_id'=>$companyId,':fiscal_year'=>$year]); }
    public function findClosedByDate(string $companyId,string $date): ?array { return $this->one("SELECT * FROM ledger_period_closures WHERE company_id=:company_id AND :target_date BETWEEN period_start_date AND period_end_date AND close_status_code='CLOSED' LIMIT 1",[':company_id'=>$companyId,':target_date'=>$date]); }
    public function period(string $companyId,int $year): array { $row=$this->one('SELECT opening_date,period_end_date FROM ledger_opening_balances WHERE company_id=:company_id AND fiscal_year=:fiscal_year LIMIT 1',[':company_id'=>$companyId,':fiscal_year'=>$year]);return['period_start_date'=>(string)($row['opening_date']??sprintf('%04d-01-01',$year)),'period_end_date'=>(string)($row['period_end_date']??sprintf('%04d-12-31',$year))]; }
    public function companies(): array { return $this->all('SELECT id,company_name_ko AS name FROM system_company ORDER BY company_name_ko'); }
    public function readiness(string $companyId,string $startDate,string $endDate): array
    {
        $p=[':start_date'=>$startDate,':end_date'=>$endDate];
        $unposted=(int)$this->scalar("SELECT COUNT(*) FROM ledger_vouchers WHERE voucher_date BETWEEN :start_date AND :end_date AND deleted_at IS NULL AND UPPER(status) NOT IN ('POSTED','CLOSED')",$p);
        $imbalanced=(int)$this->scalar("SELECT COUNT(*) FROM (SELECT v.id FROM ledger_vouchers v JOIN ledger_voucher_lines l ON l.voucher_id=v.id WHERE v.voucher_date BETWEEN :start_date AND :end_date AND v.deleted_at IS NULL AND UPPER(v.status) IN ('POSTED','CLOSED') GROUP BY v.id HAVING ROUND(SUM(l.debit-l.credit),2)<>0) AS unbalanced",$p);
        $posted=(int)$this->scalar("SELECT COUNT(*) FROM ledger_vouchers WHERE voucher_date BETWEEN :start_date AND :end_date AND deleted_at IS NULL AND UPPER(status) IN ('POSTED','CLOSED')",$p);
        $inventory=(int)$this->scalar("SELECT COUNT(*) FROM ledger_inventory_balances WHERE company_id=:company_id AND fiscal_year=YEAR(:end_date) AND status_code='CONFIRMED'",[':company_id'=>$companyId,':end_date'=>$endDate]);
        $assets=(int)$this->scalar('SELECT COUNT(*) FROM ledger_assets WHERE company_id=:company_id AND deleted_at IS NULL AND acquisition_date<=:end_date',[':company_id'=>$companyId,':end_date'=>$endDate]);
        return['unposted_voucher_count'=>$unposted,'imbalanced_voucher_count'=>$imbalanced,'posted_voucher_count'=>$posted,'confirmed_inventory_count'=>$inventory,'asset_count'=>$assets,'ready'=>$unposted===0&&$imbalanced===0];
    }
    public function saveClosed(array $row): void { $row[':closed_at']=$row[':created_at']=$row[':updated_at']=$row[':processed_at'];$row[':closed_by']=$row[':created_by']=$row[':updated_by']=$row[':actor'];unset($row[':processed_at'],$row[':actor']);$this->execute("INSERT INTO ledger_period_closures(id,company_id,fiscal_year,period_start_date,period_end_date,close_status_code,current_revision,close_reason,closed_at,closed_by,created_at,created_by,updated_at,updated_by) VALUES(:id,:company_id,:fiscal_year,:period_start_date,:period_end_date,'CLOSED',:revision,:reason,:closed_at,:closed_by,:created_at,:created_by,:updated_at,:updated_by) ON DUPLICATE KEY UPDATE period_start_date=VALUES(period_start_date),period_end_date=VALUES(period_end_date),close_status_code='CLOSED',current_revision=VALUES(current_revision),close_reason=VALUES(close_reason),closed_at=VALUES(closed_at),closed_by=VALUES(closed_by),updated_at=VALUES(updated_at),updated_by=VALUES(updated_by)",$row); }
    public function saveReopened(string $id,int $revision,string $reason,string $actor,string $at): void { $this->execute("UPDATE ledger_period_closures SET close_status_code='REOPENED',current_revision=:revision,reopened_at=:reopened_at,reopened_by=:reopened_by,reopen_reason=:reason,updated_at=:updated_at,updated_by=:updated_by WHERE id=:id",[':revision'=>$revision,':reopened_at'=>$at,':reopened_by'=>$actor,':reason'=>$reason,':updated_at'=>$at,':updated_by'=>$actor,':id'=>$id]); }
    public function addHistory(array $row): void { $this->execute('INSERT INTO ledger_period_closure_histories(id,period_closure_id,revision_no,action_code,reason,readiness_snapshot_json,processed_at,processed_by) VALUES(:id,:period_closure_id,:revision_no,:action_code,:reason,:snapshot,:processed_at,:actor)',$row); }
    public function balances(string $companyId,string $endDate): array { return $this->all("SELECT x.account_id,x.ref_tokens,SUM(x.debit) AS debit,SUM(x.credit) AS credit,x.normal_balance FROM (SELECT l.account_id,l.debit,l.credit,a.normal_balance,(SELECT GROUP_CONCAT(CONCAT(r.ref_target,':',r.ref_id) ORDER BY r.ref_target SEPARATOR '|') FROM ledger_voucher_line_refs r WHERE r.voucher_line_id=l.id) AS ref_tokens FROM ledger_vouchers v JOIN ledger_voucher_lines l ON l.voucher_id=v.id JOIN ledger_accounts a ON a.id=l.account_id WHERE v.voucher_date<=:end_date AND v.deleted_at IS NULL AND UPPER(v.status) IN ('POSTED','CLOSED') AND a.account_group IN ('자산','부채','자본')) AS x GROUP BY x.account_id,x.ref_tokens,x.normal_balance HAVING ROUND(SUM(x.debit-x.credit),2)<>0",[':end_date'=>$endDate]); }
    private function all(string$sql,array$params=[]):array{$stmt=$this->db->prepare($sql);$stmt->execute($params);return$stmt->fetchAll(PDO::FETCH_ASSOC)?:[];}private function one(string$sql,array$params=[]):?array{$stmt=$this->db->prepare($sql);$stmt->execute($params);return$stmt->fetch(PDO::FETCH_ASSOC)?:null;}private function scalar(string$sql,array$params=[]):mixed{$stmt=$this->db->prepare($sql);$stmt->execute($params);return$stmt->fetchColumn();}private function execute(string$sql,array$params):void{$stmt=$this->db->prepare($sql);$stmt->execute($params);}
}
